aws/s2n-quic

README.md
quic/s2n-quic/src/lib.rs

Fix the link to provider docs in the readme

doc: fix provider link

---

scripts/book

This change adds a script to install [mdbook](https://crates.io/crates/mdbook) if necessary and build the s2n-quic guide book

doc: add mdbook script

---

quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-transport/Cargo.toml

new release which changes `s2n-quic-core`
diff: https://github.com/aws/s2n-quic/compare/v1.0.0...main

release: s2n-core

---

quic/s2n-quic-bench/Cargo.toml
quic/s2n-quic-h3/Cargo.toml
quic/s2n-quic-integration/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-qns/Cargo.toml
quic/s2n-quic-ring/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

By using explicit versions we make it clearer what is being updated for every release.

release: use explicit version for depending on internal crates

---

netbench/README.md

This change adds some initial documentation around `netbench` and tries to explain why it exists and how it works.

docs(netbench): add readme

---

netbench/netbench-collector/src/generic.rs

fix(netbench): update timestamp for generic collector

---

quic/s2n-quic/api.snap

Fixes docdiff from previous PR https://github.com/aws/s2n-quic/pull/1314

fix: update docdiff

---

quic/s2n-quic-transport/src/transmission/application.rs

related to #1253
Adds code to alternate between datagrams and control data.

feat(s2n-quic-transport): Alternate Between Prioritizing Datagrams and Prioritizing Control Frames

---

.github/workflows/ci.yml
.github/workflows/qns.yml
.github/workflows/release.yml

A few ci dependencies have version updates. This updates them to the latest.

ci: update dependencies

---

netbench/netbench-cli/src/report.rs
quic/s2n-quic-core/src/recovery/congestion_controller.rs
quic/s2n-quic-transport/src/recovery/manager/tests.rs

Clippy beta started complaining about new stuff. This PR fixes the new nitpicks.

fix(s2n-quic-core): use new type for testing CC packet info

---

quic/s2n-quic-core/src/event/generated.rs
quic/s2n-quic-events/events/common.rs
quic/s2n-quic-events/events/connection.rs
quic/s2n-quic-transport/src/connection/connection_impl.rs
quic/s2n-quic-transport/src/path/manager.rs
quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__adding_new_path.snap
quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__connection_migration_challenge_behavior.snap
quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__connection_migration_new_path_abandon_timer.snap
quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__connection_migration_use_max_ack_delay_from_active_path.snap
quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__limit_number_of_connection_migrations.snap
quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__temporary_until_authenticated.snap
quic/s2n-quic-transport/src/path/mtu.rs
quic/s2n-quic-transport/src/path/snapshots/quic__s2n-quic-transport__src__path__mtu__events__on_packet_ack_search_requested.snap
quic/s2n-quic-transport/src/path/snapshots/quic__s2n-quic-transport__src__path__mtu__events__on_packet_ack_within_threshold.snap
quic/s2n-quic-transport/src/path/snapshots/quic__s2n-quic-transport__src__path__mtu__events__on_packet_ack_within_threshold_of_max_plpmtu.snap
quic/s2n-quic-transport/src/path/snapshots/quic__s2n-quic-transport__src__path__mtu__events__on_packet_loss_black_hole.snap
quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__detect_lost_packets_persistent_congestion_path_aware.snap
quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__no_rtt_update_when_receiving_packet_on_different_path.snap
quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__on_packet_sent.snap
quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__on_packet_sent_across_multiple_paths.snap
quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__process_new_acked_packets_congestion_controller.snap
quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__process_new_acked_packets_pto_timer.snap
quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__process_new_acked_packets_update_pto_timer.snap
quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__remove_lost_packets_persistent_congestion_path_aware.snap
quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__rtt_update_when_receiving_ack_from_multiple_paths.snap

This change adds a `cause` field to the `MtuUpdated` event to indicate why the MTU changed. 

feat(s2n-quic-core): add cause to Mtu Updated event

---

.github/workflows/ci.yml
.github/workflows/qns.yml
quic/s2n-quic-platform/src/io/testing.rs
quic/s2n-quic-platform/src/io/testing/model.rs
quic/s2n-quic-sim/Cargo.toml
quic/s2n-quic-sim/README.md
quic/s2n-quic-sim/plans/baseline.toml
quic/s2n-quic-sim/plans/max_inflight.toml
quic/s2n-quic-sim/plans/network_jitter.toml
quic/s2n-quic-sim/plans/throughput.toml
quic/s2n-quic-sim/src/batch.html
quic/s2n-quic-sim/src/batch.rs
quic/s2n-quic-sim/src/main.rs
quic/s2n-quic-sim/src/query.rs
quic/s2n-quic-sim/src/report.rs
quic/s2n-quic-sim/src/run.rs
quic/s2n-quic-sim/src/run/config.rs
quic/s2n-quic-sim/src/run/endpoint.rs
quic/s2n-quic-sim/src/run/events.rs
quic/s2n-quic-sim/src/run/range.rs
quic/s2n-quic-sim/src/stats.rs
quic/s2n-quic/src/provider/io/testing.rs
scripts/sim

This change implements a [monte carlo simulation](https://en.wikipedia.org/wiki/Monte_Carlo_method) environment for s2n-quic.
Simulation plans are specified in a toml file:
```toml
[sim]
max_inflight = "1..1000"
connections = 100
iterations = 10000
stream_data = 100000
[report.duration]
filters = ["conn.success"]
x = "net.max_inflight"
y = "conn.duration"
[report.tx-packets]
filters = ["conn.success"]
x = "net.max_inflight"
y = "conn.tx.packets"
```
Plans can be executed with the `batch` command:
```
cd quic/s2n-quic-sim
cargo run --release -- batch ./path/to/plan.toml
```
`s2n-quic-sim` uses a [Monte Carlo method](https://en.wikipedia.org/wiki/Monte_Carlo_method) to explore the execution bounds of `s2n-quic`. From [Wikipedia](https://en.wikipedia.org/wiki/Monte_Carlo_method#Overview):
> …

feat(s2n-quic-sim): add simulation testing environment

---

quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
quic/s2n-quic-core/src/recovery/bbr.rs
quic/s2n-quic-core/src/recovery/bbr/congestion.rs
quic/s2n-quic-core/src/recovery/bbr/data_rate.rs
quic/s2n-quic-core/src/recovery/bbr/data_volume.rs
quic/s2n-quic-core/src/recovery/bbr/full_pipe.rs
quic/s2n-quic-core/src/recovery/bbr/round.rs
quic/s2n-quic-core/src/recovery/bbr/windowed_filter.rs

This change adds more compliance citations for the various components of BBRv2

 docs(s2n-quic-core): Add BBRv2 compliance citations

---

quic/s2n-quic/src/stream/receive.rs

resolves #1427
one line code change at:
quic/s2n-quic/src/stream/receive.rs#L360

fix receive_stream's tokio AsyncRead implementaion

---

quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

Version bump for 1.9.0 release

chore: release 1.9.0

---

quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

Version bump for 1.9.1 release

chore: release 1.9.1

---

quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
quic/s2n-quic-core/src/recovery/bbr/data_volume.rs
quic/s2n-quic-core/src/recovery/bbr/drain.rs
quic/s2n-quic-core/src/recovery/bbr/full_pipe.rs
quic/s2n-quic-core/src/recovery/bbr/pacing.rs
quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
quic/s2n-quic-core/src/recovery/bbr/probe_rtt.rs
quic/s2n-quic-core/src/recovery/bbr/round.rs
quic/s2n-quic-core/src/recovery/bbr/startup.rs
quic/s2n-quic-core/src/recovery/bbr/tests.rs
quic/s2n-quic-core/src/recovery/bbr/windowed_filter.rs
quic/s2n-quic-transport/src/recovery/manager.rs

This change increases unit test coverage of BBRv2
The change is the testing

test(s2n-quic-core): Add more BBRv2 unit tests

---

quic/s2n-quic-transport/src/recovery/manager.rs

The `on_slow_start_exited` event is recorded whenever the congestion controller changes from slow_start to !slow_start after packet loss, RTT update, ECN update, or Ack. There was one code path in the Ack processing that was missing this event, this change fixes that.

fix(s2n-quic-core): record on_slow_start_exited event for all acks

---

netbench/netbench-driver/Cargo.toml
quic/s2n-quic-core/src/buffer/receive_buffer.rs
quic/s2n-quic-core/src/buffer/receive_buffer/request.rs
quic/s2n-quic-core/src/buffer/receive_buffer/slot.rs
quic/s2n-quic-core/src/recovery/simulation.rs
quic/s2n-quic-core/src/transport/parameters/disabled_parameter.rs
quic/s2n-quic-crypto/src/ghash/testing.rs
quic/s2n-quic-crypto/src/ghash/x86/precomputed.rs
quic/s2n-quic-crypto/src/iv.rs
quic/s2n-quic-platform/src/features.rs
quic/s2n-quic-platform/src/socket/std.rs
quic/s2n-quic-sim/src/batch.rs
quic/s2n-quic-sim/src/run/range.rs
quic/s2n-quic-sim/src/stats.rs
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-tls/src/client.rs
quic/s2n-quic-tls/src/server.rs
quic/s2n-quic-transport/src/ack/ack_transmission_state.rs
quic/s2n-quic-transport/src/connection/local_id_registry.rs
quic/s2n-quic-transport/src/endpoint/version.rs
quic/s2n-quic-transport/src/interval_set/fuzz_target.rs
quic/s2n-quic-transport/src/interval_set/mod.rs
quic/s2n-quic-transport/src/stream/stream_container.rs
quic/s2n-quic-transport/src/sync/data_sender.rs

A new rust version means new clippy complaints. This change addresses the new lints.

fix: apply clippy fixes from stable and beta

---

quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

Doing the release; it's been a month since the last one!

chore: release 1.9.2

---

quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

Bumping version numbers for the 1.10.0 release

chore: release 1.10.0

---

scripts/local_test

chore: fix clippy warning for local_test script

---

quic/s2n-quic-core/src/event/generated.rs
quic/s2n-quic-core/src/recovery/bbr.rs
quic/s2n-quic-core/src/recovery/bbr/drain.rs
quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
quic/s2n-quic-core/src/recovery/bbr/probe_rtt.rs
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__drain__events__check_drain_done.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__drain__events__enter_drain.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__probe_bw__events__enter_probe_bw.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__probe_bw__events__is_time_to_probe_bw.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__probe_bw__events__start_cruise.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__probe_bw__events__start_down.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__probe_bw__events__start_refill.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__probe_bw__events__start_up.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__probe_rtt__events__check_probe_rtt_enter_probe_rtt.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__probe_rtt__events__check_probe_rtt_exit_probe_rtt.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__probe_rtt__events__exit_probe_rtt.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__startup__events__check_startup_done.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__startup__events__check_startup_done_filled_pipe_on_loss_round_start.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__startup__events__check_startup_done_filled_pipe_on_round_start.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__startup__events__enter_startup.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__tests__events__bound_cwnd_for_model.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__tests__events__handle_lost_packet.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__tests__events__is_probing_for_bandwidth.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__tests__events__pacing_cwnd_gain.snap
quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__tests__events__quantization_budget.snap
quic/s2n-quic-core/src/recovery/bbr/startup.rs
quic/s2n-quic-core/src/recovery/bbr/tests.rs
quic/s2n-quic-core/src/recovery/congestion_controller.rs
quic/s2n-quic-events/events/common.rs
quic/s2n-quic-events/events/connection.rs

This change will emit an event from BBR every time the State changes, including the CyclePhase within the ProbeBW state.
Snapshot tests

feat(s2n-quic-core): Add BBR state change event

---

quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

Bumping version numbers for the 1.11.0 release

 chore: release 1.11.0

---

.github/workflows/ci.yml
.github/workflows/netbench.yml
.github/workflows/qns.yml
.github/workflows/release.yml

replaces #1544, #1534, #1529, #1443
Manually merging the dependabot PRs for GHA updates.

ci: update GHA dependencies

---

common/s2n-codec/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-transport/Cargo.toml

This change updates bolero to 0.8. No API changes are required in our case.

test: update bolero to 0.8

---

netbench/netbench-driver/Cargo.toml
quic/s2n-quic-tls/Cargo.toml

This change updates s2n-tls to the latest version.

build(deps): update s2n-tls to 0.0.17

---

.github/workflows/ci.yml

N/A
Update Kani to its newest version.

ci: update Kani action version to v0.15

---

netbench/netbench-driver/Cargo.toml
quic/s2n-quic-tls/Cargo.toml

update s2n-tls to latest version

build(deps): update s2n-tls to 0.0.19

---

quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

chore: release 1.13.0

---

README.md
quic/s2n-quic/src/lib.rs

N/a
Fixes minor spelling issue in documentation.
N/a
N/a

docs: Fix spelling

---

quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

pending https://github.com/aws/s2n-quic/pull/1572
Technically we broke our API but as called out in the PR https://github.com/aws/s2n-quic/pull/1583 but its doubtful customers are using this yet.

chore: release 1.14.0

---

quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

chore: release 1.15.0

---

common/s2n-codec/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

None
Updates the s2n-quic version to 1.16.0.

chore: release 1.16.0

---

docs/SUMMARY.md
docs/dev-guide/kani.md

I had a couple of people ask how to get started with the kani proofs in the codebase. This change adds a basic "getting started" doc to help onboard.

docs: write a short getting started with kani

---

common/s2n-codec/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml

N/A
Release for s2n-quic. Note that I did a minor bump for s2n-quic crate since there was a feat commit in this [release](https://github.com/aws/s2n-quic/compare/v1.17.1...main)

chore: release v1.18.0

---

quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

N/A
Version bump for release. Minor patch bump since the change includes features.
N/A
N/A

chore: release version bump

---

netbench/netbench-driver/Cargo.toml
netbench/netbench-driver/src/bin/netbench-driver-native-tls-client.rs
netbench/netbench-driver/src/bin/netbench-driver-native-tls-server.rs
netbench/netbench-driver/src/bin/netbench-driver-s2n-quic-client.rs
netbench/netbench-driver/src/bin/netbench-driver-s2n-quic-server.rs
netbench/netbench-driver/src/bin/netbench-driver-s2n-tls-client.rs
netbench/netbench-driver/src/bin/netbench-driver-s2n-tls-server.rs
netbench/netbench-driver/src/lib.rs

This is helpful for perf testing against different tokio runtime types.

netbench: add multithread runtime option

---

.gitignore
quic/s2n-quic-core/src/stream/id.rs
scripts/perf/README.md

Typos added some new words to the dictionary and this PR fixes our new failures.

docs: fix typos

---

quic/s2n-quic-core/src/crypto/tls.rs
quic/s2n-quic-transport/src/space/initial.rs

In #996, we added the functionality to read ClientHello and ServerHello messages in the event provider. This functionality was added directly in the `Initial` space implementation itself, rather than delegating the parsing to the TLS provider.
This change, instead, adds a new trait method to do the actual parsing. This enables the TLS provider to override the parsing, if needed. It also cleans up the Initial space from doing any parsing of TLS messages.
I've added a bunch of new tests for this functionality, including some bolero/kani tests to check for any panic reachability.

refactor(s2n-quic-core): delegate hello message parsing to TLS session

---

common/s2n-codec/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

This bumps the crate versions for the v1.27.0 release.

chore: release 1.27.0

---

common/s2n-codec/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bumps for the 1.31.0 release.

chore: release 1.31.0

---

tools/memory-report/src/main.rs

We've had the `dhat` job failing for quite a while. Looking into it, the cause seems to be due to us raising buffer limits, which causes the receive buffer to allocate more at a time during the transfer.
In order to be less sensitive to settings, the fix here is to call `flush` on each chunk written to the stream. This should reduce the variability.
There was also a slight increase in the amount of memory consumed after closing the connection. It seems to be coming from the closing state for the connection, but it's not very large so I think we're fine to just increase it.
Tested this locally as well in CI.

ci: fix memory report test

---

README.md
common/s2n-codec/Cargo.toml
examples/rustls-mtls/rust-toolchain
examples/s2n-mtls/rust-toolchain
examples/turmoil-provider/rust-toolchain
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-events/Cargo.toml
quic/s2n-quic-h3/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-qns/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-sim/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/udp-attack/rust-toolchain
tools/xdp/rust-toolchain
tools/xdp/s2n-quic-xdp/Cargo.toml

We missed a couple of changes in #2104 so this change fixes that.

chore: additional msrv updates

---

.github/workflows/ci.yml

This change updates our nightly version to a recent build.
The existing tests should continue to pass

ci: update rust nightly version

---

common/s2n-codec/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

New release PR. More context in https://github.com/aws/s2n-quic/pull/2174 and https://github.com/aws/s2n-quic/pull/2176

chore: release 1.35.1

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bump for 1.37.0 release

chore: release 1.37.0

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bump for 1.38.0 release

chore: release 1.38.0

---

quic/s2n-quic-core/src/packet/number/sliding_window.rs
quic/s2n-quic-core/src/probe.rs
quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
quic/s2n-quic-core/src/recovery/bbr.rs
quic/s2n-quic-core/src/recovery/bbr/pacing.rs
quic/s2n-quic-core/src/stream/testing.rs
quic/s2n-quic-core/src/task.rs
quic/s2n-quic-core/src/task/waker.rs
quic/s2n-quic-core/src/varint/mod.rs

This change imports various features/fixes required for the latest s2n-quic-dc import.

feat(s2n-quic-core): various features for s2n-quic-dc

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bump for 1.39.0 release

chore: release 1.39.0

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bump for 1.40.0 release

chore: release 1.40.0

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bump for 1.42.0 release

chore: release 1.42.0

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bump for 1.43.0 release

chore: release 1.43.0

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Release new version 1.44.1. This is just a patch bump in all of the major versions to address the new s2n-tls dependency.
All CI should pass.

chore: release 1.44.1

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

This change bumps the version for this week's release.

chore: release 1.45.0

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-platform/src/message/cmsg/encode.rs
quic/s2n-quic-platform/src/message/cmsg/storage.rs
quic/s2n-quic-platform/src/message/msg/ext.rs
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

This change bumps the version for the latest release.

chore: release 1.46.0

---

dc/s2n-quic-dc/src/stream/recv.rs

feat(s2n-quic-dc): Make stream::recv::error::Kind pub

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

This releases 1.47.0 of s2n-quic.

chore: release 1.47.0

---

quic/s2n-quic/src/tests/deduplicate.rs
quic/s2n-quic/src/tests/recorder.rs

This is expected to not be particularly interesting, but a test likely makes sense anyway.
This is a test.

Test failure is not fatal for dedupe

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Bumps version for the 1.50.0 release.

chore: release 1.50.0

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bump for 1.51.0 release

chore: release 1.51.0

---

dc/s2n-quic-dc/src/path/secret/map/cleaner.rs

Giving threads names can make debugging a bit easier.

feat(s2n-quic-dc): name the path::secret::map::Cleaner thread

---

dc/s2n-quic-dc/src/path/secret/map/state.rs

n/a
This deduplicates the (send only) control socket amongst many same-process path secret maps, shrinking the port and file descriptor usage for that process. Primarily useful for testing (we don't expect real usage to have more than a few path secret maps), but reasonable regardless.
This does not leak the socket -- only live path secret maps hold a strong reference to the cache.
n/a
No tests added, though the code should be run in many of our tests (just incidentally). The global nature of the cache makes regular testing somewhat annoying, since we'd need to process-isolate the test most likely, and that doesn't seem worth the hassle for how simple this is.

feat(s2n-quic-dc): Globally cache the control socket

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bump for 1.52.0 release

chore: release 1.52.0

---

.github/ISSUE_TEMPLATE/s2n-quic-issue.md
docs/SUMMARY.md
docs/user-guide/debugging.md

Adds a [debugging guide](https://aws.github.io/s2n-quic/user-guide/debugging.html) for guidance on collecting information necessary for investigating issues.
resolves #2442 
Adds a debugging guide on collecting a trace log and packet capture necessary for investigating issues. Also updates the Issue template to link to this guide.
[Rendered](https://dnglbrstg7yg.cloudfront.net/1bc9b610ecc038e7c60005807c5ee9a58af51469/book/user-guide/debugging.html)

docs(s2n-quic): Add debugging guide

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bump for 1.52.1 release

chore: release 1.52.1

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

Version bump for the 1.53.0 release.

chore: release 1.53.0

---

examples/rustls-mtls/src/lib.rs
quic/s2n-quic-core/src/inet/ecn.rs
quic/s2n-quic-core/src/inet/ipv4.rs
quic/s2n-quic-core/src/inet/ipv6.rs
quic/s2n-quic-core/src/packet/long.rs
quic/s2n-quic-core/src/packet/stateless_reset.rs

ci: Fix Clippy

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

chore: release 1.55.0

---

.github/workflows/ci.yml
quic/s2n-quic-bench/Cargo.toml

N/A
Fixes parsing of MSRV. Previously we were testing with the newest toolchain, rather than our stated MSRV. Also includes a pin of the package 'half' which bumped their MSRV.
N/A
CI needs to pass.

ci: Fixes parsing of MSRV

---

dc/s2n-quic-dc/src/packet/tag.rs
dc/s2n-quic-dc/src/stream/recv/error.rs
quic/s2n-quic-core/src/inet/ethernet.rs
quic/s2n-quic-core/src/inet/ipv4.rs
quic/s2n-quic-core/src/inet/ipv6.rs
quic/s2n-quic-core/src/inet/udp.rs
quic/s2n-quic-core/src/packet/number/packet_number_range.rs
quic/s2n-quic-core/src/path/ecn.rs

Clippy started complaining about a bunch of new issues:
- https://github.com/aws/s2n-tls/actions/runs/14251165289/job/39944019785?pr=5242
- https://github.com/aws/s2n-quic/actions/runs/14271640021/job/40006018325#step:5:655
- https://github.com/aws/s2n-quic/actions/runs/14271848202/job/40006648392#step:5:659
This PR fixes the warnings.
Clippy should no longer error on this PR.

chore: Fix new clippy warnings

---

common/s2n-codec/Cargo.toml
dc/s2n-quic-dc/Cargo.toml
quic/s2n-quic-core/Cargo.toml
quic/s2n-quic-crypto/Cargo.toml
quic/s2n-quic-platform/Cargo.toml
quic/s2n-quic-rustls/Cargo.toml
quic/s2n-quic-tls-default/Cargo.toml
quic/s2n-quic-tls/Cargo.toml
quic/s2n-quic-transport/Cargo.toml
quic/s2n-quic/Cargo.toml
tools/xdp/s2n-quic-xdp/Cargo.toml

chore: release 1.57.0

---

dc/s2n-quic-dc/src/stream/send/flow/non_blocking.rs

This change fixes an issue with the stream flow error propagation mechanism. Before it was setting the wrong offset - should be `stream` instead of `flow. It was also using `fetch_and` instead of `fetch_or`, which resulted in the bit never being set :facepalm:.
I added a test showing that it now works after the fix.

fix(s2n-quic-dc): correctly propagate stream flow errors

---

tools/xdp/s2n-quic-xdp/src/ring.rs

resolves #2605
Fixes the violation of Rust's aliasing rules by using pointer `read/write` instead of references.
Staring with Rust version 1.80.0, `NonNull::read/write` can be used to remove the `as_ptr`.

fix(s2n-quic-xdp): fix aliasing violation in ring flags

---

dc/s2n-quic-dc/src/path/secret/map/state/tests.rs
dc/s2n-quic-dc/src/stream/client/rpc.rs
dc/s2n-quic-dc/src/stream/send/flow/blocking.rs
dc/s2n-quic-dc/src/stream/send/flow/non_blocking.rs
dc/s2n-quic-dc/src/task/waker/set.rs
quic/s2n-quic-core/src/buffer/reassembler/tests.rs
quic/s2n-quic-core/src/crypto/tls/null.rs
quic/s2n-quic-core/src/frame/crypto.rs
quic/s2n-quic-core/src/frame/stream.rs
quic/s2n-quic-core/src/packet/number/map.rs
quic/s2n-quic-core/src/packet/number/sliding_window.rs
quic/s2n-quic-core/src/path/mtu.rs
quic/s2n-quic-core/src/path/mtu/tests.rs
quic/s2n-quic-core/src/recovery/pacing/tests.rs
quic/s2n-quic-core/src/recovery/rtt_estimator.rs
quic/s2n-quic-core/src/sync/cursor.rs
quic/s2n-quic-platform/src/io/turmoil/tests.rs
quic/s2n-quic-qns/src/tls.rs
quic/s2n-quic-qns/src/xdp.rs
quic/s2n-quic-transport/src/dc/manager.rs
quic/s2n-quic-transport/src/path/manager/fuzz_target.rs
quic/s2n-quic-transport/src/path/manager/tests.rs
quic/s2n-quic-transport/src/stream/manager/tests.rs
quic/s2n-quic-transport/src/stream/send_stream/tests.rs
quic/s2n-quic-transport/src/stream/testing.rs
quic/s2n-quic-transport/src/sync/data_sender.rs
quic/s2n-quic/src/tests/deduplicate.rs
quic/s2n-quic/src/tests/issue_1717.rs

Fix failed Clippy test
CI should pass after this change

ci: fix clippy test

---

.github/workflows/ci.yml
examples/async-client-hello-callback/src/bin/quic_async_client_hello_callback_server.rs
examples/event-framework/src/lib.rs
examples/jumbo-frame/src/lib.rs
examples/post-quantum/src/bin/pq_server.rs
examples/rustls-mtls/src/lib.rs
examples/unreliable-datagram/src/bin/datagram_receiver.rs
examples/unreliable-datagram/src/bin/datagram_sender.rs
scripts/local_test

This PR removes some exceptions for Clippy lints that have either been improved to reduce false positives, or can be fixed in code.
Clippy passing in CI

ci: remove exceptions for clippy

---

.github/workflows/codebuild.yml

s2n-quic version of https://github.com/aws/s2n-tls/pull/5441

ci: document how to manually run the codebuild jobs

---

.github/workflows/ci.yml
.github/workflows/qns.yml

resolves #ISSUE-NUMBER1, resolves #ISSUE-NUMBER2, etc.

testing ci change

---

.github/interop/required.json

resolves #ISSUE-NUMBER1, resolves #ISSUE-NUMBER2, etc.

testing ci changes
