- .github/config/cargo-deny.toml
- .github/workflows/ci.yml
- Cargo.toml
- common/docdiff/Cargo.toml
- common/docdiff/src/main.rs
- common/duvet/Cargo.toml
- quic/s2n-quic/api.snap
- scripts/compliance
- scripts/docdiff
This change adds a `docdiff` tool to track public API changes with a `.snap` file. The tool generates the crate documentation with `cargo doc` and scrapes the HTML files for all of the exported structs, enums, traits, etc. and compares it against the `api.snap` file in the crate. This will ensure nothing in the public API changes without an explicit `cargo insta review`.
I tried getting semverver to work but it panicked in a few places and doesn't seem actively maintained (See #18)
> tools: add doc diff

- .github/workflows/qns.yml
- .github/workflows/release.yml
- quic/s2n-quic-qns/benchmark/docker-compose.yml
This change migrates publishing of the s2n-quic-qns image from GitHub container registry to Amazon Elastic Container Registry Public. I've also added a tags event to trigger the release workflow on so it is executed on tag pushes that match semver syntax.
> release: push s2n-quic-qns to Amazon Elastic Container Registry Public

- .github/workflows/qns.yml
The service quota for unauthenticated pull requests to Amazon ECR is 1 per second, which we occasionally exceed. This change we login to Amazon ECR prior to pulling so that the service quota of 10 per second is applied.
> ci: authenticate ECR pull

- quic/s2n-quic-core/src/recovery/pacing.rs
We currently pace out packets regardless of RTT. This can cause bandwidth limiting in networks where the RTT is low because it takes longer to put the connection to sleep and wake up than it does to send the packet now.
This change disables packet pacing for RTTs lower than 2ms.
> core: disable pacing when RTT is less than 2ms

- netbench/netbench/src/driver.rs
- netbench/netbench/src/multiplex.rs
- netbench/netbench/src/multiplex/stream.rs
- netbench/netbench/src/snapshots/netbench__multiplex__tests__checkpoint__client.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__checkpoint__server.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__low_max_streams__client.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__low_max_streams__server.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__low_stream_window__client.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__low_stream_window__server.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__multiple_streams__client.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__multiple_streams__server.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__single_slow_recv_stream__client.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__single_slow_recv_stream__server.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__single_slow_send_stream__client.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__single_slow_send_stream__server.snap
- netbench/netbench/src/snapshots/netbench__multiplex__tests__single_stream__server.snap
- netbench/netbench/src/timer.rs
After merging #1133, I found a bug with the testing timer expiration that only advances the timer if the client timer has a pending time. I've added a test to make sure it's working now. I've also cleaned up a few of the multiplexing closing logic.
> netbench: fix test timer expiration

- quic/s2n-quic-transport/src/connection/api.rs
- quic/s2n-quic-transport/src/connection/api_provider.rs
- quic/s2n-quic-transport/src/connection/connection_container.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/connection/mod.rs
- quic/s2n-quic-transport/src/connection/open_token.rs
- quic/s2n-quic-transport/src/stream/controller.rs
- quic/s2n-quic-transport/src/stream/stream_manager.rs
- quic/s2n-quic-transport/src/stream/tests/stream_managers_tests.rs
This change adds a `OpenToken` struct to the connection handle which allows the stream controller to track `poll_open_stream` requests.
I've added unit tests for the `OpenToken` behavior. I've also updated all of the stream manager tests to use the new API.
> transport: add OpenToken to track poll_open_stream requests

- netbench/netbench/Cargo.toml
- netbench/netbench/src/timer.rs
- netbench/netbench/src/timer/testing.rs
- netbench/netbench/src/timer/tokio.rs
- netbench/netbench/src/trace.rs
This change adds tokio support for the netbench driver `Timer` trait.
I added a unit test using tokio's time testing utils to validate that it works as intended.
> netbench: add tokio timer

- quic/s2n-quic-bench/Cargo.toml
- quic/s2n-quic-h3/Cargo.toml
- quic/s2n-quic-integration/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-ring/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
Based on https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility the current dependency matching results in:
`1.2.3` or `^1.2.3`  => `>=1.2.3`, `<2.0.0`
What we want instead is:
`=1.2.3` => `=1.2.3`
> release: use exact versions for all internal dependencies

- .github/workflows/ci.yml
- .github/workflows/netbench.yml
- netbench/netbench-driver/Cargo.toml
- netbench/netbench-driver/README.md
- netbench/netbench-driver/etc/Dockerfile
- netbench/netbench-driver/etc/docker-compose.yml
- netbench/netbench-driver/src/bin/netbench-driver-native-tls-client.rs
- netbench/netbench-driver/src/bin/netbench-driver-native-tls-server.rs
- netbench/netbench-driver/src/bin/netbench-driver-s2n-quic-client.rs
- netbench/netbench-driver/src/bin/netbench-driver-s2n-quic-server.rs
- netbench/netbench-driver/src/bin/netbench-driver-tcp-client.rs
- netbench/netbench-driver/src/bin/netbench-driver-tcp-server.rs
- netbench/netbench-driver/src/lib.rs
- netbench/netbench-scenarios/src/lib.rs
- netbench/netbench/src/client.rs
- netbench/netbench/src/client/thread.rs
- netbench/netbench/src/driver.rs
- netbench/netbench/src/lib.rs
- netbench/netbench/src/multiplex.rs
- netbench/netbench/src/operation.rs
- netbench/netbench/src/s2n_quic.rs
- netbench/netbench/src/scenario.rs
- netbench/netbench/src/scenario/builder/certificate.rs
- netbench/netbench/src/timer.rs
- netbench/netbench/src/trace.rs
- netbench/netbench/src/units/rate.rs
- quic/s2n-quic-core/src/time/timer.rs
This change adds netbench drivers for s2n-quic, [native-tls](https://docs.rs/tokio-native-tls/0.3.0/tokio_native_tls/index.html), and tcp. s2n-tls will be added after the async bindings are available.
I added a README on how to run one of the drivers locally. This will change after I get the CLI working, but should be enough to get an idea of how to run it.
> feat(netbench): add built-in drivers

- quic/s2n-quic-transport/src/stream/contract.rs
- quic/s2n-quic-transport/src/stream/receive_stream.rs
- quic/s2n-quic-transport/src/stream/send_stream.rs
- quic/s2n-quic-transport/src/stream/tests/receive_stream_tests.rs
- quic/s2n-quic-transport/src/sync/mod.rs
- quic/s2n-quic-transport/src/sync/once_sync.rs
When entering the STOP_SENDING state in the receive stream, we currently wait for the peer to either finish transmitting all outstanding data or send a RESET frame. This isn't really needed since the application has already indicated that it's not going to read any more data.
This change, instead, marks the stream as finalized when the STOP_SENDING frame is ACKed. Any additional frames that are received will be ignored:
https://github.com/aws/s2n-quic/blob/222a807564946e03900b1f2ea391c61d64995a69/quic/s2n-quic-transport/src/stream/stream_manager.rs#L807-L813
I've updated all of the receive stream unit tests to reflect the new behavior.
> fix(s2n-quic-transport): optimize STOP_SENDING state

- .github/config/cargo-deny.toml
- .github/interop/runner.patch
- .github/workflows/qns.yml
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-qns/etc/Dockerfile
- quic/s2n-quic-qns/etc/Dockerfile.build
- scripts/interop/run
This updates the quic-interop-runner to the latest ref. I've also updated the patch to only do a single round of throughput tests to cut down on the time spent in CI.
> ci(interop): update interop ref and patch

- quic/s2n-quic-bench/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-events/Cargo.toml
- quic/s2n-quic-h3/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-ring/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
This change updates the versions for all published crates that had changes or changed dependencies in preparation for the v1.0.1 release
I've also specified an exact version for the s2n-codec crate, and have removed the version from internal dev-dependencies.
> chore: update version for s2n-quic v1.0.1 release

- common/s2n-codec/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-ring/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
This change excludes fuzz test corpus files from the crates published to crates.io. I've also corrected the s2n-codec version to be an exact version.
> chore: exclude corpus files when publishing to crates.io

- .github/workflows/release.yml
The release workflow was failing due to the newline separating docker image tags being sanitized:
`Error: buildx failed with: error: invalid tag "public.ecr.aws/s2n/s2n-quic-qns:1.0.1\\npublic.ecr.aws/s2n/s2n-quic-qns:latest": invalid reference format`
This change uses a comma instead of the newline, which is also accepted according to https://github.com/docker/build-push-action#inputs
> ci: use comma for separating docker image tags

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/events/platform.rs
- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/io/tokio/clock.rs
- quic/s2n-quic/api.snap
- scripts/events
- scripts/perf/build
* Add a `application_wakeup` field to the event loop event struct
* Move the clock and timer functionality in the tokio integration to a separate module - it was getting a bit big and intertwined with the rest of the code
* Add a call to docdiff to update the `api.snap` file after generating/changing events
* Updates quinn to the latest commit - it's been broken for a bit after tokio updated to mio 0.8
> platform: refactor the clock/timer functionality

- .github/workflows/qns.yml
- quic/s2n-quic-core/src/crypto/tls/testing.rs
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-tls/src/callback.rs
- quic/s2n-quic-tls/src/client.rs
- quic/s2n-quic-tls/src/session.rs
- quic/s2n-quic-tls/src/tests.rs
s2n-tls has updated its key schedule to supply tls keys as soon as they are available. This now matches rustls behavior so we can undo workarounds for testing rustls vs s2n-tls.
Todo:
> feat(s2n-quic-tls): import key schedule fixes from s2n-tls

- .github/interop/required.json
- quic/s2n-quic-qns/src/server/h09.rs
According to the [HTTP 0.9 spec](https://www.w3.org/Protocols/HTTP/AsImplemented.html), we're supposed to ignore any trailing words on the request line.
> The document address will consist of a single word (ie no spaces). If any further words are found on the request line, they MUST either be ignored, or else treated according to the full HTTP spec.
> fix(s2n-quic-qns): ignore any additional words on request line

- quic/s2n-quic-qns/src/main.rs
- quic/s2n-quic-transport/src/connection/connection_id_mapper.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/local_id_registry.rs
- quic/s2n-quic-transport/src/connection/peer_id_registry.rs
- quic/s2n-quic-transport/src/connection/peer_id_registry/tests.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
This PR fixes s2n-quic for multi-thread usecases. 
This was previously missed since the tests(qns) only ran on single thread; so this also changes s2n_quic_qns to run in multi-threaded mode so that CI is now verifying the multi-threaded behavior (single thread is a sub-set of multi-thread).
> fix(s2n-quic-transport): add multi-thread support

- quic/s2n-quic-core/src/path/mod.rs
- quic/s2n-quic-core/src/recovery/mod.rs
- quic/s2n-quic-core/src/recovery/sent_packets.rs
- quic/s2n-quic-core/src/recovery/snapshots/s2n_quic_core__recovery__sent_packets__test__sent_packet_info_size_test.snap
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/manager/fuzz_target.rs
- quic/s2n-quic-transport/src/path/manager/tests.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/recovery/mod.rs
- quic/s2n-quic-transport/src/recovery/snapshots/s2n_quic_transport__recovery__sent_packets__test__sent_packet_info_size_test.snap
In anticipation of potentially adding `SentPacketInfo` to the public API (either through the CongestionController trait or the Bandwidth Estimator or both), this change moves `SentPacketInfo` and `SentPackets` to `s2n-quic-core` and makes `SentPacketInfo` non-exhaustive.  This also required moving `path::Id`.
> refactor(s2n-quic-core): move SentPackets, SentPacketInfo, and path::Id to core

- quic/s2n-quic-core/src/crypto/tls.rs
- quic/s2n-quic-core/src/crypto/tls/testing.rs
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-rustls/src/client.rs
- quic/s2n-quic-rustls/src/server.rs
- quic/s2n-quic-rustls/src/session.rs
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-tls/src/callback.rs
- quic/s2n-quic-tls/src/client.rs
- quic/s2n-quic-tls/src/server.rs
- quic/s2n-quic-tls/src/session.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic-transport/src/space/session_context.rs
- specs/www.rfc-editor.org/rfc/rfc7301.txt
Currently s2n-quic emits the `on_server_name_information` event after it receives and installs the 1-rtt keys (and does a bunch of validation). This means that its possible to abort the handshake if any of the validation fails and not emit the server_name event.
This makes it difficult for servers to debug which clients(server_name) is experiencing failures.
This PR moves the `on_server_name_information` event to right after the server_name is parsed which solves the issue above.
Similarly this PR also emits the `application_protocol` and the associated event earlier.
Existing test which complete the handshake should still pass. There is an inline assert which confirms that `on_server_name` happens prior to 1-rtt keys.
Is this a refactor change? If so, how have you proved that the …
> feat(s2n-quic-tls, s2n-quic-rustls): emit server_name and application_protocol events sooner in the handshake

- quic/s2n-quic-transport/src/connection/connection_container.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/space/mod.rs
This change adds some consistency checks to connection nodes in the connection container. These checks will ensure connections are continually making progress through interests.
Since these are internal consistency checks, the existing tests should cover most cases. I'm working on adding fuzzing through netbench in another branch and this will help cover the remaining failure scenarios.
> fix(s2n-quic-transport): add consistency checks to connection nodes

- quic/s2n-quic-core/src/crypto/tls/testing.rs
- quic/s2n-quic-qns/src/server/unstable.rs
- quic/s2n-quic-rustls/src/lib.rs
- quic/s2n-quic-tls/src/server.rs
- quic/s2n-quic-tls/src/tests.rs
This PR adds support for client_hello callback when using the s2n-tls provider. This mechanism allows for executing some async code when the server processes the client hello (load cert based on server name).
Note the feature is added behind the `unstable` flag since the s2n-tls apis have not yet been stabilized.
- I have added **unit tests** to test the callback behavior.
- qns currently uses the client_hello callback (behind the unstable flag) but it doesnt do anything very interesting at the moment (returns Ready on first call) and also we dont have it enabled by default in our CI. *I dont want to turn it on(atleast with a [sleep future](https://docs.rs/tokio/latest/tokio/time/fn.sleep.html)) since it will affect perf and other benchmarks). This is also something we can address in the …
> feat(s2n-quic-tls): enable support for async client hello callback

- quic/s2n-quic-tls/Cargo.toml
s2n-tls 0.0.5 has been published and needs to be updated to the latest version.
> build(deps): update s2n-tls requirement from 0.0.4 to 0.0.5

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
This bumps all of the versions of the changed crates, including the `s2n-quic` crate to 1.0.2.
> chore: release s2n-quic 1.0.2

- scripts/perf/test
The `ultraman` `--no-timestamp` argument changed to take a bool, which causes our perf script to fail. This change updates the usage to the latest interface.
> ci: fix perf script

- netbench/netbench-driver/README.md
None
Adds a note for mac users to set the local IP of the netbench client driver to 0.0.0.0 in order to connect properly.
None
Documentation change.
> docs(netbench): add driver instructions for mac

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/path/migration.rs
- quic/s2n-quic-core/src/path/mod.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic/api.snap
- quic/s2n-quic/src/provider/endpoint_limits.rs
- specs/tools.ietf.org/id/draft-ietf-quic-applicability-16.txt
From [this code](https://quiche.googlesource.com/quiche/+/bac04054bccb2a249d4705ecc94a646404d41c1b/quiche/quic/core/quic_dispatcher.cc#498) in Google Quiche:
> These UDP source ports have been observed in large scale denial of service attacks and are not expected to ever carry user traffic, they are therefore blocked as a safety measure
I've blocked these ports as part of the default Endpoint Limiter, as well as the default Path Migration Validator. 
Iteration was used instead of a HashSet as the performance of iteration with <=15 items was shown to be better than HashMap lookups: https://gist.github.com/daboross/976978d8200caf86e02acb6805961195. With the addition of an early return for most port numbers, I believe iteration is better and it also avoids adding a dependency on lazy_static …
> feat: block restricted ports

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/transport/parameters/mod.rs
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__snapshot_tests__ClientTransportParameters__default.snap
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__snapshot_tests__ServerTransportParameters__default.snap
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__snapshot_tests__client_snapshot_test.snap
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__snapshot_tests__server_snapshot_test.snap
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic/api.snap
part of  #1253
Defines the max_datagram_frame_size transport parameter. Note that currently we do not send this transport parameter because it is set to the default value of 0. When we do want to allow people to recv datagrams we will switch to sending the recommended datagram size.
Also added this parameter to our ZeroRttParameters struct as it can be used to send 0-RTT datagrams. Not sure if we are going to need that functionality though. 
Basically nothing changes here since we don't send the default transport parameters.
> Defines unreliable datagram transport parameter

- .github/workflows/ci.yml
- .github/workflows/netbench.yml
- .github/workflows/qns.yml
In #1181 we added gating of authenticated steps to the GitHub actions CI workflows, since pull requests from forked repositories do not have access to the credentials needed for these steps. Because the repository was private at the time, this could not be tested. This change fixes the gating to properly prevent authenticated steps from running on pull requests from forked repositories.
This PR is the test (it is from a forked repository)
> ci: fix gating of authenticated steps

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/frame/ack_elicitation.rs
- quic/s2n-quic-core/src/frame/congestion_controlled.rs
- quic/s2n-quic-core/src/frame/crypto.rs
- quic/s2n-quic-core/src/frame/datagram.rs
- quic/s2n-quic-core/src/frame/mod.rs
- quic/s2n-quic-core/src/frame/path_validation.rs
- quic/s2n-quic-core/src/frame/snapshots/s2n_quic_core__frame__snapshots__datagram.snap
- quic/s2n-quic-core/src/frame/test_samples/datagram.bin
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic/api.snap
Related to #1253 
Defines the datagram frame to be ack-eliciting and congestion controlled. Since we are not sending the datagram transport parameter we don't have to worry about receiving datagram frames before we're ready to process them.
Wasn't exactly sure how this should be tested. There is a try_fit test that I added from the Stream and Crypto frames tests.
> feat(s2n-quic-core): add DATAGRAM frame

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/packet/interceptor.rs
- quic/s2n-quic-core/src/packet/mod.rs
- quic/s2n-quic-events/src/main.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/endpoint/config.rs
- quic/s2n-quic-transport/src/endpoint/initial.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic-transport/src/transmission/mod.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/client/builder.rs
- quic/s2n-quic/src/client/providers.rs
- quic/s2n-quic/src/provider.rs
- quic/s2n-quic/src/provider/packet_interceptor.rs
- quic/s2n-quic/src/server/builder.rs
- quic/s2n-quic/src/server/providers.rs
This change adds a packet interceptor provider which allows an application to intercept each transmitted and received packet before it's encrypted and processed, respectively. This allows for a few interesting applications:
* turn s2n-quic into a general-purpose, online, QUIC fuzzer.
* rewriting a packet in a semantic-preserving way and ensuring s2n-quic correctly processes it (i.e. metamorphic testing).
* testing s2n-quic itself in an offline, non-real time setting
> feat(s2n-quic): implement unstable packet interceptor provider

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/windowed_filter.rs
This change introduces a data structure for tracking the minimum or maximum value seen over a configurable time period. This will be used in BBRv2 for tracking minimum RTT, maximum bandwidth, and maximum extra ACKed data. 
The `TimeType` is generic as minimum RTT will use `Timestamp`, while bandwidth and extra ACKed use a virtual time measured as number of Rounds or probe Cycles.
Maximum bandwidth in BBRv2 is tracked for just 2 values of "CycleCount", so the RFC mentions "CycleCount" can be tracked with just 1 bit. I would probably just end up using a `u8` for this, but that `u8` would need to be using `core::num::Wrapping` so the subtraction performed in the `update` method does not overflow. I wasn't sure there was a better way to handle this.
I also did not want the raw …
> feat(s2n-quic-core): windowed filter

- quic/s2n-quic-core/src/datagram.rs
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-transport/src/endpoint/config.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/client/providers.rs
- quic/s2n-quic/src/provider.rs
- quic/s2n-quic/src/provider/datagram.rs
- quic/s2n-quic/src/server/providers.rs
related to #1253 
Adding the skeleton of a datagram provider. This is a pretty minimal PR. I am not defining the Sender and Receiver traits, as I just wanted to make sure I'm creating the provider correctly. 
I'm not sure if this is the cleanest way of implementing the Disabled DatagramEndpoint. Lmk if there's a better way.
> feat(s2n-quic): Define the datagram provider

- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-platform/src/io.rs
- quic/s2n-quic-platform/src/io/select.rs
- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/io/testing/model.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
- quic/s2n-quic-platform/src/io/testing/snapshots/s2n_quic_platform__io__testing__network__tests__address_generator.snap
- quic/s2n-quic-platform/src/io/testing/time.rs
- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/lib.rs
- quic/s2n-quic/src/provider/event/mod.rs
- quic/s2n-quic/src/provider/io.rs
- quic/s2n-quic/src/provider/io/testing.rs
- quic/s2n-quic/src/tests.rs
This change wires up s2n-quic to my [discrete event simulator](https://en.wikipedia.org/wiki/Discrete-event_simulation) framework, [bach](https://docs.rs/bach), which is an async rust runtime that it executes in hyper-real time by looking at the scheduler and fast-forwarding on to the next event. its execution is completely determined by the initial seed of the executor so it's really easy to reproduce results.
One thing I'm excited about is running [monte carlo](https://en.wikipedia.org/wiki/Monte_Carlo_method) simulations, for example, with network loss rates and get an idea of connection failure rates. It should be really interesting to explore this more and get an idea of the boundaries of failure modes:
```rust
#[test]
fn loss_test() {
let model = Model::default(); …
```
> feat(s2n-quic-platform): add testing io implementation

- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic-transport/src/space/rx_packet_numbers/ack_manager.rs
- quic/s2n-quic-transport/src/space/rx_packet_numbers/tests/endpoint.rs
- quic/s2n-quic-transport/src/space/tx_packet_numbers.rs
This PR changes function signatures to take `Timestamp` instead of `DatagramInfo`.
Some functions in recovery manager take `DatagramInfo` but only use the `Timestamp` field. Since the delayed ack optimization is planning to store ack information and process it later, it would be nice to only store the timestamp rather than the entire datagram info.
> refactor(s2n-quic-transport): change fn signature to take timestamp

- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-tls/src/client.rs
- quic/s2n-quic-tls/src/lib.rs
- quic/s2n-quic-tls/src/server.rs
- quic/s2n-quic-tls/src/session.rs
s2n-tls has published version 0.0.7, which included some breaking changes. This PR updates to the latest version.
As part of the update, I've made it possible to enable post-quantum key shares through an unstable `cfg` flag.
> fix(s2n-quic-tls): update to latest s2n-tls 0.0.7

- netbench/netbench-driver/src/bin/netbench-driver-native-tls-client.rs
- netbench/netbench-driver/src/bin/netbench-driver-native-tls-server.rs
- netbench/netbench-driver/src/bin/netbench-driver-tcp-client.rs
- netbench/netbench-driver/src/bin/netbench-driver-tcp-server.rs
- netbench/netbench-driver/src/lib.rs
- netbench/netbench/src/multiplex.rs
This change adds the ability to buffer IO on native-tls and TCP sockets. This allows the buffer sizes to be taken into account when running tests for each of the drivers.
> feat(netbench): add io buffering to native-tls and tcp

- quic/s2n-quic-transport/src/stream/receive_stream.rs
- quic/s2n-quic-transport/src/stream/send_stream.rs
- quic/s2n-quic-transport/src/stream/tests/receive_stream_tests.rs
In #1119, the functionality was added to flush streams when the connection was dropped. The change, however, was missing a check for when there isn't a waker associated with the stream. In this case it should consider the stream finalized. It currently does not and causes the connection to wait until the idle timer expires.
I updated the stream tests to reflect the new behavior.
> fix(s2n-quic-transport): mark streams in final state without wakers

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
This bumps the versions of all changed crates based on semver.
> chore: release s2n-quic 1.1.1

- quic/s2n-quic-core/src/datagram.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/connection/mod.rs
- quic/s2n-quic-transport/src/endpoint/initial.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/datagram.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic-transport/src/space/session_context.rs
- quic/s2n-quic-transport/src/stream/stream_container.rs
- quic/s2n-quic-transport/src/stream/stream_manager.rs
- quic/s2n-quic-transport/src/transmission/application.rs
related to #1253 
Creates the backend logic around calling customer callbacks to send unreliable datagrams.
This PR ended up being larger than I intended, primarily because of all the places I had to feed the datagram provider into in order to call the callback in the correct location. Because of this, I did _not_ include the logic to switch between sending datagrams versus sending control data or adding the transmission_interest function to the sender callback. I want that to be in a separate PR, unless someone says otherwise.
Also this PR includes code customers would use to write datagrams to the wire, I can break that logic into a separate PR it's currently too much to review.
By …
> feat(s2n-quic-transport): Datagram Sender Trait

- quic/s2n-quic-core/src/havoc.rs
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-core/src/packet/interceptor.rs
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/io/testing/model.rs
There's a few places we want to havoc a slice of bytes. This change adds a `havoc` module in s2n-quic-core to make this easy to do. I've adapted the IO testing model to utilize the new functionality:
```rust
let new_len = havoc::Truncate
.randomly()
.and_then(havoc::Swap.repeat(0..packet.payload.len()).randomly())
.and_then(havoc::Mutate.repeat(0..packet.payload.len()).randomly())
.havoc_slice(&mut super::rand::Havoc, &mut packet.payload);
```
I've added fuzz tests for each one of the strategies to make sure they don't panic or spin forever.
> feat(s2n-quic-core): add havoc utilities

- quic/s2n-quic-transport/src/ack/interest.rs
- quic/s2n-quic-transport/src/ack/mod.rs
- quic/s2n-quic-transport/src/ack/pending_ack_ranges.rs
- quic/s2n-quic-transport/src/connection/connection_container.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/mod.rs
This PR paves the path for delayed ACK processing. NOTE: delayed ack processing is still not enabled. 
- store `pending_ack_ranges: PendingAckRanges` on space::Application
- indicate interest if there are pending ACKs for the connection
- introduce fn in space/application for `update_pending_acks` and `on_process_pending_acks` which can be used for delayed ack processing
- refactor recovery/manger interface to take `impl Iterator<Item = RangeInclusive<PacketNumber>>`
- The next and last task remaining for feature complete is to selectively store ACKs for delayed processing rather than processing immediately
refactor change
> feat(s2n-quic-transport): allow connections to store aggregate ack info and indicate ack interest

- quic/s2n-quic-core/src/io/tx.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
- quic/s2n-quic-platform/src/message/mmsg.rs
- quic/s2n-quic-platform/src/message/msg.rs
- quic/s2n-quic-platform/src/message/queue/slice.rs
- quic/s2n-quic-platform/src/message/simple.rs
- quic/s2n-quic-transport/src/connection/close_sender.rs
- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/endpoint/retry.rs
- quic/s2n-quic-transport/src/endpoint/stateless_reset.rs
- quic/s2n-quic-transport/src/endpoint/version.rs
When determining if a packet can be included as a GSO segment, we currently just consider the type of packet in this decision. This information can be limiting and artificially limit packet buffer sizes.
This change passes the current GSO segment size to the `can_gso` function, which allows the sender component to now take the segment len into account.
I've also cleaned up the packet writing interface to reduce duplication of logic.
> fix(s2n-quic-transport): determine GSO capability from the segment_len

- quic/s2n-quic-core/src/endpoint/limits.rs
- quic/s2n-quic-core/src/event.rs
- quic/s2n-quic-core/src/path/mod.rs
- quic/s2n-quic-core/src/time/mod.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic/api.snap
- quic/s2n-quic/src/provider/endpoint_limits.rs
resolves #1259 
* Start to throttle some ports that are vulnerable to a reflection
attack.
* Added a basic rate limiting implementation to perform throttling.
I did not test this end to end, only in unit tests.
Ran unit tests on this code. Will try to set up an end to end test.
> feat: port throttling

- quic/s2n-quic-core/src/datagram.rs
- quic/s2n-quic-core/src/frame/datagram.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/datagram.rs
- quic/s2n-quic-transport/src/space/session_context.rs
- quic/s2n-quic-transport/src/stream/stream_container.rs
- quic/s2n-quic-transport/src/stream/stream_manager.rs
- quic/s2n-quic-transport/src/transmission/application.rs
related to #1253 
Adds the extra functionality that didn't make it into #1289. Also applies the extra feedback that didn't make it into that PR.
Currently this function doesn't contain the functionality to alternate between writing datagrams and writing control data. 
I added a test to show that the datagram sender will refuse to write datagrams that don't fit in the packet.
> feat(s2n-quic-transport): Adds transmission interest to Datagram Sender

- common/docdiff/src/main.rs
- quic/s2n-quic/src/client/builder.rs
- quic/s2n-quic/src/lib.rs
- quic/s2n-quic/src/provider.rs
- quic/s2n-quic/src/provider/io.rs
- quic/s2n-quic/src/server/builder.rs
Currently, unstable features check that `s2n_quic_unstable` is set in addition to the feature flag itself. This isn't entirely correct, since there are other flags that can be passed to enable unstable features (such as `s2n_internal_dev`).
This change simplifies the unstable feature flags to just query if the feature is set or not. I've also changed docdiff to pass a `cfg` so we can filter out the unstable features from being snapshotted.
> fix(s2n-quic): simplify unstable feature flags

- quic/s2n-quic-core/src/datagram.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/datagram.rs
- quic/s2n-quic-transport/src/space/mod.rs
related to #1253 
Small PR to add the receiver side to the datagram trait. I thought about just appending it to the last sender PR I did, but I'm trying to keep these issues separate.
I think this is it? We just give the datagram to the user each time we encounter a Datagram frame in the application space.
> feat(s2n-quic-transport): Adds Receiver trait for Datagram Provider

- quic/s2n-quic-core/src/io/tx.rs
- quic/s2n-quic-core/src/recovery/congestion_controller.rs
- quic/s2n-quic-platform/src/message/queue/slice.rs
- quic/s2n-quic-transport/src/connection/close_sender.rs
- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/endpoint/retry.rs
- quic/s2n-quic-transport/src/endpoint/stateless_reset.rs
- quic/s2n-quic-transport/src/endpoint/version.rs
From the BBR Congestion Control RFC §4.6.3:
> In order to amortize per-packet overheads involved in the sending process (host CPU, NIC processing, and interrupt processing delays), high-performance transport sender implementations (e.g., Linux TCP) often schedule an aggregate containing multiple packets (multiple SMSS) worth of data as a single quantum (using TSO, GSO, or other offload mechanisms). The BBR congestion control algorithm makes this control decision explicitly, dynamically calculating a quantum control parameter that specifies the maximum size of these transmission aggregates.
This change adds `send_quantum` to the `CongestionController` trait to allow congestion controllers like BBRv2 to influence the amount of data aggregated by GSO. 
By submitting this pull request, I …
> feat: add send quantum to congestion controller trait

- .github/workflows/ci.yml
- examples/post-quantum/.cargo/config.toml
- examples/post-quantum/Cargo.toml
- examples/post-quantum/README.md
- examples/post-quantum/src/bin/pq_client.rs
- examples/post-quantum/src/bin/pq_server.rs
In #1283, we added support for building s2n-quic with support for post-quantum key shares. This PR adds an example of how to enable this functionality in an application, along with a short README about what the example is doing.
> example(post-quantum): initial commit

- netbench/netbench-cli/src/report.rs
- netbench/netbench-collector/src/bpftrace.rs
- netbench/netbench-collector/src/netbench.bt
- netbench/netbench-scenarios/src/request_response.rs
- netbench/netbench/src/scenario/builder.rs
- netbench/netbench/src/scenario/builder/connection.rs
- netbench/netbench/src/stats.rs
When writing a nebench scenario, establishing multiple connections with the exact same operations will result in multiple connection entries. This needlessly bloats the scenario JSON.
This change implements a check to compare the connection instructions to existing instructions and returns that ID instead of creating a new one.
> feat(netbench): dedupe connection operations

- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/io/testing/model.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
- quic/s2n-quic/src/tests.rs
Previously, the testing IO provider relied on drop to close the executor and clean up the pending tasks. This caused a problem in which all of the outstanding connections technically failed and weren't able to send a CONNECTION_CLOSE and successfully complete.
This change adds a `close` function and calls it at the end of a test.
> feat(s2n-quic-platform): add close capability for testing io

- quic/s2n-quic-core/src/event.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/packet/number/packet_number.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-events/events/connection.rs
- quic/s2n-quic-transport/src/ack/ack_manager.rs
- quic/s2n-quic-transport/src/ack/ack_ranges.rs
- quic/s2n-quic-transport/src/ack/pending_ack_ranges.rs
- quic/s2n-quic-transport/src/ack/snapshots/quic__s2n-quic-transport__src__ack__ack_manager__events__activate.snap
- quic/s2n-quic-transport/src/ack/snapshots/quic__s2n-quic-transport__src__ack__ack_manager__events__ecn_counts.snap
- quic/s2n-quic-transport/src/ack/tests/endpoint.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic/api.snap
This PR exposes specific error information from `AckRanges` and publishes them as events.
There are a few actions(commented out currently) which will be added in the future. But that is pending delayed ACK PR https://github.com/aws/s2n-quic/pull/1298
> feat(s2n-quic): add on_ack_processed events

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/congestion_controller.rs
- quic/s2n-quic-core/src/recovery/cubic.rs
- quic/s2n-quic-core/src/recovery/cubic/tests.rs
- quic/s2n-quic-core/tests/recovery/simulation.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/path/mod.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/space/mod.rs
- scripts/recovery-sim
Some congestion controllers (such as BBRv2) may wish to incorporate randomness into their algorithm to allow for better mixing and fairness with other flows. This change wires the `random::Generator` through to the `on_ack` and `on_packets_lost` methods in the Congestion Controller.
I originally added the `random::Generator` to the `RecoveryContext`, but this had two issues:
* `CongestionController::on_packet_sent` uses the `RecoveryContext`, so either I would have to stop it from using the `RecoveryContext` or wire the `random::Generator` through all the transmission code for no reason. 
* There are several places in the `recovery::Manager` where the `RecoveryContext` is mutably borrowed so that the congestion controller can be updated. When I added the `random::Generator` to the …
> feat: Add RandomGenerator to Congestion Controller

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/congestion.rs
- quic/s2n-quic-core/src/recovery/bbr/data_rate.rs
- quic/s2n-quic-core/src/recovery/bbr/data_volume.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
Implementation of the `ProbeBW` state machine and related methods described in the [BBRv2 draft RFC §4.3.3 ](https://www.ietf.org/archive/id/draft-cardwell-iccrg-bbr-congestion-control-02.html#name-probebw)
- There's a bit of a discrepancy between the type of `inflight_hi` (currently u64) and `bytes_in_flight`/`cwnd` (u32). I started trying to change `inflight_hi` but it was triggering too many changes for this PR, so I'll have to revisit that.
- The `update_upper_bound` methods in the `data_volume::Model` and `data_rate::Model` previously would not allow the bounds to be lowered, so I've fix them. I also noticed that the `bw_hi` value is never lowered from `Infinity` in the BBRv2 draft RFC, which would cause the `BBRAdaptUpperBounds` method specified in …
> feat(s2n-quic-core): BBRv2 bandwidth probing

- quic/s2n-quic-core/src/inet/ecn.rs
resolves #1322
The most-significant 6 bits of the 8-bit traffic class field ECN markings are read from are used for the differentiated services code point. Previously we were debug asserting these bits were always 0. This was too strict, as it is valid to set these bits, so this change removes the debug assertion.
Updated unit tests
> fix(s2n-quic-core): Allow for DSCP markings in the IP header

- quic/s2n-quic-core/src/frame/ack.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/space/mod.rs
This PR consolidates the `on_ack_frame` and `on_pending_ack_ranges` api into a single `process_acks` api.
refactor
> refactor(s2n-quic-transport): consolidate recovery manager interface

- netbench/netbench/src/duplex.rs
- netbench/netbench/src/lib.rs
None
Currently, Netbench has one implementation for the [Connection](https://github.com/aws/s2n-quic/blob/main/netbench/netbench/src/connection.rs) trait: [Multiplex](https://github.com/aws/s2n-quic/blob/main/netbench/netbench/src/multiplex.rs). This PR implements an additional connection, Duplex, which can be used for configurations with single streams. This connection reduces some of the performance overhead introduced in the implementation for application-level multiplexing.
The change to drivers to enable this mode will be made in a separate PR.
> feat(netbench): Duplex connection mode

- common/docdiff/src/main.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/events/platform.rs
- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic/api.snap
Currently, we have no way of tracking how much time s2n-quic spends in a single event loop iteration. This change adds a `PlatformEventLoopSleep` which can be used to do just that.
> feat(s2n-quic-core): add platform event loop sleep event

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-events/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
Reverts aws/s2n-quic#1334
Postponing the s2n-quic release until https://github.com/aws/s2n-quic/pull/1333 is merged.
> Revert "chore(s2n-quic): release 1.4.0"

- quic/s2n-quic-core/src/counter.rs
- quic/s2n-quic-transport/src/stream/stream_manager.rs
- quic/s2n-quic-transport/src/stream/tests/stream_managers_tests.rs
- quic/s2n-quic-transport/src/sync/periodic_sync.rs
The current `DATA_BLOCKED`, `STREAM_DATA_BLOCKED`, `STREAMS_BLOCKED` frames are sent 1 smoothed RTT before the idle timer expires. In testing, however, I've found this to be suboptimal and I don't think actually in line with the purpose of these frames. From [RFC9000 Section 4.1](https://www.rfc-editor.org/rfc/rfc9000#section-4.1):
> To keep the connection from closing, a sender that is flow control limited SHOULD periodically send a STREAM_DATA_BLOCKED or DATA_BLOCKED frame when it has no ack-eliciting packets in flight.
Since we likely don't have any bytes in flight when we're blocked by flow control, these frames are intended to act as a replacement for PTO, which only is armed when there are bytes in flight. This is important for when there's high loss on the connection and we may not …
> fix(s2n-quic-transport): make periodic sync more frequent

- quic/s2n-quic-transport/src/ack/ack_manager.rs
- quic/s2n-quic-transport/src/ack/ack_transmission_state.rs
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_transmission_state__tests__should_transmit.snap
Currently, when we send probes the ACK manager will only transmit an ACK frame when it is in Active or Passive mode. This is suboptimal as we miss out on transmitting an ACK, which would allow the peer to recover more quickly from its own loss.
This change, instead looks at the transmission mode and, if it's a probe, will bundle an ACK frame with the packet. In testing, this showed to improve connection resiliency.
I've updated the ACK transmission state tests with a snapshot of all of the possible inputs and outputs for `should_transmit`. This should prevent a regression in this change.
> fix(s2n-quic-transport): bundle ACK frames with probes

- common/s2n-codec/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/slice.rs
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
This change updates to the latest bolero, which includes support for running harnesses as kani proofs. I've refactored the vectored copy test to be more friendly to kani as a demonstration of it working.
Depends on #1337 
> build(deps): update bolero to 0.7.0

- quic/s2n-quic-transport/src/path/mtu.rs
This reverts commit 88aa6a28468fff90b84d7e3b8f9dccbf3918dcd3.
When deploying to test servers, we noticed a significant loss in throughput from this change. We will need to investigate further into why that is happening.
> Revert "fix(s2n-quic-transport): Unmap peer address when determining MTU probe size (#1321)"

- .github/config/cargo-deny.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-crypto/src/aes/testing/rust_crypto.rs
Updating the dev-dependencies for s2n-quic-crypto.
> build(s2n-quic-crypto): update to the latest rust-crypto crates

- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-tls/src/client.rs
- quic/s2n-quic-tls/src/server.rs
- quic/s2n-quic-tls/src/session.rs
Updates the s2n-tls dependency to the latest version.
> build(s2n-quic-tls): update s2n-tls dependency to 0.0.8

- .github/workflows/netbench.yml
- netbench/netbench-driver/Cargo.toml
- netbench/netbench-driver/src/bin/netbench-driver-s2n-tls-client.rs
- netbench/netbench-driver/src/bin/netbench-driver-s2n-tls-server.rs
None
Adds a client/server netbench driver implementation for s2n-tls.
Requires a change made in https://github.com/aws/s2n-tls/pull/3299 to build, so the s2n-tls crate version was preemptively set to 0.0.8: ed25c915d5b14b120f43a5f2e302c8794e8ea0ee
> feat(netbench): s2n-tls netbench driver

- quic/s2n-quic-platform/src/io/tokio.rs
This change will always set the "don't fragment" flag for the IPv4 protocol, which is necessary for Path MTU probing to work correctly. Previously, if the tx address was an IPv4 mapped IPv6 address, only the setting for IPv6 would be set, which may not work on some systems. 
Tested locally
> fix(s2n-quic-platform): set don't fragment flag for IPv4 mapped IPv6 tx addresses

- quic/s2n-quic-core/src/recovery/sent_packets.rs
- quic/s2n-quic-core/src/transmission/mode.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/persistent_congestion.rs
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__persistent_congestion_mtu_probe.snap
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
Previously we determined if a lost packet was an MTU probe if its sent bytes was greater than the current MTU. Since the MTU can decrease as part of the lost packet processing (due to a detected blackhole), this can cause some packets that were not actually MTU probes to be considered MTU probes as part of the OnPacketLost event. This change adds `transmission::Mode` to `SentPacketInfo` so we can explicitly track if a sent packet was an MTU probe. I've also used this information in the persistent congestion calculator to prevent MTU probes from being considered part of a persistent congestion period.
Existing tests and added a new test
> fix: explicitly track MTU probes

- quic/s2n-quic-core/src/stream/ops.rs
- quic/s2n-quic-transport/src/stream/api.rs
- quic/s2n-quic-transport/src/stream/receive_stream.rs
- quic/s2n-quic-transport/src/stream/send_stream.rs
- quic/s2n-quic-transport/src/stream/stream_container.rs
- quic/s2n-quic-transport/src/stream/tests/receive_stream_tests.rs
- quic/s2n-quic-transport/src/stream/tests/send_stream_tests.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/setup.rs
This change fixes a couple of issues with streams in terminal state:
On drop, we now detach the application from the stream, to notify the s2n-quic endpoint that the stream is no longer reachable from the application and won't have any way to receive progress updates. This ensures streams continue to make progress, even without wakers. WIthout this, it's possible for a stream to get into a state where the application isn't able to observe any updates and the stream is never cleaned up.
https://github.com/aws/s2n-quic/blob/bfe6491b3189ed7802f6582d117afab504366909/quic/s2n-quic-transport/src/stream/api.rs#L66
https://github.com/aws/s2n-quic/blob/bfe6491b3189ed7802f6582d117afab504366909/quic/s2n-quic-transport/src/stream/api.rs#L73-L75
In #1217, the behavior of STOP_SENDING was modified to …
> fix(s2n-quic-transport): detach streams on drop

- netbench/netbench-driver/src/lib.rs
None
Currently, the local_ip argument for clients must be passed in with `--local-ip`. However, when running a driver with netbench collector, passing this argument is not possible. This PR allows for this argument to be set with the `LOCAL_IP` environment variable.
None
> fix(netbench): allow local ip arg to be set from an environment variable

- .github/actions/duvet/README.md
- .github/actions/duvet/action.yml
- .github/workflows/ci.yml
None
Currently, s2n-quic generates Duvet reports in the ci.yml Github workflow. As a workflow, this functionality is restricted to s2n-quic only. This PR refactors this workflow into a new Duvet Github action, which allows for other repositories to clone s2n-quic and run Duvet in their CIs as well.
None
> build(duvet): Add Github action for Duvet

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/congestion_controller.rs
- quic/s2n-quic-core/src/recovery/cubic.rs
- quic/s2n-quic-core/src/recovery/cubic/tests.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-events/events/connection.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__process_new_acked_packets_process_ecn.snap
This change introduces a new event `SlowStartExited` that can be used to determine the timing, cause, and congestion window size at the time the "Slow Start" phase of the congestion controller is exited.
The slow start state may be re-entered (and subsequently exited) after persistent congestion is experienced, so applications that are not interested in recording `SlowStartExited` events after the initial slow start will need to ensure the metric is recorded only once per connection. 
Snapshot test
> feat(s2n-quic-core): Add SlowStartExited event

- quic/s2n-quic-core/src/recovery/cubic.rs
- quic/s2n-quic-core/src/recovery/cubic/tests.rs
This disables resetting congestion window when blackholes are detected through MTU probes. 
This is because we currently do not probe MTU until after the handshake is complete and 
this logic could lead to very poor performances when there're bursty packet losses
* disable resetting congestion window after blackhole is detected in cubic.rs.
* disable test cases for it to avoid errors.
we should re-visit this part when we enhance mtu probe mechanism in the future.
Perform A/B tests between 2 instances and confirmed that there's no regression.
> fix(s2n-quic-core): disable resetting congestion window after blackhole is detected.

- .github/interop/runner.patch
- .github/workflows/ci.yml
- .github/workflows/netbench.yml
- .github/workflows/qns.yml
- .license-template
- .rustfmt.toml
- scripts/interop/README.md
- scripts/interop/run
pyshark recently published a few breaking changes, which in turn breaks the quic-interop-runner. This PR:
* Pins the pyshark version to the current
* Fixes the backward-incompatible API usage
* Updates the nightly toolchain to the latest
* Removes the rustfmt license check (see https://github.com/rust-lang/rustfmt/issues/5103)
> ci: pin pyshark dependency

- quic/s2n-quic-core/src/datagram/default.rs
n/a
It doesn't really make sense for this function to return a float since theres no such thing as a fractional byte. Changing to a usize.
n/a
test still passes
> fix(s2n-quic-core) F64 to usize Conversion

- .github/workflows/qns.yml
- quic/s2n-quic-transport/src/connection/connection_impl.rs
Fixes #1392 
Connection state dumping was useful with initial development. However, as applications begin to adopt s2n-quic, it adds noise to application tests and makes it difficult to figure out the actual cause.
This change preserves the ability to dump state, but make it opt-in at compile time with the `s2n_quic_dump_on_panic` flag.
> fix(s2n-quic-transport): make state dumping explicit and opt-in

- .github/workflows/ci.yml
- .github/workflows/netbench.yml
- common/s2n-codec/src/decoder/value.rs
- netbench/netbench/src/operation.rs
- netbench/netbench/src/scenario/id.rs
- netbench/netbench/src/units/rate.rs
- quic/s2n-quic-transport/src/connection/connection_container.rs
- quic/s2n-quic-transport/src/interval_set/interval.rs
- quic/s2n-quic-transport/src/space/mod.rs
Clippy introduced a new lint in beta that checks to see if Eq can be derived if PartialEq is also derived. This is fine for applications but it makes ensuring backward-compatibility in libraries more fragile. If a field is added that doesn't implement Eq, then the derive would have to be removed, which could break existing callers.
This change adds an allow for the new lint globally, since I don't think it's very compelling.
See https://github.com/rust-lang/rust-clippy/issues/9063
I've also made beta clippy errors into warnings since it clutters up actual statuses every time clippy adds one of these things.
> fix(s2n-quic-transport): fix clippy beta warnings

- quic/s2n-quic-transport/src/stream/controller.rs
- quic/s2n-quic-transport/src/stream/manager/tests.rs
There is a 1-of error when enforcing stream limits. This PR fixes the calculation
> fix(s2n-quic-transport): enforce inclusive bound on stream limits

- netbench/netbench-driver/Cargo.toml
- netbench/netbench-driver/src/bin/netbench-driver-s2n-tls-client.rs
- netbench/netbench-driver/src/bin/netbench-driver-s2n-tls-server.rs
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-tls/src/callback.rs
- quic/s2n-quic-tls/src/certificate.rs
- quic/s2n-quic-tls/src/client.rs
- quic/s2n-quic-tls/src/keylog.rs
- quic/s2n-quic-tls/src/lib.rs
- quic/s2n-quic-tls/src/server.rs
- quic/s2n-quic-tls/src/session.rs
- quic/s2n-quic-tls/src/tests.rs
This PR updates the s2n-tls version to 0.0.9
Some of the callback traits were renamed and needed to be changed. This does introduce a method rename on the builder so I've duplicated the function and added a `deprecated` attribute.
> deps(s2n-quic-tls): update s2n-tls to 0.0.9

- common/s2n-codec/Cargo.toml
- netbench/netbench-cli/Cargo.toml
- netbench/netbench-collector/Cargo.toml
- netbench/netbench-driver/Cargo.toml
- netbench/netbench-scenarios/Cargo.toml
- netbench/netbench/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-events/Cargo.toml
- quic/s2n-quic-h3/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-sim/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
Cargo added support to specify the MSRV in the manifest file so applications get an notification if the rust version is not supported. See https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
This PR adds the current MSRV to each of the Cargo.toml files
> build: set rust-version in manifest

- .github/config/cargo-deny.toml
This [`unicode-ident`](https://crates.io/crates/unicode-ident) crate recently added the Unicode license to the code, which breaks our current `cargo-deny` check. This change adds the license to the allow list.
> ci: allow unicode license

- quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
- quic/s2n-quic-core/src/recovery/bandwidth/estimator/tests.rs
- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_rtt.rs
This change updates the pacing rate, send quantum, and congestion window on each ACK in BBRv2.
There are a number of places I convert from a u64 to a u32 when dealing with inflight data functions. I'll follow up in a separate PR with making sure these methods are using the correct types.
Added a test for the bandwidth division, additional tests are TODO
> feat(s2n-quic-core): Updating BBRv2 control parameters

- quic/s2n-quic-tls/src/client.rs
- quic/s2n-quic-tls/src/tests.rs
resolves #1408
Add an option to configure a hostname verification callback on the
client side, analogous to the equivalent function on the server side.
Note that because the rust bindings don't support
configuring the callback on a per-connection basis, the verification
callback currently cannot be given the original server name that was
connected to, and must make its decision based solely on
client-creation-time context and the hostnames in the TLS certificate in
question.
In most cases where one would be implementing this callback, the
customer has custom logic for determining which hostnames to accept in
any case, so this may not be an issue, but in the future if s2n-tls rust
bindings expose this connection-specific verification call, a new trait
can be introduced to pass through the …
> feat(s2n-quic-tls): client hostname verify callback

- quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/congestion.rs
- quic/s2n-quic-core/src/recovery/bbr/data_rate.rs
- quic/s2n-quic-core/src/recovery/bbr/data_volume.rs
- quic/s2n-quic-core/src/recovery/bbr/full_pipe.rs
- quic/s2n-quic-core/src/recovery/bbr/recovery.rs
- quic/s2n-quic-core/src/recovery/bbr/round.rs
This change implements the BBRv2 logic for handling packet loss, as well as resumption from idle. 
I've also cleaned up a few outstanding TODOs, as well as added a new one (#1412) for an optimization that we can do later if necessary
TODO
> feat(s2n-quic-core): Handle loss and idle restart in BBRv2

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-events/events/connection.rs
- quic/s2n-quic-events/src/parser.rs
- quic/s2n-quic-transport/src/ack/ack_manager.rs
> feat(s2n-quic-core): deprecate on_ack_processed event in favor of on_rx_ack_range_dropped

- examples/unreliable-datagram/Cargo.toml
- examples/unreliable-datagram/src/bin/datagram_receiver.rs
- examples/unreliable-datagram/src/bin/datagram_sender.rs
- quic/s2n-quic-core/src/datagram/default.rs
- quic/s2n-quic-core/src/datagram/disabled.rs
- quic/s2n-quic-core/src/datagram/traits.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/space/datagram.rs
N/A
1. On the sending side, prevents datagrams from being sent if there exists some connection-level error.
2. On the poll receiving side, prevents waker from being cloned if there exists some connection-level error.
3. Includes tests for the above scenarios ^
4. Unreliable datagram example now sends and recvs in a loop.
Unit tests. Also datagrams can now be sent continuously and received continuously.
> fix(s2n-quic-core): Some Datagram Fixes

- quic/s2n-quic-core/src/connection/limits.rs
- quic/s2n-quic-core/src/stream/id.rs
- quic/s2n-quic-core/src/stream/iter.rs
- quic/s2n-quic-core/src/stream/limits.rs
- quic/s2n-quic-core/src/stream/mod.rs
- quic/s2n-quic-core/src/transport/parameters/mod.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/stream/controller.rs
- quic/s2n-quic-transport/src/stream/controller/fuzz_target.rs
- quic/s2n-quic-transport/src/stream/controller/local_initiated.rs
- quic/s2n-quic-transport/src/stream/controller/remote_initiated.rs
- quic/s2n-quic-transport/src/stream/manager.rs
- quic/s2n-quic-transport/src/stream/manager/tests.rs
- quic/s2n-quic/src/tests.rs
This PR introduces initiator aware stream controllers. With this we can track bidi local/remote streams separately, which makes it a bit easier to reason about.
Notable changes:
- The local_initiated controller is typed over the type of local_stream_limits (bidi vs uni), so the compiler can enforce correctness.
- The APIs for opening streams on the stream_controller now enforce checks at the time of opening the stream.
- fuzz testing
- unit tests
> fix(s2n-quic-transport): make bidi stream controller initiator aware

- quic/s2n-quic/src/stream/receive.rs
- quic/s2n-quic/src/tests.rs
resolves #1427, extends #1429 
This change adds an integration test for the recently fixed `tokio::io::AsyncRead` implementation.
If #1429 is reverted, this integration test fails, showing that it's an effective test in preventing a regression.
```
thread 'tests::tokio_read_exact_test' panicked at 'buf.len() must fit in remaining()', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/io/read_buf.rs:245:9
stack backtrace:
0: std::panicking::begin_panic
at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:543:12
1: tokio::io::read_buf::ReadBuf::put_slice
at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/io/read_buf.rs:245:9
2: <s2n_quic::stream::receive::ReceiveStream as tokio::io::async_read::AsyncRead>::poll_read
at …
```
> test(s2n-quic): add integration test for tokio AsyncRead and AsyncWrite

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/events/common.rs
N/A
Currently Block frame events (DataBlocked, StreamDataBlocked and StreamsBlocked) contain no fields that describe by the frame was sent. This PR adds limit values to to these events
N/A
`cargo test` succeeds.
> feat(s2n-quic-core): Add limit values for Blocked frame events 

- quic/s2n-quic-core/src/datagram/default.rs
- quic/s2n-quic-core/src/datagram/traits.rs
- specs/www.rfc-editor.org/rfc/rfc9221.txt
Related to #1253 
Fleshing out some comments for datagram-related items. Additionally found some methods that I don't think should be public since users should not need access to them directly. Noticed that the datagram spec needed to be added to our specs folder as well so that we could reference it in the compliance doc.
I think that you should be able to see the docs in our CI? I'm not sure which github action generates them though. 
cargo doc compiles. 
> docs(s2n-quic-core): Fleshing out Datagram Documentation (#1417)

- quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
- quic/s2n-quic-core/src/recovery/bandwidth/estimator/tests.rs
- quic/s2n-quic-core/src/recovery/bbr/congestion.rs
- quic/s2n-quic-core/src/recovery/bbr/data_rate.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
This change refactors the `Bandwidth` type used by BBRv2 to internally represent bandwidth as the number of nanoseconds to send 1 byte of data, rather than how many bits can be sent in a second. This allows for some of the division operations to be replaced with multiplication.
Unit tests
> refactor(s2n-quic-core): represent Bandwidth as nanos per byte

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/congestion.rs
- quic/s2n-quic-core/src/recovery/bbr/data_volume.rs
- quic/s2n-quic-core/src/recovery/bbr/ecn.rs
- quic/s2n-quic-core/src/recovery/bbr/full_pipe.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
- quic/s2n-quic-core/src/recovery/bbr/recovery.rs
- quic/s2n-quic-core/src/recovery/bbr/startup.rs
resolves #1423
This change implements lowering of the `inflight_lo` data volume parameter in response to ECN congestion experienced (CE) signals. The implementation is based on the Linux TCP BBRv2 implementation, specifically [bbr2_update_ecn_alpha](https://github.com/google/bbr/blob/1a45fd4faf30229a3d3116de7bfe9d2f933d3562/net/ipv4/tcp_bbr2.c#L1392) and [bbr2_adapt_lower_bounds](https://github.com/google/bbr/blob/1a45fd4faf30229a3d3116de7bfe9d2f933d3562/net/ipv4/tcp_bbr2.c#L1630). Effectively a weight average of the ratio of packets marked with the ECN CE marking is updated on every BBR round. That value (`alpha`) is used to reduce `inflight_lo`. `inflight_lo` may also be reduced when packet loss occurs. The lower of the ECN `inflight_lo` and packet loss `inflight_lo` is ultimately used. …
> s2n-quic-core: Lower inflight_lo based on ECN markings in BBRv2

- quic/s2n-quic-qns/src/perf.rs
#1320
When the s2n-quic perf client is requested to send data to the server, it initiates a bidirectional stream and begins sending data. Since it is the client that initiated the bidirectional stream, the client must respect the `initial_max_stream_data_bidi_remote` transport parameter sent by the server. Currently, neither the s2n-quic perf client or server set this transport parameter, so it remains at the default that is tuned for 150Mbps (assuming a 100ms RTT). This becomes a limiting factor when testing with a higher RTT, so this change sets the bidirectional_remote_data_window value that configures the `initial_max_stream_data_bidi_remote` transport parameter. 
Before:
```tsv
./target/release/s2n-quic-qns perf client --ip 127.0.0.1 --port 4433 --send 10000000000 --max-throughput …
```
> fix(s2n-quic-qns): set bidi remote data window

- quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
- quic/s2n-quic-core/src/recovery/bandwidth/estimator/tests.rs
- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_rtt.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
This change resolves a few panics and other issues found while performing some basic testing of BBRv2.
Fixes:
* `bandwidth::Estimator::on_packet_sent` was expecting the `bytes_in_flight` from before the current packet was transmitted, in order to initialize `first_sent_time` and `delivered_time`. Previously, the `bytes_in_flight` value from after the packet was sent was used, resulting in those fields not being initialized and a panic occuring
* `bytes_in_flight` was not being decremented when a packet was lost
* The calculation of `inflight_with_headroom` accurately follows the draft RFC, but the draft RFC mistakenly reduces inflight_hi to 15%, instead of the intended 85%, see https://groups.google.com/g/bbr-dev/c/xmley7VkeoE/m/uXDlnxiuCgAJ
* `inflight_hi_from_lost_packet` subtracts …
> fix(s2n-quic-core): various BBRv2 fixes

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
- quic/s2n-quic-core/src/recovery/congestion_controller.rs
- quic/s2n-quic-core/src/recovery/congestion_controller/corpus.tar.gz
- quic/s2n-quic-core/src/recovery/congestion_controller/fuzz_target.rs
- quic/s2n-quic-core/src/recovery/hybrid_slow_start.rs
- quic/s2n-quic-core/src/recovery/mod.rs
- quic/s2n-quic-core/src/recovery/pacing.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
This change introduces fuzz tests for the Cubic and BBR congestion controller. The fuzz tests simulate a series of packets being sent, acked, lost, etc and verify that no panics are encountered and that the bytes in flight count is correct.
I also included a few fixes for issues I found during some initial fuzzing:
* An underflow in BBR when the first packet sent is lost
* Overflows in hybrid slow start and the default pacer when the MTU is set to a value > 6553 bytes
Ran fuzz tests for ~20 minutes
> feat(s2n-quic-core): congestion controller fuzz tests

- .github/workflows/ci.yml
- .github/workflows/netbench.yml
- common/docdiff/Cargo.toml
- common/duvet/Cargo.toml
- netbench/netbench/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
The clippy lint `derive_partial_eq_without_eq`, which we previously ignore for the Beta CI in #1390, is now in the stable version of Rust, as of [Rust 1.63.0](https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-163). This change updates the CI to ignore this lint for both stable and beta. 
In addition, Insta requires the `json` feature in order to avoid warnings when using the `assert_json_snapshot!` macro, so I've added that feature as well.
Once Rust 1.63.0 is our MSRV, then we should be able to add ignoring `derive_partial_eq_without_eq` to `clippy.toml`
The CI for this PR tests this
> ci: fix clippy warnings

- quic/s2n-quic-core/src/datagram/traits.rs
- quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/congestion.rs
- quic/s2n-quic-core/src/recovery/bbr/drain.rs
- quic/s2n-quic-core/src/recovery/bbr/ecn.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_rtt.rs
- quic/s2n-quic-core/src/recovery/bbr/startup.rs
- quic/s2n-quic-core/src/recovery/hybrid_slow_start.rs
- quic/s2n-quic-crypto/src/aes/testing.rs
- quic/s2n-quic-crypto/src/aes/testing/rust_crypto.rs
- quic/s2n-quic-crypto/src/aes/x86/testing.rs
- quic/s2n-quic-crypto/src/aesgcm/generic.rs
- quic/s2n-quic-crypto/src/ghash.rs
- quic/s2n-quic-crypto/src/ghash/testing.rs
- quic/s2n-quic-crypto/src/ghash/testing/rust_crypto.rs
- quic/s2n-quic-crypto/src/ghash/x86/testing.rs
- quic/s2n-quic-sim/src/stats.rs
This change adds the `#[inline]` compiler suggestion to BBR methods to improve performance
I've also fixed some new Clippy issues I noticed failing, and resolved some compilation warnings on ARM targets
> refactor(s2n-quic-core): add inline to BBR methods

- .github/interop/required.json
ECN interop testing no longer works with ngtcp2 as of https://github.com/ngtcp2/ngtcp2/pull/521. This change causes ngtcp2 MTU probes to not be marked with ECN-Capable markings, which the ECN interop test requires on all packets. 
This change makes it so ECN interop tests with ngtcp2 are no longer required.
We could potentially work around this by setting the `max_udp_payload_size` transport parameter to 1200, but we don't currently expose this setting.
> ci: don't require ECN to pass for ngtcp2

- .github/interop/required.json
Reverts aws/s2n-quic#1469
ngtcp2 fixed the issue with ECN interop in https://github.com/ngtcp2/ngtcp2/pull/525
> Revert "ci: don't require ECN to pass for ngtcp2"

- quic/s2n-quic-core/src/packet/retry.rs
- quic/s2n-quic-core/src/packet/stateless_reset.rs
- quic/s2n-quic-core/src/random.rs
- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/drain.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_rtt.rs
- quic/s2n-quic-core/src/recovery/congestion_controller.rs
- quic/s2n-quic-core/src/recovery/congestion_controller/fuzz_target.rs
- quic/s2n-quic-core/src/recovery/cubic.rs
- quic/s2n-quic-crypto/src/retry.rs
- quic/s2n-quic-transport/src/connection/connection_id_mapper.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/endpoint/retry.rs
- quic/s2n-quic-transport/src/endpoint/stateless_reset.rs
- quic/s2n-quic-transport/src/path/ecn.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/mod.rs
- scripts/sim
This change updates usage of `random::Generator` in several locations to use dynamic dispatch over static dispatch. This is preferable in these cases, as the generator is rarely used and inlining the actual rng implementation wouldn't really enable any optimizations. This also means all of the functions that are generic over the `random::Generator`, can be generated at compile time of `s2n-quic-core` and `s2n-quic-transport`, rather than instantiation of a `s2n-quic` `Client` or `Server`. This _should_ help with compile times and final binary sizes.
Since this is just a type change, all of the existing tests should catch any issues.
> refactor(s2n-quic-core): use dyn random::Generator instead of static dispatch

- quic/s2n-quic-transport/src/stream/controller.rs
- quic/s2n-quic-transport/src/stream/controller/local_initiated.rs
- quic/s2n-quic-transport/src/stream/controller/remote_initiated.rs
- quic/s2n-quic-transport/src/stream/manager/tests.rs
- quic/s2n-quic-transport/src/sync/once_sync.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/setup.rs
resolves #1464 
The current stream behavior when opening a stream locally is to wait to send a `STREAM` until we have data to send to the peer. This causes a dead-lock on a connection when the local endpoint creates a stream and immediately calls `receive` on it. The peer isn't aware of the stream and won't know to send data. The connection will eventually time out as a result.
This fix adds a `open_notify` sender which sends an empty `STREAM` frame with `len = 0, offset = 0` at the creation of a local stream that can receive (basically a locally-created, bidirectional stream). If the local application opens another bidirectional stream, the previous frame transmission will be cancelled and a new transmission will be started. This prevents an empty frame being transmitted for each new …
> fix(s2n-quic-transport): notify peer of locally-created receive streams

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/congestion_controller/__fuzz__/recovery__congestion_controller__fuzz_target__bbr/corpus.tar.gz
- quic/s2n-quic-core/src/recovery/congestion_controller/__fuzz__/recovery__congestion_controller__fuzz_target__cubic/corpus.tar.gz
- quic/s2n-quic-core/src/recovery/congestion_controller/corpus.tar.gz
- quic/s2n-quic-core/src/recovery/congestion_controller/fuzz_target.rs
The fuzz test corpus files for the congestion controller fuzz tests were not organized properly, meaning they were not being used during execution of the fuzz tests or in coverage reporting. This change fixes the corpus files to keep them separated into individual directories.
While running the fuzz tests for a longer period, an issue was found when the Bandwidth reaches the maximum limit of 1GB/sec. To handle this, I've updated several usages of bandwidth to perform saturating multiplication or saturating addition. 
In addition, I've updated the fuzz test to not send packets when congestion limits, to more accurately match how the congestion controller is used by the recovery manager.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> fix(s2n-quic-core): congestion controller fuzz improvements and fixes

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/data_volume.rs
- quic/s2n-quic-core/src/recovery/bbr/drain.rs
- quic/s2n-quic-core/src/recovery/bbr/full_pipe.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
This change adds more unit test coverage for BBRv2. While adding a unit test for `fn handle_lost_packet` I found a bug in the function. I've included the fix for that in this change as well.
> fix(s2n-quic-core): add BBR unit tests and fix handle_lost_packet

- quic/s2n-quic-crypto/src/arch.rs
Rust really should catch weird stuff like this even if it's disabled with a macro...
It only fixes a typo in the source code
There's no changes except fixing a typo, so no testing is necessary. Perhaps an x86 CI pipeline should be added.
> fix x86 compilation for s2n-quic-crypto

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/full_pipe.rs
- quic/s2n-quic-core/src/recovery/bbr/pacing.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
- quic/s2n-quic-core/src/recovery/pacing.rs
The BBRv2 draft specification specifies how pacing and send_quantum (ie GSO) should work independently, but seemingly does not specify how they should work together. The result of this is that the pacing, as specified, attempts to pace out each packet individually, without regard for how the send_quantum/GSO would like to batch the packets. This can lead to underutilization of the congestion window, preventing it from growing further.
This change makes the BBR pacer track the capacity of a send interval based on the amount sent so far as well as the send_quantum, similar to how the default packet pacer that Cubic uses. 
Added unit tests
By submitting this pull request, I confirm that my …
> fix(s2n-quic-core): account for send_quantum in BBR packet pacing

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
This change updates the behavior of BBR to match that of CUBIC when the MTU of a path is updated, specifically the size of the congestion window in bytes is updated to reflect the new maximum datagram size, to keep the size of the congestion window in packets constant. 
This is not necessarily compliant with the QUIC RFC (see #959), however it is necessary to have BBR on an even footing with CUBIC while we are evaluating both.
Added unit test
> fix(s2n-quic-core): adjust BBR congestion window on MTU update

- quic/s2n-quic-transport/src/ack/ack_manager.rs
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_manager__tests__client_sending_test.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_manager__tests__delayed_client_sending_test.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_manager__tests__high_latency_test.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_manager__tests__lossy_network_test.snap
I noticed while looking at tracing logs that we were waking up to send an ACK even though we had already sent one with a STREAM frame. Digging into it, I noticed we weren't cancelling the `ack_delay_timer` after transmitting an ACK frame which resulted in redundant packets being transmitted. This change, instead, cancels the timer.
The simulation snapshots were updated which all show the improvement in the number of transmitted packets between peers.
> fix(s2n-quic-transport): cancel ack_delay_timer after ACK transmission

- quic/s2n-quic-core/src/connection/limits.rs
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-core/src/memo.rs
- quic/s2n-quic-core/src/time/timer.rs
- quic/s2n-quic-transport/src/connection/local_id_registry.rs
- quic/s2n-quic-transport/src/connection/local_id_registry/tests.rs
- quic/s2n-quic-transport/src/connection/peer_id_registry.rs
- quic/s2n-quic-transport/src/connection/peer_id_registry/tests.rs
I was doing perf measurements on light loads with infrequent send/recv and the ACK processing/interest queries in the CID registries was showing up quite a bit. This is because on every event we iterate through the whole list of registered CIDs, even if none of them are waiting for an ACK signal or have transmission interest.
This change, instead, denormalizes values on the struct itself and that's checked before iterating through the list. It is done through a new `Memo` struct that I added.
I've updated the `check_consistency` method to include making sure that the field _always_ reflects the current state of each one of the CIDs. This check is performed (in debug mode) on each mutation of the data structure, which means all of the existing tests will catch any issues.
By submitting …
> fix(s2n-quic-transport): denormalize ACK interest for CID registries

- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/stream/manager.rs
We currently iterate over every single active stream every time the RTT estimate is updated. This isn't ideal when processing a lot of ACK frames. This PR instead caches the previous estimate and only iterates if it's outside of a 16 millisecond window, as the streams don't need a 100% accurate value.
I've also optimized the PTO calculation code to use milliseconds rather than `Duration`, since we don't need sub-millisecond precision.
> fix(s2n-quic-transport): only update blocked_sync_period on significant changes

- quic/s2n-quic-transport/src/path/mod.rs
The logic in `at_amplication_limit` was a bit confusing and needlessly complicated. This PR simplifies it a bit, which also helps perf, since this is called on every single packet we send. I've also fixed the documentation to be a bit clearer.
The existing tests show that the behavior is preserved.
> fix(s2n-quic-transport): optimize at_amplification_limit function

- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
In #1491, I added a test to make sure the optimized `weighted_average` matches the unoptimized version. My test asserted the values matched to the nearest milliseconds. The problem with this approach is the result may be on the line of a full millisecond, which will get rounded down in one case and not the other:
```
======================== Test Failure ========================
BOLERO_RANDOM_SEED=13710580805818456088
Input: 
(
655509357,
3219434504,
)
Error: 
panicked at 'assertion failed: `(left == right)`
left: `976`,
right: `975`', quic\s2n-quic-core\src\recovery\rtt_estimator.rs:734:17
```
The fix is to instead take the `abs_difference` in nanos and assert that it's within the `weight`, which is precisely the amount of precision lost in our optimized, overflow-free version.
By …
> fix(s2n-quic-core): check weighted_average difference based on weight in nanos

- quic/s2n-quic-transport/src/interval_set/fuzz_target.rs
Add a bolero-based test that checks range insertion for `interval_set`.
> test(s2n-quic-transport): add a bolero harness for interval_set insert

- quic/s2n-quic-core/src/random.rs
- quic/s2n-quic-core/src/slice.rs
- quic/s2n-quic-core/src/varint/tests.rs
N/A
* Added Kani hook for a `random` test harness
* Added Kani test harness for `VarInt`
Kani proof passes. 
> test(s2n-quic-core) Kani proofs for VarInt + Random

- quic/s2n-quic-core/src/packet/number/sliding_window.rs
This change adds a fuzz test and Kani proof that inserting a packet number into the Sliding Window data structure will be detected as a duplicate when checking that packet number.
> tests(s2n-quic-core): add fuzz test/kani proof for sliding window insertion

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/congestion.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
This change fixes the behavior of BBR during Startup so that when loss is encountered during Startup, the short term data volume and data rate bounds are not updated. The original code assumed the `BBRIsProbingBW()` function mentioned (but not defined) in the [BBR RFC](https://www.ietf.org/archive/id/draft-cardwell-iccrg-bbr-congestion-control-02.html#section-4.5.6.3) should return true only if BBR is in the ProbeBW state. After looking at the [TCP Linux BBR implementation](https://github.com/google/bbr/blob/a23c4bb59e0c5a505fc0f5cc84c4d095a64ed361/net/ipv4/tcp_bbr2.c#L1348) and the [Chromium implementation](https://source.chromium.org/chromium/chromium/src/+/main:net/third_party/quiche/src/quiche/quic/core/congestion_control/bbr2_startup.h;l=40;drc=f97e7e130b02a0fee5a06aa9cdf25d3a0a3715d0 …
> fix(s2n-quic-core): don't reduce lower bounds during BBR startup

- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-platform/src/buffer/vec.rs
- quic/s2n-quic-platform/src/message/queue.rs
- quic/s2n-quic-platform/src/message/queue/behavior.rs
- quic/s2n-quic-platform/src/socket/mmsg.rs
- quic/s2n-quic-platform/src/socket/msg.rs
- quic/s2n-quic-platform/src/socket/std.rs
On main, we currently spend about 10% of CPU cycles zeroizing packet receive buffers when receiving a lot of data. This is expensive because the `zeroize` crate does a [volatile write per byte](https://github.com/RustCrypto/utils/blob/193e7ad59ec81317bafbdbd9f9014b3dc89f9935/zeroize/src/lib.rs#L771-L784).
I believe we should change this to instead zeroize on buffer drop, since the thing we care about the most is zeroizing the packet buffers before we release them to the allocator. This completely removes any overhead when receiving a bunch of packets.
[
](https://dnglbrstg7yg.cloudfront.net/e5ae19ff115a09d29a8b041728393df85f0b69ea/perf/s2n-quic-client-s2n-quic-server/1000MB-down-0MB-up.client.svg)
[
](https://dnglbrstg7yg.cloudfront.net/54fc7542f8ca58c4b4434d1ddd3fe947dc1ceb21/perf/s2n-qui …
> fix(s2n-quic-platform): only zeroize buffers on drop

- quic/s2n-quic-core/src/frame/congestion_controlled.rs
- quic/s2n-quic-core/src/recovery/cubic.rs
- quic/s2n-quic-transport/src/transmission/mod.rs
Currently, it is almost impossible for s2n-quic to construct a packet that is not congestion controlled, despite this statement from the RFC:
> Packets only containing ACK frames do not count toward bytes_in_flight to ensure congestion control does not impede congestion feedback.
This is because we enforce a [minimum indistinguishable packet len](https://github.com/aws/s2n-quic/blob/a904cdf3bc9a991474e76a58a6570f61d7092c4b/quic/s2n-quic-core/src/packet/stateless_reset.rs#L33) that ends up being 53 bytes. Since an Ack frame is often less than 53 bytes, we add padding, which then makes the whole packet count against congestion control:
> PADDING frames cause packets to contribute toward bytes in flight without directly causing an acknowledgment to be sent.
The result is that we seem to …
> fix(s2n-quic-transport): make Ack + Padding packets not congestion controlled

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
The BBR draft RFC contains pseudocode showing the congestion window being decreased when packets are determined to be lost:
```
BBRModulateCwndForRecovery():
if (rs.newly_lost > 0)
cwnd = max(cwnd - rs.newly_lost, 1)
if (BBR.packet_conservation)
cwnd = max(cwnd, packets_in_flight + rs.newly_acked)
```
This pseudocode has been in the RFC in the 00 draft, which was a specification for BBRv1. Looking at the Chromium and TCP Linux implementations of BBRv2, this pseudocode is not in those implementations. I do see the implementation in the BBRv1 implementations ([Chromium](https://source.chromium.org/chromium/chromium/src/+/main:net/third_party/quiche/src/quiche/quic/core/congestion_control/bbr_sender.cc;l=794) | [TCP](https://github.com/torvalds/linux/blob/master/net/ipv4/tcp_bbr.c#L479)). …
> fix(s2n-quic-core): remove modulate cwnd for recovery in BBR

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
The BBRv2 RFC specifies that during startup, the congestion window may grow beyond `max_inflight` as long as the amount of delivered data has not exceeded the initial congestion window. Both the [Linux TCP](https://github.com/google/bbr/blob/1ee29b79317a3028ed1fcd85cb46da009f45de00/net/ipv4/tcp_bbr2.c#L931) and [Chromium](https://source.chromium.org/chromium/chromium/src/+/main:net/third_party/quiche/src/quiche/quic/core/congestion_control/bbr2_sender.cc;l=404;bpv=1;bpt=1) implementations extend that to 2 * the initial congestion window. This allows for a longer period where more accurate bandwidth estimates can be measured for determining how to limit the congestion window.
Updated unit test
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> fix(s2n-quic-core): allow cwnd to grow past max_inflight while less than 2 * initial_cwnd

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
BBR may enter and exit the ProbeRtt state while still slow starting, which may result in the `on_slow_start_exit` metric being emitted multiple times before slow start is actually exited.  This change bases the `is_slow_start` method on the `full_pipe_estimator`, which more accurately reflects if BBR is still slow starting and will only change states once per connection.
> fix(s2n-quic-core): base BBR is_slow_start on the full pipe estimator

- .github/workflows/netbench.yml
- .github/workflows/qns.yml
- quic/s2n-quic-qns/benchmark/client/Dockerfile.build
- quic/s2n-quic-qns/src/client/h3.rs
- quic/s2n-quic-qns/src/server/h09.rs
- quic/s2n-quic-qns/src/server/h3.rs
- scripts/perf/build
- scripts/perf/test
This change adds a `/_perf/{bytes}` handler to the interop server. This will allow a client to request a certain number of bytes without the file having to exist.
I've also:
* fixed the `bench` job by updating quinn to the latest version.
* Fixed the perf script build
* Passed the optimized crypto environment variable flags to commands with `sudo`, as they're not automatically inherited
> feat(s2n-quic-qns): add /_perf path handling

- quic/s2n-quic-h3/src/s2n_quic.rs
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-qns/src/main.rs
The `s2n-quic-h3` integration code has a bug where we can potentially lose chunks from the `WriteBuf` if s2n-quic starts putting backpressure on the send stream. This PR fixes this issue by storing any chunks that may have been rejected by `poll_send` on the `SendStream`.
I've included mimalloc in the s2n-quic-qns binary, which makes performance more stable than the libc allocator.
Before this change, we get stream corruption when sending over the allowed max stream buffer size:
```
$ ./target/release/s2n-quic-qns interop server --application-protocols h3 --port 3000
$ ./target/release/s2n-quic-qns interop client --application-protocols h3 --testcase http3 --download-dir target https://localhost:3000/_perf/5000000
connecting to localhost at [::1]:3000
GET …
```
> fix(s2n-quic-h3): flush chunks entirely before taking the next one

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/pacing.rs
- quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__pacing__events__initialize_pacing_rate.snap
- quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__pacing__events__one_rtt.snap
The [BBR draft RFC](https://www.ietf.org/archive/id/draft-cardwell-iccrg-bbr-congestion-control-02.html#section-4.6.2-5) and current BBR implementation initialize pacing rate based on a nominal bandwidth calculation that ends up being about 33MB/s. Since the pacing rate does not decrease while in slow start, this very high initial pacing value could lead to bursts and potential packet loss. 
Following the [TCP Linux BBR implementation](https://github.com/google/bbr/blob/1a45fd4faf30229a3d3116de7bfe9d2f933d3562/net/ipv4/tcp_bbr2.c#L666-L667), this change will initialize the pacing rate a second time, when the first real RTT sample is measured. 
Added unit test, and local testing
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fix(s2n-quic-core): Initialize BBR pacing rate on first RTT sample

- .github/workflows/ci.yml
- quic/s2n-quic-core/src/packet/number/sliding_window.rs
- quic/s2n-quic-core/src/packet/number/tests.rs
- quic/s2n-quic-core/src/slice.rs
- quic/s2n-quic-core/src/varint/tests.rs
This change adds a Kani CI task for running all of our kani harnesses. [Task link](https://github.com/aws/s2n-quic/actions/runs/3222849352/jobs/5272343920)
I've added `unwind` values to all of the harnesses to prevent kani from endlessly unwinding if it can't figure out the bounds. I've also gated the vectored copy harness behind a `cfg(kani_slow)` as it currently takes around 30 minutes to verify.
> ci: add kani task

- quic/s2n-quic-core/src/transport/parameters/mod.rs
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__tests__ClientTransportParameters__default.snap
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__tests__ServerTransportParameters__default.snap
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__tests__client_snapshot_test.snap
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__tests__load_client_limits.snap
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__tests__load_server_limits.snap
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__tests__server_snapshot_test.snap
- quic/s2n-quic-core/src/transport/parameters/tests.rs
We currently have a couple of missing loads for copying the connection limits into transport parameters. This makes it effectively impossible for us to communicate the correct `max_idle_timeout` and `ack_delay_exponent` value to the peer.
This change adds the missing loads.
I've also added a couple of snapshot tests to show the fix is now working and prevent a similar issue from happening in the future.
> fix(s2n-quic-core): add missing fields on loading limits into TPs

- quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
- quic/s2n-quic-core/src/recovery/bandwidth/estimator/snapshots/quic__s2n-quic-core__src__recovery__bandwidth__estimator__tests__events__app_limited.snap
- quic/s2n-quic-core/src/recovery/bandwidth/estimator/tests.rs
- quic/s2n-quic-core/src/recovery/bbr.rs
This change includes three fixes to ensure BBR properly marks the connection as application limited:
* If the `app_limited` designation is not provided to BBR (i.e. app_limited = None), the delivery rate estimator will default to considering this app-limited, rather than not app-limited. `app_limited` is only `None` for the Initial and Handshake spaces, when it is more likely than not that the application is not fully utilizing the congestion window. Because the consequences of not considering the connection app-limited can be severe in BBR, it is safer to conservatively consider the connection app-limited in this case.
* When a packet is sent while app_limited, the `bandwith::estimator` marks the connection as app-limited until all the bytes in flight are acknowledged as delivered to the …
> fix(s2n-quic-core): BBR app-limited fixes

- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
The ProbeBW_Down BBRv2 state cuts the pacing rate to 90% of maximum bandwidth. The Chromium and Linux TCP implementations of BBRv2 limit the time spent in the ProbeBW_Down state to min_rtt:
* [Linux TCP](https://github.com/google/bbr/blob/1a45fd4faf30229a3d3116de7bfe9d2f933d3562/net/ipv4/tcp_bbr2.c#L1982-L1981)
* [Chromium](https://source.chromium.org/chromium/chromium/src/+/main:net/third_party/quiche/src/quiche/quic/core/congestion_control/bbr2_probe_bw.cc;l=276)
This change follows these implementations and will restrict time spent in the ProbeBW_Down state to the minimum RTT.
The Chromium implementation is more strict than the TCP Linux implementation in exiting this state, as the Linux implementation still requires inflight to be less than inflight_with_headroom. This change follows …
> fix(s2n-quic-core): Limit time in BBR ProbeBW_DOWN to min rtt

- .github/config/cargo-deny.toml
Cargo deny starting complaining about duplicate versions of the `windows-sys` crate. This is due to the `parking_lot` dependency in bach. As such, I've added `bach` to the list of ignored dependencies since it'll always be a test dependency.
> ci: ignore bach dependency in cargo-deny

- .github/workflows/ci.yml
- common/s2n-codec/src/zerocopy.rs
- quic/s2n-quic-core/src/havoc.rs
- quic/s2n-quic-core/src/packet/interceptor/loss.rs
- quic/s2n-quic-platform/build.rs
- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/message/cmsg.rs
- quic/s2n-quic-platform/src/message/msg.rs
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-qns/src/main.rs
- quic/s2n-quic-transport/src/ack/ack_manager.rs
- quic/s2n-quic-transport/src/ack/ack_ranges.rs
- quic/s2n-quic-transport/src/ack/ack_transmission_state.rs
- quic/s2n-quic-transport/src/sync/data_sender/transmissions.rs
- quic/s2n-quic/src/tests/setup.rs
closes #1485 
This change adds 32-bit platform to our CI and fixes the issues found while compiling and running the tests. This includes
* Using u64 instead of usize in a few places
* Ignoring the snapshot tests on 32bit platform
* Adding `target_os = "android"` to a few places.
The android test run currently fails. That will need to be added in another PR.
The tests were executed locally and in CI.
> fix(s2n-quic-transport): correctly handle 32-bit platforms

- quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
- quic/s2n-quic-core/src/recovery/bandwidth/estimator/snapshots/quic__s2n-quic-core__src__recovery__bandwidth__estimator__tests__events__on_packet_ack_implausible_ack_rate.snap
- quic/s2n-quic-core/src/recovery/bandwidth/estimator/snapshots/quic__s2n-quic-core__src__recovery__bandwidth__estimator__tests__events__on_packet_ack_rate_sample.snap
- quic/s2n-quic-core/src/recovery/bandwidth/estimator/tests.rs
The `bytes_in_flight` value recorded in the `PacketInfo` used by BBR's delivery rate estimator should reflect the total amount of data in flight including the packet currently being transmitted. This follows the delivery rate estimation implementation in TCP: https://github.com/google/bbr/blob/7636a4ccf0f51e69a1e37bff97851dff0d344919/net/ipv4/tcp_rate.c#L43
Updated unit test
> fix(s2n-quic-core): record total bytes in flight in PacketInfo

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
One of the parts of the bandwidth and data volume model that BBR uses to constrain the congestion window is `inflight_hi`, which is " the long-term maximum volume of in-flight data that the algorithm estimates will produce acceptable queue pressure, based on signals in the current or previous bandwidth probing cycle, as measured by loss". `inflight_hi` gets lowered when you have > 2% loss and it is supposed to be raised if you don't have loss and are fully utilizing the congestion window. The current code is checking for "are we fully using the congestion window" after bytes in flight had been updated from an ACK, meaning it would almost never report as utilizing the congestion window, and thus `inflight_hi` would not be raised.
This change introduces a `cwnd_limited_in_round` field that …
> fix(s2n-quic-core): raise inflight_hi in BBR

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/congestion.rs
- quic/s2n-quic-core/src/recovery/bbr/full_pipe.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
- quic/s2n-quic-core/src/recovery/bbr/startup.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
This change introduces some additional requirements for exiting slow start and setting the `inflight_hi` model bound.
In the Chromium BBRv2 implementation, `inflight_hi` is not lowered unless 2 bursts of loss are recorded during a round ([source](https://source.chromium.org/chromium/chromium/src/+/main:net/third_party/quiche/src/quiche/quic/core/quic_protocol_flags_list.h;l=139;bpv=1;bpt=0)). In addition, both the Chromium and Linux TCP BBRv2 implementations require 8 bursts of loss to exit Startup, as opposed to the 3 described in the draft RFC ([Chromium](https://source.chromium.org/chromium/chromium/src/+/main:net/third_party/quiche/src/quiche/quic/core/quic_protocol_flags_list.h;l=135;bpv=1;bpt=0) | [TCP](https://github.com/google/bbr/blob/1a45fd4faf30229a3d3116de7bfe9d2f933d3562/net/i …
> fix(s2n-quic-core): use loss burst count when checking inflight in BBRv2

- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/recovery.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
The BBRv2 draft RFC contains references to packet conservation and recovery mechanisms that are likely leftovers from when the RFC was implementing BBRv1. Packet conservation in BBRv2 is implemented by updating the short term bandwidth and data volume model parameters (`inflight_lo` and `bw_lo`) on packet loss, rather than just setting the cwnd to bytes_in_flight.
Neither the Linux TCP BBRv2 implementation or Chromium implement the old packet conservation requirements mentioned in the RFC, so this change removes them, as they have the potential to interfere where the newer model-based approach.
Updated unit tests and interop
> fix(s2n-quic-core): simplify BBRv2 recovery

- netbench/netbench-cli/src/report.rs
- netbench/netbench-collector/src/bpftrace.rs
- netbench/netbench-collector/src/generic.rs
- netbench/netbench-collector/src/main.rs
- netbench/netbench-collector/src/netbench.bt
- netbench/netbench-driver/src/bin/netbench-driver-native-tls-client.rs
- netbench/netbench-driver/src/bin/netbench-driver-native-tls-server.rs
- netbench/netbench-driver/src/bin/netbench-driver-s2n-tls-client.rs
- netbench/netbench-driver/src/bin/netbench-driver-s2n-tls-server.rs
- netbench/netbench-driver/src/bin/netbench-driver-tcp-client.rs
- netbench/netbench-driver/src/bin/netbench-driver-tcp-server.rs
- netbench/netbench-driver/src/lib.rs
- netbench/netbench-scenarios/src/config.rs
- netbench/netbench-scenarios/src/main.rs
- netbench/netbench-scenarios/src/ping.rs
- netbench/netbench/src/driver/thread.rs
- netbench/netbench/src/operation.rs
- netbench/netbench/src/scenario/builder.rs
- netbench/netbench/src/scenario/builder/client.rs
- netbench/netbench/src/scenario/builder/connection.rs
- netbench/netbench/src/scenario/builder/stream.rs
- netbench/netbench/src/stats.rs
- netbench/netbench/src/trace.rs
- netbench/netbench/src/trace/usdt.rs
This change adds profiling capabilities to netbench. To demonstrate the functionality, I've added a `ping` scenario that sends a configurable payload to the server, which then responds with the same size. It loops for 15s on each payload and averages the latency.
On the GitHub Actions servers s2n-quic appears to be quite competitive. With high RTT s2n-quic has some latency issues around 100k payloads, but does well at the other sizes.
I ran into [nagle issues](https://en.m.wikipedia.org/wiki/Nagle%27s_algorithm) while testing TCP-based drivers so those all disable it by default, with a CLI option to enable it.
> feat(netbench): add support for profiling

- quic/s2n-quic-core/src/application/error.rs
- quic/s2n-quic-core/src/transport/parameters/mod.rs
- quic/s2n-quic-core/src/varint/mod.rs
- quic/s2n-quic/src/provider/congestion_controller.rs
I noticed that when configuring connection limits I wasn't able to convert validation errors into `Box<dyn std::error::Error>`. So I did a scan of all of the errors in `s2n-quic-core` and implemented `std::error::Error` for all of the error types that were missing it.
I included a change to make it easier to switch the default congestion controller in code. It's a super small, but unrelated, change. Didn't seem worth opening a PR just for that 😄.
> fix(s2n-quic-core): implement std Error for other error types

- .github/workflows/ci.yml
- common/s2n-codec/src/decoder/mod.rs
- common/s2n-codec/src/testing/mod.rs
This change updates the kani version in CI to 0.13.
To work around this issue described in https://github.com/model-checking/kani/issues/1767, I've applied the suggested fix: https://github.com/model-checking/kani/issues/1767#issuecomment-1275449305. We should be able to revert these changes once it is addressed upstream.
The mir-linker was also enabled by default so I removed that flag. 
I tested both locally and in [ci](https://github.com/aws/s2n-quic/actions/runs/3314584782/jobs/5474060658).
> ci: update kani to 0.13

- netbench/netbench-cli/src/report.rs
- netbench/netbench-collector/src/bpftrace.rs
- netbench/netbench-collector/src/netbench.bt
- netbench/netbench-driver/src/bin/netbench-driver-native-tls-server.rs
- netbench/netbench-driver/src/bin/netbench-driver-s2n-quic-server.rs
- netbench/netbench-driver/src/bin/netbench-driver-s2n-tls-server.rs
- netbench/netbench-driver/src/bin/netbench-driver-tcp-server.rs
- netbench/netbench/src/stats.rs
- netbench/netbench/src/trace/usdt.rs
This change adds connect time reporting to netbench. The trace event was already there; just needed to wire it up to the bpftrace module.
Originally the metric was only implemented on the client but I went ahead and added it to the server drivers to make the report generic.
I ran the `connect` scenario over my LAN between two hosts.
> feat(netbench): include connect time metrics in report

- .github/workflows/ci.yml
N/A
Currently, quic uses a hardcoded install script to run Kani in CI.  Change to use the new kani action.
This CI is tagged to a particular version of kani.  Changes to this version will require updating the CI action used.
This is a CI change. Testing is on the PR itself.
> Use Kani action in CI

- quic/s2n-quic-core/src/stream/testing.rs
- quic/s2n-quic-core/src/transport/parameters/disabled_parameter.rs
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__tests__ClientTransportParameters__default.snap
- quic/s2n-quic-core/src/transport/parameters/snapshots/s2n_quic_core__transport__parameters__tests__load_client_limits.snap
- quic/s2n-quic/Cargo.toml
This fixes a few things after the most recent rust beta was released:
* There seems to have been a change in how const instructions were counted and resulted in the static stream data to fail (see https://github.com/rust-lang/rust/issues/103814). I was able to get around this issue by replacing `data.len()` with `DATA_LEN`.
* The `derive(Debug)` for `PhantomData` now includes the inner `T` in its output. This breaks our snapshot tests so I've implemented a manual debug where it caused issues
I also noticed that the `s2n-quic` crate had not updated its `bolero` dependency as part of #1552. I've also done that here.
> test(s2n-quic-core): reduce const instruction counts

- quic/s2n-quic-core/src/interval_set/tests.rs
The IntervalSet tests seem to be too expensive for miri. Ignoring these seems to make the miri CI more reliable.
The CI tests now pass. Hopefully this fixes it moving forward.
> test(s2n-quic-core): disable miri for interval set tests

- quic/s2n-quic-tls/src/client.rs
- quic/s2n-quic-tls/src/lib.rs
- quic/s2n-quic-tls/src/server.rs
- quic/s2n-quic-tls/src/tests.rs
resolves #1533. resolves #1407.
This change adds a `ConfigLoader` trait to the s2n-quic-tls crate. This allows applications to define the behavior for loading s2n-tls config objects per connection. Specifically this enables the ability to rotate certificates, as the trust store is tied to `Config`s.
This does include a potentially sharp edge of the config needing to be in a valid state for it to be accepted. This includes:
* setting a security policy that supports TLS 1.3
* enabling QUIC support
* setting at least one application protocol
If these requirements aren't met, the connection will fail at runtime. Luckily, the `Server` and `Client` structs implement the `ConfigLoader` themselves so they can be used to correctly construct a valid config.
By submitting this pull request, I …
> feat(s2n-quic-tls): add config loader trait

- .github/config/cargo-deny.toml
- netbench/netbench/src/scenario/id.rs
This PR fixes the following clippy error:
https://github.com/aws/s2n-quic/actions/runs/3422661099/jobs/5700329160
```
error: the borrowed expression implements the required traits
Error:   --> netbench/src/scenario/id.rs:31:41
|
31 |         let out = base64::encode_config(&hash, base64::URL_SAFE_NO_PAD);
|                                         ^^^^^ help: change this to: `hash`
|
= note: `-D clippy::needless-borrow` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
```
And fixes the following duplicate dependency error by ignoring duplicate dependencies in private s2n-quic crates.
https://github.com/aws/s2n-quic/actions/runs/3422661100/jobs/5700327679
```
warning[A007]: advisory was not encountered …
```
> ci: CI fixes

- common/s2n-codec/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
Bumping version numbers for the 1.12.0 release
The following crates were [changed since the 1.11.0 release](https://github.com/aws/s2n-quic/compare/v1.11.0...main):
- common/s2n-codec
- s2n-quic-core
- s2n-quic-crypto
- s2n-quic-platform
- s2n-quic-tls
- s2n-quic-transport
- s2n-quic
> chore: release 1.12.0

- quic/s2n-quic/src/provider/datagram.rs
This allows customer applications to implement their own Receiver/Sender without depending on s2n-quic-core.
I believe this captures everything needed for these implementations to happen without a s2n-quic-core dependency, but I didn't verify this. Some things that aren't covered by this PR but may be useful to implementors (based on the default impls):
* MaxDatagramFrameSize::RECOMMENDED
* packet space smoothing (implemented [here](https://github.com/aws/s2n-quic/blob/e1353ac5b7bebb2ab523748adafcc6400b8130be/quic/s2n-quic-core/src/datagram/default.rs#L426))
But both of these are directly in the RFC text for QUIC, so it doesn't seem like they have to be separately exposed; users can define their own versions easily.
By submitting this pull request, I confirm that my contribution is made …
> Expose the datagram traits from s2n-quic

- quic/s2n-quic-core/src/crypto/initial.rs
- quic/s2n-quic-core/src/crypto/label.rs
- quic/s2n-quic-core/src/crypto/retry.rs
- quic/s2n-quic-core/src/packet/number/mod.rs
- quic/s2n-quic-core/src/packet/number/tests.rs
- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/cubic.rs
- quic/s2n-quic-core/src/recovery/sent_packets.rs
- quic/s2n-quic-core/src/varint/tests.rs
- quic/s2n-quic-crypto/src/one_rtt.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/path/ecn.rs
- quic/s2n-quic-transport/src/path/ecn/tests.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
There used to be an issue in duvet when copying references in appendix sections, where the `appendix-` prefix was assumed to be `section-`. This was fixed in https://github.com/awslabs/duvet/pull/68. 
This change fixes all of the cited appendix links to the correct prefix.
> test: fix duvet appendix links

- quic/s2n-quic-core/src/transport/parameters/mod.rs
The max_ack_delay transport parameter is loaded multiple times. This commit removes that multiple load.
The `max_ack_delay` parameter is currently loaded multiple times. This looks to be redundant, and this commit removes it.
There are no semantic changes expected with this commit. I also wouldn't be surprised if this gets optimized out by the compiler, so I don't expect any performance changes either.
I have this commit under the style tag, since it isn't necessarily a bug fix. And if the compiler is optimizing this out, then it's not a perf thing either.
Passed all unit tests.
> style(s2n-quic-core): remove redundant assignment

- quic/s2n-quic-core/src/datagram/default.rs
- quic/s2n-quic-core/src/datagram/disabled.rs
- quic/s2n-quic-core/src/datagram/traits.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/datagram.rs
- quic/s2n-quic-transport/src/space/mod.rs
This allows the receiver to differentiate the handling based on the connection's remote address. For example, if a datagram receiver wants to process the payload differently depending on the source address, this allows it to do so. The path a connection takes may change over time, so passing this state on each on_datagram call seems like the best bet.
One alternative design (not thoroughly explored) is to expose the datagram payloads to the Subscriber interface, and just have the datagram provider ignore payloads. Since there are no payloads anywhere in that trait today that I can see, it seems like it might be intentional to not surface them there?
This doesn't fully address #1565, but does surface most of the (by me) currently desired information. Based on poking around the code it …
> Give datagram receiver access to current connection path

- quic/s2n-quic/src/connection/handle.rs
The internal API is locking anyway, so there's no need for the &mut here. This doesn't change anything from being *possible* (you can `.clone().datagram_mut(...)` already), but it does mean that callers need that extra clone().
Note that this changes a technically stable API, though I doubt there are users (since datagrams themselves are unstable). The change is also likely to be compatible with most call sites.
No particular testing.
> Remove &mut from datagram_mut

- netbench/netbench-driver/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-tls/src/certificate.rs
- quic/s2n-quic-tls/src/tests.rs
Update s2n-tls bindings and use the new APIs for the async client hello
> build(deps): update s2n-tls to 0.0.21

- examples/async_client_hello_callback/.cargo/config.toml
- examples/async_client_hello_callback/Cargo.toml
- examples/async_client_hello_callback/src/bin/quic_async_client_hello_callback_client.rs
- examples/async_client_hello_callback/src/bin/quic_async_client_hello_callback_server.rs
- quic/s2n-quic-tls/src/lib.rs
- quic/s2n-quic-tls/src/server.rs
pending PR https://github.com/aws/s2n-quic/pull/1587
This example demonstrates the ability for an application to set a `ClientHelloCallback`, which loads the certificate/key associated with the Client. The certificate/key is set on a new Config object and set on the connection. The callback runs as an asynchronous task and caches the result so that subsequent callbacks can resolve immediately.
A test [commit](https://github.com/aws/s2n-quic/commit/ec88c6689d4f42041c2e79557bb6950f7687caf6) which simulates random async task failure (this is likely for network calls). It also demonstrates the Config caching and the async task not running after a successful run.
Server:
```
> ./target/debug/quic_async_client_hello_callback_server
running server ---
simulating network failure. failed: true …
```
> example(client_hello_callback): add an example demonstrating use of the async cert loading

- quic/s2n-quic-core/src/varint/mod.rs
- quic/s2n-quic-core/src/varint/tests.rs
I had a branch from ~6 months ago that included a kani proof showing that the optimized version of the varint table matches the non-optimized version that more clearly matches what the RFC describes. It also included a proof that the math operations matched the underlying `u64` operations, when possible.
```sh
$ cargo kani --tests --harness round_trip_values_test
$ cargo kani --tests --harness table_differential_test
$ cargo kani --tests --harness checked_ops_test
```
[CI Job](https://github.com/aws/s2n-quic/actions/runs/3624251741/jobs/6111021374)
> test(s2n-quic-core): add a bolero harness for the varint table

- .github/workflows/ci.yml
- netbench/netbench/src/scenario.rs
- quic/s2n-quic-core/src/packet/decoding.rs
- quic/s2n-quic-core/src/packet/interceptor.rs
- quic/s2n-quic-core/src/packet/interceptor/loss.rs
- quic/s2n-quic-core/src/recovery/cubic.rs
- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
- quic/s2n-quic-platform/src/message/cmsg.rs
- quic/s2n-quic-platform/src/message/msg.rs
- quic/s2n-quic-platform/src/message/queue/slice.rs
- quic/s2n-quic-platform/src/message/simple.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/stream/receive_stream/tests.rs
- quic/s2n-quic-transport/src/stream/send_stream/tests.rs
- scripts/local_test
Clippy released a couple of broken lints that were rolled back in beta (and eventually the next release). This PR makes an exception for them so it doesn't break our CI.
The exceptions should probably be removed after the next stable release but it isn't a huge deal if it's not.
The CI checks are all passing now.
> ci: ignore more broken clippy lints

- .github/Dockerfile.tshark
- .github/interop/runner.patch
- .github/workflows/qns.yml
- .github/workflows/tshark.yml
The tshark and interop runner started failing after `ubuntu-latest` changed to 22.04 instead of 20.04. This change pins the broken jobs to 20.04 until the interop runner docker image is updated.
The latest version of wireshark has a problem with the longrtt test. This will need a separate fix applied upstream.
> ci: move tshark build to separate workflow

- quic/s2n-quic/src/provider/datagram.rs
This was missed in the original PR review (the type was introduced in a refactor and overlooked as a new thing to expose).
No testing. I think in the future it might be nice to have some kind of pass (with rustdoc-json, maybe?) that validates that there's only intentional non-exposed types in the s2n-quic API, but that would require quite a bit of work I think.
> Expose ReceiveContext too

- quic/s2n-quic-core/src/datagram/default.rs
- quic/s2n-quic-core/src/datagram/traits.rs
- quic/s2n-quic-transport/src/space/session_context.rs
This waker allows datagram receiver/senders to wake up the connection,
which will re-poll the connection for interest in sending. When
implementing a custom datagram Receiver which wants to schedule a reply
datagram, this Waker or something like it is necessary to indirect the
wakeup of the connection and subsequent call to the Sender's
on_transmit.
This is a waker and not a connection handle for two reasons:
* The Waker does not directly extend the lifetime of the connection,
which avoids keeping the connection data indefinitely alive for cases
where the Waker is stored within the Sender or Receiver.
* s2n-quic calling datagram Endpoint::new_connection doesn't have easy
access to an application handle to the connection.
Note that applications still must retain the Connection or a Handle …
> Provide access to connection Waker to datagram Endpoint

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/events/connection.rs
- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/io/testing/model.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/setup.rs
#1444 
This PR adds a `packet_len` field to the `PacketSent` event. It also adds a unit test to check that the `packet_len` is correct.
I don't particularly love the location of the unit test right now, but because it relies on the network simulator and the setup methods, it feels easiest to fit it in the `s2n-quic` crate. 
1. run the client_server interaction on the network simulator
2. capture all network packets transmitted
3. record all PacketSent events from the server
4. ensure that packet sent events have the correct lengths, given that we know the size of the network packets
> add packet_len field to Packet Sent event

- quic/s2n-quic-platform/src/buffer/vec.rs
- quic/s2n-quic-transport/src/connection/connection_container.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/path/mod.rs
- tools/memory-report/src/main.rs
I noticed an issue when determining if a transmission can be included as a GSO segment or not. The current logic is to allow any packet sizes to be considered for GSO, as long we aren't MTU probing. This isn't really ideal, since a previous transmission to the same tuple could have been a small ACK packet. This means we're artificially clamping MTU to the small ACK size, rather than allowing the connection to transmit a full MTU.
This change, instead, only allows GSO on transmissions if the segment size is `>=` than the path's MTU for the current transmission mode. This results in more connections transmitting correctly, rather than bailing since we may end up deciding to not write a packet if the segment size is too small (initial packets, etc).
In experimentation, I also noticed the …
> fix(s2n-quic-transport): only allow GSO of MTU-sized packets

- .github/workflows/ci.yml
- quic/s2n-quic-bench/Cargo.toml
- quic/s2n-quic-bench/src/lib.rs
- quic/s2n-quic-bench/src/sync.rs
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-core/src/slice.rs
- quic/s2n-quic-core/src/sync.rs
- quic/s2n-quic-core/src/sync/__fuzz___/sync__spsc__tests__model/corpus.tar.gz
- quic/s2n-quic-core/src/sync/spsc.rs
- quic/s2n-quic-core/src/sync/spsc/primitive.rs
- quic/s2n-quic-core/src/sync/spsc/recv.rs
- quic/s2n-quic-core/src/sync/spsc/send.rs
- quic/s2n-quic-core/src/sync/spsc/slice.rs
- quic/s2n-quic-core/src/sync/spsc/state.rs
- quic/s2n-quic-core/src/sync/spsc/tests.rs
- quic/s2n-quic-core/src/testing.rs
- quic/s2n-quic-crypto/src/aes/x86.rs
- quic/s2n-quic-crypto/src/aesgcm/generic.rs
- quic/s2n-quic-crypto/src/aesgcm/x86.rs
- quic/s2n-quic-crypto/src/block/x86.rs
- quic/s2n-quic-crypto/src/cipher_suite.rs
- quic/s2n-quic-crypto/src/ghash/x86/precomputed.rs
- quic/s2n-quic-crypto/src/lib.rs
This change adds a `spsc` (single-producer/single-consumer) channel to s2n-quic-core. This will be used to split the endpoint up into multiple tasks, which _should_ improve packet processing latencies.
I needed the `unsafe_assert` macro from `s2n-quic-crypto` moved into `s2n-quic-core` for this. I also renamed it to `assume!`, since you already have to call it in an `unsafe` block, the name seemed redundant.
The feature includes a `bolero` test that generates random sequences of events to push/pop items from the queue. I ran the test under `kani` but am waiting on https://github.com/model-checking/kani/issues/2169 to be released. I also used `loom` to exhaustively explore atomic interleavings and assert that invariants hold in each case (I caught a few _very_ subtle bugs with this - …
> feat(s2n-quic-core): add spsc channel

- quic/s2n-quic-platform/src/socket/std.rs
When a tx error occurs in the standard queue (used for recvfrom and sendto system call) we previously emitted an rx error. This commit corrects this, so now tx failures result in tx error events.
We don't currently have tests for these events, but if there is interest I can add some.
Manually looked through the rest of the queue implementations and confirmed that errors corresponded to the proper methods. See call-out about unit tests.
> fix(s2n-quic-events): correct tx error emission

- .github/workflows/ci.yml
- quic/s2n-quic-core/src/interval_set/tests.rs
- quic/s2n-quic-core/src/packet/number/sliding_window.rs
- quic/s2n-quic-core/src/packet/number/tests.rs
- quic/s2n-quic-core/src/random.rs
- quic/s2n-quic-core/src/slice.rs
- quic/s2n-quic-core/src/sync/spsc/tests.rs
- quic/s2n-quic-core/src/varint/tests.rs
Kani 0.21 was released recently and this is upgrading our version to that. With it, includes the ability to override the solver. After running some performance tests locally, we saw a reduction in proof time for every single one of our proofs by using the `kissat` solver instead of the default (`minisat`). I was even able to enable the `vectored_copy` proof, which was previously marked with `cfg(kani_slow)` as well as expand the `spsc` proof to include more checks, which as also gated behind `cfg(kani_slow)`.
I tested this all locally. Kani is also [part of our CI](https://github.com/aws/s2n-quic/actions/runs/4147909238/jobs/7175336688).
> tests(s2n-quic-core): update kani to 0.21

- common/s2n-codec/src/zerocopy.rs
- quic/s2n-quic-core/src/inet/ethernet.rs
- quic/s2n-quic-core/src/inet/ip.rs
- quic/s2n-quic-core/src/inet/ipv4.rs
- quic/s2n-quic-core/src/inet/ipv6.rs
- quic/s2n-quic-core/src/inet/macros.rs
- quic/s2n-quic-core/src/inet/mod.rs
- quic/s2n-quic-core/src/inet/snapshots/s2n_quic_core__inet__ethernet__tests__snapshot_filled_test.snap
- quic/s2n-quic-core/src/inet/snapshots/s2n_quic_core__inet__ethernet__tests__snapshot_test.snap
- quic/s2n-quic-core/src/inet/snapshots/s2n_quic_core__inet__ipv4__tests__snapshot_filled_test.snap
- quic/s2n-quic-core/src/inet/snapshots/s2n_quic_core__inet__ipv4__tests__snapshot_test.snap
- quic/s2n-quic-core/src/inet/snapshots/s2n_quic_core__inet__ipv6__tests__snapshot_filled_test.snap
- quic/s2n-quic-core/src/inet/snapshots/s2n_quic_core__inet__ipv6__tests__snapshot_test.snap
- quic/s2n-quic-core/src/inet/snapshots/s2n_quic_core__inet__udp__tests__snapshot_filled_test.snap
- quic/s2n-quic-core/src/inet/snapshots/s2n_quic_core__inet__udp__tests__snapshot_test.snap
- quic/s2n-quic-core/src/inet/udp.rs
- specs/www.rfc-editor.org/rfc/rfc768.txt
- specs/www.rfc-editor.org/rfc/rfc8200.txt
When using raw sockets or AF_XDP, the userspace is in charge of complete packet construction and parsing. This includes ethernet, IP, UDP, etc.
This change implements decoding/encoding for
* Ethernet headers, including well-known ethertype values
* IP Protocols for well know values
* IPv4 headers
* IPv6 headers
* UDP headers
Some things are known to be missing at this point and will be added at a later time:
* Checksum calculation for each of the header types
* IPv4 Options parsing
* IPv6 Hop-by-hop/Options parsing
For each of the header formats, I've added:
* Snapshot tests for monotonic byte encodings (i.e. `[0, 1, 2, 3, ...]`)
* Snapshot tests for filled out byte encodings (i.e. `[255, 255, 255, ...]`)
* Round trip decoding and encoding tests
* Getter/setter fuzz tests for the more …
> feat(s2n-quic-core): add L2/L3/L4 inet structs

- .github/workflows/ci.yml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/application/mod.rs
- quic/s2n-quic-core/src/crypto/tls.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/stream/mod.rs
- quic/s2n-quic-core/src/sync/spsc/tests.rs
- quic/s2n-quic-events/src/main.rs
- scripts/test_no_std
I tried pulling s2n-quic-core into a BPF program and got a couple of compilation errors related to no_std. Our current no_std checks are clearly not checking what we thought.
This PR fixes the no_std errors as well as updates the no_std script to compile to BPF instead of the `thumbv7m-none-eabi` target, since this is something that we're wanting to test for anyway.
The netbench MSRV needs to be updated to fix that failing task. However this has already been incorporated into #1630 so I'll just let that take care of it so we don't get merge conflicts.
The [no_std](https://github.com/aws/s2n-quic/actions/runs/4236631844/jobs/7361674444) job is now targeting BPF and passes locally and in CI.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> fix(s2n-quic-core): enable building for bpf applications

- quic/s2n-quic-rustls/src/client.rs
- quic/s2n-quic-rustls/src/server.rs
N/A
Currently, if you have existing `ClientConfig` and `ServerConfig` objects from rustls, in order to feed them into `s2n-quic`, you need to clone the entire backing rustls config objects. This can be an extremely expensive operation memory-wise, especially if you have a large number of certificates installed.
I've changed the code to allow both implementations of tls::Endpoint to be cloned. I've also implemented their respective `From<Arc<*>>` traits to allow you to construct them from existing Arcs. 
N/A
It doesn't alter any major functionality, so if it builds, it should work.
> Allow rustls provider to be cloned and take in Arcs

- quic/s2n-quic-core/src/ct.rs
- quic/s2n-quic-core/src/inet/ipv4.rs
- quic/s2n-quic-core/src/inet/ipv6.rs
- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
N/A
Enable Kani on a few Bolero harnesses (`ct`, `ipv4`, `ipv6`, and `rtt_estimator`). This brings up the number of harnesses run by Kani from 16 to 30.
The runtime goes up by about 4 minutes. Current:
```
Complete - 16 successfully verified harnesses, 0 failures, 16 total.
Command being timed: "cargo kani --tests"
User time (seconds): 412.77
System time (seconds): 22.20
Percent of CPU this job got: 107%
Elapsed (wall clock) time (h:mm:ss or m:ss): 6:43.56
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 3067656
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 527
Minor (reclaiming a frame) page faults: 9324258
Voluntary context switches: …
```
> test(s2n-quic-core): enable kani on a few harnesses

- quic/s2n-quic-bench/Cargo.toml
- quic/s2n-quic-bench/src/inet.rs
- quic/s2n-quic-bench/src/lib.rs
- quic/s2n-quic-core/src/inet/__fuzz__/inet__checksum__tests__differential/corpus.tar.gz
- quic/s2n-quic-core/src/inet/checksum.rs
- quic/s2n-quic-core/src/inet/checksum/__fuzz__/inet__checksum__x86__tests__differential/corpus.tar.gz
- quic/s2n-quic-core/src/inet/checksum/x86.rs
- quic/s2n-quic-core/src/inet/mod.rs
- specs/www.rfc-editor.org/rfc/rfc1071.txt
When constructing raw IP and UDP packets, we need a way to compute the checksum for the appropriate fields. This PR implements the internet checksum function, as described in [RFC1071](https://www.rfc-editor.org/rfc/rfc1071).
I wanted to see if using SIMD/x86 intrinsics could improve performance at all over the generic version. Turns out that it's pretty significant! Below are the comparisons to [Fuchsia's internet-checksum crate](https://docs.rs/internet-checksum), which itself is pretty optimized.
```
inet/s2n/checksum/1500  time:   [27.122 ns 27.129 ns 27.136 ns]
thrpt:  [51.482 GiB/s 51.494 GiB/s 51.508 GiB/s]
inet/fuchsia/checksum/1500
time:   [59.451 ns 59.478 ns 59.504 ns]
thrpt:  [23.477 GiB/s 23.488 GiB/s 23.498 GiB/s]
inet/s2n/checksum/9000  time:   [146.39 ns 146.41 ns 146.44 …
```
> feat(s2n-quic-core): add IP checksum function

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/varint/mod.rs
- quic/s2n-quic-events/events/connection.rs
- quic/s2n-quic-transport/src/ack/ack_manager.rs
- quic/s2n-quic-transport/src/contexts/mod.rs
- quic/s2n-quic-transport/src/transmission/context.rs
resolves: https://github.com/aws/s2n-quic/issues/1416
Specialize `write_frame` for ack frame: `write_ack_frame`.
Advantage: essentially zero-cost: `write_ack_frame` only specializes for `Frame::Ack` anyway.
Alternatives considered:
1. expose `get_publisher(&self) -> &mut Publisher` (requires exposing generic Publisher through `WriteContext`)
2. Add a method `on_ack_range_sent` to `WriteContext` accepting `event::builder::AckRangeSent`/`AckRanges` (It looks slightly ad-hoc, and a lot of data-passing, may as well combine into `write_ack_frame`). 
Not sure how to generate appropriate tests - `MockContext` for `WriteContext` currently doesn't accept a publisher.
Here is some sample output running the `event-framework` example with the `async-client` example. 
As you can see, `AckRangeSent` is …
> feat(event): `WriteContext::write_ack_frame` records events `AckRangeSent`

- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
Currently s2n-quic enforces a minimum RTT estimate of 1 millisecond, which may be too high a value for intra datacenter connections. I thought this might be an RFC requirement, but it [looks like](https://github.com/aws/s2n-quic/pull/38/commits/601df33f700fade618b289b9846071ab128d04bb#r458321409) we just did it to save on having an `is_first_rtt_sample` in the `RTTEstimator` (which we ended up adding back in anyway). This change reduces the minimum RTT estimate to 1 microsecond.
Updated existing unit test
> fix(s2n-quic-core): decrease minimum allowed RTT sample to 1 microsecond

- common/s2n-codec/src/encoder/buffer.rs
- common/s2n-codec/src/encoder/estimator.rs
- common/s2n-codec/src/encoder/mod.rs
- common/s2n-codec/src/lib.rs
- quic/s2n-quic-bench/src/lib.rs
- quic/s2n-quic-bench/src/xdp.rs
- quic/s2n-quic-core/src/inet/checksum.rs
- quic/s2n-quic-core/src/inet/ecn.rs
- quic/s2n-quic-core/src/inet/ethernet.rs
- quic/s2n-quic-core/src/inet/ip.rs
- quic/s2n-quic-core/src/inet/ipv6.rs
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-core/src/xdp.rs
- quic/s2n-quic-core/src/xdp/__fuzz__/xdp__encoder__tests__round_trip/corpus.tar.gz
- quic/s2n-quic-core/src/xdp/bpf.rs
- quic/s2n-quic-core/src/xdp/decoder.rs
- quic/s2n-quic-core/src/xdp/encoder.rs
- quic/s2n-quic-core/src/xdp/path.rs
- specs/www.rfc-editor.org/rfc/rfc2460.txt
This change adds some XDP utilities to s2n-quic-core:
* A raw packet decoder, which is also BPF-aware and can be compiled into a BPF program (coming later)
* A raw packet encoder
* A new raw `path::Handle` which now stores the ethernet addresses in addition to IP/port.
* I noticed that the EncoderBuffer wasn't being optimized if the compiler knew that a write would be in bounds. So I had to remove the `#[forbid(unsafe)]` in `s2n_codec` to ensure it was optimized.
* I had to add/fix a few small things in various `inet` modules
I added a bolero test that generates a bunch of random paths and packet values and encodes them and ensures they all decode to the exact same input values.
I wrote a bunch of these random packets out to a pcap file and opened them in wireshark to ensure they parsed …
> feat(s2n-quic-core): add XDP helper modules

- netbench/netbench-driver/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-tls/src/certificate.rs
- quic/s2n-quic-tls/src/server.rs
- quic/s2n-quic-tls/src/tests.rs
- quic/s2n-quic/Cargo.toml
Surface the new private key offloading feature from the s2n-tls Rust bindings.
I only made the feature available on the server for now, but it should be fairly trivial to extend to the client if necessary.
Added a test of the handshake with private key offloading.
> feat(s2n-quic-tls): add support for s2n-tls private key offload

- common/s2n-codec/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
Updates the s2n-quic version to 1.17.0.
> chore: release 1.17.0

- quic/s2n-quic-platform/src/socket/std.rs
Resolves #1448
As discussed in #1448, Windows raises a ConnectionReset if the remote side executes a hard or abortive close. From the [recvfrom API](https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-recvfrom) for WSAECONNRESET:
> The virtual circuit was reset by the remote side executing a hard or abortive close. The application should close the socket; it is no longer usable. On a UDP-datagram socket this error indicates a previous send operation resulted in an ICMP Port Unreachable message.
Instead of panicing when this happens, we should ignore the error and continue processing entries.
This PR is a copy of the code from #1448 as recommended by @camshaft. 
Tested locally to confirm that a ConnectionReset no longer causes a panic.
By submitting this pull request, I …
> fix(s2n-quic-platform): handle ConnectionReset on Win sockets (#1448)

- quic/s2n-quic-core/src/frame/crypto.rs
- quic/s2n-quic-core/src/stream/iter.rs
N/A
Enable Kani on a few Bolero harnesses (try_fit_test and fuzz_builder). This brings up the number of harnesses run by Kani from 32 to 34.
The runtime doesn't change much on my local machine. Current:
```
Complete - 32 successfully verified harnesses, 0 failures, 32 total.
Command being timed: "cargo kani --tests"
User time (seconds): 2075.21
System time (seconds): 43.13
Percent of CPU this job got: 100%
Elapsed (wall clock) time (h:mm:ss or m:ss): 34:59.25
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 2261392
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 14352
Minor (reclaiming a frame) page faults: 14704137
Voluntary context …
```
> test(s2n-quic-core): Enable Kani on more Bolero harnesses

- .github/workflows/ci.yml
- quic/s2n-quic-h3/Cargo.toml
- quic/s2n-quic-h3/README.md
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
* add alloc dependency to rustls and tls crates
* add default dependency to h3 crate
* add CI step to check that each crate builds.
Note that the name of this PR is confusing. "default" features is literally referring to "the set of features included when build is invoked directly on the package", and not necessarily cargo's concept of "default-features".
Currently we are unable to release to crates.io because `s2n-quic-rustls` and `s2n-quic-tls` do not build with default features. This happened because in a #1633 , components that `s2n-quic-rustls` depends on were moved behind the `alloc` feature flag.
We failed to detect this in our CI because the workspace build builds from `s2n-quic` with `default` features enabled. This build happens successfully because the `alloc` feature is …
> fix(s2n-quic-rustls, s2n-quic-tls): enable building with default features

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
updates s2n-quic to 1.17.1
1.17.0 was not released. I don't expect there to be any particular complications with that, but please comment if you see some issue with that.
CI should pass
> chore: release 1.17.1

- .github/interop/required.json
- .github/workflows/ci.yml
- quic/s2n-quic-crypto/Cargo.toml
Zeroize [recently broke generic bounds](https://github.com/RustCrypto/utils/issues/878) in the derive macro. The fix in https://github.com/RustCrypto/utils/pull/879 does not resolve our current usage of the macro.
This change pins the dependency until a fix is available.
> fix(s2n-quic-crypto): pin zeroize_derive until fixed

- examples/turmoil-provider/Cargo.toml
- examples/turmoil-provider/rust-toolchain
- examples/turmoil-provider/src/lib.rs
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-platform/src/io.rs
- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/io/turmoil.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/lib.rs
- quic/s2n-quic/src/provider/io.rs
- quic/s2n-quic/src/provider/io/turmoil.rs
This change adds an experimental IO provider for [turmoil](https://github.com/tokio-rs/turmoil). This allows applications to inject latency and faults into packet transmission and make assertions about behavior.
I've added [an example](https://github.com/aws/s2n-quic/blob/1c608baacd008bf89b546b399658de57a492bd3a/examples/turmoil-provider/src/lib.rs) of how an application might use the s2n-quic API to perform this kind of testing.
I [added a test](https://github.com/aws/s2n-quic/pull/1663/files#diff-ba0fdd8c77c39fdcb6d19223f03ba597a13af1b74607c7b092a3ccf7bb7a0a81R434) for the provider, similar to the [tokio provider tests](https://github.com/aws/s2n-quic/blob/36ee44ad66c07e44389d834cea07e13726719884/quic/s2n-quic-platform/src/io/tokio.rs#L777). The example can also be executed and show …
> feat: add experimental turmoil IO provider and example

- quic/s2n-quic-core/src/packet/number/map.rs
Adds a kani proof. Note that this takes approx 30 min on my mac to run.
> testing: kani test for packet number map

- quic/s2n-quic-transport/src/path/mtu.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic/src/tests.rs
resolves #1680
This change decreases the sensitivity of MTU black hole detection by requiring >3 distinct bursts of packet loss to trigger a blackhole, rather then >3 individual packets. 
I had to update the `interceptor_failure_test`, as it was not panicking anymore after this change. I guess the decreased likely hood of a blackhole meant a higher MTU was maintained and all the data was being transmitted before the test would time out as expected.
Added integration tests and updated existing unit tests.
> fix(s2n-quic-transport): decrease sensitivity of MTU black hole detection

- quic/s2n-quic-core/src/recovery/bbr/full_pipe.rs
BBR is supposed to exit startup when 3 consecutive rounds do not increase the estimated bandwidth by 25%:
> If BBR notices that there are several (three) rounds where attempts to double
the delivery rate actually result in little increase (less than 25 percent),
then it estimates that it has reached BBR.max_bw, sets BBR.filled_pipe to true,
exits Startup and enters Drain.
The ratio used to represent a 25% increase was incorrectly set to 4/3 (133%) rather than 5/4 (125%). This corrects that ratio
Corrected the unit test too
> fix(s2n-quic-core):  Use correct delivery rate increase ratio in BBR

- quic/s2n-quic-core/src/connection/limits.rs
- quic/s2n-quic-qns/src/perf.rs
- quic/s2n-quic-transport/src/stream/manager.rs
- quic/s2n-quic/src/tests.rs
https://github.com/aws/s2n-quic/issues/1675
[Limits::with_data_window](https://docs.rs/s2n-quic/latest/s2n_quic/provider/limits/struct.Limits.html#method.with_data_window) accepts a u64 and is a limit specified by our users. In the `debug` build, we currently enforce that max_data limit is [<= u32::MAX](https://github.com/aws/s2n-quic/blob/5ba26ae6d243d1ad53d518245064e2d592a246f9/quic/s2n-quic-transport/src/stream/manager.rs#L429-L432) with a debug_assert. In the `release` build, the debug_assert is compiled out and applications can erroneously provide a value larger than u32::MAX.
This PR adds validation to the Limits builder which checks the value is less than u32 and provides a better user error. I also added comments on why its reasonable to restrict the value to u32 in this case. …
> fix(s2n-quic-core): enforce max data limit size for stream and connection

- quic/s2n-quic-core/src/recovery/bbr/data_rate.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
- quic/s2n-quic-core/src/recovery/bbr/snapshots/quic__s2n-quic-core__src__recovery__bbr__probe_bw__events__update_ack_phase.snap
BBRv2 uses a `WindowedMaxFilter` of size 2 to track the maximum bandwidth sample that had been obtained over the current bandwidth probing cycle and the previous bandwidth probing cycle. The way this is supposed to work is each time BBR completes a cycle from ProbeBW_Down -> ProbeBW_Cruise -> ProbeBW_Refill -> ProbeBW_Up, a counter is incremented. 
This can be seen in the [BBR draft RFC](https://www.ietf.org/archive/id/draft-cardwell-iccrg-bbr-congestion-control-02.html#section-4.3.3.6-8) pseudo-code. `BBRAdvanceMaxBwFilter()` increments the counter:
```
if (BBR.ack_phase == ACKS_PROBE_STOPPING and BBR.round_start)
/* end of samples from bw probing phase */
if (IsInAProbeBWState() and !rs.is_app_limited)
BBRAdvanceMaxBwFilter()
```
Unfortunetly this pseudocode does not change the …
> fix(s2n-quic-core): Advance max bw filter only once per probe bw cycle

- quic/s2n-quic-qns/src/perf.rs
This change adds the maximum pacing rate and maximum delivery rate that has been observed over the reporting interval to the stats output from the Perf client and server. I've also added a header to the output.
Delivery rate is only recorded for BBRv2, so if CUBIC is being used this will always report 0bps.
Ran the perf client:
```
Tx Rate Rx Rate Max Cwnd        Max Inflight    Lost Packets    Wakeups Duration        Max RTT Max SRTT        PTO Count       Max Pacing Rate Max Delivery Rate
435.67Mbps      0bps    1.93MB  1.84MB  0       769     26.492ms        30.159ms        18.832736ms     0       872.70Mbps      642.06Mbps
443.62Mbps      0bps    6.30MB  3.86MB  0       791     83.642ms        62.176ms        45.982567ms     0       635.68Mbps      535.11Mbps
479.89Mbps      0bps …
```
> feat(s2n-quic-qns): Add max pacing rate and delivery rate to perf stats

- netbench/netbench-driver/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
Bumping the s2n-tls versions.
The CI
> build(deps): update s2n-tls requirement from =0.0.26 to =0.0.29

- .github/workflows/ci.yml
- tools/xdp/Cargo.toml
- tools/xdp/lib/s2n-quic-xdp-bpfeb-trace.ebpf
- tools/xdp/lib/s2n-quic-xdp-bpfeb.ebpf
- tools/xdp/lib/s2n-quic-xdp-bpfel-trace.ebpf
- tools/xdp/lib/s2n-quic-xdp-bpfel.ebpf
- tools/xdp/s2n-quic-xdp/Cargo.toml
- tools/xdp/s2n-quic-xdp/README.md
- tools/xdp/s2n-quic-xdp/src/if_xdp.rs
- tools/xdp/s2n-quic-xdp/src/lib.rs
- tools/xdp/xtask/src/build_ebpf.rs
This PR:
* initializes the s2n-quic-xdp crate. This will be the crate applications pull in to enable AF-XDP support in the IO provider.
* Adds the `if_xdp.rs` module, which implements the structs, flags, and definitions in [the kernel](https://github.com/torvalds/linux/blob/master/include/uapi/linux/if_xdp.h).
The `if_xdp` could _probably_ have been auto-generated with bindgen. However, the macro definitions aren't correctly translated, since they don't have an explicit type. I also wanted to make it a bit more ergonomic by using the `bitflags` crate, expanding the struct names/fields, and adding some additional documentation and references.
I also regenerated the bpf code while I was here, as a few dependencies have been updated since they were last committed.
The [xdp CI …
> feat(s2n-quic-xdp): add if_xdp module

- .github/workflows/ci.yml
- tools/xdp/s2n-quic-xdp/Cargo.toml
- tools/xdp/s2n-quic-xdp/src/lib.rs
- tools/xdp/s2n-quic-xdp/src/mmap.rs
- tools/xdp/s2n-quic-xdp/src/syscall.rs
- tools/xdp/xtask/src/ci.rs
This PR adds a `syscall` module which contains all of the required interactions for AF_XDP sockets. I've tried to link to all of the relevant parts in libxdp. I also implemented a small mmap abstraction that cleans itself up on `drop` to make it easier to test some of the syscalls.
The syscalls are relatively low level, still. Higher-level abstractions are in the works.
I updated the `xtask ci` script to include tests that run under `sudo`, which has permission to open raw sockets. 
> feat(s2n-quic-xdp): add syscall module

- tools/xdp/s2n-quic-xdp/src/lib.rs
- tools/xdp/s2n-quic-xdp/src/umem.rs
This PR adds the last component of the libxdp port. This is the UMEM component which holds the region of memory with actual packet data. It can be indexed with either a UmemDescriptor and RxTxDescriptor. However, this is not a safe operation since descriptors can be forged and/or copied, meaning holding one doesn't guarantee uniqueness. Luckily, this API will just be internal implementation details of the XDP IO provider so I don't think we need a completely safe abstraction (which could affect performance).
I added a simple test making sure the indexing works. I've also got an overall integration test in another branch that shows this working.
> feat(s2n-quic-xdp): add umem module

- tools/xdp/s2n-quic-xdp/src/lib.rs
- tools/xdp/s2n-quic-xdp/src/ring.rs
- tools/xdp/s2n-quic-xdp/src/ring/__fuzz__/ring__cursor__tests__oracle/corpus.tar.gz
- tools/xdp/s2n-quic-xdp/src/ring/cursor.rs
- tools/xdp/s2n-quic-xdp/src/socket.rs
This change adds the XDP ring data structure for coordinating with the kernel. Most of this code is based on the [xsk.h](https://github.com/xdp-project/xdp-tools/blob/master/headers/xdp/xsk.h) file from the xdp-project.
Each ring type (TX, RX, Fill, Comp) wraps the generic Ring structure and exports a well-typed API.
I considered generating bindings from the libxdp project for this. However, the implementation is all contained in the header, which bindgen has a hard time with - none of the meaningful functions are actually exposed. This means this logic has to be either wrapped in a C module or it needs to be ported to Rust. In this case I opted for porting it, since we'd potentially incurring runtime costs without cross-language LTO enabled. It also keeps the build simpler.
I added a …
> feat(s2n-quic-xdp): add ring module

- Cargo.toml
Cargo complains about a crate depending on another crate in a subdirectory that isn't part of a workspace:
```
$ cargo build
error: package `/home/cameron/Projects/aws/s2n-quic/tools/xdp/s2n-quic-xdp/Cargo.toml` is a member of the wrong workspace
expected: /home/cameron/Projects/aws/s2n-quic/Cargo.toml
actual:   /home/cameron/Projects/aws/s2n-quic/tools/xdp/Cargo.toml
```
Adding an explicit `exclude` field to the root workspace fixes this issue.
> build: add excluded directories for main workspace

- tools/xdp/s2n-quic-xdp/src/if_xdp.rs
- tools/xdp/s2n-quic-xdp/src/mmap.rs
- tools/xdp/s2n-quic-xdp/src/ring.rs
- tools/xdp/s2n-quic-xdp/src/socket.rs
- tools/xdp/s2n-quic-xdp/src/syscall.rs
- tools/xdp/s2n-quic-xdp/src/umem.rs
I ran into a couple of incompatibilities with our current MSRV (1.63) and the XDP code. Namely:
* the AsRawFd trait was exposed in a generic location (`std::os`) in a later version. However, the same trait is still available in `std::os::unix` so we can just use that since XDP is always going to be Linux-specific.
* The 1.63 rustc complains about nested `unsafe` blocks in the `libc` macro so I just opted to make the caller responsible for the unsafe block.
* The structs with raw pointers needed `Sync` and `Send` impls, which are safe according to the inline comments.
> fix(s2n-quic-xdp): use unix-specific traits for better compat

- examples/async-client-hello-callback/src/bin/quic_async_client_hello_callback_server.rs
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic/src/tests/setup.rs
- tools/xdp/s2n-quic-xdp/Cargo.toml
> ci: fix errors

- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic/src/tests.rs
PTO is a loss recovery mechanism that works by sending packet probes to the peer to trigger an acknowledgement. Repeated probes are separated by a time value calculated using the round trip time estimate and a backoff factor. The backoff factor is reset each time a packet number space is discarded, as this is an indication of connection progress. During the handshake, this backoff factor was being reset each time a handshake packet was transmitted. This PR fixes this by only resetting the backoff factor once when the initial space is discarded.
Adds an integration test.
> fix(s2n-quic-transport): reset PTO backoff once per space discard

- quic/s2n-quic/src/tests/setup.rs
Generate timestamps from the IO provider for our testing
> test(s2n-quic): generate tracing timestamps from the IO provider during testing

- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
Currently the PTO period is calculated by converting RTT `Duration`s to milliseconds as an optimization (see #1493). This change updates this calculation to use microseconds as the minimum allowed RTT is now 1 microsecond (#1651). 
I updated the Godbolt link with one using microseconds and the results look similar
Updated unit tests
> fix(s2n-quic-core): calculate PTO period with microsecond precision

- README.md
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-crypto/src/aesgcm/ring.rs
- quic/s2n-quic-crypto/src/cipher_suite.rs
- quic/s2n-quic-crypto/src/cipher_suite/negotiated.rs
- quic/s2n-quic-crypto/src/cipher_suite/ring.rs
- quic/s2n-quic-crypto/src/header_key.rs
- quic/s2n-quic-crypto/src/initial.rs
- quic/s2n-quic-crypto/src/iv.rs
- quic/s2n-quic-crypto/src/lib.rs
- quic/s2n-quic-crypto/src/one_rtt.rs
- quic/s2n-quic-crypto/src/retry.rs
- quic/s2n-quic-tls/src/callback.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/provider/address_token/default.rs
Relates to #1683
This change migrates the cryptographic library used on unix platforms from [ring](https://crates.io/crates/ring) to [aws-lc-rs](https://crates.io/crates/aws-lc-rs).
aws-lc-rs does not yet support Windows platforms, but support for Windows is planned. For non-unix platforms, ring will continue to be used.
Performed the release build and tests. Ran rustfmt and clippy.
> feat(s2n-quic-crypto): use aws-lc-rs on linux/aarch64

- quic/s2n-quic-core/src/sync.rs
- quic/s2n-quic-core/src/sync/primitive.rs
- quic/s2n-quic-core/src/sync/spsc.rs
- quic/s2n-quic-core/src/sync/spsc/recv.rs
- quic/s2n-quic-core/src/sync/spsc/send.rs
- quic/s2n-quic-core/src/sync/spsc/state.rs
- quic/s2n-quic-core/src/sync/spsc/tests.rs
- quic/s2n-quic-core/src/sync/worker.rs
- quic/s2n-quic-core/src/testing.rs
The change adds a synchronization module that I've extracted from the AF_XDP work. The module is useful for scenarios where a worker needs a mechanism to know if it has outstanding work to do and a way for work producers to wake it up if it's gone to sleep.
In the AF_XDP provider, there isn't a mechanism to `poll` on the completion queue so we're left with busy polling. The problem is we only need to busy poll while there is outstanding packets in the TX queue.
I've refactored some of the `spsc` code to make it easier to share the testing facilities between the two modules.
This includes a few `loom` tests to check that it behaves correctly in all ordering interleavings. It actually caught an error where the Sender didn't implement drop and notified the Receiver, thus resulting in a …
> feat(s2n-quic-core): add sync::worker module

- .github/workflows/ci.yml
- tools/xdp/s2n-quic-xdp/Cargo.toml
- tools/xdp/s2n-quic-xdp/src/if_xdp.rs
- tools/xdp/s2n-quic-xdp/src/lib.rs
- tools/xdp/s2n-quic-xdp/src/ring.rs
- tools/xdp/s2n-quic-xdp/src/ring/cursor.rs
- tools/xdp/s2n-quic-xdp/src/socket.rs
- tools/xdp/s2n-quic-xdp/src/task.rs
- tools/xdp/s2n-quic-xdp/src/task/completion_to_tx.rs
- tools/xdp/s2n-quic-xdp/src/task/completion_to_tx/assign.rs
- tools/xdp/s2n-quic-xdp/src/task/rx.rs
- tools/xdp/s2n-quic-xdp/src/task/rx_to_fill.rs
- tools/xdp/s2n-quic-xdp/src/task/testing.rs
- tools/xdp/s2n-quic-xdp/src/task/tx.rs
This PR adds a set of async tasks responsible for managing ring buffer and queue state
Fundamentally, each task takes a set of input sources and routes them to one or more output
queues. Each task is generic over the execution environment, meaning it can be using in
something driven by polling for events, like `tokio`, or spawned on its own thread in a busy
poll loop.
These new tests caught an issue in the ring cursor implementation that deadlocked if the consumer consumed the entire ring from being completely full. Very fun to debug that one...
The ordering of operations in each of the tasks is critical for correctness. It's very easy to
get into a deadlock if things aren't exactly right. As such, each task has a fuzz test that
tries to show the tasks working properly, even in extreme …
> feat(s2n-quic-xdp): add async tasks

- common/s2n-codec/src/lib.rs
- quic/s2n-quic-core/src/inet/ip.rs
- quic/s2n-quic-core/src/inet/mod.rs
- quic/s2n-quic-core/src/xdp/decoder.rs
- quic/s2n-quic-core/src/xdp/encoder.rs
- quic/s2n-quic-core/src/xdp/path.rs
- tools/xdp/ebpf/rust-toolchain.toml
- tools/xdp/ebpf/src/main.rs
- tools/xdp/lib/s2n-quic-xdp-bpfeb-trace.ebpf
- tools/xdp/lib/s2n-quic-xdp-bpfeb.ebpf
- tools/xdp/lib/s2n-quic-xdp-bpfel-trace.ebpf
- tools/xdp/lib/s2n-quic-xdp-bpfel.ebpf
While implementing the AF_XDP IO provider, I realized I didn't expose a way to get the ECN value out of the XDP decoding function. I've repurposed the `Validator` trait to be a more generic `EventHandler` trait which has callbacks for each of the different types of headers we handle. I've also implemented this trait for the `xdp::path::Tuple` and `datagram::Header` to make it easy to extract all of the required information for the IO traits.
The latest nightly started complaining about conflicting exports in `inet` - each module has a `Header` and does a `pub use module::*;`. I made it so they all explicitly export types that are used in the code base.
All of the XDP decoder tests should handle this change. I've also updated the BPF programs and checked that they continue to load and pass …
> refactor(s2n-quic-core): use an event handler for XDP decoding

- quic/s2n-quic-core/src/path/mod.rs
- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/lib.rs
- quic/s2n-quic-platform/src/syscall.rs
While implementing the AF_XDP IO provider, I need a way to create a configured UDP socket outside of the tokio IO provider to reserve the port for the endpoint.
This change moves all of the syscalls out of the tokio IO provider into a separate module.
While I was here, I realized that we were allowing MTU probing to occur even on platforms where we can't guarantee the DF bit is set. I've gone ahead and added logic to set the max MTU to the minimum value in these cases:
https://github.com/aws/s2n-quic/blob/f1beb3dc9e81d4c2e73f4a22560105304ab07c69/quic/s2n-quic-platform/src/io/tokio.rs#L139-L142
Since this is just extracting function calls into a separate module, the existing tests should cover the differences. I've opened an issue to implement a test that the MTU sizes are correct on …
> refactor(s2n-quic-platform): move socket config to separate module

- quic/s2n-quic-core/src/io/rx.rs
- quic/s2n-quic-core/src/io/tx.rs
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/io/turmoil.rs
- quic/s2n-quic-platform/src/message.rs
- quic/s2n-quic-platform/src/message/macros.rs
- quic/s2n-quic-platform/src/message/mmsg.rs
- quic/s2n-quic-platform/src/message/msg.rs
- quic/s2n-quic-platform/src/message/queue/slice.rs
- quic/s2n-quic-platform/src/message/simple.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
While implementing the AF_XDP IO provider, I wanted to make a generic event loop implementation so I didn't have to copy/paste the one from the tokio provider.
In this change, the core IO traits are refactored to make it possible to use in the generic IO provider event loop.
The previous versions of the IO traits assumed that all of the incoming and outgoing packets were addressable through a slice. This was done to integrate with something like [`rayon`](https://docs.rs/rayon/latest/rayon/) to perform packet crypto in parallel. The problem is that assumption isn't really the case with AF_XDP, where we're putting descriptors in a ring buffer and they're not dereferenceable without the `UMEM`. I also think there's other ways to perform packet encryption in parallel that don't force the IO …
> refactor(s2n-quic-core): simplify IO traits

- quic/s2n-quic-core/src/time/clock.rs
- quic/s2n-quic-core/src/time/clock/std.rs
- quic/s2n-quic-core/src/time/clock/testing.rs
- quic/s2n-quic-core/src/time/mod.rs
- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/io/testing/time.rs
- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/io/tokio/clock.rs
- quic/s2n-quic-platform/src/io/turmoil.rs
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic-transport/src/ack/ack_manager.rs
- quic/s2n-quic-transport/src/ack/tests/environment.rs
- quic/s2n-quic-transport/src/ack/tests/simulation.rs
- quic/s2n-quic-transport/src/connection/close_sender.rs
- quic/s2n-quic-transport/src/connection/local_id_registry/tests.rs
- quic/s2n-quic-transport/src/connection/peer_id_registry/tests.rs
- quic/s2n-quic-transport/src/endpoint/version.rs
- quic/s2n-quic-transport/src/path/ecn/tests.rs
- quic/s2n-quic-transport/src/path/mtu.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/handshake_status.rs
- quic/s2n-quic-transport/src/space/handshake_status/fuzz_target.rs
- quic/s2n-quic-transport/src/stream/manager/tests.rs
- quic/s2n-quic-transport/src/stream/testing.rs
- quic/s2n-quic-transport/src/sync/data_sender.rs
- quic/s2n-quic-transport/src/sync/flag.rs
While implementing the AF_XDP IO provider, I wanted to make a generic event loop implementation so I didn't have to copy/paste the one from the tokio provider. Today, the clock to get the current time is generic. However, there's no trait for getting a timer from the clock and `await`ing on its expiration.
In this change, the clock and timer traits are refactored to make it possible to use in the IO provider event loop. This is done by adding a `ClockWithTimer` trait that is used in the IO event loop.
While I was changing the interface, I went through and removed all references to `s2n-quic-platform` in  `s2n-quic-transport` with the `testing` module in `s2n-quic-core`. This simplifies the testing dependencies a bit and makes it so every crate can use the clock in a consistent way. The …
> refactor(s2n-quic-core): simplify clock and timer traits

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
Bump all the versions for a release.
xdp broke when I bumped core. Instead of updating its pinned version, I just removed the version requirement since we're getting the crate from a local location anyway.
No new tests.
> chore: release version bump

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/io/event_loop.rs
- quic/s2n-quic-core/src/io/event_loop/select.rs
- quic/s2n-quic-core/src/io/mod.rs
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-platform/src/io.rs
- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/io/turmoil.rs
Using the refactors from #1734 and #1733, this PR adds a generic event loop implementation to make it easier to maintain the existing IO providers and develop new ones. I've updated the `io/testing` IO provider to use the new event loop and was able to remove quite a bit of code. This event loop will also be used in the new AF_XDP IO provider.
Note that I haven't changed either the tokio or turmoil event loops in this PR, since that will require some additional work to implement the new `Rx` and `Tx` traits for `platform/message/Queue`. This is tracked in #1746.
The event loop is being tested through the `io/testing` provider and all of the associated integration tests that use it. I've opened #1745 to track this.
By submitting this pull request, I confirm that my contribution is made …
> feat(s2n-quic-core): add generic IO event loop

- examples/custom-congestion-controller/.cargo/config.toml
- examples/custom-congestion-controller/Cargo.toml
- examples/custom-congestion-controller/README.md
- examples/custom-congestion-controller/src/bin/main.rs
- examples/custom-congestion-controller/src/lib.rs
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/recovery/congestion_controller.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/client/builder.rs
- quic/s2n-quic/src/lib.rs
- quic/s2n-quic/src/provider.rs
- quic/s2n-quic/src/provider/congestion_controller.rs
- quic/s2n-quic/src/server/builder.rs
This change removes the `unstable-provider-congestion-controller` feature that was previously required to use a congestion controller other than the default. In addition, this change introduces a `unstable-congestion-controller` feature to allow users to implement their own congestion controllers. I've also included an example of implementing a custom congestion controller.
The [sealed trait](https://rust-lang.github.io/api-guidelines/future-proofing.html#sealed-traits-protect-against-downstream-implementations-c-sealed) pattern is used to prevent implementation of the `CongestionController` trait.
I believe removing the `unstable-provider-congestion-controller` feature is not backward compatible, though since it is unstable that is OK. 
Tested via the included example code.
By submitting …
> feat(s2n-quic): Stabilize congestion control provider and allow for custom congestion controllers

- quic/s2n-quic-core/src/sync/spsc/recv.rs
- quic/s2n-quic-core/src/sync/spsc/send.rs
- quic/s2n-quic-core/src/sync/spsc/state.rs
While testing the AF_XDP IO provider, I noticed that the spsc cursors would only reload capacity once they didn't have any capacity. This led to unoptimal situations where we would wake up to only be able to send a single message, when in reality we could have sent more if we would have reloaded the cursor.
This is a bit more expensive since we're fetching cursor counts every time we load the slice. However, overall it does make things more efficient since we're not waking up as much and processing messages in bulk.
Since this is an implementation detail, the existing tests should suffice.
> fix(s2n-quic-core): skip check in spsc cursors before loading peer value

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/sync/spsc/state.rs
- quic/s2n-quic-core/src/sync/worker.rs
The cache-padded crate was deprecated in favor of crossbeam-utils crate. This change now gets cache_padded from crossbeam.
cargo clippy passes.
> build(deps): switch cache-padded to crossbeam-utils

- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-platform/src/io.rs
- quic/s2n-quic-platform/src/io/xdp.rs
- quic/s2n-quic-platform/src/io/xdp/builder.rs
- quic/s2n-quic-platform/src/syscall.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/lib.rs
- quic/s2n-quic/src/provider/io.rs
- quic/s2n-quic/src/provider/io/xdp.rs
- tools/xdp/s2n-quic-xdp/src/lib.rs
- tools/xdp/s2n-quic-xdp/src/ring.rs
- tools/xdp/s2n-quic-xdp/src/ring/cursor.rs
- tools/xdp/s2n-quic-xdp/src/umem.rs
This change exports an experimental XDP IO provider in the s2n-quic crate.
Because there are many ways to configure AF_XDP sockets, it currently exports a very large API. As we gather more information about how the setup could be made more standardized the exported types can be reduced.
> feat(s2n-quic): add experimental XDP IO provider

- .github/workflows/release.yml
- quic/s2n-quic-qns/etc/Dockerfile.build
In #1749, we added the s2n-quic-xdp crate as an optional dependency to `s2n-quic`. This caused issues for the release workflow since the `tools/xdp` directory wasn't being added to the docker build.
I've enabled the workflow to run on pull requests to prevent this kind of issue in the future.
> ci: fix release workflow

- tools/xdp/s2n-quic-xdp/src/task/rx.rs
- tools/xdp/s2n-quic-xdp/src/task/rx/tokio_impl.rs
- tools/xdp/s2n-quic-xdp/src/task/tx.rs
- tools/xdp/s2n-quic-xdp/src/task/tx/tokio_impl.rs
This PR implements the tx/rx traits for tokio sockets, including ones behind an `Arc`. This allows TX AF_XDP sockets to be `poll`ed to drive progress rather than `send_to`.
I changed the TX trait a bit to better capture the differences between the TX queue sending items and not having capacity to send. I've also refactored the impls into their own module to shorten the length of the file.
> feat(s2n-quic-xdp): implement tx/rx traits for shared tokio sockets

- tools/xdp/s2n-quic-xdp/src/io.rs
- tools/xdp/s2n-quic-xdp/src/io/rx.rs
- tools/xdp/s2n-quic-xdp/src/io/tests.rs
- tools/xdp/s2n-quic-xdp/src/io/tx.rs
While integrating the AF_XDP IO provider into the qns application, I needed to have a channel per NIC queue on the TX and RX paths. This drove a refactor of the IO trait impls to handle a vector of channel pairs, rather than a single pair.
With a single pair of channels, the behavior should be the exact same.
I've updated the tests to also check for more than one pair of channels.
> feat(s2n-quic-xdp): implement IO traits for vectors of channel pairs

- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic/Cargo.toml
N/A
Previously the version for this crate was not bumped even though its dependencies had their versions bumped.
We probably should have some kind of testing in place to make sure this doesn't happen again.
> chore: bump version for s2n-quic-tls-default 

- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/client_handshake_confirm.rs
- quic/s2n-quic/src/tests/setup.rs
This change adds a test that shows an example of an event provider that blocks the client from opening any streams until the handshake is completely confirmed by the server.
When using mTLS, the client is technically allowed to start sending application data before the server has actually authenticated the client. For clients that want to wait before getting a confirmation of the server accepting the client's certificate, they can use the `ClientConfirm` struct as an event provider on the `Client`.
Note that waiting for handshake confirmation will add another round trip to the handshake so keep that in mind when deciding if this functionality is useful.
This module includes 3 distinct tests to show the behavior:
* The `mtls_happy_case` creates a successful connection and sends some data
* …
> test(s2n-quic): show how to block clients on handshake confirmation

- quic/s2n-quic-sim/Cargo.toml
More packages bumped their MSRV so we'll need to pin them until we can go beyond 1.63.
> build: pin more MSRV-breaking dependencies

- quic/s2n-quic-core/src/packet/number/tests.rs
- quic/s2n-quic-core/src/slice.rs
- quic/s2n-quic-core/src/varint/tests.rs
- quic/s2n-quic-core/src/xdp/decoder.rs
This commit switches the solver from Kissat to Cadical for some of the Kani harnesses, in cases where Cadical is faster and for harnesses that take longer than 1 second to run.
The results of running these 8 harnesses with Cadical, Kissat, and the default solver (where possible) are below.
quic/varint::tests::round_trip_values_test
default: avg 1.13 [1.1278493299999997, 1.1265045, 1.1301544999999997]
cadical: avg 0.89 [0.8822812, 0.9042669, 0.875616]
kissat: avg 3.25 [3.2597189999999996, 3.24811, 3.2498839999999998]
speedup default -> cadical: 1.27
quic/packet::number::tests::round_trip
default: avg 2.10 [2.0913535, 2.1126869999999998, 2.11061815]
cadical: avg 1.63 [1.6425245, 1.6270909999999998, 1.6270189]
kissat: avg 4.62 [4.617643, 4.619624, 4.617560000000001]
speedup default -> …
> Use cadical solver for some Kani harnesses

- .github/workflows/ci.yml
- .github/workflows/netbench.yml
- .github/workflows/qns.yml
Based on [docs](https://docs.github.com/en/enterprise-server@3.4/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events) and a test dependabot [PR](https://github.com/aws/s2n-quic/pull/1617), the `ouzi-dev/commit-status-updater` task is failing.
[ouzi](https://github.com/ouzi-dev/commit-status-updater) requires the `statuses: write` permissions to work, which I add in this PR.
Testing this would require one of the two methods:
- merge this to see if it works (recommended)
- try in a separate repo
Since the `statuses: write` is a safe permission and I am pretty certain this should help resolve the issue, I think we should just merge this and test it out. I also compared the [failing CI's permissions …
> chore: give depandabot permissions to update PR status

- quic/s2n-quic-core/src/io/tx.rs
- quic/s2n-quic-platform/src/message/queue/slice.rs
- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
I noticed that some MTU probe packets were getting both `EMSGSIZE` and `EINVAL` errors returned, depending on if the packet included a GSO segment or not. This causes extra flakiness for packets that are bundled with the MTU probe, since the whole packet is discarded on error.
This change, instead, forces MTU probes to _always_ be standalone packets. It does this by checking `can_gso` before writing the message and uses that value to know if it needs to be standalone or not.
```
$ SCENARIO=./target/netbench/ping.json strace -e 'trace=sendmmsg' --status=failed ./target/debug/netbench-driver-s2n-quic-server --trace=disabled
sendmmsg(8, [{msg_hdr={msg_name={sa_family=AF_INET6, sin6_port=htons(45162), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::ffff:10.0.128.116", &sin6_addr), …
```
> fix(s2n-quic-core): flush packet queue between connections/MTU probes

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/packet/number/packet_number.rs
- quic/s2n-quic-core/src/packet/number/packet_number_range.rs
- quic/s2n-quic-core/src/path/migration.rs
- quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-transport/src/path/ecn.rs
I noticed that a bunch of `into_event` impls were missing `#[inline]` and so this PR adds those. Having this attribute is important to ensure that the event framework is truly zero cost for each of the events.
> fix(s2n-quic-core): add missing inline attributes for into_event

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/inet/datagram.rs
- quic/s2n-quic-events/events/platform.rs
- quic/s2n-quic-platform/build.rs
- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/message/cmsg.rs
- quic/s2n-quic-platform/src/syscall.rs
- quic/s2n-quic-platform/src/syscall/mmsg.rs
- quic/s2n-quic-platform/src/syscall/msg.rs
Currently, the msg/mmsg syscalls require a particular not-so-flexible interface to be implemented to interact with them. This PR moves the actual syscall to a simple function to make it easier to use in more contexts.
This is needed to separate the endpoint task from the IO operations.
I've added a few changes to add GRO support in the syscalls while I was here to minimize the merge conflicts.
I also have _not_ refactored the old syscalls to use the new functions, as that implementation will be deleted in a later PR.
There's not really a great way to test the syscalls on their own, however tests are coming in a later PR that tests them in context of the tokio IO provider.
> refactor(s2n-quic-platform): move more syscalls to syscall module

- quic/s2n-quic-platform/src/features.rs
- quic/s2n-quic-platform/src/features/gso.rs
- quic/s2n-quic-platform/src/message/mmsg.rs
- quic/s2n-quic-platform/src/message/msg.rs
Currently, we disable GSO if we get an `EIO` error on send. This causes a `disable_gso` function to be called, which overrides the maximum number of GSO segments to `1`. This causes issues when we split the endpoint task from the IO operations, since the endpoint is in charge of assembling packets where the IO operation task is in charge of flushing them to the socket. 
This change refactors the GSO max segment tracking to a shared, atomic variable so it's easier for the two tasks to synchronize their state.
The current implementation isn't synchronous but it has been updated to use this for simplicity.
The existing tests should be sufficient to catch any regressions in the refactor.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> refactor(s2n-quic-platform): track GSO segment counts in shared memory

- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/endpoint/config.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/datagram.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic-transport/src/space/session_context.rs
- quic/s2n-quic-transport/src/stream/manager.rs
- quic/s2n-quic-transport/src/stream/manager/tests.rs
- quic/s2n-quic-transport/src/stream/manager_api.rs
- quic/s2n-quic-transport/src/stream/mod.rs
- quic/s2n-quic-transport/src/transmission/application.rs
- quic/s2n-quic/src/client/providers.rs
- quic/s2n-quic/src/server/providers.rs
I'm planning on experimenting with optimizing the stream manager a bit and making the endpoint generic over the stream manager interface will make this easier.
Since this is just moving the public API to a trait, all of the existing tests show no change in behavior.
> refactor(s2n-quic-transport): move stream manager behind trait

- quic/s2n-quic-platform/src/message.rs
- quic/s2n-quic-platform/src/message/mmsg.rs
- quic/s2n-quic-platform/src/message/msg.rs
- quic/s2n-quic-platform/src/message/simple.rs
- quic/s2n-quic-platform/src/socket.rs
- quic/s2n-quic-platform/src/socket/ring.rs
This change uses the `s2n_quic_core::sync::Cursor` added in #1774 to implement a ring buffer for passing messages between the endpoint and socket tasks. We're also adding an `alloc` method to the `Message` trait that allocates the underlying ring buffer for a given message.
Note that we still maintain the primary/secondary regions on the ring buffer to make it possible to have a single syscall for the `mmsg` message type. Without the primary/secondary replication, we would be left with 2 slices and would end up roughly doubling the number of syscalls performed.
I've included tests for replication behavior of each type of message to make sure that's working properly. Those also implicitly test the `alloc` methods as well.
By submitting this pull request, I confirm that my contribution is …
> feat(s2n-quic-platform): add message ring using sync::Cursor

- .github/workflows/ci.yml
- netbench/rust-toolchain
- rust-toolchain
- tools/xdp/rust-toolchain
Dependabot isn't able to read the old `rust-toolchain` file anymore so we aren't getting any updates. This PR uses the modern format instead.
The CI workflow had to be updated since we used the `rust-toolchain` file to extract out or MSRV.
> ci: use modern rust-toolchain format

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
version bump for release
I think that our previous github release tag might be wrong? My script assumes that the commit tagged in the release is the same one published to cargo, but I think that the currently published crates already include the `Fixing previous version bump (#1768)`  commit.
> chore: version bump

- quic/s2n-quic-platform/src/message.rs
- quic/s2n-quic-platform/src/message/mmsg.rs
- quic/s2n-quic-platform/src/message/msg.rs
- quic/s2n-quic-platform/src/message/simple.rs
- quic/s2n-quic-platform/src/socket.rs
- quic/s2n-quic-platform/src/socket/io.rs
- quic/s2n-quic-platform/src/socket/io/rx.rs
- quic/s2n-quic-platform/src/socket/io/tx.rs
Using the socket ring buffer added in #1787, this PR implements the `s2n_quic_core::io` traits. This enables the ring buffer to be used by a s2n-quic endpoint to write and read packets from a ring buffer queue.
The task that actually performs the syscall is in #1789.
In this PR, I don't have explicit tests for these implementations, since it requires a task on the other side of the ring doing something with it. In the final PR, there will be some tests that show it all working end-to-end.
> feat(s2n-quic-platform): implement io traits for sync rings

- quic/s2n-quic-platform/src/socket.rs
- quic/s2n-quic-platform/src/socket/task.rs
- quic/s2n-quic-platform/src/socket/task/events.rs
- quic/s2n-quic-platform/src/socket/task/rx.rs
- quic/s2n-quic-platform/src/socket/task/tx.rs
- quic/s2n-quic-platform/src/syscall.rs
Using the socket ring buffer added in #1787, this PR implements async tasks that interact with the syscalls and either send or receive messages into the ring buffer. Note that the tasks are generic over the message/syscall type.
The implementation that interacts with the s2n-quic endpoint is in #1788.
In this PR, I don't have explicit tests for these implementations, since it requires a task on the other side of the ring doing something with it. In the final PR, there will be some tests that show it all working end-to-end.
> feat(s2n-quic-platform): add socket tasks for sync rings

- common/s2n-codec/src/encoder/value.rs
- quic/s2n-quic-core/src/datagram/default.rs
- quic/s2n-quic-core/src/datagram/traits.rs
- quic/s2n-quic-transport/src/endpoint/version.rs
- quic/s2n-quic-transport/src/space/datagram.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/stream/controller/local_initiated.rs
- quic/s2n-quic-transport/src/sync/data_sender/writer.rs
This lets callers who have "headers" associated with each datagram in separate buffers avoid needing to copy into a buffer just for the write call (which results in another copy into the destination).
No intended functional changes, only more efficient callers.
The EncoderValue implementation for slices isn't using the s2n-quic-core vectored copy implementation - it seems like that would require a new write_vectored_slice or similar. Open to writing that but maybe I missed some implementation that already exists and I can just call into.
No tests added - I was looking for some UDP datagram tests but nothing seems to call write_datagram today? So I assume this works.
> Vectored write for datagrams

- .github/workflows/ci.yml
- quic/s2n-quic-core/src/io/tx.rs
- quic/s2n-quic-platform/build.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
- quic/s2n-quic-platform/src/io/tokio/tests.rs
- quic/s2n-quic-platform/src/message.rs
- quic/s2n-quic-platform/src/message/cmsg.rs
- quic/s2n-quic-platform/src/message/msg.rs
- quic/s2n-quic-platform/src/message/msg/ext.rs
- quic/s2n-quic-platform/src/message/msg/handle.rs
- quic/s2n-quic-platform/src/message/msg/tests.rs
- quic/s2n-quic-platform/src/message/queue.rs
- quic/s2n-quic-platform/src/message/simple.rs
- quic/s2n-quic-platform/src/socket/ring.rs
- quic/s2n-quic-platform/src/syscall/msg.rs
In #1790, @Mark-Simulacrum had some concerns about the code from #1787. This PR aims to address those separately.
There were a few violations of stacked borrows in the cmsg module. Unfortunately, they aren't completely solvable, as some of them come from the `libc` crate. I've modified the code to use our own cmsg implementation, which actually simplifies things a bit.
I've added MIRI tests for the `s2n-quic-platform` crate to ensure we don't violate the stacked borrows memory model. I've also added a few Kani tests to increase some confidence in the new cmsg code.
> fix(s2n-quic-platform): use custom storage type for messages

- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/io/tokio/task.rs
- quic/s2n-quic-platform/src/io/tokio/task/simple.rs
- quic/s2n-quic-platform/src/io/tokio/task/unix.rs
- quic/s2n-quic-platform/src/message/simple.rs
- quic/s2n-quic-platform/src/socket/std.rs
- quic/s2n-quic-platform/src/socket/task.rs
- quic/s2n-quic-platform/src/socket/task/rx.rs
- quic/s2n-quic-platform/src/socket/task/tx.rs
- quic/s2n-quic-platform/src/syscall.rs
- quic/s2n-quic-platform/src/syscall/mmsg.rs
- quic/s2n-quic-platform/src/syscall/msg.rs
This change implements the new socket traits for tokio sockets.
Tests are finally added in #1792.
> feat(s2n-quic-platform): wire up tokio sockets to ring

- quic/s2n-quic-platform/src/io/turmoil.rs
We finally have enough PRs merged to use the generic event loop for the turmoil IO provider.
Since the current turmoil API doesn't allow splitting the sockets, we still need a smaller event loop to both send and receive on the socket.
The existing turmoil tests should be sufficient.
> refactor(s2n-quic-platform): use generic event loop for turmoil

- quic/s2n-quic-platform/src/message/cmsg.rs
- quic/s2n-quic-platform/src/message/msg.rs
In testing, I was seeing ECN markings get disabled. After some digging, this is due to the OS returning both `pktinfo` _and_ `pktinfo6` and the cmsg buffer not having enough capacity for those.
As such, I've added the sizes for both rather than taking the max.
I also added an assertion to make sure the cmsg buffer wasn't truncated in testing. I didn't make it a `debug_assert`, since I'm not sure if the OS will randomly return more cmsgs or not and didn't want the application to panic.
> fix(s2n-quic-platform): increase cmsg buffer size for multiple pktinfo

- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/transmission/early.rs
I noticed that we had [some scenarios](https://dnglbrstg7yg.cloudfront.net/7f50be7e190a65d9e958a0d23edc8b3821f67cbd/interop/logs/latest/s2n-quic_s2n-quic/amplificationlimit/index.html) on a s2n-quic client where we would stall a handshake if the server was amplification-limited.
The fix is to have the client:
* Pad all packets until the handshake is confirmed. This ensures the server is getting as many credits as possible.
* Make all early packets ACK-eliciting. This ensures the recovery mechanisms kick in for when packets are lost. This is especially important on the client where it doesn't have anything to send and is waiting on the server's CRYPTO frames.
Interop results: https://dnglbrstg7yg.cloudfront.net/169b6c37402b4d9079958306c78c1a9f7cf93901/interop/index.html
By submitting this …
> fix(s2n-quic-transport): improve amplification credits on client

- quic/s2n-quic-core/src/path/mod.rs
The MaxMtuError doesn't currently implement `std::error::Error`, which makes it annoying to use in applications. This change implements it.
N/A
> feat(s2n-quic-core): implement std error for MaxMtuError

- quic/s2n-quic-core/src/sync/cursor.rs
There's a few places in the codebase that pass a `u32::MAX` watermark to the cursor acquire methods to simply say "try to acquire the most items possible". In the case where all items have been acquired, we still do a load and calculation. This change caps the watermark to the maximum number of items a ring can have to avoid this scenario.
I had to update the test harness, which relied on the functionality to force a fetch when passing `u32::MAX`.
> fix(s2n-quic-core): cap cursor watermarks by size

- quic/s2n-quic-core/src/sync/atomic_waker.rs
The atomic waker handle doesn't implement the Send/Sync traits, which prevents its use in multithreading environments.
This change adds those implementations.
While I was here, I added a `poll_close` method to the atomic waker, which was useful in the XDP branch I'm working on.
> fix(s2n-quic-core): add trait markers for atomic waker handle

- quic/s2n-quic-core/src/slice.rs
While implementing the XDP functionality, I needed a way to zip up slices of slices and iterate over each item. This could be accomplished with `head.iter().chain(tail).zip(head2.iter_mut().chain(tail2))`. However, this is a bit slow and we already have an optimized slices of slices iterator in `vectored_copy`.
This change refactors the `vectored_copy` iteration functionality into a separate `zip_chunks` function. This function accepts a callback for each pair of overlapping slices. The `vectored_copy` function now uses this to implement the copy. I've also added a simple `zip` function which operates on single items.
The bolero/kani tests for the vectored_copy should verify all of the safety in the underlying function.
By submitting this pull request, I confirm that my contribution is …
> feat(s2n-quic-core): add slice::zip function

- quic/s2n-quic-core/src/interval_set/intersection.rs
- quic/s2n-quic-core/src/interval_set/mod.rs
- quic/s2n-quic-core/src/interval_set/tests.rs
resolves #746
This change introduces a method for performing an `IntervalSet` intersection in place, mutating the original interval set instead of allocating a new `VecDeque`. 
I left the original `intersection_iter` code in place even though I don't think anything is using it, as I believe we are treating `IntervalSet` as a general purpose data structure, and this `intersection_iter` could be useful for someone that just wants to iterate over the intersection rather than actually apply the intersection.
Updated the existing fuzz tests to compare both `intersection` and `intersection_iter` with the oracle `BTreeSet`. I've run the fuzz test on release mode for > 1 hour (and counting)
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> refactor(s2n-quic-core): optimize interval set intersection

- quic/s2n-quic-core/src/io/mod.rs
- quic/s2n-quic-core/src/io/rx.rs
- quic/s2n-quic-core/src/io/rx/pair.rs
- quic/s2n-quic-core/src/io/testing.rs
- quic/s2n-quic-core/src/io/tx.rs
- quic/s2n-quic-core/src/io/tx/handle_map.rs
- quic/s2n-quic-core/src/io/tx/router.rs
- tools/xdp/s2n-quic-xdp/src/io.rs
- tools/xdp/s2n-quic-xdp/src/io/router.rs
This change implements several extensions to the IO channels in order to make it easier to combine multiple types of channels into a single interface:
This channel merges messages received from two channels into a single channel. For example, it can be used to receive from both an AF_XDP socket and standard UDP socket.
This channel maps the handle from one type to another. For example, if the endpoint's handle type is the XDP one (with mac addresses) and we want to send a message on a regular UDP socket, we need to remove the mac addresses and convert it into the type the UDP socket expects.
This channel uses a `Router` trait to decide which channel to push a message into. For example, this will be used for the client to decide if it needs to send a message on a regular UDP socket for the …
> feat(s2n-quic-core): add IO extensions

- scripts/interop/run
This change fixes the `quic-interop-runner` commit in the `interop/run` script to match the [qns workflow](https://github.com/aws/s2n-quic/blob/9c144b3078366d8bef158d9f70f91f235f46f079/.github/workflows/qns.yml#L18)
Tested locally
> fix(s2n-quic-qns): update interop commit to match interop workflow

- quic/s2n-quic-sim/src/run/endpoint.rs
- quic/s2n-quic-sim/src/stats.rs
The current delay code for the sim unintentionally performs a parallel delay when establishing connections. However, the original intent was to make it serial. This fixes that.
> test(s2n-quic-sim): fix the connect delay implementation

- quic/s2n-quic-transport/src/transmission/interest.rs
This change adds a transmission interest debugger which prints out which component is wanting to transmit and what type of interest it has. I was using it in testing awhile back and thought it would be useful to have.
> test(s2n-quic-transport): add transmission interest debugger

- README.md
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-crypto/src/lib.rs
N/A
Switch from ring to aws-lc-rs for all Linux platforms.
The switch had previously been made for Linux/aarch64.
`cargo test` succeeds on my Mac (x86-64) and Linux (x86-64 and aarch64) hosts.
> Use aws-lc-rs on all Linux platforms

- .github/config/cargo-deny.toml
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-qns/src/main.rs
- quic/s2n-quic-qns/src/server/interop.rs
- quic/s2n-quic-qns/src/server/perf.rs
- quic/s2n-quic-qns/src/xdp.rs
This change adds an XDP server to the qns application. Because of the complexity of configuring XDP (how many queues, how to register the BPF program, how to pin sockets to cores, etc), applications will need to use this code as a starting point. We may add an "easy mode" in the future to simplify this integration but I think it's best to unblock and get some feedback first.
The qns application can be compiled with the `xdp` feature and it works just like the regular application, outside of needing NET_ADMIN permissions to register the socket.
[
](https://gist.githubusercontent.com/camshaft/698d88935f0397186525ff0b95a9dcdd/raw/udp-recv.svg)
[
](https://gist.githubusercontent.com/camshaft/698d88935f0397186525ff0b95a9dcdd/raw/xdp-recv.svg)
[ …
> feat(s2n-quic-qns): add XDP server

- quic/s2n-quic-qns/etc/Dockerfile.build
In #1840, we switched to using aws-lc-rs for Linux. This requires that cmake is installed on the build target. This wasn't added to our Dockerfile for qns builds so it started failing.
This change adds cmake as a dependency.
I also applied the webpki patch in the `prepare` phase of cargo-chef, to ensure it was downloaded and built there, rather than in the `cook` phase.
The `release` CI workflow should now be passing.
> ci: fix qns Docker release

- quic/s2n-quic-qns/src/client/perf.rs
- quic/s2n-quic-qns/src/perf.rs
When testing stream creation latency, it is helpful to have a command to create streams in a loop, send/recv some data and measure total throughput.
This change adds a `--streams` argument to the qns perf client to accomplish this.
Now that `array::from_fn` is stable in 1.63, we can get rid of the Vec allocation for the chunks.
```
$ ./target/release/s2n-quic-qns perf server --ip 192.167.1.10 --port 4433 --stats
```
```tsv
Tx Rate	Rx Rate	Max Cwnd	Max Inflight	Lost Packets	Wakeups	Duration	Max RTT	Max SRTT	PTO Count	Max Pacing Rate	Max Delivery Rate
94.37Mbps	93.12Mbps	89.42kB	9.60kB	0	40738	26.04ms	333ms	333ms	0	0bps	0bps
95.85Mbps	94.59Mbps	89.42kB	669B	0	41382	26.038ms	296µs	96.262µs	0	0bps	0bps
97.27Mbps	95.99Mbps	89.42kB	674B	0	41996	26.04ms	300µs	73.638µs	0	0bps	0bps
98.25Mbps …
```
> feat(s2n-quic-qns): add --streams arg for perf client

- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/io/xdp.rs
- quic/s2n-quic-qns/src/client/interop.rs
- quic/s2n-quic-qns/src/client/perf.rs
- quic/s2n-quic-qns/src/io.rs
- quic/s2n-quic-qns/src/main.rs
- quic/s2n-quic-qns/src/server/interop.rs
- quic/s2n-quic-qns/src/server/perf.rs
- quic/s2n-quic-qns/src/xdp.rs
- quic/s2n-quic/src/provider/io/xdp.rs
Similar to #1765, this change adds a client.
The interesting thing about the client is, since it's the one to initiate the connection, it doesn't know any of the ethernet addresses, or even its own source IP in some cases. So what we do is open a UDP socket to transmit initial packets on. This allows us to offload address resolution onto the OS and not have to re-implement ARP. Once we hear back from the server, we know what all of the address fields are since the server responded with a completely filled-in ethernet/ip/udp packet. We then store the field on the path handle and send all future traffic over the AF_XDP socket instead.
I've refactored the IO setup a bit to be in a central module, rather than copy/pasted in each qns command.
The same testing applies as was done in #1765.
By …
> feat(s2n-quic-qns): add xdp client

- quic/s2n-quic-platform/src/message/cmsg.rs
Clearly this was meant to be `pktinfo_size`
> fix(s2n-quic-platform): Fix compilation in non-pktinfo platforms

- common/s2n-codec/src/zerocopy.rs
- quic/s2n-quic-bench/src/inet.rs
- quic/s2n-quic-core/src/crypto/tls/testing.rs
- quic/s2n-quic-core/src/inet/checksum.rs
- quic/s2n-quic-core/src/inet/checksum/x86.rs
- quic/s2n-quic-core/src/inet/ipv4.rs
- quic/s2n-quic-core/src/xdp/encoder.rs
This change optimized the checksum routines for smaller payloads. This is especially important for the IPv4 header, which only checksums 18 bytes (20 if you include the zeroed checksum itself).
With these optimizations I was able to improve things by about 20%.
I've updated the benchmarks to include the 20 bytes:
```
inet/s2n/checksum/20    time:   [3.8394 ns 3.8579 ns 3.8828 ns]
thrpt:  [4.7972 GiB/s 4.8282 GiB/s 4.8514 GiB/s]
change:
time:   [-18.044% -17.376% -16.737%] (p = 0.00 < 0.05)
thrpt:  [+20.102% +21.030% +22.017%]
Performance has improved.
inet/s2n/checksum/1500  time:   [38.249 ns 38.280 ns 38.309 ns]
thrpt:  [36.466 GiB/s 36.494 GiB/s 36.523 GiB/s]
change:
time:   [-0.4633% -0.3641% -0.2679%] (p = 0.00 < 0.05)
thrpt:  [+0.2687% +0.3654% +0.4655%]
Change within noise …
```
> perf(s2n-quic-core): optimize checksums for small payloads

- quic/s2n-quic-core/src/application/mod.rs
- quic/s2n-quic-core/src/application/server_name.rs
- quic/s2n-quic-core/src/crypto/tls.rs
- quic/s2n-quic-core/src/crypto/tls/null.rs
- quic/s2n-quic-qns/src/client/interop.rs
- quic/s2n-quic-qns/src/client/perf.rs
- quic/s2n-quic-qns/src/server/interop.rs
- quic/s2n-quic-qns/src/server/perf.rs
- quic/s2n-quic-qns/src/tls.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/no_tls.rs
- quic/s2n-quic/src/tests/setup.rs
When doing performance testing, it can be helpful to disable crypto entirely in order to isolate and identify bottlenecks.
This change adds a private TLS provider that simply exchanges transport parameters over cleartext and doesn't encrypt anything. This has somewhat similar goals as the [quic-disable-encryption](https://datatracker.ietf.org/doc/html/draft-banks-quic-disable-encryption-00) draft, but is quite a bit simpler since it doesn't do any negotiation or handshaking.
I added an integration test to make sure the null TLS provider negotiated with itself. I also added support for using it in the qns application to make it easier to benchmark.
```
$ ./target/release/s2n-quic-qns perf server --ip 192.167.1.10 --port 4433 --stats --max-throughput 1000 --tls null
```
```
$ …
```
> feat(s2n-quic-core): add null TLS provider for testing

- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/io/tokio/builder.rs
- quic/s2n-quic-platform/src/io/tokio/tests.rs
resolves #1811
This exposes new APIs for changing the internal send/receive buffers in the Tokio provider. It also changes the default transmit buffer to 128kb from 8mb, which on some hardware platforms significantly reduces latencies on one workload. (These are overheads from a baseline, which is why negatives can slip in, but should still be roughly comparable, as the baseline and runs with QUIC are the same workload).
* 1.21: p10: 652 / p50: 724 / p80: 770
* 1.23 (8Mb): p10: 1014 / p50: 1082 / p80: 2276
* 1.23 (512kb): p10: 599 / p50: 760 / p80: 903
* 1.23 (128kb): p10: 303 / p50: -84 / p80: 112
Not a huge fan of the name of these new methods, happy to change that.
See latency figures above.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> feat(s2n-quic-platform): Configurable buffer sizes + default tx buffer change

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
This bumps the crate versions for `v1.24.0`.
> chore: release 1.24.0

- .github/workflows/ci.yml
After some recent testing additions to core, the miri tests have started failing in CI due to using too much memory. This change bumps the instance size for these CI jobs.
> ci: run miri in larger instances

- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/io/tokio/builder.rs
Currently, if the platform supports GRO, it enables GRO. However, it can be helpful to disable GRO when testing to see how much of a difference it makes. This change adds the ability to do that in the tokio IO provider.
> feat(s2n-quic-platform): add option to disable GRO

- quic/s2n-quic-core/src/buffer/receive_buffer.rs
- quic/s2n-quic-core/src/buffer/receive_buffer/request.rs
- quic/s2n-quic-core/src/buffer/receive_buffer/slot.rs
- quic/s2n-quic-core/src/buffer/receive_buffer/tests.rs
- quic/s2n-quic-transport/src/stream/receive_stream.rs
Currently, the receive buffer always allocates chunks for at least 4096 bytes (a page), even if the total receive stream is a single byte. This also causes us to promote the `BytesMut` to shared (which causes another allocation), since the single byte would be split and the other 4097 would remain in the `ReceiveBuffer`.
This change optimizes the receive buffer for when the final size of the receive stream is known. In this case we _only_ allocate exactly what we need.
I've moved the final size tracking into the `ReceiveBuffer`, rather than the `ReceiveStream`, in order to not duplicate the logic in both places.
The `ReceiveBuffer` tests have been updated to account for the new `fin` tracking. I've also added some tests to show that the allocations are ideal when the final offset is …
> perf(s2n-quic-core): optimize receive buffer for known final sizes

- common/s2n-codec/src/zerocopy.rs
- quic/s2n-quic-core/src/inet/checksum.rs
- quic/s2n-quic-core/src/packet/decoding.rs
- quic/s2n-quic-core/src/xdp/bpf.rs
- quic/s2n-quic-platform/src/message.rs
- quic/s2n-quic-platform/src/message/msg.rs
- quic/s2n-quic-platform/src/message/simple.rs
- quic/s2n-quic-qns/src/server/h09.rs
- quic/s2n-quic-qns/src/tls.rs
- quic/s2n-quic-transport/src/connection/local_id_registry.rs
- quic/s2n-quic-transport/src/connection/peer_id_registry.rs
- quic/s2n-quic-transport/src/path/ecn/tests.rs
- quic/s2n-quic-transport/src/path/manager/tests.rs
- quic/s2n-quic-transport/src/path/mod.rs
- quic/s2n-quic-transport/src/path/mtu.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/wakeup_queue.rs
- quic/s2n-quic/src/provider/random.rs
Clippy beta added a few new warnings so I've gone through and fixed those before they become stable.
> fix: address beta clippy issues

- .github/workflows/netbench.yml
- .github/workflows/qns.yml
- scripts/perf/bin/s2n-quic-null
- scripts/perf/test
resolves #1857 
In #1834, we added the null TLS provider for analyzing perf outside of the crypto operations. This change adds the perf report to CI so it's continually available.
I've increased the default socket buffer sizes to allow for higher sending throughput. I've also applied the same change to the netbench runs.
The report for this PR is available [here](https://dnglbrstg7yg.cloudfront.net/0cee96e6ee1bed8ada433440f9cb044f72271d97/perf/index.html).
> ci: run null tls perf tests

- netbench/netbench/src/lib.rs
- quic/s2n-quic-events/src/main.rs
- quic/s2n-quic/src/provider.rs
- quic/s2n-quic/src/provider/address_token/mod.rs
- quic/s2n-quic/src/provider/congestion_controller.rs
- quic/s2n-quic/src/provider/connection_close_formatter.rs
- quic/s2n-quic/src/provider/connection_id.rs
- quic/s2n-quic/src/provider/datagram.rs
- quic/s2n-quic/src/provider/endpoint_limits.rs
- quic/s2n-quic/src/provider/event/mod.rs
- quic/s2n-quic/src/provider/io.rs
- quic/s2n-quic/src/provider/limits.rs
- quic/s2n-quic/src/provider/macros.rs
- quic/s2n-quic/src/provider/packet_interceptor.rs
- quic/s2n-quic/src/provider/path_migration.rs
- quic/s2n-quic/src/provider/random.rs
- quic/s2n-quic/src/provider/stateless_reset_token.rs
- quic/s2n-quic/src/provider/sync.rs
- quic/s2n-quic/src/provider/tls.rs
- tools/memory-report/src/main.rs
#1709 
This PR adds Start and Sync to StartError, which also requires adding it to the error types that the providers use.
```
refactor(s2n-quic): Add Send + Sync to StartError
This commit adds Send and Sync bounds to the StartError type. This makes usage of the error across threads and tasks more ergonomic.
BREAKING CHANGE: Adding additional bounds to a public trait is a breaking change. Customers using externally implemented providers will have to add Send and Sync implementations to their error types.
```
I think this is a breaking change :(
We are adding additional requirements for a public trait that customers may have implemented. If a customer has written their own EndpointLimits provider that uses an Error type that doesn't implement Send + Sync, they will receive a compile time …
> refactor(s2n-quic): Add Send + Sync to StartError

- .github/workflows/qns.yml
- quic/s2n-quic-qns/src/main.rs
- tools/udp-attack/Cargo.toml
- tools/udp-attack/rust-toolchain
- tools/udp-attack/src/main.rs
This change adds a simple tool to generate random UDP packets against an endpoint. This tool is then used in CI against an s2n-quic-qns perf server for 5 minutes to catch any obvious issues with packet handling.
The run for this PR is available [here](https://github.com/aws/s2n-quic/actions/runs/5428019613/jobs/9871944679?pr=1856).
> ci: run udp-attack tests

- quic/s2n-quic-platform/src/io/tokio.rs
While using the probes from #1866, I noticed that the sendmmsg syscall could take quite a long time (upwards of 1ms), especially when the total number of messages being sent was high.
One thing that did help was to use the multithreaded runtime and multiple TX sockets. This does increase CPU usage but also increases throughput and minimizes latency, since we're executing multiple syscalls in parallel, each with smaller buffers.
I've made this an unstable option for now, in case we want to change how the socket initialization works. Currently, it just calls `try_clone()` on the single socket for each task, which might cause issues later down the line (not sure). 
```bash
$ S2N_QUIC_UNSTABLE_TX_SOCKET_COUNT=16 s2n-quic-qns perf server --port 4433 --stats --multithread
```
By submitting this …
> feat(s2n-quic-platform): add unstable option for multiple sockets

- .github/workflows/ci.yml
- quic/s2n-quic-platform/build.rs
resolves #1850
As discussed in the issue, it can be useful to override the platform features for a given build if your target environment is different than the build environment.
I added a couple of CI jobs to test fewer features being enabled for Linux than what would be otherwise, to prevent something like #1849 in the future.
> feat(s2n-quic-platform): support features override

- quic/s2n-quic-qns/src/client/interop.rs
- quic/s2n-quic-qns/src/client/perf.rs
- quic/s2n-quic-qns/src/io.rs
- quic/s2n-quic-qns/src/main.rs
- quic/s2n-quic-qns/src/runtime.rs
- quic/s2n-quic-qns/src/server/interop.rs
- quic/s2n-quic-qns/src/server/perf.rs
The way the multithread selection on the qns application works right now is kind of annoying since you have to pass the argument before the program is selected:
```bash
$ s2n-quic-qns --multithread true perf server --port 4433
```
This change fixes it to allow the `--multithread` flag to be put where all of the other flags go:
```bash
$ s2n-quic-qns perf server --port 4433 --multithread
```
> feat(s2n-quic-qns): move runtime selection to common module

- quic/s2n-quic-qns/src/client/h09.rs
- quic/s2n-quic-qns/src/client/h3.rs
- quic/s2n-quic-qns/src/client/interop.rs
- quic/s2n-quic-qns/src/client/perf.rs
- quic/s2n-quic-qns/src/main.rs
- quic/s2n-quic-qns/src/task.rs
When using the qns application for testing, it can be useful to specify a limit for the total number of concurrent connections. This change allows for just that.
> feat(s2n-quic-qns): add connection concurrency parameter

- netbench/netbench-driver/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
N/A
Changing s2n-quic-tls crate to use newest s2n-tls rust bindings version.
I don't think I need to change the version of the s2n-quic-tls crate right? I feel like that only happens when we do an s2n-quic release 🤔.
N/A
> chore(s2n-quic-tls): bump s2n-tls version

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
This bumps the crate versions for the `v1.25.0` release.
> chore: release 1.25.0

- common/s2n-codec/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
In #1887, I missed that `s2n-codec` had a small change and needed a version bump. This corrects that.
> chore: bump s2n-codec version for v1.25.0

- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__on_transmit_burst_complete.snap
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/space/mod.rs
resolves #1839
The packet time out (PTO) timer is restarted each time an ack-eliciting packet is sent, as its main function is to trigger probes when tail packets are not ACKed in time:
```
//= https://www.rfc-editor.org/rfc/rfc9002#section-6.2.1
//# A sender SHOULD restart its PTO timer every time an ack-eliciting
//# packet is sent or acknowledged,
```
Previously we were updating this timer on each packet being sent, even if we send several packets in one burst due to aggregation mechanisms like GSO. This was showing up in Flamegraphs, from .1% to 1% of CPU.
With this change we will wait to update the pto timer until the burst of packets has been transmitted. This doesn't change the actual timing of the PTO timer as the timestamp used for each packet within the burst is identical. 
I …
> refactor(s2n-quic-transport): update PTO timer once per transmission burst

- CONTRIBUTING.md
Clarify that we use conventional commit style for our messages.
Standard CI/CD tests.
> docs: Add conventional commit info

- quic/s2n-quic-core/src/path/mod.rs
- quic/s2n-quic-transport/src/path/mtu.rs
In #1737 we starting disabling MTU probing when the socket cannot support it by setting the `MaxMtu` for the endpoint to `MaxMtu::MIN`. `MaxMtu::MIN` is based on the smaller of the minimal IPv4 and IPv6 header lengths. The `mtu::controller` had a debug assertion that validated that the given `MaxMtu` is larger than a value that was dependent on if the peer socket address was `IPv4` or `IPv6`. This means that an endpoint starting on a platform that cannot support MTU probing but can support IPv6 would fail this debug assertion, as the IPv6 header is larger. This change removes the debug assertion and instead just takes the max with the `BASE_PLPMTU`.
I've also removed some usage of the `IPV6` feature that had previously been removed in #886
Updated unit test, and tested locally on MacOS, …
> fix(s2n-quic-transport): handle MaxMtu smaller than Base PLPMTU

- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/io/testing/message.rs
- quic/s2n-quic-platform/src/io/testing/model.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
- quic/s2n-quic-platform/src/io/testing/socket.rs
This change refactors the testing IO provider a bit to use the same queues and tasks that the other IO providers use. This brings the implementations a lot closer to have a high fidelity simulation.
While I was refactoring the network implementation, I added support for address rebinding. I've got another PR (#1874) that actually adds some tests around it.
All of the existing integration tests should pass as before and show this refactor is working.
> test(s2n-quic-platform): refactor testing IO provider to use tasks/queues

- .github/workflows/ci.yml
- .github/workflows/netbench.yml
- netbench/rust-toolchain
- tools/xdp/rust-toolchain
Netbench and XDP no longer build with the following error:
```
package `time-macros v0.2.11` cannot be built because it requires rustc 1.67.0 or newer, while the currently active rustc version is 1.66.0
```
This change upgrades the rust toolchain for Netbench and XDP to 1.67.0
CI
> fix: upgrade rust version for netbench and xdp

- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/pto.rs
[QUIC-TLS§4.9.1](https://datatracker.ietf.org/doc/html/rfc9001#section-4.9.1) makes it clear that Initial secrets should be discarded aggressively:
> Packets protected with Initial secrets ([Section 5.2](https://datatracker.ietf.org/doc/html/rfc9001#initial-secrets)) are not authenticated, meaning that an attacker could spoof packets with the intent to disrupt a connection. To limit these attacks, Initial packet protection keys are discarded more aggressively than other keys.
> 
> The successful use of Handshake packets indicates that no more Initial packets need to be exchanged, as these keys can only be produced after receiving all CRYPTO frames from Initial packets. Thus, a client MUST discard Initial keys when it first sends a Handshake packet and a server MUST discard Initial keys …
> feat(s2n-quic-transport): discard client initial keys when we have handshake keys

- netbench/netbench/src/duplex.rs
After merging #1883, the s2n-tls netbench driver has been consistently failing on the ping test. Digging in a bit deeper on it, it looks like the `Duplex` driver wasn't correctly handling cases where the stream shut down and it got into an infinite loop.
This change fixes the receive to handle all of the error cases correctly.
> fix(netbench): correctly handle stream shutdown in duplex

- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/transmission/early.rs
In #1818 we made two changes to improve the success of handshakes succeeding in the face of packet loss and amplification limits on the server. 
These two changes were:
1) Pad all datagrams transmitted by the client until the handshake has been confirmed, regardless of whether an initial packet was included in the datagram
2) Force all packets transmitted during the handshake to be ack-eliciting by including a `Ping` frame in the packet
`1.` Should not be necessary since receipt of a `Handshake` packet on the server removes amplification limits, so padding a solitary `Handshake` packet would only serve to give amplification credits that would no longer be needed. From [QUIC§8,1](https://www.rfc-editor.org/rfc/rfc9000#section-8.1):
> Connection establishment implicitly provides address …
> fix(s2n-quic-transport): revert "improve amplification credits on client #1818"

- quic/s2n-quic-transport/src/connection/connection_container.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
The count of currently handshaking connections in the connection container was not being decremented when a connnection moved from handshaking directly to finalizing. This change corrects this behavior.
There is a brief moment between when `update_interests()` is called and `finalize_done_connections()` is called when the `handshake_connections` count is technically incorrect. This is because I decided to account for both handshaking connections and handshaking completed connections in the `update_interests()` method so I would not need to lock the connection multiple times. A connection that is handshaking and finalizing will decrement the `handshake_connections` count, but is not be removed from the connection map until `finalize_done_connections` is called. This meant I had to call …
> fix(s2n-quic-transport): decrement handshake count for non-accepted finalized connections

- quic/s2n-quic-qns/src/client.rs
- quic/s2n-quic-qns/src/client/interop.rs
- quic/s2n-quic-qns/src/client/perf.rs
- quic/s2n-quic-qns/src/congestion_control.rs
- quic/s2n-quic-qns/src/main.rs
- quic/s2n-quic-qns/src/server.rs
- quic/s2n-quic-qns/src/server/interop.rs
- quic/s2n-quic-qns/src/server/perf.rs
- quic/s2n-quic-qns/src/tls.rs
This change adds the ability to specify which congestion controllers (Cubic or BBR) to use in interop testing or the perf app. 
The default for both interop and perf is now BBR.
CI
> feat(s2n-quic-qns): add ability to set congestion controller in interop/perf

- quic/s2n-quic-qns/etc/run_endpoint.sh
- quic/s2n-quic-qns/src/client/interop.rs
- quic/s2n-quic-qns/src/limits.rs
This change includes a few small changes to improve the likelihood of interop tests succeeding when they deliberately drop or corrupt packets:
- Increased `MaxHandshakeDuration` from 10 seconds to 60 seconds. Under the heavy loss scenarios tested in interop, a handshake may take longer than 10 seconds to complete
- Increased `MaxIdleTimeout` from 30 seconds to 60 seconds. Under heavy loss, a connection may appear idle for long periods.
- Increased connection concurrency from 10 to 20. With the increased limits above, it is possible the tests may bump into the overall maximum time limit for a single interop test to execute. By handling more requests at the same time, we can attempt to avoid this
- Disable MTU probing for the ECN test. The ECN interop test requires that every packet sent by …
>  ci: improve interop resiliency to loss and corruption

- common/s2n-codec/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
This bumps the crate versions for the v1.26.0 release.
> chore: release 1.26.0

- tools/udp-attack/rust-toolchain
- tools/xdp/rust-toolchain
A udp-attack and xdp dependency requires a newer rust version:
```
package `anstream v0.5.0` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.68.0
```
This change updates udp-attack and xdp to rust 1.70.0
Built locally
> chore(tools): update udp-attack and xdp rust version

- examples/dos-mitigation/src/lib.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
[QUIC§21.9](https://www.rfc-editor.org/rfc/rfc9000.html#name-peer-denial-of-service) describes a peer denial of service attack that may be mitigated through tracking connection progress relative to processing:
>While there are legitimate uses for all messages, implementations SHOULD track cost of processing relative to progress and treat excessive quantities of any non-productive packets as indicative of an attack. Endpoints MAY respond to this condition with a connection error or by dropping packets.
The existing "Connection Supervisor" introduced in #1097 is suitable for this purpose. I've added a citation for this, and have also mentioned this section in the slow-loris example code.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> docs: add citation for Peer Denial of Service

- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-crypto/src/aesgcm/ring.rs
resolves #1684
This PR enables the implementation done in #1899 now that `aws-lc-rs` has released v1.3.0.
As noted in #1899, the copy on the sender has been removed:
[
](https://dnglbrstg7yg.cloudfront.net/d1a0702795ec72b0b0c57c1dcac7788e147cb04b/perf/s2n-quic-client-s2n-quic-server/0MB-down-10000MB-up.client.svg)
[
](https://dnglbrstg7yg.cloudfront.net/1bc618bbaa59b082ddb4dc46907404bf0ff93bfa/perf/s2n-quic-client-s2n-quic-server/0MB-down-10000MB-up.client.svg)
> feat(s2n-quic-crypto): use scatter API with AWS-LC

- quic/s2n-quic-core/src/stateless_reset/token.rs
- quic/s2n-quic/src/provider/stateless_reset_token.rs
[QUIC§21.11](https://www.rfc-editor.org/rfc/rfc9000.html#reset-oracle) highlights a denial of service attack that is possible if an attacker can cause an endpoint to transmit a valid stateless reset token for a connection ID of the attacker's choosing. This attack can be mitigated when implementing a `stateless_reset::token::Generator` by ensuring a valid (non-random) token is only generated if the given `local_connection_id` does not correspond to any active connection on any endpoint that uses the same static key for generating stateless reset tokens.
This change adds some additional documentation for this mitigation to the stateless_reset_token provider.
Rendered [here](https://dnglbrstg7yg.cloudfront.net/1eb5f4144d328bf6fada01896c19744ab1d8a253/doc/s2n_quic/provider/stateless_reset_tok …
> docs: describe mitigations for QUIC§21.11 in stateless reset token provider 

- quic/s2n-quic-core/src/connection/error.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/packet/encoding.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/endpoint/initial.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic/src/tests/mtu.rs
- quic/s2n-quic/src/tests/pto.rs
- quic/s2n-quic/src/tests/recorder.rs
The current packet processing code is spread between the endpoint and connection. This makes it a bit tricky to reason about how packets flow through a connection and how they're checked for validity.
This change refactors this processing code by moving more of this logic into the connection, which simplifies the endpoint logic quite a bit.
There was a missing check for initial packets being carried in 1200+ byte packets on the server. This could potentially reduce the path reliability for clients that are misconfigured to send smaller initial datagrams.
I added a new test for the initial datagram check showing that the event is emitted. All of the existing integration tests should show no behavior changes in the rest of the packet processing.
By submitting this pull request, I confirm …
> refactor(s2n-quic-transport): simplify packet processing

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
```
quic/s2n-quic-tls has a MINOR bump because of
feat(s2n-quic-tls): adds server session resumption functionality (#1930)
quic/s2n-quic-transport has a MINOR bump because of
feat(s2n-quic-tls): adds server session resumption functionality (#1930)
quic/s2n-quic has a MINOR bump because of
feat(s2n-quic-tls): adds server session resumption functionality (#1930)
quic/s2n-quic-crypto has a MINOR bump because of
feat(s2n-quic-crypto): use scatter API with AWS-LC (#1947)
quic/s2n-quic-core has a PATCH bump because of
refactor(s2n-quic-transport): simplify packet processing (#1952)
docs: describe mitigations for QUIC§21.11 in stateless reset token provider  (#1948)
fix(s2n-quic-transport): invoke on_packet_loss for all lost packets (#1944)
```
```
quic/s2n-quic-platform has a bump because of …
```
> chore: release 1.28

- quic/s2n-quic-core/src/connection/id.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/inet/datagram.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-transport/src/ack/ack_manager.rs
- quic/s2n-quic-transport/src/ack/tests/endpoint.rs
- quic/s2n-quic-transport/src/connection/connection_id_mapper.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/local_id_registry/tests.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/endpoint/version.rs
- quic/s2n-quic-transport/src/path/manager/fuzz_target.rs
- quic/s2n-quic-transport/src/path/manager/tests.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
The RFC mentions that IDCIDs should only be used in Initial and Stateless Resets.
https://www.rfc-editor.org/rfc/rfc9000#section-21.2
> Except for Initial and Stateless Resets, an endpoint only accepts packets that include a Destination Connection ID field that matches a value the endpoint previously chose.
While it's not a MUST, SHOULD, or even a MAY, it's still good to enforce. Note that this really doesn't do much to prevent a Handshake Denial of Service, since the packets that we check are using cryptographic secrets only the peers know (i.e. Handshake, Application).
I was able to test that this check works correctly by modifying our client to ignore the server's chosen DCID in a self-talk test. However, I'm not sure if we can easily test this with the current testing framework.
In …
> fix(s2n-quic-transport): check initial dcid usage

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
Bumps the crate versions for the 1.29.0 release.
A feature commit modified `s2n-quic-core`, `s2n-quic-platform`, and `s2n-quic-transport`, so the minor versions of these crates and their dependencies were bumped.
> chore: release 1.29.0

- quic/s2n-quic-core/src/ct.rs
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic/Cargo.toml
This change pins `regex` and `jobserver` to avoid needing to bump our MSRV. I've also fixed a clippy lint false positive.
I've opened #1991 and #1993 to track removal of the pins
Tested in CI
> fix(s2n-quic): fix clippy and msrv issues

- quic/s2n-quic-core/src/ct.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-events/events/connection.rs
- quic/s2n-quic-platform/src/socket/task/rx.rs
- quic/s2n-quic-platform/src/socket/task/tx.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/space/tx_packet_numbers.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/client_handshake_confirm.rs
- quic/s2n-quic/src/tests/connection_migration.rs
- quic/s2n-quic/src/tests/interceptor.rs
- quic/s2n-quic/src/tests/issue_1361.rs
- quic/s2n-quic/src/tests/issue_1717.rs
- quic/s2n-quic/src/tests/issue_954.rs
- quic/s2n-quic/src/tests/mtls.rs
- quic/s2n-quic/src/tests/mtu.rs
- quic/s2n-quic/src/tests/no_tls.rs
- quic/s2n-quic/src/tests/pto.rs
- quic/s2n-quic/src/tests/recorder.rs
- quic/s2n-quic/src/tests/self_test.rs
- quic/s2n-quic/src/tests/setup.rs
- quic/s2n-quic/src/tests/skip_packets.rs
https://github.com/aws/s2n-quic/issues/1962
The RFC actually does a decent job of describing the issue:
> An endpoint that acknowledges packets it has not received might cause a congestion controller to permit sending at rates beyond what the network supports. An endpoint MAY skip packet numbers when sending packets to detect this behavior. An endpoint can then immediately close the connection with a connection error of type PROTOCOL_VIOLATION
This PR implements packet skipping for Opt Ack mitigation. I also added events to make this easier to test/introspect upon.
I fixed a few new clippy lints in the PR.
- Unit and integration tests.
- I would also like to add a negative test where we receive an Ack and close the connection. I tested this case manually but need to expose the …
> feat(s2n-quic-transport): add mitigation for optimistic ack attack

- quic/s2n-quic-transport/src/connection/close_sender.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/mod.rs
Currently, when a connection is in the process of being closed, we switch the active path it is using back to the "Amplification Limited" state. This limits the amount of outgoing packets that can be sent. There is already a limiter in the `close_sender` that limits the amount of packets that a closed connection can send, so this change removes the redundant behavior.  
Tested with quic-attack
> fix(s2n-quic-transport): don't move path back to amplification limited when closing

- examples/resumption/Cargo.toml
- netbench/netbench-driver/Cargo.toml
- quic/s2n-quic-core/src/crypto/tls.rs
- quic/s2n-quic-core/src/crypto/tls/testing.rs
- quic/s2n-quic-core/src/event.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/events/connection.rs
- quic/s2n-quic-rustls/src/session.rs
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-tls/src/session.rs
- quic/s2n-quic-transport/src/space/session_context.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/exporter.rs
This adds support for exporting symmetric keys from the negotiated QUIC connection for use by other applications/protocols. See https://datatracker.ietf.org/doc/html/rfc5705 for some further details.
See s2n-tls upstream (https://github.com/aws/s2n-tls/pull/4230), released as part of s2n-tls 0.0.39 on crate.io. rustls already supports the relevant [API](https://docs.rs/rustls/latest/rustls/struct.ConnectionCommon.html#method.export_keying_material).
The event API is somewhat novel as added here, but should be relatively extensible and works out ok.
New test added.
> feat(s2n-quic-transport): support exporting from TLS sessions

- scripts/quic-attack/run
The [rust compiler documentation](https://doc.rust-lang.org/rustc/codegen-options/index.html#overflow-checks) for the `-C debug_assertions` option states that:
> overflow checks are enabled if debug-assertions are enabled, disabled otherwise.
This statement does not apply to the `--cfg debug_assertions` option however. This change switches `quic-attack` to use `-C debug_assertions`.
I've also switched to using an actual TLS provider (instead of null TLS) as that is more reflective of actual s2n-quic usage
Tested locally with a small proof of concept:
```rust
pub fn test(input: u64) -> u64 {
0 - input
}
pub fn main() {
let result = test(5);
println!("{}", result);
debug_assert_ne!(result, 18446744073709551611);
}
```
```
$ RUSTFLAGS="--cfg debug_assertions" cargo run --release …
```
> tests(s2n-quic-qns): enable overflow checks in quic-attack

- quic/s2n-quic-core/src/path/mod.rs
- quic/s2n-quic-core/src/recovery/congestion_controller.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__process_new_acked_packets_congestion_controller.snap
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
When invoking the congestion controller's `on_ack` method, we currently pass a `newest_acked_packet_info` that is the newest acked packet for the entire `ACK` frame, regardless of whether that packet was sent on the path the congestion controller is attached to. This change fixes this to send the newest/largest newly acked packet that was actually sent on the path the congestion controller is attached to.
Updated some existing tests and added some new assertions in the `MockCongestionController`
> fix(s2n-quic-transport): send the largest acked for the current path to the congestion controller

- common/s2n-codec/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
Version bumps for the 1.30.0 release
I synced up all internal crates to use the `s2n-quic` version number without the `1.` part. So all internal crates are on the same version now, `0.30.0`
>  chore: release 1.30.0

- quic/s2n-quic-bench/src/varint.rs
- quic/s2n-quic-core/src/varint/mod.rs
- quic/s2n-quic-core/src/varint/snapshots/s2n_quic_core__varint__tests__table_2_pow_0_.snap
- quic/s2n-quic-core/src/varint/snapshots/s2n_quic_core__varint__tests__table_2_pow_13_.snap
- quic/s2n-quic-core/src/varint/snapshots/s2n_quic_core__varint__tests__table_2_pow_14_.snap
- quic/s2n-quic-core/src/varint/snapshots/s2n_quic_core__varint__tests__table_2_pow_1_.snap
- quic/s2n-quic-core/src/varint/snapshots/s2n_quic_core__varint__tests__table_2_pow_29_.snap
- quic/s2n-quic-core/src/varint/snapshots/s2n_quic_core__varint__tests__table_2_pow_30_.snap
- quic/s2n-quic-core/src/varint/snapshots/s2n_quic_core__varint__tests__table_2_pow_5_.snap
- quic/s2n-quic-core/src/varint/snapshots/s2n_quic_core__varint__tests__table_2_pow_61_.snap
- quic/s2n-quic-core/src/varint/snapshots/s2n_quic_core__varint__tests__table_2_pow_6_.snap
- quic/s2n-quic-core/src/varint/table.rs
- quic/s2n-quic-core/src/varint/tests.rs
This PR focuses on improving varint encoding a bit by:
* improving the table function to be completely branchless (see https://godbolt.org/z/9xrxd1osd)
* Adding a special case when we have at least 8 bytes in the target buffer and just doing a single 64 bit `mov`, rather than having to branch based on our integer size:
https://github.com/aws/s2n-quic/blob/b84785290f147a8b97616d449ab93632c8842bab/quic/s2n-quic-core/src/varint/table.rs#L262-L271
I've also cleaned the code up a bit by moving the table functions into a separate module with an named struct, rather than a `(u64, usize, u64)`.
Performance has improved by about 30-40%
```
varint/encode/array/1   time:   [1.6209 ns 1.6211 ns 1.6212 ns]
change: [-40.046% -39.123% -37.678%] (p = 0.00 < 0.05)
varint/encode/slice/1   time:   [2.4321 …
```
> perf(s2n-quic-core): optimize varint encoding

- .github/workflows/ci.yml
- common/s2n-codec/src/zerocopy.rs
- quic/s2n-quic-core/src/inet/datagram.rs
- quic/s2n-quic-core/src/inet/ecn.rs
- quic/s2n-quic-core/src/inet/ip.rs
- quic/s2n-quic-core/src/inet/macros.rs
- quic/s2n-quic-core/src/path/mod.rs
- quic/s2n-quic-platform/src/message/msg/tests.rs
N/A.
We add a stub for cmsg::decode where we return a non-deterministic AncillaryData object. With this stub, the handle_get_set_test harness terminates successfuly, since it doesn't include any assertions (that would be checked by Kani) over the content of the nondet object.
Verification time is less than a minute.
N/A.
> Enable handle_get_set_test test in Kani via stubbing

- quic/s2n-quic-core/src/ack.rs
- quic/s2n-quic-core/src/ack/ranges.rs
- quic/s2n-quic-core/src/ack/snapshots/s2n_quic_core__ack__ranges__tests__Ranges.snap
- quic/s2n-quic-core/src/packet/number/mod.rs
- quic/s2n-quic-core/src/packet/number/testing.rs
- quic/s2n-quic-transport/src/ack/ack_manager.rs
- quic/s2n-quic-transport/src/ack/ack_transmission_state.rs
- quic/s2n-quic-transport/src/ack/mod.rs
- quic/s2n-quic-transport/src/ack/snapshots/quic__s2n-quic-transport__src__ack__ack_manager__events__activate.snap
- quic/s2n-quic-transport/src/ack/snapshots/quic__s2n-quic-transport__src__ack__ack_manager__events__ecn_counts.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_eliciting_transmission__tests__AckElicitingTransmission.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_eliciting_transmission__tests__AckElicitingTransmissionSet.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_manager__tests__AckManager.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_manager__tests__client_sending_test.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_manager__tests__delayed_client_sending_test.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_manager__tests__high_latency_test.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_manager__tests__lossy_network_test.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_ranges__tests__AckRanges.snap
- quic/s2n-quic-transport/src/ack/snapshots/s2n_quic_transport__ack__ack_transmission_state__tests__AckTransmissionState.snap
- quic/s2n-quic-transport/src/ack/tests/report.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
This change moves the ack::Ranges data structure from transport to core. This will make it easier to test and experiment with in different contexts.
Since this is just a move from one crate to the other all of the tests have been moved along with it and should continue to pass.
Note that the `s2n-quic-transport package` CI check is failing since it downloads the s2n-quic-core from crates instead of using the local one. This will continue to fail until we do a new release (which may be something we need to fix in another PR).
> refactor(s2n-quic-core): move ack::Ranges from transport

- common/s2n-codec/src/decoder/checked_range.rs
- quic/s2n-quic-core/src/inet/ecn.rs
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-core/src/packet/key_phase.rs
- quic/s2n-quic-core/src/varint/mod.rs
- quic/s2n-quic-platform/src/lib.rs
- quic/s2n-quic-platform/src/message.rs
- quic/s2n-quic-platform/src/message/msg.rs
I've been doing some experimentation with performance and made a few changes that didn't seem like they all warranted their own PR.
* Added `inline` to several functions that were missing it in the hot path
* Added an `ensure!` macro that works similar to s2n-tls's ENSURE macros to make it easier to follow code (instead of saying "if not this, then return an error" it says "ensure this is true, otherwise return an error)
* Exported more of the platform internals. Since this is an internal crate we don't have any stability guarantees.
* impl `TryFrom<VarInt> for {u8,u16,u32}`
> fix(s2n-quic-core): minor fixes for perf and testing

- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-core/src/recovery/mod.rs
- quic/s2n-quic-core/src/recovery/pto.rs
- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
- quic/s2n-quic-core/src/transmission/interest.rs
- quic/s2n-quic-core/src/transmission/mod.rs
- quic/s2n-quic-core/src/transmission/writer.rs
- quic/s2n-quic-core/src/transmission/writer/testing.rs
- quic/s2n-quic-transport/src/contexts/mod.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/transmission/mod.rs
In order to make it easier to test and use in alternative contexts, this change moves the PTO struct to the `s2n-quic-core` crate.
I also moved the `transmission::interest` module to `s2n-quic-core` to make it possible to have components in there that are able to transmit.
I moved the applicable recovery manager tests into the PTO module and refactored the recovery manager tests to only use the public interfaces.
> refactor(s2n-quic-core): move PTO to core

- quic/s2n-quic-core/src/recovery/mod.rs
- quic/s2n-quic-core/src/recovery/persistent_congestion.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
Similar to #2026, this change moves the persistent congestion calculator to `s2n-quic-core`.
The recovery manager has a bunch of tests that implicitly test the persistent congestion calculations. Ideally the new module would have its own, but I think it's fine for now. This work is tracked in https://github.com/aws/s2n-quic/issues/2032.
> refactor(s2n-quic-core): move persistent congestion to core

- quic/s2n-quic-core/src/frame/ack.rs
- quic/s2n-quic-core/src/frame/connection_close.rs
- quic/s2n-quic-core/src/frame/crypto.rs
- quic/s2n-quic-core/src/frame/mod.rs
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/io/testing/model.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
- quic/s2n-quic-platform/src/io/testing/socket.rs
I'm doing some experiments and wanted to have a socket interface for the discrete event sim environment. This change exports some functions for sending/receiving packets.
I've also added some tracing events for when packets get dropped to give a better idea about what the simulation decided to do.
There's also a few functions elsewhere that were missing `#[inline]` attributes that should really have them. Rather than making a separate PR for those, I've included it here.
This was mostly just exposing what was already there so the existing tests should be sufficient.
> feat(s2n-quic-platform): export IO testing socket construction

- quic/s2n-quic-qns/src/server/h09.rs
- quic/s2n-quic-qns/src/tls.rs
- quic/s2n-quic-rustls/src/client.rs
- quic/s2n-quic-transport/src/stream/controller.rs
- quic/s2n-quic-transport/src/stream/controller/fuzz_target.rs
- quic/s2n-quic-transport/src/stream/testing.rs
- quic/s2n-quic-transport/src/sync/mod.rs
- quic/s2n-quic-transport/src/wakeup_queue.rs
- quic/s2n-quic/src/provider/path_migration.rs
- quic/s2n-quic/src/tests/self_test.rs
A new stable rust release just went out and you know what that means: clippy fixes!
The clippy task is now passing.
> fix: address clippy warnings for 1.74

- quic/s2n-quic-core/src/recovery/bbr.rs
- specs/todos/recovery/7.8.toml
resolves #247
This change adds a citation to BBR pointing out the BBR does implement an alternative mechanism for updating its congestion window (really the pacing rate in this case) after periods of under-utilization
>  docs(s2n-quic-core): add underutilization citation to BBR

- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
The RttEstimator currently initializes itself with the assumed default initial RTT value of 333ms. For running in environments with known lower RTTs (e.g. data centers), this can be too high to be useful.
This change adds a method that allows the caller to override the default initial RTT to a provided value.
I haven't actually wired anything up in the rest of the protocol to override this value. I've opened an issue to track this in #2041.
> feat(s2n-quic-core): allow rtt estimator to take default value

- quic/s2n-quic-platform/src/syscall/mmsg.rs
resolves #ISSUE-NUMBER1, resolves #ISSUE-NUMBER2, etc.
> fix libc recvmmsg paramter type error on musl

- specs/todos/transport/5.1.2.toml
#2043 was opened in favor of #239 to track the remaining connection ID task in its own issue. This change updates the tracking issue for the compliance report
> docs(s2n-quic-transport): update tracking issue for peer CID todo

- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-crypto/src/aesgcm/ring.rs
- quic/s2n-quic-crypto/src/lib.rs
This change removes ring for all platforms except windows. I tried to replace it on windows as well, but ran into issues where NASM is required to be installed, which is a dependency regression from ring. I've opened an issue to track a possible fix: https://github.com/aws/aws-lc-rs/issues/285.
The non-windows builds should continue to pass after the switch.
> feat(s2n-quic-crypto): replace ring with aws-lc on non-windows

- quic/s2n-quic-core/src/recovery/loss.rs
- quic/s2n-quic-core/src/recovery/mod.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
This change moves the detection of whether a packet should be considered lost or not to s2n_quic_core, for use in different contexts.
There is a little bit of overlap in the tests between the new code and the `recovery::Manager`, but for now I think its ok to ensure coverage until we have a better idea of how the `recovery::Manager` will evolve.
Added some new tests
> refactor(s2n-quic-transport): move loss detection to core

- .github/workflows/ci.yml
- quic/s2n-quic-core/src/connection/limits.rs
- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
- quic/s2n-quic-core/src/transport/parameters/mod.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/manager/fuzz_target.rs
- quic/s2n-quic-transport/src/path/manager/tests.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/initial_rtt.rs
resolves #2041
This change adds the ability to specify an initial round trip value by setting a value on the connection limits provider. 
I've updated the nightly toolchain as `udeps` was failing to build on the current version
Added an integration test
> feat(s2n-quic): allow configuring initial RTT

- quic/s2n-quic-bench/src/buffer.rs
- quic/s2n-quic-core/src/buffer/receive_buffer.rs
- quic/s2n-quic-core/src/buffer/receive_buffer/__fuzz__/buffer__receive_buffer__tests__model/corpus.tar.gz
- quic/s2n-quic-core/src/buffer/receive_buffer/request.rs
- quic/s2n-quic-core/src/buffer/receive_buffer/slot.rs
- quic/s2n-quic-core/src/buffer/receive_buffer/tests.rs
- quic/s2n-quic-core/src/stream/testing.rs
The current ReceiveBuffer implementation requires copying all stream data into `BytesMut` buffers to ensure stream data is correctly ordered. This ends up requiring an allocation and a copy, even in scenarios where the stream data being received is at the current offset, and could potentially be copied into an application-provided buffer.
This change adds support for that usecase by adding a `skip(len: usize)` method that allows a caller to increment the current offset by `len` and bypass copying the data into the buffer itself.
I added a `Skip` operation to the fuzz tests, along with a data checker to ensure the data being written to the buffer is the same that is being read. I also updated the committed corpus to include the new input coverage.
By submitting this pull request, I confirm …
> feat(s2n-quic-core): add skip functionality to ReceiveBuffer

- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__on_invalid_ack_frame.snap
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
In #2046, the loss detection algorithm was refactored. As part of the refactor, a debug assertion was added that asserts the following:
```rust
debug_assert!(
largest_acked_packet_number > packet_number,
"only packets sent before the largest acknowledged packet may be considered lost"
);
```
`quic-attack` encountered a case where `largest_acked_packet_number` == `packet_number`, causing this debug assertion to fail. This shouldn't happen, because the loss detection algorithm should not be invoked for packets that have already been acknowledged, such as the `largest_acked_packet_number`. This can happen, however, if an invalid `Ack` frame was received, as the validation of `Ack` frames occurs after the `largest_acked_packet_number` from that `Ack` frame has been updated. I believe the …
> fix(s2n-quic-transport): set largest acked packet after ack is validated

- Cargo.toml
- quic/s2n-quic-bench/Cargo.toml
- quic/s2n-quic-bench/src/buffer.rs
- quic/s2n-quic-core/src/buffer/receive_buffer.rs
- quic/s2n-quic-core/src/buffer/receive_buffer/tests.rs
- scripts/perf/build
For an application that needs to copy data out into, for example, a [tokio::io::ReadBuf](https://docs.rs/tokio/latest/tokio/io/struct.ReadBuf.html#), the current `ReceiveBuffer::pop` interface is less than ideal. The way it is implemented, it assumes that the `BytesMut` will be passed around for copy-avoidance. Splitting bytes off from other chunks only to copy it and drop the new reference requires [shared promotion](https://github.com/tokio-rs/bytes/blob/72cbb92e0e53680c67c27b56fabbe1f3ed5dbae9/src/bytes_mut.rs#L973) and refcount increment/decrement.
This change, instead, provides a `copy_into_buf` function that avoids the `split` calls and instead uses `BufMut::advance_mut`, which avoids the previously-mentioned downsides.
I updated the benchmarks to use the `copy_into_buf` function …
> feat(s2n-quic-core): add ReceiveBuffer::copy_into_buf

- quic/s2n-quic-core/src/connection/id.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-transport/src/connection/connection_id_mapper.rs
- quic/s2n-quic-transport/src/connection/local_id_registry.rs
- quic/s2n-quic-transport/src/connection/local_id_registry/tests.rs
- quic/s2n-quic-transport/src/connection/peer_id_registry.rs
- quic/s2n-quic-transport/src/connection/peer_id_registry/tests.rs
- quic/s2n-quic-transport/src/endpoint/initial.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/path/manager/fuzz_target.rs
- quic/s2n-quic-transport/src/path/manager/tests.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic/src/provider/connection_id.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/handshake_cid_rotation.rs
- quic/s2n-quic/src/tests/recorder.rs
By default, an s2n-quic endpoint will retire the connection ID used during the handshake and will request the peer endpoint to retire the connection ID it used during the handshake as well. This helps reduce linkability between data exchanged during and after the handshake. In certain environments and scenarios, this behavior may not be desired or necessary. This change exposes an option on the `connection::Id` provider to disable handshake connection ID rotation.
Added unit tests and integration tests
> feat(s2n-quic): allow disabling handshake CID rotation

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/tests/setup.rs
This change adds a `branch-tracing` feature to s2n-quic-core which hooks into the `ensure!` macro and logs each decision point with the outcome and the action it took in case of a failure. This is really useful for debugging why something happened or how often a check occurred.
Here's an example output:
```
0:00:00.300000 s2n_quic_core::buffer::receive_buffer: branch="self.max_recv_offset <= final_offset" result=true file="quic/s2n-quic-core/src/buffer/receive_buffer.rs" line=212
0:00:00.300000 s2n_quic_core::buffer::receive_buffer: branch="excess.is_empty()" result=true file="quic/s2n-quic-core/src/buffer/receive_buffer.rs" line=238
0:00:00.300000 s2n_quic_core::buffer::receive_buffer: branch="!request.is_empty()" result=true file="quic/s2n-quic-core/src/buffer/receive_buffer.rs" …
```
> feat(s2n-quic-core): add branch tracing support

- .github/workflows/ci.yml
#2009 added additional checks to the CI that ensure that the cargo package command succeeds on every PR. This was intended to catch build issues that a normal cargo build does not catch prior to publishing the crates. cargo package works by pulling dependencies (including those in the workspace) directly from crates.io, meaning that when changes are made in one crate that depend on another crate, the cargo package command may fail. Until we have a better solution that doesn't fail for this reason, this PR removes this additional check. I opened #2064 to follow up on this.
I left the `detect-new-release` script intact, as it could be useful in some other context. 
CI
By submitting this pull …
>  ci: undo cargo package ci task

- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/stream/manager.rs
- quic/s2n-quic-transport/src/stream/manager/tests.rs
- quic/s2n-quic-transport/src/stream/manager_api.rs
- quic/s2n-quic/src/tests/issue_1464.rs
In #1467 we added an `open_notify` sender that would send an empty Stream frame from an endpoint that locally opened a bi-directional stream, to signal to the peer that the Stream is created and can start receiving data. Typically the `open_notify` sender would transmit the Stream when the connection is woken up due to a timer firing or a packet being received from the peer, but in case neither of those happen, it is possible the connection will not wake up and send the empty Stream frame, resulting in a deadlock. This change will ensure that the connection wakes up when a stream is created. 
Updated the existing integration test to include a delay before opening the stream. This delay allows for all armed timers to fire and packet ACKs to be received by the time the client opens the …
> fix(s2n-quic-transport): wakeup connection on locally-created receive streams

- quic/s2n-quic-core/src/crypto/tls.rs
- quic/s2n-quic-core/src/event.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-rustls/src/session.rs
- quic/s2n-quic-tls/src/callback.rs
- quic/s2n-quic-tls/src/session.rs
- quic/s2n-quic/src/tests/exporter.rs
#1984 added the ability to export symmetric keys negotiated during the QUIC handshake by adding an `on_tls_exporter_ready` event. This change adds `cipher_suite()` to the TLS session exposed as part of the event for use when using the exported keys.
I use `CipherSuite::Unknown` in place of returning an error, it seemed a little more user friendly and I wasn't sure the error would be useful
Updated the exporter integration test to confirm the client and server ciphersuites are the same and neither of them are unknown
> feat(events): Add cipher suite to TLS Session in the TlsExporterReady event

- quic/s2n-quic-core/src/connection/limits.rs
- quic/s2n-quic-core/src/stream/limits.rs
This change increases the default value for the `max_send_buffer_size` to a value commonly used as a maximum for TCP. This can prevent this buffer from acting as a bottleneck in high bandwidth/high RTT connections, but does bring with it additional caveats regarding additional memory consumption and latency. I've added some documentation to the `with_max_send_buffer_size` setting highlighting this tradeoff.
>  feat(s2n-quic): increase max send buffer size default

- .github/workflows/ci.yml
N/A
Kani proofs in the `tools/xdp/s2n-quic-xdp` crate were moved to `quic/s2n-quic-core`, so there's no longer a need to run Kani on this crate:
https://github.com/aws/s2n-quic/actions/runs/7453776726/job/20279841353#step:3:425
> ci: remove crate without Kani proofs

- .github/workflows/qns.yml
Both the upload and download actions need to be bumped together - see #2074 and #2073 for individual details on each action.
> build(deps): bump actions/{download,upload}-artifact from 3 to 4

- quic/s2n-quic-platform/src/io/tokio/builder.rs
- quic/s2n-quic-qns/src/io.rs
In #2078, it was suggested that the GSO/GRO configuration methods could be a bit nicer to use. This change adds new methods that take `bool`s which makes it easier to chain.
I've updated the qns application to use the new methods.
I think it's fine to keep the old methods. I debated marking them deprecated but I don't think it really hurts anything them being there indefinitely.
> feat(s2n-quic-platform): make GSO/GRO configuration more ergonomic

- quic/s2n-quic-platform/build.rs
- quic/s2n-quic-platform/src/features.rs
- quic/s2n-quic-platform/src/features/tos_v4.rs
- quic/s2n-quic-platform/src/features/tos_v6.rs
- quic/s2n-quic-platform/src/message/cmsg.rs
- quic/s2n-quic-platform/src/message/msg/ext.rs
- quic/s2n-quic-platform/src/syscall.rs
Similar to #2062, this change makes TOS/ECN features readable at runtime in order to reduce the amount of conditional compilation.
I split ipv4 and ipv6 into separate features since they use distinct values/types.
This is mostly just a refactor so all of the existing tests should suffice.
> feat(s2n-quic-platform): make TOS features readable at runtime

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/buffer/receive_buffer.rs
- quic/s2n-quic-core/src/buffer/receive_buffer/probe.rs
- quic/s2n-quic-core/src/buffer/receive_buffer/request.rs
- quic/s2n-quic-core/src/buffer/receive_buffer/slot.rs
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-core/src/probe.rs
- quic/s2n-quic-core/src/sync/spsc/tests.rs
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic/Cargo.toml
This change adds support for defining static probes throughout the codebase:
https://github.com/aws/s2n-quic/blob/cd06c5847574ee37a28370f103a423db1b07892f/quic/s2n-quic-core/src/buffer/receive_buffer/probe.rs#L4-L18
In the code, you can then just call your probes like regular functions - all with autocompletion and strict typing!
https://github.com/aws/s2n-quic/blob/cd06c5847574ee37a28370f103a423db1b07892f/quic/s2n-quic-core/src/buffer/receive_buffer/request.rs#L64-L65
The probe can then be configured through feature flags to:
* emit a `tracing` record
* register as a USDT probe, which can be read by tools like bpftrace.
I've enabled `probe-tracing` on the `s2n-quic` dev-dependencies, so all of the integration tests can be more-easily traced:
```
$ S2N_LOG=trace cargo test -p s2n-quic …
```
> feat(s2n-quic-core): add USDT probe support

- .github/workflows/qns.yml
- quic/s2n-quic-qns/etc/Dockerfile
In order to simplify the supply chain, this changes the base image for the s2n-quic-qns docker image to use AL2023.
To make it clear which software is being distributed, I've also added `cargo-auditable` to list all of the dependencies used by the s2n-quic-qns binary.
The `release` CI job will show the build working end-to-end. I also made a temporary change to show it working in the context of the [interop runner in CI](https://dnglbrstg7yg.cloudfront.net/98fea38742cf112acac7adf649271ea7ed2659d8/interop/index.html). I've also tested locally, including using `syft` to print out a SBOM:
```
$ sudo DOCKER_BUILDKIT=1 docker build . --file quic/s2n-quic-qns/etc/Dockerfile --target default --tag aws/s2n-quic-qns --build-arg tls=s2n-tls --build-arg release=true
$ syft aws/s2n-quic-qns --scope …
```
> ci: use AL2023 for qns image

- .github/interop/required.json
- examples/resumption/README.md
- quic/s2n-quic-core/src/connection/error.rs
- quic/s2n-quic-qns/src/client/interop.rs
- quic/s2n-quic-qns/src/tls.rs
- quic/s2n-quic-tls/src/session.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/endpoint/initial.rs
N/A
Adds functionality so that the client resumption feature is added to the interop test. 
Also adds a readme for the resumption example.
> feat(s2n-quic-qns): Client Resumption Interop test

- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-h3/src/s2n_quic.rs
- quic/s2n-quic-platform/src/io/testing/time.rs
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-qns/src/file.rs
- quic/s2n-quic-sim/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic-transport/src/stream/api.rs
- quic/s2n-quic-transport/src/stream/controller.rs
- quic/s2n-quic-transport/src/stream/manager.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/connection/acceptor.rs
- quic/s2n-quic/src/connection/handle.rs
- quic/s2n-quic/src/stream/receive.rs
- quic/s2n-quic/src/stream/send.rs
- rust-toolchain
This PR bumps the MSRV to 1.71.1. It also bumps and unpins many crates that were previously pinned due to a lower MSRV.
CI passes
> chore: MSRV bump

- quic/s2n-quic-core/src/connection/error.rs
- quic/s2n-quic-core/src/token.rs
- quic/s2n-quic-qns/src/server/interop.rs
- quic/s2n-quic/src/provider/datagram.rs
We're currently getting a failure on rustc beta on `main` (and a handful of warnings). This PR addresses those issues.
> fix: implement custom PartialEq for connection::Error

- .github/workflows/qns.yml
- .github/workflows/release.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
The testing environment currently closes a socket on drop. This means that any outstanding packets in the TX queue are not submitted.
This change fixes that by marking the socket as closed and draining it. Once empty, the socket queue is removed from the network.
I've also added a small function to know if the caller is running inside of a test environment or not.
> test(s2n-quic-platform): drain tx packets before closing host

- quic/s2n-quic-transport/Cargo.toml
ahash 0.8.8 requires rust 1.72, see https://github.com/aws/s2n-quic/issues/2118
> chore(s2n-quic-transport): pin ahash to 0.8.7

- quic/s2n-quic/Cargo.toml
The pinned `ahash` dev-dependency in `s2n-quic-transport` is not respected during the build process that `cargo publish` executes (see #2009 for a similar issue). This change pins `ahash` in the s2n-quic cargo.toml as well.
> chore(s2n-quic): pin ahash in s2n-quic

- quic/s2n-quic-core/src/inet/checksum.rs
This fixes the issue of Kani going out of memory in CI on the `inet::checksum::tests::differential` test, e.g.
https://github.com/aws/s2n-quic/actions/runs/7892365794/job/21538690964
The current length used in the `inet::checksum::tests::differential` test is 16, which causes Kani's latest version (v0.46.0) to run out of memory (see https://github.com/model-checking/kani/issues/3030). Until this issue is fixed, reducing the length to 4 to allow a smaller unwinding depth to prevent the OOM issue.
> test(s2n-quic-core): use a smaller length in the Kani test

- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
ahash 0.8.7+ requires rust 1.72 on aarch64-apple-darwin. This change pins ahash to 0.8.6 in dev-dependencys. Applications consuming s2n-quic will still need to pin ahash in their own `Cargo.toml` if they need to build on rust < 1.72
See #2125 
> chore(s2n-quic): pin ahash to 0.8.6

- quic/s2n-quic-core/src/interval_set/mod.rs
When using the IntervalSet in tests outside of `s2n-quic-core`, you currently incur the cost of internal consistency checking. This change replaces `cfg(debug_assertions)` with `cfg(test)` to avoid these costs.
The existing tests will still ensure these checks stay consistent.
> test(s2n-quic-core): only check IntervalSet integrity in tests

- .github/workflows/ci.yml
- common/s2n-codec/Cargo.toml
- common/s2n-codec/src/decoder/checked_range.rs
- common/s2n-codec/src/decoder/mod.rs
- common/s2n-codec/src/decoder/value.rs
- common/s2n-codec/src/encoder/value.rs
- common/s2n-codec/src/testing/mod.rs
- common/s2n-codec/src/unaligned.rs
The `unaligned` types in `s2n-codec` currently don't have `to_be_bytes` and `from_be_bytes` methods. This change adds them.
I've included round trip tests for all of the integer types to show this working.
> feat(s2n-codec): add bytes methods for unaligned types

- quic/s2n-quic-core/src/time/clock.rs
- quic/s2n-quic-core/src/time/timer.rs
This adds a mechanism to cache the clock value after the first call. This can reduce the number of times we read from the system clock, where we don't care about high precision between events.
I've also added a timer debugger that you can query all of the locations in the timer tree that print where they are and if they're armed or not.
> feat(s2n-quic-core): add Cached clock implementation

- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
This PR changes the SAT solver for `weighted_average_test` from `kissat` to `cadical`. Therefore, it only changes the s2n-quic's behavior when it's being analyzed with Kani.
We're proposing this change because we've observed +33% SAT solving time in https://github.com/model-checking/kani/pull/3052 for this test after a Rust Toolchain Upgrade (RTU). The RTU didn't cause changes in the SAT problem w.r.t. size nor other properties. During our investigation, we also tested `weighted_average_test` with `cadical` and the results showed a lower overall times in addition to lower increases:
| | before RTU (s) | after RTU (s)| increase (%) |
| --- | --- | --- | --- |
| kissat | 150.85266 | 200.95573 |  +33.2 |
| cadical | 113.84968 |  116.03474 | +1.9 |
By submitting this pull request, I confirm …
> chore(s2n-quic-core): use cadical for `weighted_average_test`

- tools/xdp/s2n-quic-xdp/src/umem.rs
Provides a method on Umem to expose the raw pointer to the memory mapped memory. This is necessary backdoor for 3rd party use, for instance to use madvise on the memory region, or to expose to other crates. Any such use would require the user to caveat it as unsafe (de-referencing a pointer)
> Expose XDP umem ptr

- quic/s2n-quic-core/src/stream/mod.rs
- quic/s2n-quic-core/src/stream/state.rs
- quic/s2n-quic-core/src/stream/state/recv.rs
- quic/s2n-quic-core/src/stream/state/send.rs
- quic/s2n-quic-core/src/stream/state/snapshots/s2n_quic_core__stream__state__recv__tests__snapshots.snap
- quic/s2n-quic-core/src/stream/state/snapshots/s2n_quic_core__stream__state__send__tests__snapshots.snap
This change adds a state enum for both Send and Receive. These enums make it easy to ensure only valid state transitions are taken in the actual usage of the code. It also includes some tracing to show when these transitions take place for easy debugging.
I will switch the current stream implementations to use these state enums as a separate PR.
> feat(s2n-quic-core): add stream state enums

- tools/xdp/s2n-quic-xdp/src/if_xdp.rs
Adds the `XDP_USE_SG` flag to the set of XDP flags, introduced in [81470b5c3c6649eef8e5f282cd06793f788ae165](https://github.com/torvalds/linux/commit/341ac980eab90ac1f6c22ee9f9da83ed9604d899)
> Add Flag for XDP Scatter-gather mode

- quic/s2n-quic-platform/src/io/tokio.rs
resolves #2155
Previously, when the syscall to configure MTU discovery failed, we would reduce the MTU used for both transmitting and receiving packets to the minimum MTU. This can prevent receiving packets from peers that are using a larger MTU. This change will only reduce the MTU for transmitting packets, leaving the rx MTU at the originally configured value.
Tested locally on MacOS, where the configure_mtu_disc syscall fails.
> fix(s2n-quic-platform): don't reduce rx MTU when tx MTU is reduced

- .github/workflows/ci.yml
- quic/s2n-quic-crypto/Cargo.toml
This PR adds a CI job to run our `cargo test` command in a musl environment.
This required adding a `aws-lc-bindgen` feature to the `s2n-quic-crypto` crate, since musl doesn't have pregenerated bindings at this time.
The job is passing: https://github.com/aws/s2n-quic/actions/runs/8381808920/job/22954227581?pr=2102
> ci: add musl tests

- examples/async-client-hello-callback/src/bin/quic_async_client_hello_callback_server.rs
- quic/s2n-quic/src/provider/packet_interceptor.rs
A new version of rustc dropped with new clippy checks. This PR fixes those.
> build: fix clippy warnings for 1.77

- .github/actions/duvet/action.yml
- .github/workflows/ci.yml
- .github/workflows/dependencies.yml
- .github/workflows/qns.yml
https://github.com/aws/s2n-quic/issues/2096
This PR removes actions-rs GHA (deprecated) and replaces it with rustup operations.
Existing tests should pass
> ci: use rustup instead of actions-rs

- .github/workflows/release.yml
This change will publish the `s2n-quic-qns` image to the GitHub container registry, in addition to Amazon ECR. 
I followed the instructions from https://docs.docker.com/build/ci/github-actions/push-multi-registries/ for pushing to multiple registries. #1189 contains the change to move to ECR originally, I took the GitHub Container Registry values from that PR.
Will verify once this is merged to main
> ci: publish to GitHub Container Registry

- examples/rustls-mtls/Cargo.toml
- examples/rustls-mtls/src/lib.rs
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-qns/src/tls.rs
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-rustls/src/certificate.rs
- quic/s2n-quic-rustls/src/cipher_suite.rs
- quic/s2n-quic-rustls/src/client.rs
- quic/s2n-quic-rustls/src/error.rs
- quic/s2n-quic-rustls/src/lib.rs
- quic/s2n-quic-rustls/src/server.rs
- quic/s2n-quic-rustls/src/session.rs
This reverts commit 15f234c495f98cf61652cf70e8dbc3c7565098b4.
See https://github.com/aws/s2n-quic/issues/2173 for more details.
Needed to add a new pem parser, `rustls_pemfile::ec_private_keys`, since the interop runner has started using new EC based keys and we were [not able to parse them](https://github.com/aws/s2n-quic/actions/runs/8573119698/job/23497429453?pr=2174#step:13:156). But also because this prob should have been present from the beginning.
Existing CI should pass.
> Revert "feat(s2n-quic-rustls): update rustls from 0.21 to 0.23 (#2143)"

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/path/mtu.rs
- quic/s2n-quic-core/src/path/mtu/tests.rs
- quic/s2n-quic-events/events/connection.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/mod.rs
- quic/s2n-quic-transport/src/space/application.rs
This change renames some usages of the term `MTU` to `max_datagram_size` to better reflect what the value represents. 
`MTU` is usually used for referring to the maximum size of an IP packet that can be transmitted on a path, which includes the size of the IP headers and UDP headers that prefix a QUIC packet. In QUIC we are more concerned with the maximum size of a QUIC datagram that can be sent on a path. This "max datagram size" value does not include the size of IP headers and UDP headers.
I added a comment on the `mtu` field of the `MtuUpdated` event indicating the value does not include IP header or UDP header sizes, but I did not mark the field as deprecated and add a new field, as it didn't seem worth it. 
Existing tests
By submitting this pull request, I confirm that my …
> refactor: rename mtu to max_datagram_size

- .github/workflows/ci.yml
- quic/s2n-quic-core/src/connection/limits.rs
- quic/s2n-quic-core/src/transport/parameters/mod.rs
- quic/s2n-quic-tls/src/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/manager/fuzz_target.rs
- quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__active_connection_migration_disabled.snap
- quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__active_connection_migration_disabled_passive_migration.snap
- quic/s2n-quic-transport/src/path/manager/tests.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- tools/xdp/ebpf/rust-toolchain.toml
This change adds a `with_connection_migration(enabled: bool)` setting to the default connection limiter provider. When set to `false`, the `disable_active_migration` transport parameter will be sent to the peer, and any attempt by the peer to perform an active connection migration will be ignored.
The definition of "active connection migration" is the peer sending from a different source address while also changing the destination connection ID it was using previously. This is in contrast to a passive cnonection migration (caused by a NAT rebind or similar), where the peer would not know its source address changed, and thus would not change the destination connection ID.
I went back and forth on whether this belonged in the path migration validator provider, but ultimately decided against …
>  feat(s2n-quic): allow disabling active connection migration support

- quic/s2n-quic-core/src/buffer/reader/incremental.rs
This change adds a `new` method to the incremental `reader` to allow starting at an offset other than 0. 
Added to existing unit test
> feat(s2n-quic-core): Add ability to create an incremental reader initialized with an offset

- quic/s2n-quic-platform/src/message.rs
- quic/s2n-quic-platform/src/message/simple.rs
The need is described in https://github.com/aws/s2n-quic/issues/2188.
This is the minimal change I needed to implement my own custom io provider. 
resolves #2188
> feat(s2n-quic-provider): make some message methods public

- examples/custom-congestion-controller/README.md
- examples/post-quantum/README.md
- examples/resumption/README.md
- examples/unreliable-datagram/README.md
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-qns/src/server.rs
- quic/s2n-quic-qns/src/tls.rs
- quic/s2n-quic-tls/src/certificate.rs
- quic/s2n-quic-tls/src/lib.rs
- quic/s2n-quic-tls/src/server.rs
- quic/s2n-quic-tls/src/tests.rs
- quic/s2n-quic/src/lib.rs
This cfg (intentionally) prevents a downstream library from wrapping s2n-quic unstable API internally without the final build explicitly opting into that instability. Unfortunately, with s2n-quic-dc, we want to do exactly that. Essentially we'll be treating `s2n-quic` from `s2n-quic-dc` the same way we treat `s2n-quic-core` from `s2n-quic`.
For the time being drop the cfg entirely. Since it's only set to allow unstable features, we should technically be able to revert this change at some point (e.g., if dc stops depending on unstable surface area): it would be fairly similar to just breaking consumers of those unstable features, which is already allowed.
Not sure I caught everything in this -- mostly relying on a grep for s2n_quic_unstable and just blindly updating cfgs.
None.
By …
> Remove --cfg s2n_quic_unstable

- .github/interop/required.json
The neqo client has started to fail the resumption interop test with the s2n-quic server. This PR temporarily removes neqo from the list of required client implementations for the resumption test, until we finish investigating the cause of the failure.
After resolving the issue, we should revert this change. See https://github.com/aws/s2n-quic/issues/2192.
The interop job should succeed.
> ci: Remove neqo from required resumption test clients

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-core/src/macros.rs
- quic/s2n-quic-core/src/state.rs
- quic/s2n-quic-core/src/stream/state.rs
- quic/s2n-quic-core/src/stream/state/recv.rs
- quic/s2n-quic-core/src/stream/state/send.rs
- quic/s2n-quic-core/src/stream/state/snapshots/s2n_quic_core__stream__state__recv__tests__dot_test.snap
- quic/s2n-quic-core/src/stream/state/snapshots/s2n_quic_core__stream__state__send__tests__dot_test.snap
This change exposes the `stream/state` macros to be more general and used outside of the core crate. As a bonus, we get free dot graphs:
I moved all of the root-level macros into a `macros` module to keep the root a bit cleaner.
The existing snapshot tests of the stream state impls should prevent any regressions in behavior. I've also added new snapshot tests for the dot output.
> feat(s2n-quic-core): add state construction

- quic/s2n-quic-core/src/frame/__fuzz__/frame__tests__round_trip/corpus.tar.gz
With the new frame introduced in https://github.com/aws/s2n-quic/pull/2198, I fuzz tested the frame code for a couple hours. This change updates the corpus from that fuzzing. 
> chore(s2n-quic-core): update frame round trip fuzz corpus

- .github/workflows/ci.yml
- quic/s2n-quic-core/src/crypto/application/keyset.rs
- quic/s2n-quic-core/src/crypto/application/limited.rs
- quic/s2n-quic-core/src/crypto/key.rs
- quic/s2n-quic-core/src/crypto/mod.rs
- quic/s2n-quic-core/src/crypto/tests.rs
- quic/s2n-quic-core/src/crypto/tls/null.rs
- quic/s2n-quic-core/src/crypto/tls/testing.rs
- quic/s2n-quic-core/src/packet/encoding.rs
- quic/s2n-quic-core/src/packet/tests.rs
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-crypto/src/aead/default.rs
- quic/s2n-quic-crypto/src/aead/fips.rs
- quic/s2n-quic-crypto/src/aead/mod.rs
- quic/s2n-quic-crypto/src/cipher_suite.rs
- quic/s2n-quic-crypto/src/cipher_suite/negotiated.rs
- quic/s2n-quic-crypto/src/cipher_suite/ring.rs
- quic/s2n-quic-crypto/src/initial.rs
- quic/s2n-quic-crypto/src/lib.rs
- quic/s2n-quic-crypto/src/negotiated.rs
- quic/s2n-quic-crypto/src/one_rtt.rs
- quic/s2n-quic-crypto/src/retry.rs
- quic/s2n-quic-crypto/src/zero_rtt.rs
- quic/s2n-quic-rustls/src/cipher_suite.rs
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/lib.rs
This PR exposed a new `provider-fips-crypto` feature flag and makes the necessary changes for s2n-quic to use FIPS-approved cryptography for encryption.
We want to support fips mode for:
- if s2n-quic-crypto `fips` flag is set (compile time check)
- target_os != windows (compile time check)
- negotiated cipher is not CHACHA20_POLY1305  (runtime check)
To avoid branching on the `fips` and windows, I throw a compiler error if the `fips` flag is set on windows:
```
#[cfg(all(feature = "fips", target_os = "windows"))]
std::compile_error!("feature `fips` is not supported on windows");
```
To avoid branching on the CHACHA20_POLY1305 I don't derive FipsKeys when using this cipher. This was a macro level change (`key!`) rather than code branching, which helps with readability imo. 
A lot of the …
> feat(s2n-quic): provider-crypto-fips feature flag

- examples/rustls-mtls/Cargo.toml
- examples/rustls-mtls/src/lib.rs
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-qns/src/tls.rs
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-rustls/src/certificate.rs
- quic/s2n-quic-rustls/src/cipher_suite.rs
- quic/s2n-quic-rustls/src/client.rs
- quic/s2n-quic-rustls/src/error.rs
- quic/s2n-quic-rustls/src/lib.rs
- quic/s2n-quic-rustls/src/server.rs
- quic/s2n-quic-rustls/src/session.rs
**DO NOT MERGE** this PR introduces a change since we now build with aws-lc-rs rather than ring. We should figure out who this impacts before merging this.
This PR reverts the revert PR to upgrade rustls:
- Original PR: (#2143)
- Revert PR: (#2174)
One noteworthy change: rustls now has a concept of crypto providers (ring or aws-lc-rs) and by default uses aws-lc-rs. For this reason I choose to use aws-lc-rs also, which is a change in behavior since previously we used ring. In the future we could expose the option for s2n-quic customers to choose their own crypto provider.
I removed some deprecated exports because either:
- they no longer exist (`::rustls::{Certificate, PrivateKey}`)
- they are not useful (`pub static DEFAULT_CIPHERSUITES: &[rustls::SupportedCipherSuite]`)
Existing unit …
> feat(s2n-quic-rustls): update rustls from 0.21 to 0.23

- quic/s2n-quic-core/src/buffer.rs
- quic/s2n-quic-core/src/buffer/deque.rs
- quic/s2n-quic-core/src/buffer/deque/storage.rs
- quic/s2n-quic-core/src/buffer/deque/tests.rs
- quic/s2n-quic-core/src/buffer/duplex/interposer.rs
- quic/s2n-quic-core/src/buffer/reader/storage/chunk.rs
- quic/s2n-quic-core/src/buffer/reader/storage/slice.rs
- quic/s2n-quic-core/src/buffer/writer/storage.rs
- quic/s2n-quic-core/src/buffer/writer/storage/vec_deque.rs
- quic/s2n-quic-core/src/slice.rs
- quic/s2n-quic-core/src/slice/deque.rs
- quic/s2n-quic-core/src/slice/deque/pair.rs
This adds a byte ring buffer for efficient vectored reads/writes between socket syscalls.
I've added several bolero harnesses for checking the correctness of the implementation.
> feat(s2n-quic-core): add buffer::Deque implemention

- .github/workflows/ci.yml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-rustls/src/cipher_suite.rs
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-tls/src/client.rs
- quic/s2n-quic-tls/src/server.rs
- quic/s2n-quic/Cargo.toml
This PR passes the `fips` flag down to the tls libraries. We also `assert` that each tls library is built with a fips-approved libcrypto when the `provider-tls-fips` is enabled for s2n-quic.
Extended the fips testing to rustls. The failing commits validate that we are in fact testing both s2n-tls and rustls in fips mode.
> feat(s2n-quic-tls, s2n-quic-rustls): pass `fips` flag to tls backend

- quic/s2n-quic-core/src/dc.rs
- quic/s2n-quic-core/src/dc/disabled.rs
- quic/s2n-quic-core/src/dc/mod.rs
- quic/s2n-quic-core/src/dc/traits.rs
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/connection/mod.rs
- quic/s2n-quic-transport/src/endpoint/config.rs
- quic/s2n-quic-transport/src/endpoint/initial.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic-transport/src/space/session_context.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/client/builder.rs
- quic/s2n-quic/src/client/providers.rs
- quic/s2n-quic/src/provider.rs
- quic/s2n-quic/src/provider/dc.rs
- quic/s2n-quic/src/server/builder.rs
- quic/s2n-quic/src/server/providers.rs
This change adds an unstable dc provider for configuring dc functionality. The provider will not actually be used until subsequent PRs. 
I've implemented `Path` for `Option<P>` as I was planning to have the `dc::Manager` operate on an `Option<Path>` rather than just `Path`. This is because dc can end up disabled for a path in 2 ways: 
1) by not configuring a provider, in which case the `Disabled` provider is used (which has an associated type of `DisabledPath`)
2) by not being able to negotiate a dc version. In this case, the associated `Path` type of the dc provider is used but shouldn't actually do anything. 
I didn't want the implementor of the provider to have to handle when no dc version is negotiated, so instead I'll have the `dc::Manager` handle that case.
Will add tests after …
> feat(s2n-quic): unstable dc provider

- quic/s2n-quic-core/src/slice.rs
- quic/s2n-quic-core/src/state.rs
- quic/s2n-quic-core/src/state/snapshots/s2n_quic_core__state__tests__dot_test.snap
- quic/s2n-quic-core/src/state/snapshots/s2n_quic_core__state__tests__snapshots.snap
- quic/s2n-quic-core/src/state/tests.rs
- quic/s2n-quic-core/src/stream/state/snapshots/s2n_quic_core__stream__state__recv__tests__snapshots.snap
- quic/s2n-quic-core/src/stream/state/snapshots/s2n_quic_core__stream__state__send__tests__snapshots.snap
This adds a mechanism for the state machine macro to allow for multiple states to react to the same events. I've added an example test to show the behavior:
```rust
#[derive(Clone, Debug, Default, PartialEq, Eq)]
enum State {
#[default]
Init,
Left,
Right,
LeftLeft,
LeftRight,
RightLeft,
RightRight,
}
impl State {
event! {
on_left(
Init => Left,
Left => LeftLeft,
Right => RightLeft,
);
on_right(
Init => Right,
Left => LeftRight,
Right => RightRight,
);
}
}
```
The example is being used as a test with snapshot tests for the dot output as well as each state+event combination.
> feat(s2n-quic-core): allow for branching states on common events

- quic/s2n-quic-core/src/state.rs
- quic/s2n-quic-core/src/state/snapshots/s2n_quic_core__state__tests__snapshots.snap
- quic/s2n-quic-core/src/state/tests.rs
- quic/s2n-quic-core/src/stream/state/recv.rs
- quic/s2n-quic-core/src/stream/state/send.rs
- quic/s2n-quic-core/src/stream/state/snapshots/s2n_quic_core__stream__state__recv__tests__snapshots.snap
- quic/s2n-quic-core/src/stream/state/snapshots/s2n_quic_core__stream__state__send__tests__snapshots.snap
This change adds a test helper method for state machine implementations that prints out each state and its reaction to an event, i.e. if it is successful or if it's an invalid transition. This was being done manually for the current state implementations so each of those were cleaned up as part of this.
The existing snapshot tests have been updated to use the new helper method.
> feat(s2n-quic-core): generate state reactions to events

- quic/s2n-quic-core/src/state.rs
- quic/s2n-quic-core/src/state/snapshots/s2n_quic_core__state__tests__lr_dot_test.snap
- quic/s2n-quic-core/src/state/snapshots/s2n_quic_core__state__tests__lr_snapshots.snap
- quic/s2n-quic-core/src/state/snapshots/s2n_quic_core__state__tests__microwave_dot_test.snap
- quic/s2n-quic-core/src/state/snapshots/s2n_quic_core__state__tests__microwave_snapshots.snap
- quic/s2n-quic-core/src/state/tests.rs
- quic/s2n-quic-core/src/stream/state/snapshots/s2n_quic_core__stream__state__recv__tests__dot_test.snap
- quic/s2n-quic-core/src/stream/state/snapshots/s2n_quic_core__stream__state__send__tests__dot_test.snap
I wanted to get a bit better coverage on the state machine macro for a more complicated example so this adds a test for a microwave state machine.
> test(s2n-quic-core): add microwave state example

- quic/s2n-quic-transport/src/dc/manager/snapshots/s2n_quic_transport__dc__manager__tests__dot_test.snap
#2222 changed the dot snapshot format a bit, but didn't have the latest dc manager code pulled in, so the snapshot test was failing in main. This fixes the snapshot 
> chore(s2n-quic-transport): update dc manager dot snapshot

- quic/s2n-quic/src/lib.rs
Document how to enable FIPS mode when using the rustls TLS backend.
> docs(s2n-quic): fips mode usage with rustls TLS provider

- dc/s2n-quic-dc/src/congestion.rs
- quic/s2n-quic-core/src/recovery/bbr.rs
- quic/s2n-quic-core/src/recovery/bbr/drain.rs
- quic/s2n-quic-core/src/recovery/bbr/full_pipe.rs
- quic/s2n-quic-core/src/recovery/bbr/pacing.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_rtt.rs
- quic/s2n-quic-core/src/recovery/bbr/startup.rs
- quic/s2n-quic-core/src/recovery/bbr/tests.rs
- quic/s2n-quic-core/src/recovery/congestion_controller/fuzz_target.rs
- quic/s2n-quic-core/src/recovery/cubic.rs
- quic/s2n-quic-core/src/recovery/cubic/tests.rs
- quic/s2n-quic-core/src/recovery/simulation.rs
- quic/s2n-quic/src/provider/congestion_controller.rs
This PR exposes a few configuration options that modify the default congestion controllers.
While it is possible to create a [custom congestion controller](https://github.com/aws/s2n-quic/pull/1758), customers might find it more useful to simply override some key parameters on the deafult congestion controller algorithm rather than replicating the entire congestion control algorithm.
- The `with_congestion_window` API is exposed as a stable API, while other options are marked as unstable
- While it makes sense to expose CC configuration parameters behind an unstable flag (getting them wrong can render the network impaired), setting the initial congestion window ([initcwnd](https://www.cdnplanet.com/blog/tune-tcp-initcwnd-for-optimum-performance/)) is also supported on TCP and seems like a …
> feat(s2n-quic): expose configuration options for congestion control

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/connection/limits.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/manager/tests.rs
- quic/s2n-quic-transport/src/path/mod.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic/Cargo.toml
> The primary defense against amplification attacks is verifying that a peer is able to receive packets at the transport address that it claims. Therefore, after receiving packets from an address that is not yet validated, an endpoint MUST limit the amount of data it sends to the unvalidated address to three times the amount of data received from that address. This limit on the size of responses is known as the anti-amplification limit.
https://www.rfc-editor.org/rfc/rfc9000#section-8
QUIC suggest an anti-amplification limit of 3, however customers operating s2n-quic in trusted environments might want to opt for higher anti-amplification limits so that they can complete the handshake/start transferring data quicker. This PR exposes an unstable configuration so that application can provide …
> feat(s2n-quic): allow application to configure the anti_amplification_multiplier

- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
Version bump for 1.38.1 release
I added a version to the optional `s2n-quic-tls` dependency in the `s2n-quic-tls-default` crate, as it is required to publish to crates.io
>  chore: release 1.38.1

- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/inet/checksum.rs
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic-transport/src/ack/tests/generator.rs
- quic/s2n-quic-transport/src/ack/tests/network_event.rs
- quic/s2n-quic-transport/src/ack/tests/network_interface.rs
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
`bolero` `v0.11` was released. This updates our dependency.
I fixed the checksum tests with kani that slowed down after a change in the rustc version (see https://github.com/model-checking/kani/issues/3030). Using `get_unchecked` instead of `split_at` seems to have improved performance quite a bit - the job now completes in [10m](https://github.com/aws/s2n-quic/actions/runs/9453148563/job/26037892798) instead of [15m](https://github.com/aws/s2n-quic/actions/runs/9406675053/job/25910651328).
The CI tests should continue to pass.
> build(deps): update bolero to 0.11.0

- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/stream/send/worker.rs
resolves #2241
`generational-arena` is unmaintained and needs to be replaced with `slotmap`
The interface/functionality is the same so the existing unit tests should suffice.
> fix(s2n-quic-dc): replace generational-areana with slotmap

- quic/s2n-quic-core/src/dc.rs
- quic/s2n-quic-core/src/dc/disabled.rs
- quic/s2n-quic-core/src/dc/testing.rs
- quic/s2n-quic-core/src/dc/traits.rs
- quic/s2n-quic-transport/src/dc/manager.rs
- quic/s2n-quic-transport/src/dc/manager/tests.rs
- quic/s2n-quic-transport/src/space/session_context.rs
dc provider implementations need to know if the local endpoint is a server or a client. This change adds that information to the `dc::ConnectionInfo` passed to the provider.
Also, the `on_path_secrets_ready` method may have reason to fail (such as if the given path secrets are using a cipher suite not supported by the provider implementation). This change makes that method fallible. 
Updated unit test
> feat(s2n-quic-core): updates to dc provider

- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/lib.rs
- dc/s2n-quic-dc/src/socket.rs
- dc/s2n-quic-dc/src/socket/bpf.rs
- dc/s2n-quic-dc/src/socket/pair.rs
- dc/s2n-quic-dc/src/socket/snapshots/s2n_quic_dc__socket__bpf__tests__routing_logic.snap
- dc/s2n-quic-dc/src/socket/snapshots/s2n_quic_dc__socket__bpf__tests__snapshot_test.snap
- quic/s2n-quic-platform/src/bpf.rs
- quic/s2n-quic-platform/src/bpf/cbpf.rs
- quic/s2n-quic-platform/src/bpf/common.rs
- quic/s2n-quic-platform/src/bpf/ebpf.rs
- quic/s2n-quic-platform/src/bpf/instruction.rs
- quic/s2n-quic-platform/src/bpf/program.rs
- quic/s2n-quic-platform/src/bpf/snapshots/s2n_quic_platform__bpf__cbpf__tests__static_program_debug.snap
- quic/s2n-quic-platform/src/bpf/snapshots/s2n_quic_platform__bpf__cbpf__tests__static_program_display.snap
- quic/s2n-quic-platform/src/lib.rs
- quic/s2n-quic-platform/src/socket.rs
- quic/s2n-quic-platform/src/socket/options.rs
This change adds a mechanism to easily construct UDP and TCP sockets with a `socket::Options` struct. I've also included an in-memory BPF assembler, which enables creating pairs of UDP sockets and route packets between them.
Several tests were added as part of these changes.
> feat(s2n-quic-dc): add socket constructor

- quic/s2n-quic/src/lib.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/fips.rs
Our documentation should make an actual recommendation for a FIPS security policy, rather than rely on the customer reading the s2n-tls docs. Ideally it would be `default_fips`, but that doesn't support TLS 1.3 currently. When it does, we should update this documentation to refer to that instead.
I added a test to show the recommended policy working.
> docs: make an actual policy recommendation for fips

- dc/wireshark/pcaps/secret-control-tcp.pcapng
- dc/wireshark/pcaps/secret-control-udp.pcapng
- dc/wireshark/src/dissect.rs
- dc/wireshark/src/plugin.rs
- dc/wireshark/src/test.rs
- dc/wireshark/xtask/Cargo.toml
- dc/wireshark/xtask/src/main.rs
This change renamed the `dissect::udp_segment` function to `dissect::segment` and calls it from both UDP and TCP now. This ensures that all packet types are handled. It also can make it easier to diagnose issues if, for example, TCP is transmitting Control or Datagram packets.
I've added some sample pcaps to show it working for `UnknownPathSecret` packets.
> fix(dc-wireshark): parse all packet types in TCP

- quic/s2n-quic-core/src/crypto/tls.rs
- quic/s2n-quic-core/src/inet/unspecified.rs
- quic/s2n-quic-core/src/task/waker.rs
- quic/s2n-quic-core/src/task/waker/contract.rs
- quic/s2n-quic-platform/src/socket/io/rx.rs
- quic/s2n-quic-platform/src/socket/io/tx.rs
- quic/s2n-quic-transport/src/endpoint/connect.rs
- quic/s2n-quic/src/connection/handle.rs
- quic/s2n-quic/src/server.rs
- quic/s2n-quic/src/stream/receive.rs
- quic/s2n-quic/src/stream/send.rs
This change adds a helper function to ensure `poll_*` methods adhere to the required contract of either storing the provided `Waker` for later or immediately waking the waker to reschedule the task to be polled again. If neither of these events happen, you end up with a zombie task that is never able to make any progress.
I've also wired up this helper to all of our top-level poll APIs to ensure this contract is preserved. Luckily, we don't have any issues there.
> feat(s2n-quic-core): add waker contract helper

- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/src/dc.rs
- quic/s2n-quic-core/src/dc/testing.rs
- quic/s2n-quic-core/src/path/mtu.rs
- quic/s2n-quic-core/src/path/mtu/tests.rs
- quic/s2n-quic-transport/src/path/mod.rs
- quic/s2n-quic-transport/src/space/session_context.rs
This change replaces the usage of `MaxMtu` in `dc::ApplicationParams` with the `max_datagram_size`, which is a value based on the actual confirmed MTU size, rather than a configured setting. This removes the last remaining usage of `MaxMtu` from the `mtu::Controller`, so I've cleaned that up a bit as well.
This requires setting the `InitialMtu` setting to quickly probe a given MTU size, as the `dc::ApplicationParams` are configured before any regular MTU probing occurs.
I've also derived `Copy` for `ApplicationParams` and added a `TEST_APPLICATION_PARAMS` const for convenience. 
Existing tests
> feat(s2n-quic-dc): set max_datagram_size in ApplicationParams

- .clippy.toml
- .github/workflows/ci.yml
- dc/s2n-quic-dc/src/packet/control/encoder.rs
- dc/s2n-quic-dc/src/packet/datagram/encoder.rs
- dc/s2n-quic-dc/src/packet/stream/encoder.rs
- dc/s2n-quic-dc/src/stream/send.rs
- dc/s2n-quic-dc/src/stream/send/probes.rs
- quic/s2n-quic-core/src/crypto/application/keyset.rs
- quic/s2n-quic-core/src/crypto/application/limited.rs
- quic/s2n-quic-core/src/inet/macros.rs
- quic/s2n-quic-core/src/path/ecn.rs
- quic/s2n-quic-core/src/path/mtu.rs
- quic/s2n-quic-core/src/probe.rs
- quic/s2n-quic-core/src/recovery/bbr/congestion.rs
- quic/s2n-quic-core/src/recovery/congestion_controller.rs
- quic/s2n-quic-core/src/recovery/pacing.rs
- quic/s2n-quic-core/src/recovery/sent_packets.rs
- quic/s2n-quic-tls/src/callback.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/mod.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic-transport/src/transmission/application.rs
- specs/todos/tls/4.6.2.toml
https://github.com/aws/s2n-quic/issues/2204
During grooming we identified a couple issues that don't have immediate next steps and no longer make sense to track.
- #301 This should be addressed once we add 0-RTT to s2n-quic. 
- #312 ignore `clippy::too_many_arguments` since our implementation needs all the args we pass to the functions.
> chore: cleanup github issues and clippy warnings

- dc/s2n-quic-dc/src/path/secret/map.rs
- quic/s2n-quic-core/src/dc.rs
- quic/s2n-quic-core/src/dc/disabled.rs
- quic/s2n-quic-core/src/dc/testing.rs
- quic/s2n-quic-core/src/dc/traits.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
This change adds a method to the `dc::Endpoint` trait that allows implementors of the trait to handle secret control packets. 
I didn't add new tests for this for now, but I think it should be possible to add an integration test as a follow up. 
> feat(s2n-quic-dc): Handle secret control packets in dc Endpoint

- quic/s2n-quic-h3/Cargo.toml
- quic/s2n-quic-h3/src/s2n_quic.rs
This change simply supports `h3` v0.0.6 that updates its trait definitions and supports `tracing` feature.
This PR changes the APIs of `s2n-quic-h3` according to the update of `h3`'s trait definition. This also adds an optional feature `tracing` as  the updates of the official crate `h3-quinn`  implementing `h3` traits.
I believe the change does not need to be updated at this point since it just follows the `h3`'s API changes.
Existing tests (but there is no test in `s2n-quic-h3` as well as `h3-quinn`)
> deps: h3-0.0.6 (w/ tracing feature as h3-quinn)

- quic/s2n-quic/src/provider/event/disabled.rs
This change implements `Default` (and `Debug`) for the disabled event Subscriber, so that one can call `s2n_quic::provider::event::default::Subscriber::default()` to get a default instance regardless if tracing is enabled or not
>  fix(s2n-quic): implement Debug and Default for the disabled event Subscriber

- quic/s2n-quic-core/src/application/server_name.rs
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic-transport/src/connection/connection_container.rs
- quic/s2n-quic-transport/src/connection/connection_id_mapper.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/mod.rs
- quic/s2n-quic-transport/src/endpoint/connect.rs
- quic/s2n-quic-transport/src/endpoint/initial.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/deduplicate.rs
- quic/s2n-quic/src/tests/recorder.rs
- quic/s2n-quic/src/tests/skip_packets.rs
resolves https://github.com/aws/s2n-quic/issues/2211
This implements support for utilizing s2n-quic to track open (or pending open) connection handles, effectively de-duplicating requests to open a connection.
* Currently using a `HashMap<Connect, InternalId>`. It's possible this could be made intrusive and save memory, though I'm not sure if the SNI and initial open SocketAddr are actually tracked within the connection state. This is purely an optimization though and shouldn't affect public API if we choose to apply it.
* I'm not very confident that all of the structures/counters are updated in the right places. For example, I had to add a manual drop of the tracking state rather than relying on implicitly dropping it. There's nothing in that code that drops other maps though, so that …
> feat(s2n-quic-transport): Support de-duplicating concurrent connections to the same peer

- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/test.rs
- quic/s2n-quic-core/src/dc/testing.rs
* Remove unused `ongoing_handshakes` storage, since we no longer expect to use it. This is just drive-by cleanup.
* See commit message for details on justification.
* Introduce new mechanism to enqueue a secret as stale based on time since it was added. Currently we keep requesting new handshakes every minute (at a random time), which is probably too often, but should be fine for current usage. A follow-up PR will add a builder for configuring the `Map`, which will ease providing knobs for customer-dependent usage.
Unfortunately, essentially none yet. I suspect that we'll want to have a long-lived canary of some kind that observes handshakes rates, etc. in practice as our highest fidelity test. Periodic, randomized functionality is otherwise pretty annoying to test.
By submitting this …
> feat(s2n-quic-dc): Periodically re-handshake existing path secrets

- quic/s2n-quic/src/provider/dc.rs
- quic/s2n-quic/src/provider/dc/client_confirm.rs
- quic/s2n-quic/src/provider/dc/confirm.rs
- quic/s2n-quic/src/tests/dc.rs
This change adds an `event::Subscriber` that allows a client that is negotiating DC to wait for the dc handshake to complete before closing the connection.
Updated the dc integration test to use the ClientConfirm 
> feat(s2n-quic-dc): add ClientConfirm subscriber

- dc/s2n-quic-dc/src/packet/control/decoder.rs
- dc/s2n-quic-dc/src/packet/control/encoder.rs
- dc/s2n-quic-dc/src/packet/datagram/decoder.rs
- dc/s2n-quic-dc/src/packet/datagram/encoder.rs
- dc/s2n-quic-dc/src/packet/secret_control/replay_detected.rs
- dc/s2n-quic-dc/src/packet/secret_control/stale_key.rs
- dc/s2n-quic-dc/src/packet/secret_control/unknown_path_secret.rs
- dc/s2n-quic-dc/src/packet/stream/decoder.rs
- dc/s2n-quic-dc/src/packet/stream/encoder.rs
- dc/wireshark/src/dissect.rs
This change reorders the wire_version and credential fields to better conform to the QUIC wire invariants.
> fix(s2n-quic-dc): reorder wire version to preserve wire invariants

- quic/s2n-quic-core/src/connection/error.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-transport/src/space/session_context.rs
- quic/s2n-quic/src/provider/dc/confirm.rs
- quic/s2n-quic/src/tests/dc.rs
The `ConfirmComplete` event subscriber is intended to allow a client or server using `dc` to wait for the `dc` handshake to complete before dropping the QUIC connection. In the case that the peer does not support `dc`, or does not support a `dc` version in common with the local endpoint, the current `ConfirmComplete` will not unblock the application. This change adds a new `NoVersionNegotiated` dc state changed event, and integrates it into the `ConfirmComplete` so that the application will be notified in such cases.
I'm not emitting the dc state changed event if the local endpoint has not configured a `dc` provider, so that these events wouldn't pollute logs for applications that are not using `dc`. This does mean that an application that has mistakenly not configured the `dc` provider …
> feat(s2n-quic-dc): return from ConfirmComplete when no dc version negotiated

- quic/s2n-quic-core/src/dc/testing.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic/src/tests/dc.rs
Currently, we only invoke `on_possible_secret_control_packet` if the datagram payload was not decoded as a valid packet. Since `dc` packets are formatted as valid short header packets, this meant the `on_possible_secret_control_packet` function was never called. This change moves the call to ``on_possible_secret_control_packet` after it is determined the packet does not belong to any known connection.
I added new integration tests to confirm `on_possible_secret_control_packet` is called. I also verified the new tests fail with the existing code.
>  fix(s2n-quic-dc): handle possible secret control packet correctly

- quic/s2n-quic-core/src/slice.rs
- quic/s2n-quic-platform/src/message/cmsg/tests.rs
- quic/s2n-quic-platform/src/message/msg/tests.rs
CaDiCaL version 1.9.2 and later have a substantially worse performance on some instances produced by CBMC (via Kani). Use MiniSat or Kissat instead to avoid this performance penalty when running proofs with (future versions of) Kani.
Tested in CI.
> chore: selectively change solvers to use with Kani

- quic/s2n-quic-core/src/packet/number/tests.rs
- quic/s2n-quic-platform/src/message.rs
CaDiCaL version 1.9.2 and later have a substantially worse performance on some instances produced by CBMC (via Kani). Use MiniSat to change overall verification time from over 800 seconds down to 20 (`rx_message_test`) and from over 80 seconds down to 15 (`round_trip`).
Tested in CI.
> chore: change further solvers in harnesses used with Kani

- common/s2n-codec/src/lib.rs
- dc/s2n-quic-dc/src/lib.rs
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/application/server_name.rs
- quic/s2n-quic-core/src/lib.rs
- quic/s2n-quic-platform/src/lib.rs
- quic/s2n-quic-qns/src/main.rs
- quic/s2n-quic-tls/src/lib.rs
- quic/s2n-quic-transport/src/lib.rs
- quic/s2n-quic-transport/src/space/handshake_status.rs
- quic/s2n-quic/src/lib.rs
- quic/s2n-quic/src/provider/stateless_reset_token.rs
resolves #2289
The latest bytes release corrects the issue with 1.7.0 so we can remove the pin on the old version, see https://github.com/tokio-rs/bytes/issues/725
I've also fixed some new Clippy lints.
I disabled the new `unexpected_cfgs` lint, as the MSRV we use does not support the recommended way to avoid this lint. This can be removed when the MSRV is 1.74.0, see https://github.com/aws/s2n-quic/issues/2292
Ran clippy +stable locally
>   chore(s2n-quic): remove bytes pin and fix new clippy lints

- .github/workflows/dashboard.yml
#2293 
Similar to s2n-tls Issue/PR dashboard, but with some quic specific searches.
- Labels are different from tls, things like `stale` and `do_not_merge` don't exist
- s2n-quic uses dependabot, which deserves to be excluded from most of these queries, but also with a dedicated stat
- we're not labeling internal vs external contributors, I'm hoping to come up with a better way to do  this before add to quic.
- The dashboard css isn't managed by the action and is directly checked into the `gh-pages` branch
How is this change tested: forked repo https://dougch.github.io/s2n-quic/dashboard/
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
> PR/Issue Dashboard

- README.md
- docs/dev-guide/ci.md
This change updates the docs to contain more information about all the different tests and other checks run as part of s2n-quic continuous integration
[Rendered](https://github.com/aws/s2n-quic/blob/f0df9e8abecc26aa7005799c42e7ac5bd15da7df/docs/dev-guide/ci.md)
I've updated the CI artifact links to point to a "latest" folder (which is actually using Cloudfront origin path to point to a specific CI artifact folder). This isn't updated automatically though, so I've opened https://github.com/aws/s2n-quic/issues/2302 to track automation of that
> docs(s2n-quic): update CI docs

- .github/workflows/dashboard.yml
The static page generator from #2296 is having issues when pushing to gh-pages. It's possible there is a race with the other document generation action.  For now, go to a daily run.
> ci: remove static page rebuild on push to main

- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic/src/tests/mtu.rs
MTU probing currently begins as soon as the handshake completes and the path has been validated. This is normally OK, but can cause issues when mutual TLS has been configured. 
When mTLS is used, MTU probes may be transmitted from the client prior to the handshake being confirmed (via receipt of `HANDSHAKE_DONE`). Prior to the handshake being confirmed, though, the client is not allowed to send PTO probes:
From [QUIC9002§6.2.1](https://www.rfc-editor.org/rfc/rfc9002.html#name-computing-pto):
> An endpoint MUST NOT set its PTO timer for the Application Data packet number space until the handshake is confirmed. 
The consequence of this is that MTU probes may be sent which are never detected as lost, as the client cannot send a PTO probe to trigger loss detection. This may result in a …
> fix(s2n-quic-transport): wait until handshake is confirmed to start MTU probing

- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/provider/dc/confirm.rs
- quic/s2n-quic/src/tests/dc.rs
Previously, we only stored a single Waker, which meant that when the underlying s2n-quic connection/handle was returned to applications multiple times it ended up only waking one of the application tasks.
This modifies the ConfirmComplete logic such that we now store as many Wakers as needed (using Tokio's Semaphore) and wake all of them on final readiness.
None.
This takes a new dependency on tokio's `sync` feature. This feature was previously not enabled in the s2n-quic dependency tree, but seems likely to be fine to enable. If needed, we can gate it behind the dc provider.
Confirmed locally that a concurrent handshake now successfully confirms from multiple connect with_dedupe handles. Also added a test 
By submitting this pull request, I confirm that my contribution is made under the …
> Fix ConfirmComplete with handshake de-duplication

- docs/dev-guide/ci.md
The link in the CI docs for compliance was pointing to the interop report. This fixes that.
> docs(s2n-quic): fix link to compliance report in CI docs

- quic/s2n-quic-core/src/inet/checksum.rs
N/A
In #2128, the length used in a Kani test was reduced from 16 to 4 because Kani was running out of memory (https://github.com/model-checking/kani/issues/3030). This issue is now resolved, so reverting to the previously used length of 16.
With Kani 0.54.0, memory usage for this harness does not exceed 1.5 GB.
N/A
> test(s2n-quic-core): revert to bigger length for Kani test

- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/test.rs
This ensures that when we prune entries from the map, we bound the size of the peer set as well, if slightly eventually consistently (but that's currently true for both maps). Our expectation is that the source of "truth" is always the ids map -- the peers map is essentially just an index over it. On the other hand, the peers map represents the *important* entries, since they are the latest negotiated secret for a given peer.
Follow-up work is planned to replace these maps to remove the eventual consistency and hard-constrain memory usage up front, but this patches an immediate memory leak, so prioritizing the simple fix first.
Invariant checking is updated -- more changes than I'd like, but previously we weren't testing the overflow at all in those tests (impossible to fill the 500,000 …
> dc: Prune peer map if we've pruned the id map

- quic/s2n-quic-h3/Cargo.toml
- quic/s2n-quic-h3/src/s2n_quic.rs
`s2n-quic-core` is an internal crate that is not guaranteed to be stable, and thus it should not be used directly. `s2n-quic-h3` is a proof of concept of an HTTP3 integration of s2n-quic, so it should follow this recommendation as well. This change removes the `s2n-quic-core` dependency from `s2n-quic-h3`
> refactor(s2n-quic-h3): remove s2n-quic-core dependency

- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/path/mtu.rs
- quic/s2n-quic-core/src/path/mtu/snapshots/quic__s2n-quic-core__src__path__mtu__tests__events__on_packet_ack_search_requested.snap
- quic/s2n-quic-core/src/path/mtu/snapshots/quic__s2n-quic-core__src__path__mtu__tests__events__on_packet_ack_within_threshold.snap
- quic/s2n-quic-core/src/path/mtu/snapshots/quic__s2n-quic-core__src__path__mtu__tests__events__on_packet_ack_within_threshold_of_max_plpmtu.snap
- quic/s2n-quic-core/src/path/mtu/snapshots/quic__s2n-quic-core__src__path__mtu__tests__events__on_packet_loss_black_hole.snap
- quic/s2n-quic-core/src/path/mtu/snapshots/quic__s2n-quic-core__src__path__mtu__tests__events__on_packet_loss_initial_mtu_configured.snap
- quic/s2n-quic-core/src/path/mtu/tests.rs
- quic/s2n-quic-events/events/common.rs
- quic/s2n-quic-events/events/connection.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__active_connection_migration_disabled.snap
- quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__adding_new_path.snap
- quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__connection_migration_challenge_behavior.snap
- quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__connection_migration_new_path_abandon_timer.snap
- quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__connection_migration_use_max_ack_delay_from_active_path.snap
- quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__limit_number_of_connection_migrations.snap
- quic/s2n-quic-transport/src/path/manager/snapshots/quic__s2n-quic-transport__src__path__manager__tests__events__temporary_until_authenticated.snap
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__detect_lost_packets_persistent_congestion_path_aware.snap
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__no_rtt_update_when_receiving_packet_on_different_path.snap
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__on_packet_sent.snap
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__on_packet_sent_across_multiple_paths.snap
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__process_new_acked_packets_congestion_controller.snap
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__process_new_acked_packets_pto_timer.snap
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__process_new_acked_packets_update_pto_timer.snap
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__remove_lost_packets_persistent_congestion_path_aware.snap
- quic/s2n-quic-transport/src/recovery/manager/snapshots/quic__s2n-quic-transport__src__recovery__manager__tests__events__rtt_update_when_receiving_ack_from_multiple_paths.snap
- quic/s2n-quic/src/tests/mtu.rs
This change adds a `search_completed` boolean field to the `mtu_updated` event, to indicate when MTU probing has completed 
At the time the MTU is changed (after a probe is acked for example), we often don't know if that MTU value is going to be the final MTU, so the search_completed flag will be false. It some cases, the MTU may not change again, but we this PR will emit an additional `mtu_updated` event in these cases to update the `search_completed` flag.
Added tests and integration tests
> feat(s2n-quic-events): add search_completed boolean to mtu updated event

- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-crypto/src/aead/default.rs
- quic/s2n-quic-crypto/src/aead/fips.rs
- quic/s2n-quic-crypto/src/cipher_suite.rs
- quic/s2n-quic-crypto/src/cipher_suite/negotiated.rs
- quic/s2n-quic-crypto/src/cipher_suite/ring.rs
- quic/s2n-quic-crypto/src/header_key.rs
- quic/s2n-quic-crypto/src/iv.rs
- quic/s2n-quic-crypto/src/lib.rs
- quic/s2n-quic-crypto/src/negotiated.rs
- quic/s2n-quic-crypto/src/retry.rs
- quic/s2n-quic-tls/src/callback.rs
Since https://github.com/aws/aws-lc/issues/1477 was addressed, `aws-lc-rs` can now build on Windows without requiring NASM to be installed. This was the last hurdle before removing our dependency on `ring`, so this PR does that.
Including `prebuilt-nasm` as a feature makes it difficult to opt out of this functionality, so we may want to bump it up to an `s2n-quic` level feature in the future
Builds in CI
> chore(s2n-quic-crypto): remove ring

- .github/workflows/ci.yml
- dc/s2n-quic-dc/benches/src/crypto.rs
- dc/s2n-quic-dc/benches/src/crypto/hmac.rs
- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/test.rs
- dc/s2n-quic-dc/src/path/secret/receiver.rs
- dc/s2n-quic-dc/src/path/secret/schedule.rs
- dc/s2n-quic-dc/src/path/secret/sender.rs
This adds a custom SizeOf trait and implements it for the types contained in a given Entry, and adds a GHA CI-only test that checks the size of the entry is as we expect. It's likely that we will want to change this but this is an initial proposal of how to do that without breaking downstream consumers.
We also add a benchmark for hmac init (locally I get 200-600ns depending on key type) and removes the OnceCell cache as part of Entry, bringing us down to ~300 bytes.
See added test.
> Optimize path secret Entry size

- dc/s2n-quic-dc/src/event/generated.rs
- quic/s2n-quic-core/src/event.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/event/metrics.rs
- quic/s2n-quic-events/src/main.rs
- quic/s2n-quic-events/src/parser.rs
N/A
Adds a Subscriber that can emit metrics for events. Also removes the "Arc" per field in the dc-quic events since it isn't needed. Also changed ordering to Relaxed for the dc-quic event counters.
> feat(s2n-quic-events): Adds metrics subscriber

- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/fixed_map.rs
- dc/s2n-quic-dc/src/fixed_map/test.rs
- dc/s2n-quic-dc/src/lib.rs
- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/test.rs
This tightly bounds the maximum memory usage of the path secret storage.
This introduces a new data structure (fixed-space HashMap) and refactors our existing flurry maps for by-IP and by-ID path secret storage to utilize it. Under the new design, a given entry is hashed and placed in at most one of 8 slots -- currently replacement just rotates through if there are no empty slots left (this can be improved with LFU/LRU in the future). The new data structure is all safe code and has some tests inline (plus the existing testing from the path secret map).
Due to the fixed-size slots, we are very likely much more prone to evicting entries from the map. In some sense, with as few as 32 peers (particularly for the IP map) we might start evicting entries (and permanently be unable to make use of …
> feat(s2n-quic-dc): Use a new fixed-size map for path secret storage

- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/test.rs
- dc/s2n-quic-dc/src/path/secret/schedule.rs
See individual commits. This cuts out a bit more from the path secret entries, bringing the size to 270 bytes (our current goal is 250).
See edited test.
> feat(dc): Further shrink path secret entry

- dc/s2n-quic-dc/src/fixed_map.rs
- dc/s2n-quic-dc/src/fixed_map/test.rs
- dc/s2n-quic-dc/src/path/secret/map/test.rs
- dc/s2n-quic-dc/src/stream/recv/state.rs
- dc/s2n-quic-dc/src/stream/send/state.rs
- quic/s2n-quic-core/src/dc.rs
- quic/s2n-quic-core/src/dc/testing.rs
- tools/xdp/s2n-quic-xdp/src/ring.rs
This cuts a little bit more from the path secret entries, bringing us below our current target of 250 bytes for the Entry 
n/a
See modified test.
> feat(s2n-quic-dc): shrink path secret & fix fixed-map allocation

- quic/s2n-quic/src/provider/address_token/default.rs
n/a
This avoids a 1MB allocation per endpoint if we never receive a valid token (as is typical, since users need to explicitly opt-in to this with a limiter impl).
This moves a creation-time allocation to be late (on receipt of valid token). Since we only do this after successful validation I don't think there are any strong concerns from this, but it does likely mean it's possible to distinguish whether an endpoint transitions from "using the filter" to "not using the filter" by measuring network latencies. This seems largely harmless though.
No meaningful testing. Just lazy init though.
> feat(s2n-quic): Lazy-init duplicate filter

- dc/wireshark/build.rs
- dc/wireshark/src/plugin.rs
- dc/wireshark/src/wireshark.rs
- dc/wireshark/xtask/src/main.rs
This change makes the dc wireshark plugin compatible with wireshark 4.4. Previously it only worked with 4.2.
The tests are now passing
> fix(dc): support updated wireshark definitions

- .github/workflows/ci.yml
- common/s2n-codec/src/decoder/value.rs
- common/s2n-codec/src/zerocopy.rs
- quic/s2n-quic-core/src/frame/ack.rs
- quic/s2n-quic-core/src/recovery/congestion_controller.rs
- quic/s2n-quic-core/src/transport/parameters/mod.rs
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-qns/src/xdp.rs
- tools/xdp/ebpf/Cargo.toml
- tools/xdp/ebpf/rust-toolchain.toml
- tools/xdp/ebpf/src/main.rs
- tools/xdp/rust-toolchain
- tools/xdp/s2n-quic-xdp/Cargo.toml
- tools/xdp/s2n-quic-xdp/src/bpf/s2n-quic-xdp-bpfeb-trace.ebpf
- tools/xdp/s2n-quic-xdp/src/bpf/s2n-quic-xdp-bpfeb.ebpf
- tools/xdp/s2n-quic-xdp/src/bpf/s2n-quic-xdp-bpfel-trace.ebpf
- tools/xdp/s2n-quic-xdp/src/bpf/s2n-quic-xdp-bpfel.ebpf
- tools/xdp/tester/Cargo.toml
- tools/xdp/tester/src/main.rs
This change updates our `aya` dependency, which started failing after they published a new version.
I've also updated our nightly version, since it was pretty out of date and the BPF build depends on it.
> build(deps): update aya to 0.13

- quic/s2n-quic-core/src/crypto/tls.rs
- quic/s2n-quic-core/src/crypto/tls/testing.rs
- quic/s2n-quic-core/src/event.rs
- quic/s2n-quic-rustls/src/session.rs
- quic/s2n-quic-tls/src/session.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/chain.rs
This allows users to query the certificate chain when in the TlsSession event callbacks (for dc or for on_tls_exporter_ready). 
The new API is ~immediately stable, which feels unfortunate -- the Vec<Vec<u8>> is clunky and not really what we'd ideally have. However improving on that is also tricky, so maybe it's not worth optimizing much here. s2n-tls under the hood has something closer to a linked list of buffers, with that represented by multiple layers of indirection to Rust as a `Iterator<Item = &[u8]>`. I'm pretty sure we can't directly expose a `-> impl Iterator` though, since the lifetimes don't end up working out.
Added a test showing the newly added functionality works. Note that it's mTLS, the peer_cert_chain_der method will return an Err if the other side didn't present any …
> feat(s2n-quic): Add the certificate chain to TlsSession

- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/credentials.rs
- dc/s2n-quic-dc/src/fixed_map.rs
- dc/s2n-quic-dc/src/lib.rs
- dc/s2n-quic-dc/src/path/secret.rs
- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/test.rs
- dc/s2n-quic-dc/src/stream.rs
- dc/s2n-quic-dc/src/stream/client.rs
- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/environment/tokio.rs
- dc/s2n-quic-dc/src/stream/send/state.rs
- dc/s2n-quic-dc/src/stream/server.rs
- dc/s2n-quic-dc/src/stream/server/tokio.rs
- dc/s2n-quic-dc/src/stream/server/tokio/accept.rs
- dc/s2n-quic-dc/src/stream/server/tokio/stats.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/server/tokio/udp.rs
- dc/s2n-quic-dc/src/sync.rs
- dc/s2n-quic-dc/src/sync/channel.rs
- dc/s2n-quic-dc/src/sync/ring_deque.rs
- dc/s2n-quic-dc/src/sync/ring_deque/tests.rs
- quic/s2n-quic-core/src/dc.rs
This change imports the latest changes in s2n-quic-dc.
> feat(s2n-quic-dc): import 10/17/24

- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
This releases 1.48.0 of s2n-quic.
> chore: release 1.48.0

- .github/workflows/qns.yml
- .github/workflows/release.yml
Rework the qns and release actions to use short term credentials.
There are now separate roles for S3 access vs Public ECR.
Is this a refactor change? Relying on CI
> chore: update qns actions for OIDC

- .github/actions/duvet/README.md
- .github/actions/duvet/action.yml
- .github/workflows/book.yml
- .github/workflows/ci.yml
- .github/workflows/qns.yml
- .github/workflows/tshark.yml
n/a
Similar to the change for [s2n-tls](https://github.com/aws/s2n-tls/pull/4839), update the use of AWS credentials from GitHub secrets to OpenID Connect.
This also includes a change to the Duvet action that will need to be merged in coordinated with an update to the s2n-tls workflow https://github.com/aws/s2n-tls/pull/4850
The [publish to public ECR](https://github.com/aws/s2n-quic/blob/main/.github/workflows/qns.yml#L367) needs more work and will be in a future PR.
How was this change tested ? in the s2n-netbench repo.  Changes based on [this doc](https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)
In this PR, you can see a successful use of the OIDC auth in the `book/deploy` action, on …
> chore(GHA): allow OIDC aws credentials

- README.md
Small PR - commit 562ca11b6d40c4b9c822ee2f721d4d271b9fc531 moved the location of `ci.md`. This PR adjusts sources to changes.
> fix: update CI reference

- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/test.rs
- quic/s2n-quic-core/src/dc/disabled.rs
- quic/s2n-quic-core/src/dc/testing.rs
- quic/s2n-quic-core/src/dc/traits.rs
- quic/s2n-quic-transport/src/dc/manager.rs
- quic/s2n-quic-transport/src/dc/manager/tests.rs
resolves #2314
Currently, a dc path secret entry is inserted into both the `Secret ID -> Entry` map and the `Socket Address -> Entry` map at the same time (when dc stateless reset tokens are received). Since the dc handshake hasn't completed yet when this occurs, it is possible that the server may start encrypting with path secrets that the client is not yet aware of (as highlighted in #2314). This change splits the insertion of entries into the two maps into two operations, with the insertion into the `Socket Address -> Entry` map only occurring once the dc handshake has completed
Updated existing testing
By submitting this pull request, I confirm that my contribution is made under the …
> fix(s2n-quic-dc): wait to insert in peer map until handshake completes

- dc/s2n-quic-dc/src/fixed_map.rs
- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/cleaner.rs
- dc/s2n-quic-dc/src/path/secret/map/entry.rs
- dc/s2n-quic-dc/src/path/secret/map/entry/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/handshake.rs
- dc/s2n-quic-dc/src/path/secret/map/size_of.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
- dc/s2n-quic-dc/src/path/secret/map/state/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/status.rs
- dc/s2n-quic-dc/src/path/secret/map/store.rs
This change puts the path secret map behind a trait. This is needed to keep the type concrete while still including a `event::Subscriber`. My goal was to keep any `dyn`s we have as high up in the tree as possible to maximize the information the compiler has. With this, it can remove functions that aren't subscribed to, or at least inline them to be inexpensive.
I've spent some time splitting up the `map.rs` module into various submodules. It was getting quite large and no interfaces were really being enforced so there was quite a bit of refactoring involved.
> refactor(s2n-quic-dc): put map impl behind trait

- quic/s2n-quic-core/src/datagram/default.rs
This change fixes #2213.
I've written a test covering the case where the capacity limit is hit and the waker is now called. The test failed otherwise.
> fix(s2n-quic-core): always wake application on available datagram capacity

- dc/s2n-quic-dc/events/common.rs
- dc/s2n-quic-dc/events/connection.rs
- dc/s2n-quic-dc/events/map.rs
- dc/s2n-quic-dc/src/event.rs
- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/cleaner.rs
- dc/s2n-quic-dc/src/path/secret/map/handshake.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
- dc/s2n-quic-dc/src/path/secret/map/state/snapshots/path__secret__map__state__tests__thread_shutdown__events.snap
- dc/s2n-quic-dc/src/path/secret/map/state/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/status.rs
- dc/s2n-quic-dc/src/path/secret/map/store.rs
- dc/s2n-quic-dc/src/stream/recv/shared.rs
- dc/s2n-quic-dc/src/stream/send/worker.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-events/src/main.rs
- quic/s2n-quic-events/src/parser.rs
This change adds a bunch of new events to the dc map implementation. These events should provide the following:
* Knowing when a map was initialized/destroyed
* Knowing when an entry was requested to perform another handshake
* Providing insights into secret control packet metrics
* Knowing when replay protection is being applied and what the current gap is
There's a few more things I still need to include in a follow-up:
* Ages of secrets - this can be emitted by the cleaner
* Cache hit ratios for `contains` calls
I've currently only manually tested that the events are being emitted. As a follow-up PR (since this one is already quite large), I will add several event snapshot tests to show it all working and prevent regressions in events.
By submitting this pull request, I confirm that my …
> feat(s2n-quic-dc): add map events

- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
This releases 1.49.0 of s2n-quic.
> chore: release 1.49.0

- .cargo/audit.toml
- .github/workflows/dependencies.yml
Will also resolve https://github.com/aws/s2n-quic/pull/2330
This updates the cargo audit version in our CI.
I added a few advisories to our allow list since they are dependencies of structopt and only used in s2n-quic-qns and s2n-quic-sim. These can be removed as part of completing https://github.com/aws/s2n-quic/issues/2324
> chore: update cargo audit

- dc/s2n-quic-dc/events/connection.rs
- dc/s2n-quic-dc/events/endpoint.rs
- dc/s2n-quic-dc/events/map.rs
- dc/s2n-quic-dc/src/event.rs
- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
- quic/s2n-quic-core/events/connection.rs
- quic/s2n-quic-core/events/endpoint.rs
- quic/s2n-quic-core/src/connection/error.rs
- quic/s2n-quic-core/src/connection/snapshots/s2n_quic_core__connection__error__metrics__variants_test.snap
- quic/s2n-quic-core/src/crypto/tls/error.rs
- quic/s2n-quic-core/src/crypto/tls/snapshots/s2n_quic_core__crypto__tls__error__variants_test.snap
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/event/generated/metrics/aggregate.rs
- quic/s2n-quic-core/src/event/generated/metrics/probe.rs
- quic/s2n-quic-core/src/event/metrics/aggregate.rs
- quic/s2n-quic-core/src/event/metrics/aggregate/info.rs
- quic/s2n-quic-core/src/event/metrics/aggregate/metric.rs
- quic/s2n-quic-core/src/event/metrics/aggregate/probe/dynamic.rs
- quic/s2n-quic-core/src/event/metrics/aggregate/recorder.rs
- quic/s2n-quic-core/src/event/metrics/aggregate/variant.rs
- quic/s2n-quic-core/src/transport/error.rs
- quic/s2n-quic-core/src/transport/snapshots/s2n_quic_core__transport__error__variants_test.snap
- quic/s2n-quic-events/src/output.rs
- quic/s2n-quic-events/src/output/metrics/aggregate.rs
- quic/s2n-quic-events/src/parser.rs
This change adds the ability to emit counter metrics based on individual variants. For example, we want a total number of errors for each type of error that can occur.
The event specifies this aggregation as such:
```rust
struct MyEvent {
#[nominal_counter("state", "")]
state: State,
}
enum State {
A,
B,
C,
}
```
There will be a total of 4 counters registered for this particular event: 1 for the overall event, and then an individual counter for each possible variant inside of `State`.
The dc path secret map tests can be run to show it all working:
```console
$ S2N_LOG=trace cargo test -p s2n-quic-core -p s2n-quic-dc --features probe-tracing -- map::event_tests::control_packets --nocapture
...
2024-11-06T22:36:20.268288Z TRACE s2n_quic_core::event::metrics::aggregate::probe::dynamic::counte …
```
> feat(s2n-quic-core): add nominal counter aggregations

- .github/workflows/release.yml
none
In https://github.com/aws/s2n-quic/pull/2352, we switched to short term credentials for actions use with AWS. This added a [permissions stanza to the workflow](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#how-the-permissions-are-calculated-for-a-workflow-job), but missed a permission needed to publish docker to GitHub container registry.
Authentication is succeeding, but permissions are insufficient to publish, e.g. https://github.com/aws/s2n-quic/actions/runs/11724796171/job/32659577102
> chore: grant more permissions to the qns release workflow

- .github/PULL_REQUEST_TEMPLATE.md
s2n-quic version of https://github.com/aws/s2n-tls/pull/4885
I wasn't sure what testing I could list under "Testing" the way I listed testing requirements for s2n-tls. The unit tests requirement hold true, but I'm not sure about the others. Suggestions? That could also just be a separate PR from someone more familiar with s2n-quic tests.
documentation change
> core: update github PR template

- dc/s2n-quic-dc/events/acceptor.rs
- dc/s2n-quic-dc/events/map.rs
- dc/s2n-quic-dc/src/event.rs
- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
- dc/s2n-quic-dc/src/stream/application.rs
- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/server.rs
- dc/s2n-quic-dc/src/stream/server/tokio/accept.rs
- dc/s2n-quic-dc/src/stream/server/tokio/stats.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/server/tokio/udp.rs
- quic/s2n-quic-core/src/event.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/event/metrics/aggregate/info.rs
- quic/s2n-quic-core/src/event/metrics/aggregate/metric.rs
- quic/s2n-quic-events/src/main.rs
- quic/s2n-quic-events/src/parser.rs
- quic/s2n-quic-events/src/validation.rs
This change adds several acceptor events for the s2n-quic-dc crate. This will provide a lot better insight into the decisions being made by the workers.
The `info::Variant` struct is marked as `#[non_exhaustive]` and can't be constructed outside of s2n-quic-core. I needed to modify the event generator script to use a `info::variant::Builder` instead.
> feat(s2n-quic-dc): add acceptor events

- dc/s2n-quic-dc/events/map.rs
- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
None
Goal is to have essentially a +/- tracker so we get a better sense of both positive and negative reordering.
I'm not sure if we should be using a consistent pre-auth baseline or the setup here. Naming is also... suboptimal, but I don't have better ideas.
None
> Metric for forward gaps in key ID tracking

- quic/s2n-quic-tls/src/session.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/provider.rs
This change includes a few additions that will better assist in debugging handshake failures:
* For the `s2n-tls` provider, it includes the `error.message()` as the `reason`, which is much more descriptive than a generic `HANDSHAKE_FAILURE`
* It uses `connection::Error::from` instead of `Into::into` which has issues with passing on the `#[track_caller]` information
* Finally, it exposes the `CONNECTION_CLOSE` formatter provider as an unstable feature, which allows for more descriptive errors to be sent over the wire, if desired. This option comes with the warning outlined in the docs: https://docs.rs/s2n-quic-core/latest/s2n_quic_core/connection/close/struct.Development.html
> feat(s2n-quic): improve local handshake failure visibility

- dc/s2n-quic-dc/events/map.rs
- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/event_tests.rs
- dc/s2n-quic-dc/src/path/secret/map/peer.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
- dc/s2n-quic-dc/src/path/secret/map/state/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/store.rs
- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/testing.rs
This change adds events around cache hits for path secrets. This should give a good idea of how often flows are needing to wait for handshakes to complete before continuing.
In adding these, I've also included a TOCTOU issue I've been wanting to address for awhile. Now, we return the path secret entry atomically when checking if we have an entry or not.
The `get_by_addr` method were missing the same checks that the `contains` method has around `requested_handshakes.contains(peer)`, so I've added that.
> feat(s2n-quic-dc): implement cache events

- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/stream/application.rs
- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/environment.rs
- dc/s2n-quic-dc/src/stream/environment/tokio.rs
- dc/s2n-quic-dc/src/stream/recv/application.rs
- dc/s2n-quic-dc/src/stream/recv/application/builder.rs
- dc/s2n-quic-dc/src/stream/recv/shared.rs
- dc/s2n-quic-dc/src/stream/recv/worker.rs
- dc/s2n-quic-dc/src/stream/runtime.rs
- dc/s2n-quic-dc/src/stream/runtime/tokio.rs
- dc/s2n-quic-dc/src/stream/send/application.rs
- dc/s2n-quic-dc/src/stream/send/application/builder.rs
- dc/s2n-quic-dc/src/stream/send/worker.rs
- dc/s2n-quic-dc/src/stream/server/tokio/accept.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/server/tokio/udp.rs
- dc/s2n-quic-dc/src/stream/shared.rs
- dc/s2n-quic-dc/src/stream/testing.rs
- quic/s2n-quic-events/src/output.rs
This change makes it possible to emit events from s2n-quic-dc streams by threading through a generic `event::Subscriber` in all of the data structures and functions.
I haven't actually emitted any events at this point, since the change is already quite large. Actual events will come in a later PR.
> refactor(s2n-quic-dc): thread event::Subscriber through streams

- dc/s2n-quic-dc/events/connection.rs
- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/event/generated/metrics.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/recv/application.rs
- dc/s2n-quic-dc/src/stream/recv/shared.rs
- dc/s2n-quic-dc/src/stream/recv/worker.rs
- dc/s2n-quic-dc/src/stream/send/application.rs
- dc/s2n-quic-dc/src/stream/send/queue.rs
- dc/s2n-quic-dc/src/stream/send/worker.rs
- dc/s2n-quic-dc/src/stream/shared.rs
This change adds several stream events for s2n-quic-dc streams. This can provide better insight into what is happening to streams both in aggregate and individually.
You can see the events showing up in the tracing logs for the tests:
```
$ cargo test -p s2n-quic-dc stream::send::tests::tcp::current_thread::write_10k::send_limited::shutdown_test -- --nocapture
running 1 test
2024-12-03T18:36:54.585999Z DEBUG s2n_quic_dc: path_secret_map_initialized: capacity=16
2024-12-03T18:36:54.590528Z DEBUG server:s2n_quic_dc: path_secret_map_initialized: capacity=16
2024-12-03T18:36:54.595035Z DEBUG server:s2n_quic_dc: acceptor_tcp_started: id=0 local_address=127.0.0.1:54249 backlog=16
expected=10000
2024-12-03T18:36:54.595274Z DEBUG server:s2n_quic_dc: acceptor_tcp_fresh_batch_completed: enqueued=0 …
```
> feat(s2n-quic-dc): emit top-level stream events

- dc/s2n-quic-dc/events/connection.rs
- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/event/generated/metrics.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
- dc/s2n-quic-dc/src/stream/shared.rs
- quic/s2n-quic-core/events/connection.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/event/generated/metrics.rs
- quic/s2n-quic-core/src/event/generated/metrics/aggregate.rs
- quic/s2n-quic-core/src/event/generated/metrics/probe.rs
- quic/s2n-quic-events/src/output/metrics/aggregate.rs
- quic/s2n-quic-events/src/output_mode.rs
- quic/s2n-quic-events/src/parser.rs
This change implements connection-level counter aggregation. This allows aggregating counters at the connection level and then aggregating them as metrics, as opposed to them being pure counters or measurements, which don't have enough granularity to give insight into distribution of connection behaviors. For example, this change allows getting a distribution of the number of bytes sent and received on streams.
> feat(s2n-quic-dc): implement connection-level counter aggregation

- dc/s2n-quic-dc/events/connection.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
This fixes some redundantly suffixed measurement names from #2397, since measurements are already prefixed by the event name they're attached to.
> fix(s2n-quic-dc): remove redundant measure_counter naming suffix

- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
This change ensures `TCP_NODELAY` is set to `true` on TCP sockets, as it can greatly affect latencies, especially with smaller payloads.
> fix(s2n-quic-dc): set TCP_NODELAY on TCP sockets

- .github/workflows/ci.yml
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/lib.rs
- quic/s2n-quic/src/provider.rs
- quic/s2n-quic/src/provider/congestion_controller.rs
- quic/s2n-quic/src/provider/tls.rs
https://github.com/aws/s2n-quic/issues/1831
This PR enables feature tagging in our [rust docs](https://dnglbrstg7yg.cloudfront.net/e2d8618eb0658c13f1f749afc53e7f7b3b4fdcaf/doc/s2n_quic/index.html). This is useful for customers that want to use enable APIs that require building s2n-quic with certain features.
This PR only covers the main s2n-quic crate. Future work might be to expand feature tagging to other s2n-quic crates.
We need to gate the feature on `docsrs` since it requires nightly cargo and would otherwise break stable builds.
We rely `doc_auto_cfg` to auto generate the feature tagging where applicable. However, we also require manually tagging with `doc_cfg`
- since auto isn't able to detect the use of `cfg_if!` macro
- for the tls providers since they key on the crate name
- …
> docs: enable feature tagging

- Cargo.toml
- common/s2n-codec/Cargo.toml
- common/s2n-codec/src/decoder/checked_range.rs
- common/s2n-codec/src/zerocopy.rs
- dc/s2n-quic-dc/Cargo.toml
- dc/wireshark/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/connection/id.rs
- quic/s2n-quic-core/src/frame/ack.rs
- quic/s2n-quic-core/src/frame/ack_elicitation.rs
- quic/s2n-quic-core/src/frame/path_validation.rs
- quic/s2n-quic-core/src/inet/ecn.rs
- quic/s2n-quic-core/src/inet/ip.rs
- quic/s2n-quic-core/src/inet/macros.rs
- quic/s2n-quic-core/src/packet/number/packet_number.rs
- quic/s2n-quic-core/src/packet/number/packet_number_space.rs
- quic/s2n-quic-core/src/packet/number/truncated_packet_number.rs
- quic/s2n-quic-core/src/path/mod.rs
- quic/s2n-quic-core/src/stream/id.rs
- quic/s2n-quic-core/src/stream/iter.rs
- quic/s2n-quic-core/src/stream/testing.rs
- quic/s2n-quic-core/src/transmission/constraint.rs
- quic/s2n-quic-core/src/transmission/mode.rs
- quic/s2n-quic-core/src/varint/mod.rs
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-platform/src/message/msg.rs
- quic/s2n-quic-platform/src/message/msg/tests.rs
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
> build(deps): update bolero requirement from 0.11 to 0.12

- dc/s2n-quic-dc/src/stream/application.rs
- dc/s2n-quic-dc/src/stream/environment/tokio.rs
- dc/s2n-quic-dc/src/stream/recv/application.rs
- dc/s2n-quic-dc/src/stream/send/application.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
The current TCP acceptor calls `peer_addr` quite a few times, especially after events were added. This change, instead, caches the value and uses that everywhere.
I noticed that our `fmt::Debug` impls were calling `peer_addr().unwrap()`, which isn't good. So I refactored those to not panic.
> refactor(s2n-quic-dc): reduce the number of `peer_addr` calls

- .github/interop/runner.patch
- .github/workflows/qns.yml
- scripts/interop/run
Recently some `neqo` client interop tests started failing, but they appear to work in the public QUIC interop runner. This change updates the commit used for QUIC interop runner to the latest to see if that fixes anything. (Update: it didn't fix the neqo tests, but its still worth updating)
Will be tested in CI
> chore: updating to latest quic interop commit

- dc/s2n-quic-dc/src/stream/socket/fd/tcp.rs
- dc/s2n-quic-dc/src/stream/socket/tokio/tcp.rs
This change makes TCP shutdown a no-op. This is done for a few reasons:
* We already authenticate stream closures at the record layer so doing it in TCP is redundant
* It avoids an extra syscall
Above all, we can avoid more complex shutdown behavior in the TCP layer:
https://datatracker.ietf.org/doc/html/rfc9293#section-3.3.2
> A RST can be sent from any state with a corresponding transition to TIME-WAIT (see [[70](https://doi.org/10.1109/INFCOM.1999.752180)] for rationale). These transitions are not explicitly shown; otherwise, the diagram would become very difficult to read. Similarly, receipt of a RST from any state results in a transition to LISTEN or CLOSED, though this is also omitted from the diagram for legibility.
Basically, we don't need to go through the 4-way finalization flow …
> fix(s2n-quic-dc): make TCP shutdown a no-op

- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/environment/tokio.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
This change does additional reductions to the number of times that socket address calls are actually performed.
> feat(s2n-quic-dc): reduce socket addr calls even more

- tools/xdp/s2n-quic-xdp/src/io/rx.rs
This allows iteration over descriptors in the rx channel.
resolves #2404
Makes io::rx::Channel::for_each public so it can be used directly without higher level s2n implementations.
`cargo build --release`
> feat(s2n-quic-xdp): Make io::rx::Channel::for_each public

- dc/s2n-quic-dc/src/stream/client/tokio.rs
This change fixes an issue where the `connect` call provided an unspecified address. This should be resolved by the underlying socket instead of using the raw value.
> fix(s2n-quic-dc): resolve unspecified peer addrs on connect

- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
As a follow up to https://github.com/aws/s2n-quic/pull/2402#pullrequestreview-2479762567, this change sets linger to 0 on TCP sockets.
> feat(s2n-quic-dc): set linger to 0

- .github/workflows/ci.yml
We want to run ASAN for the s2n-quic library. This change is inspired by https://github.com/aws/s2n-tls/pull/4948.
I have added necessary env variables to the CI, and run it in s2n-quic's CI.
We added `detect_leak=false` flag to the CI. We need to discuss whether we want to reenable that flag in the future.
This change will be tested by the github CI.
> ci: add ASAN to s2n-quic ci

- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/fresh.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager/list.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager/tests.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/worker.rs
- dc/s2n-quic-dc/src/task/waker.rs
- dc/s2n-quic-dc/src/task/waker/set.rs
- dc/s2n-quic-dc/src/task/waker/set/bitset.rs
The TCP currently polls all pending streams on every task wakeup:
https://github.com/aws/s2n-quic/blob/e4a236578bcb36109d238753307c970d6c997666/dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs#L333-L335
This isn't super efficient since only a handful of streams may be ready to be polled again.
This change, instead, adds a `waker::Set` which hands out specific wakers to each stream and then tracks which ones actually woke up. It then only polls those tasks on wakeup, skipping the still-pending ones.
I refactored the TCP acceptor a bit to make it easier to test, especially write some fuzz tests for since the management logic is getting quite complicated.
I added quite a few tests. Most interesting one is probably the fuzz test for the accept manager, which ensures all struct invariants are …
> feat(s2n-quic-dc): only poll accepted streams that are ready

- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-tls/src/tests.rs
- quic/s2n-quic/src/tests/snapshots/tests__dc__dc_mtls_handshake_auth_failure_self_test__events.snap
In https://github.com/aws/s2n-tls/pull/4919, certificate-related errors started mapping to alerts for better debugging. As such, this causes failures for tests that assert specific errors.
This change updates which errors we are asserting.
> test: update snapshots from s2n-tls 0.3.8 behavior

- dc/s2n-quic-dc-benches/src/streams.rs
- dc/s2n-quic-dc/src/stream.rs
- dc/s2n-quic-dc/src/stream/send/tests.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager.rs
- dc/s2n-quic-dc/src/stream/testing.rs
- dc/s2n-quic-dc/src/stream/tests.rs
- dc/s2n-quic-dc/src/stream/tests/accept_queue.rs
- dc/s2n-quic-dc/src/task/waker/set.rs
- dc/s2n-quic-dc/src/task/waker/worker.rs
In #2409, I added a `waker::Set` that used `worker::Waker` to maintain the root waker for the task being polled. Unfortunately, I forgot that the worker waker uses additional status to check if it actually needs to be woken or not, so it was dropping wakes after the first wakeup.
This change fixes that by introducing a `wake_forced` that bypasses that check. This is quite a bit simpler to integrate into the waker::Set and should work fine for those purposes.
I've added high level integration tests for the accept queue to try and catch this behavior in the future.
> fix(s2n-quic-dc): use wake_forced for worker::Waker

- .github/Dockerfile.tshark
- .github/workflows/qns.yml
- .github/workflows/tshark.yml
- scripts/interop/README.md
This updates the wireshark version to the latest. We also install `editcap` so the interop runner can take advantage of embedding key log files in pcaps.
> ci: update wireshark to v4

- Cargo.toml
- tools/xdp/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
This change reworks the `release` profile to be less aggressive. Currently it does _a lot_ of optimizations which takes forever in most cases. Instead, the `bench` profile can be used for those cases.
I've also added a `release-debug` that's the same as `release`, just with better debug info.
Additionally, we have some issues with dependabot not being able to resolve workspace dependencies in the `tools/xdp` directory so i've fixed that as well.
> build: do fewer optimizations in release

- scripts/h3spec
This change updates h3spec to the latest version.
I had to add the `--no-validate` option since we only use self-signed certs for the local `s2n-quic-qns` server.
> ci: update h3spec to 0.11

- .github/interop/required.json
Revert changes from [PR#2191](https://github.com/aws/s2n-quic/pull/2191). Test if the resumption interop test with neqo client will success. This PR is related to [Issue#2192](https://github.com/aws/s2n-quic/issues/2192).
CI test. The interop neqo test is successful in CI: [test result 1](https://github.com/aws/s2n-quic/actions/runs/12302805857/job/34336691879?pr=2420), [test result 2](https://github.com/aws/s2n-quic/actions/runs/12302805857/job/34336696699?pr=2420).
> ci: add neqo from required resumption test client

- .github/workflows/release.yml
The release check in CI won't load credential if the PR is created from a forked `s2n-quic` repo. The error report is in this [test result](https://github.com/aws/s2n-quic/actions/runs/12287529137/job/34289718607). Therefore, we should add a check to load the credential.
This PR is created from @boquan-fang's forked `s2n-quic` repo. We test this PR with the release qns test in the CI to see whether it actually works.
The test result is [here](https://github.com/aws/s2n-quic/actions/runs/12306881305/job/34349444526?pr=2423).
> fix(ci): fix the release

- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager/list.rs
The current `invariants` check in `tcp::tokio::manager` ends up being quite expensive, especially when the backlog is large - basically `O(N^2)`. Instead, I made them collect all of the indexes into a vec and sort them before comparing. This ends up being quite a bit cheaper than what we were doing before.
I also made a slight change to the free list behavior. Instead of pushing back free workers it pushes them to the front. The effect is that we only end up using N workers, where N is the number of concurrent connections. In theory, this should reduce memory churn, though it might be overall quite small. But I thought it couldn't hurt.
> fix(s2n-quic-dc): make debug assertions cheaper for TCP accept manager

- Cargo.toml
- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
Dependabot for `s2n-quic` is currently down with this [error message](https://github.com/aws/s2n-quic/network/updates/931720310). I checked the dependabot update log and found this [error message](https://github.com/aws/s2n-quic/actions/runs/12284577998/job/34280654957):
```
updater | 2024/12/11 20:45:13 INFO <job_931351966> Handled error whilst updating rbpf: 
dependency_file_not_resolvable {:message=>"info: syncing channel updates for '1.80.0-x86_64-unknown-linux-
gnu'\ninfo: latest update on 2024-07-25, rust version 1.80.0 (051478957 2024-07-21)\ninfo: downloading component 
'cargo'\ninfo: downloading component 'clippy'\ninfo: downloading component 'rust-docs'\ninfo: downloading component 
'rust-std'\ninfo: downloading component 'rustc'\ninfo: downloading component 'rustfmt'\ninfo: …
```
> ci: specify specific bolero dependency rather than workspace dependency

- tools/xdp/s2n-quic-xdp/Cargo.toml
This PR follows up [PR#2424](https://github.com/aws/s2n-quic/pull/2424). The previous PR missed one `bolero.workspace = true` that needs to be removed:
https://github.com/aws/s2n-quic/blob/1d2aaa74fcbf5778d358b2eabc867619ec79c5b9/tools/xdp/s2n-quic-xdp/Cargo.toml#L25-L26
Hence, this PR will fix that problem as well.
I have done a search in the entire codebase for `bolero.workspace`. Hence, there shouldn't be any more `bolero.workspace` left after this PR is merged.
Merge this PR and see if Dependabot can properly update. Same as [PR#2424](https://github.com/aws/s2n-quic/pull/2424).
> ci: specify specific bolero dependency rather than workspace dependency in s2n-quic-xdp

- dc/s2n-quic-dc/events/map.rs
- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
- dc/s2n-quic-dc/src/fixed_map.rs
- dc/s2n-quic-dc/src/fixed_map/test.rs
- dc/s2n-quic-dc/src/path/secret/map/cleaner.rs
- dc/s2n-quic-dc/src/path/secret/map/entry.rs
- dc/s2n-quic-dc/src/path/secret/map/entry/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
- dc/s2n-quic-dc/src/path/secret/map/store.rs
Reviewed previously out of band (though re-review is probably a good idea to check the import was reasonable):
* 4900d7d35278217ae6b79785f3857b454d07cd02 declares new metrics for access and cleaner counting
* cea189333fcd4e281453aa620e5b40592c7f7795 threads those metrics in, and bundles some fixes for edge-ish cases where we can previously get stuck
> fix(s2n-quic-dc): Import fixes + new metrics

- dc/s2n-quic-dc/src/path/secret/map/cleaner.rs
n/a
This avoids the cleaner thread running ~2x more often than expected -- previously we'd have pause times of on average ~30 seconds, which meant we'd run roughly twice a minute. Now we have a total expected sleep time of ~60 seconds/minute, with runs expected to take much less than a second (so roughly executing once a minute).
No tests added. This sort of code is pretty painful to test and seems hard to break in a future commit, so I'm inclined to leave it as-is for now.
> fix(s2n-quic-dc): Pause the cleaner thread for the tail of the sleep time

- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager/tests.rs
This change fixes an issue where the following happens:
* The TCP acceptor removes a stream at index `N`, due to it being expired
* The tokio runtime is notified of stream readiness at index `N` and wakes the task
* The task polls the worker, which is no longer reading from the stream, which was previously assumed to not happen
I've made the fuzz tests less constrained to trigger this series of events. If I simply apply the test change, then it shows the error:
```
---- stream::server::tokio::tcp::manager::tests::invariants_test stdout ----
======================== Test Failure ========================
BOLERO_RANDOM_SEED=148028850864596720821768053785163681304
Input: 
[
Wake {
idx: 1,
},
Insert,
]
Error: 
panicked at dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager/tests.rs:94:17: …
```
> fix(s2n-quic-dc): handle spurious TCP acceptor worker wakeups

- quic/s2n-quic-core/src/connection/limits.rs
- quic/s2n-quic-core/src/packet/encoding.rs
- quic/s2n-quic-transport/src/stream/manager.rs
- quic/s2n-quic-transport/src/stream/manager/tests.rs
- quic/s2n-quic-transport/src/stream/stream_container.rs
Adds stream batching functionality to s2n-quic sending behavior. Stream batching is a sending strategy which provides each stream with the opportunity to fill up a packet "batch-size" times, before then passing that priority to the next stream.
Previous iteration of this PR: #2428
Adds a way for users to turn on stream batching. The current sending strategy can be described as stream batching with a size of 1 (this can be seen with the fact that all current tests pass with the default steam batch size of 1). With this change we can express batch sizes > 1.
Essentially now the transmission list keeps track of how many times its head node gets to be at the front of the list. The head node is popped off the list and moved to the back of the list once the limit is reached. I had to extract …
> feat(s2n-quic-transport): Adds stream batching functionality

- quic/s2n-quic-core/events/connection.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-transport/src/endpoint/initial.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic/src/tests/connection_migration.rs
- quic/s2n-quic/src/tests/recorder.rs
Adds address and connection ID information to the on_datagram_dropped event. 
NOTE: This is a breaking change if your application stores the `DatagramDropped` events, as a named lifetime was added to the struct. 
This change adds additional details (local/remote address, src/dst connection ID) to the `on_datagram_dropped` event, to assist with debugging. 
This is technically a breaking change, as a named lifetime was added to the struct. 
Added an integration test that changes the port before the handshake is confirmed
> events: adding detail to DatagramDropped event

- dc/s2n-quic-dc/src/stream/send/tests.rs
When we moved to use linger=0 (#2407) and not calling shutdown (#2402)  on TCP sockets, this made the send tests a bit flaky due to an `unwrap` on connection reset, even though all of the data was transmitted.
> test(s2n-quic-dc): ignore read errors for send tests

- dc/s2n-quic-dc/src/fixed_map.rs
- dc/s2n-quic-dc/src/packet/stream/decoder.rs
- dc/s2n-quic-dc/src/stream/send/application/state.rs
- quic/s2n-quic-core/src/buffer/reader.rs
- quic/s2n-quic-core/src/buffer/reassembler.rs
- quic/s2n-quic-core/src/buffer/reassembler/reader.rs
- quic/s2n-quic-core/src/recovery/bandwidth/estimator.rs
- quic/s2n-quic-core/src/recovery/bbr/probe_bw.rs
- quic/s2n-quic-core/src/recovery/bbr/windowed_filter.rs
- quic/s2n-quic-core/src/recovery/persistent_congestion.rs
- quic/s2n-quic-core/src/stream/testing.rs
- quic/s2n-quic-sim/src/stats.rs
- quic/s2n-quic-transport/src/connection/local_id_registry.rs
- quic/s2n-quic-transport/src/connection/peer_id_registry.rs
- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/stream/contract.rs
- quic/s2n-quic-transport/src/stream/send_stream.rs
- quic/s2n-quic/src/client/providers.rs
- quic/s2n-quic/src/provider/address_token/default.rs
- quic/s2n-quic/src/server/providers.rs
A new rust version (1.84.0) added new enforced clippy lints, which this PR fixes.
Addressed two lints:
- https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
- https://rust-lang.github.io/rust-clippy/master/index.html#large_const_arrays
Tests passed in CI
> build: address clippy issues from 1.84

- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
While benchmarking TCP streams, we found that deriving the crypto before opening the stream stream can increase the likelihood that when the client can write the first packet quickly after the first round trip. This increases the chances of the first read on the server being successful and not having to fall back to epoll to wait for it.
> fix(s2n-quic-dc): derive crypto before opening TCP stream

- .github/actions/duvet/action.yml
s2n-tls uses the s2n-quic duvet github action, and the latest update to duvet broke our CI. We need to pin to an older version of duvet.
This PR adds an input to the action so that s2n-tls can set a specific version of duvet.
I can minimally prove that this doesn't break anything, because the ci / compliance check succeeded.
I manually tested that it actually sets the version by opening a separate PR with the s2n-quic compliance job duvet version [changed to 0.3.0](https://github.com/aws/s2n-quic/pull/2453/commits/924b58f486434476a4beeccb62c2c0deb1d7048c). [The job](https://github.com/aws/s2n-quic/actions/runs/12919220310/job/36029282431?pr=2453#step:3:165) used that version:
```
Installing duvet with cargo
...
Cache restored successfully
Using cached `duvet` with version 0.3.0
``` …
> ci(duvet): add version input to duvet action

- quic/s2n-quic-core/src/inet/ip.rs
- quic/s2n-quic-core/src/packet/interceptor.rs
- quic/s2n-quic-core/src/path/mod.rs
- quic/s2n-quic-core/src/xdp/encoder.rs
- quic/s2n-quic-core/src/xdp/path.rs
- quic/s2n-quic-platform/src/message/msg/handle.rs
- quic/s2n-quic-qns/src/intercept.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/path/mod.rs
- quic/s2n-quic/src/tests/connection_migration.rs
- quic/s2n-quic/src/tests/recorder.rs
The `msg::Handle::eq` check currently misses unmapping IPv4-mapped local addresses when trying to check if a path has migrated. This causes issues if packets are arriving on both IPv4 and IPv4-mapped spaces.
This change fixes this issue. Additionally, I've renamed the `Path::eq` method to `unmapped_eq` to make it very clear which function is being dispatched to; otherwise you end up getting `PartialEq::eq` in scope and it ends up doing a strict comparison. 
I've added some integration tests to test that things are mostly wired up correctly. Note that these tests do not use the `msg::Handle`, so this specific instance wouldn't have been caught with those alone but are good to have in general. For that, I've added an explicit unit test asserting the behavior that we want. Without the fix, …
> fix: correctly unmap IPv4-mapped local addresses

- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
In further testing, this introduces too much reordering under high concurrency for our dedup tracking to mitigate. connect() can "complete" in reverse order of starts (e.g., due to queueing of the wake events) which leads to huge gaps (up to concurrency) in the chosen key IDs.
We can likely get the best of both worlds by deriving crypto beforehand but only associating it with a stream just-in-time as connect()s complete (keeping a per-peer pool just for opening connections) but that's a more invasive change, for now just revert this.
This reverts commit 71e56fe25d7fc793ce857bdda5e16ebc6365a86b (#2451).
This was caught in a more thorough integration test. I think it's likely possible to simulate that within a unit-ish test (TCP connect to localhost or so), but it feels a bit artificial to …
> Revert "derive crypto before opening TCP stream"

- quic/s2n-quic-core/src/path/mod.rs
- quic/s2n-quic-platform/src/message/msg/handle.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/mod.rs
- quic/s2n-quic/src/tests/connection_migration.rs
We currently consider the full 4-tuple (local + remote IP addresses and ports) when identifying a path. This seems to be an overly strict interpretation of how paths are considered in the RFC. I don't see any text indicating this is the correct approach. In fact, I see the following:
```
//= https://www.rfc-editor.org/rfc/rfc9000#section-9.3
//# Receiving a packet from a new peer address containing a non-probing frame
//# indicates that the peer has migrated to that address.
```
That text seems to indicate that we should really only be considering the peer address when deciding if it tried to migrate. So I've implemented that change here.
Additionally, I've ensured that the server does _not_ update the local address it is sending on, even if received a packet on a new one, since this …
> fix: ignore local address when considering path migration

- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/entry.rs
- dc/s2n-quic-dc/src/path/secret/map/entry/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/handshake.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
- dc/s2n-quic-dc/src/path/secret/map/state/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/store.rs
- dc/s2n-quic-dc/src/path/secret/receiver.rs
- dc/s2n-quic-dc/src/path/secret/receiver/tests.rs
n/a
n/a
This simplifies the receiver dedup implementation by replacing it with an inline bitset, which we shift over on new arrivals. The end result is that we have an effective tracker for ~896 packets fitting into about the same amount of space as the previous combination of shared map and entry data (+6 bytes/entry if we assume 500k entries).
The new implementation is also easier to tweak, since we directly expose the window size. It's likely that this slows down inserts a little (we need to shift over 112 bytes at the current size) but shuffling a 112-byte array should be sufficiently fast that I don't think it's worth worrying about it.
I'd be open to re-writing bitvec's parts into our code if we wanted to, but it's a bit tricky to get the shifting right (doable but ugly). It seems …
> feat(s2n-quic-dc): Replace shared map with larger bitset

- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/cleaner.rs
- dc/s2n-quic-dc/src/path/secret/map/entry.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
- dc/s2n-quic-dc/src/path/secret/map/store.rs
n/a
n/a
This drops the requested handshakes map in favor of supporting registering a callback. I initially tried/considered doing this as a Subscriber, but it gets pretty tricky to integrate that -- the Map is already getting passed *into* s2n-quic endpoints as a dc::Endpoint. Plus, the detailed logic on how to handshake interacts with application layer concerns (e.g., possibly throttling) that I'm not sure should live in s2n-quic.
n/a
No additional tests here - this sort of implies we *have* no tests for this functionality in s2n-quic-dc, which makes sense since that doesn't have any actual s2n-quic dependency. I'm not sure whether we should add one or otherwise tweak things in that regard. It should get caught in the internal integration tests. (Note that this is not safe by itself, all …
> Replace requested_handshakes set with a callback

- tools/xdp/s2n-quic-xdp/Cargo.toml
- tools/xdp/s2n-quic-xdp/src/io/tests.rs
Update dependency according to [PR#2460](https://github.com/aws/s2n-quic/pull/2460). As mentioned in [this comment](https://github.com/aws/s2n-quic/pull/2460#issuecomment-2622614026), the latest `rand` release contains some breaking changes that we need to fix.
`thread_rng()` and `gen_range()` have been renamed to `rand::rng()` and `random_range()`. They have also been removed from `rand::prelude`. Hence, I have updated the function names and the used crate.
For more details of the breaking change that `rand` release has introduced, refer to their [release summary](https://github.com/rust-random/rand/releases/tag/0.9.0), and specifically to their PR that [rename `thread_rng()`](https://github.com/rust-random/rand/pull/1506).
This PR will be tested by the existing tests in our CI. `ci / …
> build(deps): update rand requirement in /tools/xdp

- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager/tests.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/worker.rs
- dc/s2n-quic-dc/src/stream/testing.rs
This changes the TCP APIs to take a `linger` parameter instead of always setting it to `0`. This avoids issues where the last peer to send data reset streams before transmitting the entire thing - especially where the last chunk is large and can be blocked on things like CWIN and flow control.
> feat(s2n-quic-dc): accept linger parameter instead of always setting it

- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/path/secret/map/cleaner.rs
- dc/s2n-quic-dc/src/path/secret/map/entry.rs
- dc/s2n-quic-dc/src/path/secret/receiver/tests.rs
- dc/s2n-quic-dc/src/random.rs
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-qns/src/intercept.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/provider/connection_id.rs
- quic/s2n-quic/src/provider/random.rs
- quic/s2n-quic/src/provider/stateless_reset_token.rs
- quic/s2n-quic/src/tests/setup.rs
This PR is used to update `rand` dependencies' versions in the codebase. This PR should address problems occurred in [PR#2466](https://github.com/aws/s2n-quic/pull/2466).
The `rand` library has a version bump and introduces some API changes. Those changes involves some renaming function names, and changing some functions' parameters. Refer to the [release note](https://github.com/rust-random/rand/releases/tag/0.9.0) for more details.
* In `rand v0.9.0`, the `RngCore` trait no longer has the function `try_fill_bytes()`, so I have removed that function.
* `rand::rng()` function has been taken out of `rand::prelude::*`. We can find it in `rang::{Rng, RngCore}`.
* In `rand v0.9.0`, `rand::Error::new` no longer exists. We should return the `Unspecified` Error that AWSLC returns in case of …
> build(deps): update rand requirement except for s2n-quic-sim

- quic/s2n-quic-qns/Cargo.toml
Pin `litemap` and `zerofrom` versions to prior versions which support our current MSRV rust v1.74.1.
These two dependencies are from the `url` dep in `s2n-quic-qns` crate:
```
𝄞 cargo tree --invert zerofrom
zerofrom v0.1.6
├── icu_collections v1.5.0
│   ├── icu_normalizer v1.5.0
│   │   └── idna_adapter v1.2.0
│   │       └── idna v1.0.3
│   │           └── url v2.5.4
│   │               └── s2n-quic-qns v0.1.0 (/home/cameron/Projects/aws/s2n-quic/quic/s2n-quic-qns)
│   └── icu_properties v1.5.1
│       ├── icu_normalizer v1.5.0 (*)
│       └── idna_adapter v1.2.0 (*)
├── icu_provider v1.5.0
│   ├── icu_locid_transform v1.5.0
│   │   └── icu_properties v1.5.1 (*)
│   ├── icu_normalizer v1.5.0 (*)
│   └── icu_properties v1.5.1 (*)
├── yoke v0.7.5
│   ├── icu_collections v1.5.0 (*)
│   ├── …
```
> ci: pin litemap and zerofrom versions to support current MSRV

- dc/s2n-quic-dc/src/path/secret/receiver/tests.rs
n/a
n/a
Fixes a spurious test failure found in CI.
n/a
Re-ran tests 2000 times with no failures.
> fix(s2n-quic-dc): Fix spurious panic for empty sample range

- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-platform/src/io/testing.rs
- quic/s2n-quic-platform/src/io/testing/model.rs
- quic/s2n-quic-platform/src/io/testing/time.rs
- quic/s2n-quic-sim/Cargo.toml
- quic/s2n-quic-sim/src/run.rs
- quic/s2n-quic-sim/src/run/endpoint.rs
- quic/s2n-quic-sim/src/run/range.rs
- quic/s2n-quic/src/tests/issue_1427.rs
resolve https://github.com/aws/s2n-quic/issues/2479
I have updated all `bach` and `rand` requirements in S2N-QUIC. This PR will close the [dependabot PR to update bach](https://github.com/aws/s2n-quic/pull/2385).
After `bachv0.0.6`, it no longer provides rand backend implementation. Instead, `bach` use the Bolero generator to do the rand updates. That's why there are many `rand::Any::any()` calls to get random bits.
CI test should fix it.
> build(deps): bach and rand updates

- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/stream/server/tokio/accept.rs
- dc/s2n-quic-dc/src/stream/server/tokio/stats.rs
- dc/s2n-quic-dc/src/sync.rs
- dc/s2n-quic-dc/src/sync/mpmc.rs
- dc/s2n-quic-dc/src/sync/mpsc.rs
- dc/s2n-quic-dc/src/sync/ring_deque.rs
- dc/s2n-quic-dc/src/testing.rs
The current `s2n_quic_dc::sync` only exports a single `mpmc` channel. This change refactors the channel implementation to provide both a `mpmc` and `mpsc` channel for use cases where there will only be one receiver. This implementation can be a bit cheaper since it uses the existing `Mutex` around the `ring_deque` to store the receiver waker.
I added some high level tests showing that both channel implementations are working as expected.
> feat(s2n-quic-dc): add mpsc channel

- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/recv.rs
- dc/s2n-quic-dc/src/stream/recv/application.rs
- dc/s2n-quic-dc/src/stream/recv/application/builder.rs
- dc/s2n-quic-dc/src/stream/recv/buffer.rs
- dc/s2n-quic-dc/src/stream/recv/buffer/dispatch.rs
- dc/s2n-quic-dc/src/stream/recv/buffer/local.rs
- dc/s2n-quic-dc/src/stream/recv/shared.rs
- dc/s2n-quic-dc/src/stream/recv/worker.rs
- dc/s2n-quic-dc/src/stream/send/application.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/worker.rs
- dc/s2n-quic-dc/src/stream/server/tokio/udp.rs
This change moves recv buffer filling and packet parsing into a dedicated module, which was previously in `recv::shared`. The new location allows for multiple types of strategies for filling the packet buffer. This will enable the packets from #2483 to be processed by the existing stream code while still allowing for the current strategy where the stream owns the recv buffer and is responsible for reading bytes into it.
Since this is mostly just a refactor of where the logic lives, the existing tests should be sufficient enough to check that it's all working. That being said, I will be working on bulking up our tests overall and this module will be included in that later.
> refactor(s2n-quic-dc): add stream recv buffer trait and impls

- docs/user-guide/debugging-pcap.md
Fix a typo in S2N-QUIC Debugging runbook:
* It should be `Server`, not `Serverhell`.
> fix: typo for debugging book

- quic/s2n-quic-core/src/connection/limits.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/connection/mod.rs
- quic/s2n-quic-transport/src/endpoint/initial.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic-transport/src/space/session_context.rs
- quic/s2n-quic/src/provider/limits.rs
- quic/s2n-quic/src/tests.rs
- quic/s2n-quic/src/tests/connection_limits.rs
New API added to allow users to change connection limits based on the information in the TLS handshake, such as server name and application protocol. Previously users could only change connection limits based on their peer's remote address. 
resolves #1445
Added a new function to the connection limits provider. Had to feed the limits provider through to the place where we want it to be called. Currently on stream batching can be dynamically configured. However we can always add more setters on user request.
Not all connection limits should be allowed to be altered, given that some are transport parameters. Currently it's hard for me to tell which ones should be altered so I created a single setter for stream batching.
I added a integ test for the Connection limits. Unsure if this is the …
> feat(s2n-quic): New function added to Connection Limits provider

- dc/s2n-quic-dc/src/packet/stream/id.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/server/handshake.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/worker.rs
- dc/s2n-quic-dc/src/stream/server/tokio/udp.rs
- dc/wireshark/src/dissect.rs
- dc/wireshark/src/field.rs
- dc/wireshark/src/test.rs
This change takes the previously unused `stream_id` field in packets and renames it to `queue_id`. Long term, this field will be used when multiplexing on a shared UDP socket to map the packet into a locally assigned packet queue. Note that this is currently just a rename and having the `endpoint` functions take the parameter explicitly.
> refactor(s2n-quic-dc): rename stream_id to queue_id

- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/socket.rs
- dc/s2n-quic-dc/src/socket/recv.rs
- dc/s2n-quic-dc/src/socket/recv/__fuzz__/socket__recv__pool__tests__model/corpus.tar.gz
- dc/s2n-quic-dc/src/socket/recv/descriptor.rs
- dc/s2n-quic-dc/src/socket/recv/pool.rs
- dc/s2n-quic-dc/src/socket/recv/router.rs
- dc/s2n-quic-dc/src/socket/recv/udp.rs
- dc/s2n-quic-dc/src/testing.rs
The current recv buffer code relys on the [s2n_quic_dc::msg::recv::Message](https://docs.rs/s2n-quic-dc/latest/s2n_quic_dc/msg/recv/struct.Message.html) module. This works well for an implementation that owns all of the messages that come in on a single socket. However, once we start getting into multiplexing multiple receivers on a single socket, the `Message` struct doesn't really enable that usecase, at least not efficiently.
We also run into issues if we ever want to support AF_XDP (since the XDP UMEM wants a contiguous region of packets), GRO (since we can't easily split `Message`s across packet boundaries without a copy), or dedicated `recv` tasks/threads that dispatch to the registered channels.
This implementation adds a new `socket::recv::pool` module, which enables all of these …
> feat(s2n-quic-dc): implement recv path packet pool

- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/entry.rs
- dc/s2n-quic-dc/src/path/secret/map/entry/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/handshake.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
- dc/s2n-quic-dc/src/path/secret/map/state/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/store.rs
* feat(dc): Support storing arbitrary application-provided data in Entry
n/a
This stores arbitrary metadata (Arc<dyn Any>) in each Entry. By default, we share a single `Arc<()>` across all entries, but applications can register a callback to produce different dat per path secret.
None.
No tests added, but the functionality is pretty obvious.
> feat(s2n-quic-dc): Support storing ApplicationData in Entry

- dc/s2n-quic-dc/src/socket/recv/router.rs
- dc/s2n-quic-dc/src/stream/recv.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/__fuzz__/stream__recv__dispatch__tests__model/corpus.tar.gz
- dc/s2n-quic-dc/src/stream/recv/dispatch/descriptor.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/free_list.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/handle.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/pool.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/queue.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/sender.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/tests.rs
- dc/s2n-quic-dc/src/sync/mpsc.rs
- dc/s2n-quic-dc/src/sync/ring_deque.rs
- dc/s2n-quic-dc/src/testing.rs
With the changes in #2507, we now use the `queue_id` field to route packets to the correct queues, which will be read by the target stream. This means we need a way to allocate `queue_id`s from a pool and free them once they're no longer used for another stream to pick up.
This change implements exactly that - a queue allocator.
Additionally, it includes a packet dispatcher implementation that looks up the queue by its ID and sends the packet if there is an active owner.
A lot of the allocator code has been copied/modified from #2483. I considered trying to make some generic code between the two, but decided against it for now, since I want the implementations to settle before trying to extract the overlap and try to figure out an interface that works for both.
I added a model that tests …
> feat(s2n-quic-dc): implement queue allocator/dispatcher

- dc/s2n-quic-dc/src/stream/send/tests.rs
- dc/s2n-quic-dc/src/stream/testing.rs
The UDP stream tests were disabled due to being flaky. After investigation, this was due to the `Client` and its associated background tokio runtimes were dropped before it could finalize the stream state with the server.
After moving the client to be dropped after the server's stream is complete, I haven't seen any failures after running it in a loop for about an hour.
> test(s2n-quic-dc): fix flaky UDP stream tests

- dc/s2n-quic-dc/src/stream/socket.rs
- dc/s2n-quic-dc/src/stream/socket/application/builder.rs
- dc/s2n-quic-dc/src/stream/socket/fd/udp.rs
- dc/s2n-quic-dc/src/stream/socket/send_only.rs
- dc/s2n-quic-dc/src/stream/socket/tokio/udp.rs
This change adds a send-only UDP socket wrapper. Rather than trying to coordinate between multiple shared actors, this socket will never register waker interest and will drop any packets that get a `WouldBlock` error.
As part of a follow-up PR, this socket type will be used for transmission when coupled with the pooled recv sockets.
> feat(s2n-quic-dc): add SendOnly UDP socket

- dc/s2n-quic-dc/src/socket/recv/router.rs
- dc/s2n-quic-dc/src/socket/recv/udp.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/pool.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/sender.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/tests.rs
This change adds a `WithMap` packet router. This will forward any secret control packets to the path secret map to handle.
I fixed a few small things as part of this PR as well:
* When creating a non-zero dispatch pool, we weren't considering that in the sender lookup code. This change fixes that and adds a test for it.
* The `recv::udp` module was missing a non-blocking counterpart so I've also added that.
> feat(s2n-quic-dc): add WithMap router

- dc/s2n-quic-dc/src/stream.rs
- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/recv/application.rs
- dc/s2n-quic-dc/src/stream/recv/buffer.rs
- dc/s2n-quic-dc/src/stream/recv/buffer/channel.rs
- dc/s2n-quic-dc/src/stream/recv/buffer/local.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/handle.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/queue.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/tests.rs
- dc/s2n-quic-dc/src/stream/recv/shared.rs
- dc/s2n-quic-dc/src/stream/recv/worker.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/worker.rs
- dc/s2n-quic-dc/src/stream/server/tokio/udp.rs
This change implements a channel-based recv buffer. This uses the queue allocator channels implemented in #2517.
I've included a couple of related, small changes in here as well:
* Added an `Actor` argument to the `Buffer` traits and queues to be able to treat application and worker wakers separately.
> feat(s2n-quic-dc): add channel recv buffer impl

- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/environment.rs
- dc/s2n-quic-dc/src/stream/environment/tokio.rs
- dc/s2n-quic-dc/src/stream/environment/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/environment/tokio/udp.rs
- dc/s2n-quic-dc/src/stream/recv/shared.rs
- dc/s2n-quic-dc/src/stream/recv/worker.rs
- dc/s2n-quic-dc/src/stream/send/worker.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/worker.rs
- dc/s2n-quic-dc/src/stream/server/tokio/udp.rs
This change wires up the recv buffer trait from #2505 to the UDP stream workers. In order to do this, I refactored the `environment` traits a bit to return the appropriate buffer impl for the chosen socket type.
Since this is mostly a refactor, the existing tests should be sufficient to show it all working.
> refactor(s2n-quic-dc): wire up recv buffer trait to stream workers

- dc/s2n-quic-dc/src/stream/send/tests.rs
After #2526 plus the recent PRs, non-linux platforms broke for UDP streams. This PR temporarily disables running tests on non-linux platforms until things are fully refactored and fixed.
> test(s2n-quic-dc): only run UDP stream tests on linux for now

- quic/s2n-quic-sim/Cargo.toml
- quic/s2n-quic-sim/src/run/config.rs
- quic/s2n-quic-sim/src/run/endpoint.rs
- quic/s2n-quic-sim/src/run/range.rs
- quic/s2n-quic-sim/src/stats.rs
resolves https://github.com/aws/s2n-quic/issues/2524.
This PR will replace our `humantime` library with `jiff`.
One of our dependency `humantime` hasn't been updated for four years and is currently not maintained. Github action has cut us a ticket, asking us to consider alternatives. The recommended alternative for `humantime` is [`jiff`](https://github.com/BurntSushi/jiff), a newly developed daytime library.
I have incorporated `jiff` in `s2n-quic-sim`.
Instead of `Duration`, `jiff` provides [`SignedDuration`](https://docs.rs/jiff/0.2.4/jiff/struct.SignedDuration.html):
> Unlike [std::time::Duration](https://doc.rust-lang.org/nightly/core/time/struct.Duration.html), this duration is signed. The sign applies to the entire duration.
> That is, either both the seconds and the fractional …
> refactor(s2n-quic-sim): replace unmaintained humantime library with jiff

- dc/s2n-quic-dc/src/msg/segment.rs
- dc/s2n-quic-dc/src/stream/send/application.rs
- dc/s2n-quic-dc/src/stream/send/application/state.rs
- dc/s2n-quic-dc/src/stream/send/flow/blocking.rs
- dc/s2n-quic-dc/src/stream/send/flow/non_blocking.rs
- dc/s2n-quic-dc/src/stream/send/queue.rs
- dc/s2n-quic-dc/src/stream/send/worker.rs
`s2n-quic-dc` packets carried over UDP are required to respect several limits related to maximum payload size and flow control, as well as respecting the MTU of the path. For packets carried over TCP, however, these limits are not applicable, and actually can result in payloads being unnecessarily broken up into many more write syscalls. This can lead to lower throughput as TCP send buffers may not be saturated, causing the congestion controller window to remain limited as the flow will be "application limited". This change removes these limits when the selected underlying transport protocol is TCP.
Tested manually, additional unit tests can be added as a follow up
> fix(s2n-quic-dc): don't restrict TCP writes to limits for UDP

- dc/s2n-quic-dc/src/path/secret/map/entry.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
* fix(s2n-quic-dc): correct background handshake rate
n/a
Our design goal is to aim for 1 handshake every 24 hours (rehandshake_period).
Previously, a handshake occurred at rand(24 hours) for each entry, which makes a single peer on average see *two* handshakes every 24 hours. This produces several bad behaviors:
* The first 24 hours after coordinated handshakes (e.g., deployment) have a linear curve of total handshake rate, because the second half sees repeated handshakes from the first half (the peers that handshake quickly have opportunity to handshake again overlapping with those that handshake slowly).
* Overall rates are 2x higher than expected, since we handshake on average twice per 24 hours period.
The new approach fixes both problems.
n/a
In-progress (running a longer-running …
> Adjust background handshake rates

- dc/s2n-quic-dc-benches/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
Resolves: https://github.com/aws/s2n-quic/issues/2518
`Paste` is archived, but it is a dependencies of `aws-ls-rs`. AWS-LC has remove that dependencies and release their `aws-lc-rs` and `aws-lc-fips-sys` crates. We should use the most up to date `aws-lc-rs` crate, so that `paste` will not be one of our dependencies.
Cargo tree before:
```
ubuntu@:~/workspace/s2n-quic$ cargo tree --invert paste
paste v1.0.15 (proc-macro)
├── aws-lc-rs v1.11.1
│   ├── rustls v0.23.19
│   │   └── s2n-quic-rustls v0.54.0 (/home/ubuntu/workspace/s2n-quic/quic/s2n-quic-rustls)
│   │       └── s2n-quic v1.54.0 (/home/ubuntu/workspace/s2n-quic/quic/s2n-quic)
│   │           ├── s2n-quic-h3 v0.1.0 (/home/ubuntu/workspace/s2n-quic/quic/s2n-quic-h3)
│   │           │   └── s2n-quic-qns v0.1.0 …
```
> build(deps): use up to date aws-lc-rs

- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/event_tests.rs
- dc/s2n-quic-dc/src/stream/environment/tokio.rs
- dc/s2n-quic-dc/src/stream/testing.rs
The path secret Map `test_insert_pair` function picks the `dc::testing::TEST_APPLICATION_PARAMS`, without providing a way to override them. This change allows passing in an override, if the caller is wanting to change something, like the `max_datagram_size`.
> test(s2n-quic-dc): allow params to be specified for test credentials

- quic/s2n-quic-core/src/state.rs
This change adds the caller location to state transitions to make it easier to debug what line of code caused the transition to occur.
```
client:worker::write: s2n_quic_core::stream::state::send: event=on_send_stream prev=Ready next=Send client=0
client:worker::read: s2n_quic_dc::stream::recv::worker::waiting: event=on_cooldown_elapsed prev=Cooldown next=PeekPacket client=0
server:udp:worker::read: s2n_quic_dc::stream::recv::worker::waiting: event=on_application_progress prev=EpochTimeout next=Cooldown
client:worker::read: s2n_quic_dc::stream::recv::worker::waiting: event=on_application_progress prev=PeekPacket next=Cooldown client=0
server:udp:worker::write: s2n_quic_core::stream::state::send: event=on_send_stream prev=Ready next=Send
server:udp:worker::write: …
```
> test(s2n-quic-core): add location to state transitions

- dc/s2n-quic-dc/src/stream/server/tokio/udp.rs
We have some debug sanity checks in the UDP socket `send` code to make sure we're not wasting syscalls by sending empty packets (which are meaningless here). This code was triggering that in some of the testing I've been doing. This change, instead, checks if the packet is empty before calling it.
> fix(s2n-quic-dc): skip sending empty packets in udp acceptor

- common/s2n-codec/Cargo.toml
- common/s2n-codec/src/encoder/buffer.rs
- common/s2n-codec/src/encoder/mod.rs
- common/s2n-codec/src/encoder/scatter.rs
- common/s2n-codec/src/zerocopy.rs
- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/credentials.rs
- dc/s2n-quic-dc/src/packet/control.rs
- dc/s2n-quic-dc/src/packet/datagram.rs
- dc/s2n-quic-dc/src/packet/secret_control.rs
- dc/s2n-quic-dc/src/packet/stream.rs
- dc/s2n-quic-dc/src/packet/tag.rs
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/crypto/tls.rs
- quic/s2n-quic-core/src/frame/dc_stateless_reset_tokens.rs
- quic/s2n-quic-core/src/inet/macros.rs
- quic/s2n-quic-core/src/stateless_reset/token.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/provider/address_token/default.rs
This PR should resolves https://github.com/aws/s2n-quic/pull/2343.
Update `zerocopy` requirements in S2N-QUIC from 0.7 to 0.8 (following the [update guide](https://github.com/google/zerocopy/discussions/1680)):
* bump versions for all `zerocopy` in `Cargo.toml`s.
* Handle renaming:
* The trait `AsByte` is renamed to `IntoBytes`.
* The trait `Fromzeroes` is renamed to `Fromzeros`.
* Function renames for `slice_from_prefix`, and `mut_slice_from_prefix`.
* Derive `zerocopy::{Immutable, Knownlayout}` traits into the codebase:
* Those two traits are introduced in the new versions, and we need some of our structs (especially those setup by Macros) to derive those two traits.
* If we derive `FromBytes` trait, then we don't need to explicitly derive `TryFromBytes` and `FromZeros` traits.
```
As …
```
> build(deps): update zerocopy requirement from 0.7 to 0.8

- .github/ISSUE_TEMPLATE/s2n-quic-issue.md
Add a `Need by Date` section in the Github Issue template for customer to provide information about their estimated timeline or deadlines. Change the `s2n-quic-issue.md`.
The same as https://github.com/aws/s2n-tls/pull/5187.
> chore: include Need By Date section in github issue template

- dc/s2n-quic-dc/src/packet/control/decoder.rs
- dc/s2n-quic-dc/src/stream/send/state.rs
This change moves the control frame parsing logic to the `control::decoder` module, instead of being done in the sender state. This makes it a bit easier to do ad-hoc debugging to get all of the frames.
> refactor(s2n-quic-dc): add control_frames fn to control packets

- dc/s2n-quic-dc/src/stream/recv/dispatch.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/descriptor.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/free_list.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/handle.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/probes.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/queue.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/tests.rs
After doing some testing, the current dispatch queue closing logic has a potential race condition where the queue can end up being freed twice. This change fixes that by locking both receivers in the same order (to avoid a deadlock) and observing the other side's status before deciding to free the queue or not.
I did a little more clean up around tracing events by creating actual probes instead. I've also tried to avoid calling any of the probes while holding a mutex.
I added a stress test that was able to reproduce the original issue and show that the changes fixed.
> fix(s2n-quic-dc): synchronize dispatch queue closure

- dc/s2n-quic-dc/src/socket/recv/descriptor.rs
- dc/s2n-quic-dc/src/socket/recv/pool.rs
This change adds some debug assertions to the descriptor free lists to try and catch any issues around free list logic. With `debug_assertions` disabled, this logic will be removed at runtime.
> test(s2n-quic-dc): add debug assertions to descriptor free lists

- dc/s2n-quic-dc/src/stream/testing.rs
- dc/s2n-quic-dc/src/stream/tests.rs
- dc/s2n-quic-dc/src/stream/tests/request_response.rs
This change adds several request/response tests for s2n-quic-dc streams.
I had to disable the fuzz tests as the CI wasn't very happy about running them. The amount of logs it generated prevented me from downloading it as well, so it wasn't clear why it was failing. I will follow up with a fix to enable them later, though.
> test(s2n-quic-dc): add request/response tests

- dc/s2n-quic-dc/src/msg/segment.rs
- dc/s2n-quic-dc/src/stream/environment/tokio.rs
- dc/s2n-quic-dc/src/stream/send/flow.rs
- dc/s2n-quic-dc/src/stream/send/path.rs
As discovered in #2534, the amount of data acquired for flow control should align with the payload limit of the underlying syscall.
This change does exactly that by dividing the max payload by the max datagram size to get the total number of full datagrams that can be sent while staying under the syscall limit. In local testing, this resulted in a 20% increase in performance.
I've also tried to reduce the number of places where these maximums get placed. This includes the default GSO settings as well as the `msg::segment::MAX_COUNT`.
> fix(s2n-quic-dc): clamp send quantum to max syscall size

- dc/s2n-quic-dc-benches/src/streams.rs
- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/socket/recv/router.rs
- dc/s2n-quic-dc/src/socket/recv/router/with_map.rs
- dc/s2n-quic-dc/src/socket/recv/router/zero_router.rs
- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/environment.rs
- dc/s2n-quic-dc/src/stream/environment/tokio.rs
- dc/s2n-quic-dc/src/stream/environment/tokio/pool.rs
- dc/s2n-quic-dc/src/stream/environment/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/environment/tokio/udp.rs
- dc/s2n-quic-dc/src/stream/server.rs
- dc/s2n-quic-dc/src/stream/server/accept.rs
- dc/s2n-quic-dc/src/stream/server/tokio/accept.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/worker.rs
- dc/s2n-quic-dc/src/stream/server/tokio/udp.rs
- dc/s2n-quic-dc/src/stream/server/udp.rs
- dc/s2n-quic-dc/src/stream/testing.rs
Similar to #2533, this change wires up the recv pool for servers.
I had to refactor a few things to get this all working - mostly simplifying a few interfaces and having `Environment` now hold a reference to the subscriber, which should have been done originally since it has it as a generic argument.
Most of the interesting implementation is in `dc/s2n-quic-dc/src/stream/server/udp.rs`.
One thing to note is we are now using an LRU instead of the handshake map from before. This should be a lot simpler since we don't have to synchronize any state across workers. All of it is contained in the single acceptor task since packets are routed deterministically based on 4-tuples.
Also note that this combines the acceptor task with the socket recv loop. I started going down the path of splitting …
> feat(s2n-quic-dc): wire up recv pool to server

- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/credentials.rs
- dc/s2n-quic-dc/src/stream/environment/bach/pool.rs
- dc/s2n-quic-dc/src/stream/environment/bach/udp.rs
- dc/s2n-quic-dc/src/stream/environment/tokio/pool.rs
- dc/s2n-quic-dc/src/stream/environment/tokio/udp.rs
- dc/s2n-quic-dc/src/stream/environment/udp.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/descriptor.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/free_list.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/handle.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/keys.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/pool.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/sender.rs
- dc/s2n-quic-dc/src/stream/recv/dispatch/tests.rs
- dc/s2n-quic-dc/src/stream/server/udp.rs
As a followup to https://github.com/aws/s2n-quic/pull/2556#discussion_r2005971782, this changes the credential mapping from an LRU to a DashMap that preserves the association for the lifetime of the channel. This should avoid issues where the two get out of sync and end up trying to create a new stream only to get a replay detected error.
I added a test showing that the association is preserved as long as one of the receivers is active. As soon as both are dropped, the association is removed.
> feat(s2n-quic-dc): support key association in dispatch queue allocator

- dc/s2n-quic-dc/src/stream/tests/request_response.rs
It looks like the stream fuzz tests are having issues in CI. So this change disables it for now until we figure out why.
> test(s2n-quic-dc): disable UDP stream fuzz sims for CI

- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
Version bump for release.
Non standard release: I bumped the required s2n-tls version because of the new dependency on the supported group API from `0.3.15`.
> chore: release 1.56.0

- dc/s2n-quic-dc/src/path/secret/map/cleaner.rs
- dc/s2n-quic-dc/src/stream/send/tests.rs
- dc/s2n-quic-dc/src/stream/testing.rs
- dc/s2n-quic-dc/src/stream/tests/request_response.rs
- dc/s2n-quic-dc/src/testing.rs
It looks like the issue in #2570 was due to the tracing logs consuming too much memory. This change fixes that issue by flagging certain tests that generate a lot of logs and disabling those by default. I've also turned down the log level from `debug` to `info` in CI so that should also help.
> test(s2n-quic-dc): disable tracing by default for tests with large output

- README.md
- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-events/Cargo.toml
- quic/s2n-quic-h3/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-qns/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-sim/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- rust-toolchain
- tools/xdp/s2n-quic-xdp/Cargo.toml
This release bumps the MSRV to 1.75.
I need to use [`-> impl Trait`](https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html#async-fn-and-return-position-impl-trait-in-traits) in #2572 and thought now was a good time to bump MSRV to enable that. 1.75 is over a year old so it's probably overdue.
> chore: bump MSRV to 1.75

- .clippy.toml
- dc/s2n-quic-dc/src/stream/client.rs
- dc/s2n-quic-dc/src/stream/client/rpc.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/recv/shared.rs
- dc/s2n-quic-dc/src/stream/send/application.rs
- dc/s2n-quic-dc/src/stream/send/application/builder.rs
- dc/s2n-quic-dc/src/stream/send/state.rs
- dc/s2n-quic-dc/src/stream/send/worker.rs
- dc/s2n-quic-dc/src/stream/shared.rs
- dc/s2n-quic-dc/src/stream/shared/handshake.rs
- dc/s2n-quic-dc/src/stream/shared/snapshots/s2n_quic_dc__stream__shared__handshake__tests__dot_test.snap
- dc/s2n-quic-dc/src/stream/shared/snapshots/s2n_quic_dc__stream__shared__handshake__tests__snapshots.snap
- dc/s2n-quic-dc/src/stream/testing.rs
- dc/s2n-quic-dc/src/stream/tests.rs
- dc/s2n-quic-dc/src/stream/tests/deterministic.rs
- dc/s2n-quic-dc/src/stream/tests/rpc.rs
This change adds a client RPC API for streams. 
```rust
let response = client.rpc(server_addr, request, response_collector).await?;
```
This is a lot more optimized that the standard stream interface due to:
* No need for an empty "prelude" packet since the request data is all provided up front
* The stream packets indicate the final stream size from the very first packet so the client doesn't need to send an empty "fin" packet.
* Ensuring the application doesn't deadlock where the client is sending a large request and getting a large response back. Consider the following example:
```rust
// client
stream.write_all(&large_payload).await.unwrap();
```
```rust
// server
let mut chunk = vec![];
loop {
let len = stream.read_buf(&mut chunk).await.unwrap();
if len == 0 {
break;
} …
```
> feat(s2n-quic-dc): add RPC API for streams

- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/cleaner.rs
- dc/s2n-quic-dc/src/path/secret/map/entry.rs
- dc/s2n-quic-dc/src/path/secret/map/entry/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/rehandshake.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
* feat(s2n-quic-dc): adjust re-handshaking implementation (again)
n/a
This changes our handshake strategy again. This time, I've implemented a small simulator and marking the PR as draft until I finish some test silo experiments.
The new approach aims to be trivially provable to handshake at the expected rate (# of peers / handshake_period), because that's exactly what it does. Prior attempts relied on lots of random rolls and the law of large numbers creating that desired rate, but that doesn't always hold (e.g., with small peer counts, we don't have large numbers), and is harder to reason about.
This implementation, like the one in mainline, expects a p100 time 2x the rehandshake period (due to the shuffling on each queue fill). See comments in code for details on why. I think we …
> feat(s2n-quic-dc): Rework handshakes to use a queue

- dc/s2n-quic-dc/src/path/secret/map/rehandshake.rs
* refactor(s2n-quic-dc): shrink rehandshake queue memory footprint
* fix(s2n-quic-dc): avoid new handshake queue order on every refill
n/a
* This cuts ~6.67MB from our reserved capacity. It's still larger than we could have if we stored IPv4 addresses packed together, but I think the new overhead is sufficient to remove the FIXME, we're ~3x worse than optimal for IPv4-only workloads now. On Linux most of the backing memory doesn't get allocated anyway.
* Handshake queue ordering is now based on a hash, not full randomness. This ensures the same peer hashes into the same slot over time, while nicely absorbing changes in the peer set. The hasher is randomly seeded.
n/a
Just CI for the SocketAddr changes, the handshake queue reordering change is tested in our internal test bed and produces …
> Some more tweaks for rehandshake queue

- dc/s2n-quic-dc/src/recovery.rs
- dc/s2n-quic-dc/src/stream/send/state.rs
- dc/s2n-quic-dc/src/stream/send/state/transmission.rs
- dc/s2n-quic-dc/src/stream/tests/rpc.rs
This change applies the following fixes:
* When PTOs are required, the sender first looks at any outstanding stream segments and tries to use those instead of sending probes. This greatly improves recovery time in simulations - 14 packets sent to 6 (bach doesn't put the lost packet in the PCAP - I should probably fix that).
* We've reduced the initial RTT from 10ms to 2ms. This will cause packets that are lost on the initial round of transmissions to be retransmitted earlier. PTOs are armed for `3 * RTT` so it goes from 30ms to 6ms. Longer term I'd like to seed this value from the handshake instead.
* Uses the `requires_fast_retransmission` flag from the CCA to bypass the CWND check when retransmitting. Not sure how I missed that originally...
I've got the simulation tests asserting the …
> fix(s2n-quic-dc): convert stream segments to probes when available

- dc/s2n-quic-dc/src/stream/send/state.rs
- dc/s2n-quic-dc/src/stream/send/tests.rs
In testing I found a bug with the change in #2575 that didn't consider if one of the segments was already in the retransmit queue and ended up mutating the segment in place, which cause the last packet to override the previous value and get transmitted multiple times. This change moves the owned `Segment` into the transmission queue, which ensures the reference count is `>1`, which ensures `Arc::make_mut` does a deep clone rather than a shallow one.
This behavior was causing macOS send tests to fail. I've uncommented those and they now pass.
> fix(s2n-quic-dc): fix retransmission cloning

- dc/s2n-quic-dc/src/stream/environment/bach.rs
- dc/s2n-quic-dc/src/stream/environment/bach/pool.rs
- dc/s2n-quic-dc/src/stream/environment/tokio.rs
- dc/s2n-quic-dc/src/stream/environment/tokio/pool.rs
This allows the caller to know what address was selected for the socket pool in the case that a wild card was specified.
> fix(s2n-quic-dc): export local addr regardless of reuse_port config

- .github/actions/duvet/action.yml
- .github/workflows/book.yml
- .github/workflows/ci.yml
- .github/workflows/qns.yml
Requests to the Github actions cache recently started returning 422. In order to unblock the CI, this PR disables cacheing in `camshaft/install@v1` until we figure out what the issue is.
The CI should now succeed in this PR.
> ci: Disable Github actions cache

- .github/workflows/ci.yml
The miri CI job started hanging on PRs. For example, the following job has been stuck on "Waiting for a runner to pick up this job..." for 3 hours as of this comment:
https://github.com/aws/s2n-quic/actions/runs/14202747209/job/39793296240
I think it's getting stuck because the Ubuntu 20.04 image is being deprecated: https://github.com/actions/runner-images/issues/11101.
To unblock the CI, this PR changes the miri image to `ubuntu-latest` instead. I opened an issue to investigate whether we should look into adding another custom image with increased memory for this job: https://github.com/aws/s2n-quic/issues/2585.
The miri CI job should succeed on this PR.
> ci: Fix hanging miri job

- dc/s2n-quic-dc/src/stream/environment/udp.rs
In testing I ran into issues with mismatched address families. This fixes that issue.
> fix(s2n-quic-dc): correctly map addresses for pooled UDP streams

- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-core/src/buffer/writer/storage/byte_queue.rs
This change optimizes a read to a BytesMut queue when the Bytes we're pushing is uniquely owned, and so we can zero-copy convert to a BytesMut.
n/a
n/a
This upgrades to bytes 1.7.2 as the minimum, I don't see anything concerning in the [changelog](https://github.com/tokio-rs/bytes/blob/master/CHANGELOG.md) or any explicit pinning (not sure why I had 1.6 in my local lockfile).
Existing tests should cover this, no change in behavior.
> Avoid copy for unique Bytes in put_bytes

- .github/workflows/ci.yml
`cargo-udeps` started [failing to install in the CI](https://github.com/aws/s2n-quic/actions/runs/14253308918/job/39950917819?pr=2574#step:5:359):
```
error: failed to compile `cargo-udeps v0.1.55`, intermediate artifacts can be found at `/tmp/cargo-install6NLKp2`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
rustc 1.83.0-nightly is not supported by the following packages:
cargo-credential-libsecret@0.4.12 requires rustc 1.84
cargo-util@0.2.19 requires rustc 1.84
cargo-util-schemas@0.7.3 requires rustc 1.84
crates-io@0.40.9 requires rustc 1.84
Try re-running `cargo install` with `--locked`
```
It seems some cargo-udeps dependencies started requiring a minimum of Rust 1.84. However, bumping the nightly Rust …
> ci: Fix cargo-udeps install

- quic/s2n-quic/src/tests/connection_migration.rs
Fix the wordings for the comment describing the purpose of `rebind_before_handshake_confirmed` test. The datagram should not be dropped when it is received from a client that changes its port.
> fix: comment for rebind_before_handshake_confirmed

- .github/actions/duvet/action.yml
- .github/workflows/book.yml
- .github/workflows/ci.yml
- .github/workflows/qns.yml
Resolves https://github.com/aws/s2n-quic/issues/2583
Cacheing was disabled in https://github.com/aws/s2n-quic/pull/2582 to workaround Github's [April 1st cacheing service deprecation brownout date](https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts). Now that the `camshaft/install` action [has been updated to use the new cacheing service](https://github.com/camshaft/install/pull/1), this action should not be affected by the depreciation of the old cacheing service anymore. So, this PR re-enables `camshaft/install` cacheing in s2n-quic.
The CI jobs using `camshaft/install` should continue to succeed for this PR. I ran the jobs twice to ensure that the `install` action successfully retrieved from the …
> ci: Re-enable Github actions `install` cacheing

- quic/s2n-quic/src/tests/buffer_limit.rs
Related to https://github.com/aws/s2n-quic/issues/332
Rustls' limit for each handshake message's size is also 64KB. The `buffer_limit_test` will also use Rustls in CI. The comment should mention Rustls as well. This is missed in https://github.com/aws/s2n-quic/pull/2596.
> chore: fix comment in buffer_limit_test

- .github/actions/duvet/action.yml
- .github/workflows/book.yml
- .github/workflows/ci.yml
- .github/workflows/qns.yml
resolves https://github.com/aws/s2n-quic/issues/2302
We want to update the Cloud Front distribution to use the most up to date CI artifact in S2N-QUIC's doc. Instead of just uploading objects to a folder with the commit hash, I also upload those objects into a new folder called `latest`. I have changed the Cloud Front Origin Path to use the `/latest` folder to locate all artifacts.
According to the [github context page](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context), event_name shows the event that triggers the workflow to run. So, only when `github.event_name` is equal to `push`, a PR commit is pushed into main. We add a check for that to ensure only PR merging to main can trigger …
> doc: automatically update CI artifacts

- dc/s2n-quic-dc/src/stream/client/rpc.rs
This change optimizes the stream RPC implementation where the client only "actively" polls the response to decide when to return. This is based on the assumption that if the server is able to send the entire response then it received the request, even if the local request state hasn't completely finished for whatever reason.
The existing RPC tests show that this maintains all of the expected behavior.
> fix(s2n-quic-dc): only actively poll RPC response

- dc/s2n-quic-dc/src/stream/send/state.rs
- dc/s2n-quic-dc/src/stream/tests.rs
- dc/s2n-quic-dc/src/stream/tests/idle_timeout.rs
This change fixes a bug in the stream send state manager where it gets into a PTO feedback loop by constantly sending PTOs. This is reproduced by the test I added that shows that the sender constantly sends packets every millisecond. After the fix, no recovery packets are sent.
> fix(s2n-quic-dc): only send PTO packets when there are outstanding stream segments

- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/recv/shared.rs
- dc/s2n-quic-dc/src/stream/recv/state.rs
- dc/s2n-quic-dc/src/stream/tests/idle_timeout.rs
This change includes a fix to arm the recv idle timer on initialization. This avoids a hang where the server never sends a single packet (or the client never receives any), which means there is no timer armed and then the client hangs indefinitely.
I added a test to show the fix working.
> fix(s2n-quic-dc): arm recv idle timer on init

- dc/s2n-quic-dc/src/stream/recv/state.rs
- dc/s2n-quic-dc/src/stream/send/state.rs
- dc/s2n-quic-dc/src/stream/send/state/retransmission.rs
- dc/s2n-quic-dc/src/stream/tests/rpc.rs
While testing packet loss with very large transfers, I found that receivers can get stuck and time out. After digging in as to why, it's due to how the receiver tracks packet numbers in the stream and recovery spaces. The current implementation first computes the needed space for the stream space and then the recovery. What this does in practice is starts dropping the recovery packet numbers as the ranges start to fill up. Because lost stream packets are always re-transmitted as recovery packets, this essentially means for very large transfers with quite a bit of loss that the recovery space is always cleared out and never gets any ACKs through.
This change fixes this behavior by computing the required space for recovery packets first and then the stream packets are lower priority. I was …
> fix(s2n-quic-dc): prioritize recovery ACK ranges over stream

- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic/src/tests/connection_migration.rs
* Close the connection when the PTO overflows.
We found out that PTO would overflows if we change the port of every datagram received after the second received datagram:
```
thread 'tests::connection_migration::rebind_before_handshake_confirmed' panicked at /home/ubuntu/workspace/s2n-quic/quic/s2n-quic-transport/src/space/mod.rs:361:27:
attempt to multiply with overflow
```
https://github.com/aws/s2n-quic/blob/34f5e4b054d0fb07c767f7fe63d3c50701df4f6d/quic/s2n-quic-transport/src/space/mod.rs#L361
I have investigated the issue and this problem can't be hit in production. The PTO will overflow after about 1.8 million days, which means to hit this problem in production, the client has to continuously to run for more than 1.8 million days. That is not a particular way to configure an endpoint. …
> fix(s2n-quic-transport): handle pto overflows in connection migration

- dc/wireshark/generate-bindings.sh
quic-ci is breaking due to the following error for `dc-wireshark(ubunutu-latest)` job
```
The following information may help to resolve the situation:
The following packages have unmet dependencies:
libwireshark-dev : Depends: libgio-2.0-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
thread 'main' panicked at xtask/src/main.rs:27:10:
called `Result::unwrap()` on an `Err` value: command exited with non-zero code `./generate-bindings.sh`: 100
stack backtrace:
0: rust_begin_unwind
at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:695:5
1: core::panicking::panic_fmt
at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:75:14
2: core::result::unwrap_failed
at …
```
> chore: Remove wireshark ppa repository

- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic/src/tests/setup.rs
- quic/s2n-quic/src/tests/slow_tls.rs
- quic/s2n-quic/src/tests/snapshots/tests__pto__handshake_pto_timer_is_armed__events.snap
resolves #2599
It's technically possible for the PTO Timer to cause s2n-quic to skip the first packet number when transitioning to a new packet space. This change checks that the packet number is not zero before skipping the number, as we do not want this behavior.
The PTO module doesn't really have any knowledge of which packet number we're on. Maybe it's better to add this logic inside of the requires_probe() function. But then I would have to pass in the packet number so I really didn't think it was worth it.
slow_tls test now passes with the fips libcrypto.
> fix(s2n-quic-transport) Ensures packet number about to be skipped is not the first packet

- dc/s2n-quic-dc/src/stream/application.rs
- dc/s2n-quic-dc/src/stream/client/rpc.rs
- dc/s2n-quic-dc/src/stream/recv/application.rs
- dc/s2n-quic-dc/src/stream/recv/application/builder.rs
- dc/s2n-quic-dc/src/stream/socket/fd/udp.rs
This change fixes IPv6 address handling on the recv path for UDP streams. Before this change, we weren't updating the length of the parsed `Addr`, which was resulting in part of IPv6 addresses being interpreted as IPv4, resulting in unroutable addresses.
I've also included a change around the `ReadMode` defaults for UDP streams. Without this change, we will send an ACK for every packet we receive, which can cause quite a bit of overhead. After this change, we'll only send ACKs after we fill up the provided application buffer, which should naturally reduce it, especially for large reads.
Longer term, I plan on adding some throttling for ACKs, which should reduce the frequency independent of the application buffer sizes. But that's a larger change and this _should_ work for now under …
> fix(s2n-quic-dc): correctly process IPv6 on recv path

- quic/s2n-quic-qns/Cargo.toml
A transitive dependency of `s2n-quic-qns`, idna_adapter, did a release today and [update their MSRV to 1.82.0](https://crates.io/crates/idna_adapter/versions). We only use it once in `s2n-quic-qns`'s url dependency, so we should pin a previous version.
This issue can be related to https://github.com/aws/s2n-quic/issues/2334.
CI Testing.
> chore: pin idna_adapter to v1.2.0

- .github/workflows/ci.yml
This PR is a follow up for https://github.com/aws/s2n-quic/pull/2624. This job shouldn't run the credential verification for PR cut from forked repo. Hence, add a one line check to let daily scheduled ci job to run for scheduled triggered run only.
* This issue is detected in https://github.com/aws/s2n-quic/pull/2632.
* The scheduled job will only be ran in mainline aws/s2n-quic.
* CI will pass after https://github.com/aws/s2n-quic/pull/2632 is merged.
With this change, the steps in `scheduled-ci-status-report` shouldn't run at all for this PR, but it should run at 8PM today for scheduled job.
> chore: restrict steps for daily ci run for scheduled jobs only

- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
S2N-QUIC release to v1.58.0
Release Summary:
Close the connection when pto backoff exceeds maximum value: https://github.com/aws/s2n-quic/pull/2620.
The scheduled-ci-status-report test can be fixed by https://github.com/aws/s2n-quic/pull/2633.
> chore: release v1.58.0

- .github/workflows/qns.yml
- dc/s2n-quic-dc/src/path/secret/receiver/tests.rs
- dc/s2n-quic-dc/src/stream/client/rpc.rs
- dc/s2n-quic-dc/src/stream/environment/udp.rs
- dc/s2n-quic-dc/src/stream/pacer.rs
- dc/s2n-quic-dc/src/stream/recv/shared.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager/tests.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/worker.rs
- quic/s2n-quic-core/src/packet/number/sliding_window.rs
- quic/s2n-quic-crypto/src/one_rtt.rs
- quic/s2n-quic-platform/src/io/testing/network.rs
- quic/s2n-quic-platform/src/io/testing/socket.rs
- quic/s2n-quic-platform/src/io/tokio.rs
- quic/s2n-quic-platform/src/io/turmoil.rs
- quic/s2n-quic-sim/src/batch.rs
- quic/s2n-quic-transport/src/sync/data_sender/transmissions.rs
- quic/s2n-quic/src/provider/dc/confirm.rs
- quic/s2n-quic/src/provider/dc/mtu_confirm.rs
- tools/xdp/s2n-quic-xdp/src/syscall.rs
The newest ubuntu22/20250514 image is causing our interop tests to fail. I suspect it has to do with the docker version bump, which went from [v26 to v28](https://github.com/actions/runner-images/pull/12124). Here I am pinning our docker version to one that we know works.
I don't think this is a great long-term solution, but I would like to get our CI working again. Opened a new issue for this: https://github.com/aws/s2n-quic/issues/2640
Also fixing a new clippy lint.
Ci should pass.
> ci: Pin to older docker version

- quic/s2n-quic-h3/Cargo.toml
- quic/s2n-quic-h3/src/s2n_quic.rs
- quic/s2n-quic-qns/src/server/h3.rs
This change supports h3 v0.0.8 that has breaking changes on its API. This was implemented by referring to h3-quinn v0.10.0, specifically by following the commit [efdc2d8bfda0d86c0efdd36867ee6183f92d54d6](https://github.com/hyperium/h3/commit/efdc2d8bfda0d86c0efdd36867ee6183f92d54d6).
resolves #2628 (dependabot PR)
This change updates `quic/s2n-quic-h3/src/s2n_quic.rs` as the upstream `h3` traits changes the manner of error handling.
I believe the change does not need to be updated at this point since it just follows the h3's API changes.
However, I am not sure if changes [L53-L58](https://github.com/aws/s2n-quic/compare/main...junkurihara:s2n-quic:deps/h3-0.0.8#diff-327d115c00ee24f279e4a904977a907c658451a5d618a3acd908d3e98e8c3c8bR53-R58) and …
> deps: h3-0.0.8 (s2n-quic-h3)

- .github/workflows/qns.yml
This PR is to fix the daily qns job enabled by https://github.com/aws/s2n-quic/pull/2636. After the schedule job is enabled, I noticed that the `interop-report` fails to run. The failed test case can be found in this [report](https://github.com/aws/s2n-quic/actions/runs/15081106179/job/42398263226). I realized the schedule job doesn't run some previous required steps, because the run is triggered by the scheduled call instead of a push to main or a pull request. Hence, I make a parity for all the jobs that are required for the push to main event and the schedule run event.
This PR can only be tested after it is merged.
We should merge this PR and wait until 8 PM that night. We should monitor if the daily schedule QNS job passes. If it fails, we need to investigate and figure out why that …
> ci: fix daily qns job

- codebuild/spec/cargotiming.yml
n/a
Checks in a CodeBuild buildspec for a `cargo build` timing job.  The report at the end is uploaded to s3, example: https://d2vvhsim0lzm9u.cloudfront.net/cargotiming/cargo-timing.html
The job is scheduled to run once a day, and the metrics are used to track cargo build historical timing.
> chore(ci): cargo timing cb job

- quic/s2n-quic-platform/src/socket/ring.rs
- quic/s2n-quic-platform/src/socket/task/rx.rs
- quic/s2n-quic-platform/src/socket/task/tx.rs
Rx and Tx packet processing tasks are now properly terminated when the client endpoint is dropped, resolving a memory leak. 
resolves https://github.com/aws/s2n-quic/issues/2535.
This PR adds a `drop_waker` into the `Rx::Receiver` struct, which ensures that that the `Future` trait for `Receiver` will be called during clean up.
`poll_*` APIs  require [`either storing the provided Waker for later or immediately waking the waker to reschedule the task to be polled again`](https://github.com/aws/s2n-quic/pull/2248). Otherwise, we end up with a zombie task which doesn't make any progress and may hold onto resources indefinitely. `Rx::Receiver` is currently violating that contract, since it returns `Pending` without registering a `waker`, nor does does it immediately wake the waker. Hence, the …
> fix(s2n-quic-platform): register drop waker to avoid memory leaks

- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/entry.rs
- dc/s2n-quic-dc/src/path/secret/map/handshake.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
- dc/s2n-quic-dc/src/path/secret/map/state/tests.rs
- dc/s2n-quic-dc/src/path/secret/map/store.rs
Change return type of make_application_data callback registered by application to Result<...>, and canceling the handshake, propagating an error message when an Error is returned.
> feat(s2n-quic-dc): path_secrets_ready callback can cancel handshake

- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
S2N-QUIC release to v1.59.0
1. Rx and Tx packet processing tasks are now properly terminated when the client endpoint is dropped, resolving a memory leak.
2. Change signature of user callback provided for on_path_secrets_ready to be able to fail the handshake. The callback is still provided using the register_make_application_data function and can return an error message in case the handshake should be cancelled.
3. Support for h3 v0.0.8 that has breaking changes on its API. This was implemented by referring to h3-quinn v0.10.0.
> chore: release v1.59.0

- .github/actions/duvet/action.yml
- .github/workflows/book.yml
- .github/workflows/ci.yml
- .github/workflows/qns.yml
- .github/workflows/release.yml
- .github/workflows/tshark.yml
related to https://github.com/aws/s2n-quic/issues/2651.
We want to add logic to ensure that only `push` or `schedule` event to mainline s2n-quic will trigger AWS action to run. I believe that we only need to check if the `github.repository` is `aws/s2n-quic`.
The following conversation has more details: https://github.com/boquan-fang/s2n-quic/actions/runs/15501459732, https://github.com/boquan-fang/s2n-quic/actions/runs/15501459733.
We need to merge this PR into upstream. Pull down the code to local repo and then sync up with a forked s2n-quic repo to see if those jobs are not ran.
We need two parts of testing:
1. This PR is cut on upstream s2n-quic, so we should verify that every aws action are successfully ran.
2. After this PR is merged, as mentioned in the `Call-outs` section, we …
> ci(GithubAction): only run aws credential on upstream s2n-quic

- dc/s2n-quic-dc/events/connection.rs
- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
- dc/s2n-quic-dc/src/stream/client/tokio.rs
* feat(s2n-quic-dc): Emit additional events for TCP connects
n/a
This adds a set of events for stream opening, when dcQUIC owns the TCP connect() call. UDP streams likely want something similarly shaped but likely at least subtly different -- UDP connect() I think is either infallible or at least differently-fallible (e.g., exhausting our pool is perhaps a failure mode worth tracking there).
The new events are attached to the endpoint rather than moving the ConnectionContext earlier -- that's not perfect, but it seems reasonable enough. I'm not super happy with not tracking some of the later failures (e.g., for sending the prelude) but that can come later and this is already a useful step.
No tests added, but the modified code is run as part of our existing testing.
By submitting this …
> feat(s2n-quic-dc): Define dcQUIC stream connect events

- quic/s2n-quic-core/events/endpoint.rs
- quic/s2n-quic-core/src/event/generated.rs
- quic/s2n-quic-core/src/event/generated/metrics/aggregate.rs
- quic/s2n-quic-core/src/event/generated/metrics/probe.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic/src/tests/snapshots/tests__dc__dc_handshake_self_test__events.snap
- quic/s2n-quic/src/tests/snapshots/tests__dc__dc_mtls_handshake_auth_failure_self_test__events.snap
- quic/s2n-quic/src/tests/snapshots/tests__dc__dc_mtls_handshake_self_test__events.snap
- quic/s2n-quic/src/tests/snapshots/tests__dc__dc_mtls_handshake_server_not_supported_self_test__events.snap
- quic/s2n-quic/src/tests/snapshots/tests__dc__dc_not_secret_control_packet__events.snap
- quic/s2n-quic/src/tests/snapshots/tests__dc__dc_secret_control_packet__events.snap
* feat(s2n-quic-dc): Add event for connection-open deduplication
n/a
This event is useful by itself, but the specific goal is to use it to help explore throttling/rate limiting connection opens, which requires knowledge of whether a connection open is unique or is hitting the de-duplication.
n/a
See updated tests that ensure the event is being emitted.
> Emit event for deduplicated connection opens

- codebuild/spec/cargotiming.yml
I made a change to remove skipping `ipv4_two_socket_test`, `ipv4_test`, and `max_total_test`. We were using the a docker image in our codebuild `CargoTiming` job, but we have recently changed it to a EC2 fleet. The docker image doesn't allow endpoints to bind to a specific address, while the EC2 fleet does. Hence, we don't need to skip those three tests any more.
* This unblock one of our obstacles to add AL2023 support in our test. This was a problem mentioned in https://github.com/aws/s2n-quic/pull/2657#discussion_r2122121844, but this PR will resolve that issue. Furthermore, the EC2 fleet by default is running on AL2023, so we just need to figure out how to incorporate that into our CI.
* It seems like `CargoTiming` runs faster on EC2 fleet (It only takes 4 and a half minutes).
We have …
> ci: remove skipping tests for cargotiming

- dc/s2n-quic-dc/src/path/secret/map.rs
- dc/s2n-quic-dc/src/path/secret/map/entry.rs
- dc/s2n-quic-dc/src/path/secret/map/handshake.rs
- dc/s2n-quic-dc/src/path/secret/map/peer.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
- dc/s2n-quic-dc/src/path/secret/map/store.rs
* feat(s2n-quic-dc): Expose HandshakingPath to access entry/error after handshake completes
n/a
This refactors the HandshakingPath to allow consumers of the DcPathCreated event to store a copy of the path locally, allowing subsequent access after various events are handled (e.g., to pull out the path secret ID for logging).
This also adjusts error propagation out of the HandshakingPath to preserve more detail about errors, again propagating that into the HandshakingPath for consumers to access if desired. This also avoids panics in a few cases in favor of failing just the one handshake.
n/a
Just refactoring (mostly exposing more types), no particular tests added.
> feat(s2n-quic-dc): Expose dc::HandshakingPath publicly

- dc/s2n-quic-dc/src/stream/recv/buffer/local.rs
- dc/s2n-quic-dc/src/stream/recv/buffer/local/test.rs
* fix(s2n-quic-dc): properly detect truncated streams
n/a
Previously we ignored the return from poll_read on the underlying TcpStream (poll_fill_once calls into that), which meant that a truncated stream caused effectively a busy loop trying to parse the last packet to be sent on the stream.
This fixes a known case but doesn't fix the class of bug definitively -- there may be other poll_read's hiding whose output is ignored. Unfortunately I'm not sure we have any good tooling for catching that, but I'll attempt to manually audit soon.
See added unit test.
> fix(s2n-quic-dc): detect truncated streams

- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
1. Bump S2N-QUIC's MSRV to 1.82.0
2. (s2n-quic-dc) Increase background handshake jitter
3. (s2n-quic-dc) Emit additional events for TCP connects
4. (s2n-quic-dc) Add event for connection-open deduplication
5. (s2n-quic-dc) Expose HandshakingPath to access entry/error after handshake completes
6. (s2n-quic-dc) Properly detect truncated streams
S2N-QUIC release to v1.60.0
> chore: release v1.60.0

- dc/s2n-quic-dc/src/event/generated/metrics.rs
- quic/s2n-quic-core/src/event/generated/metrics.rs
- quic/s2n-quic-events/src/output/metrics.rs
n/a -- only affects s2n-quic-core API
n/a
This lets applications wrapping their own Subscriber access the context via query_event_context on Connection.
n/a
No particular testing, but just exposing the inner field, so pretty straightforward. This is all unstable API anyway.
> Expose inner context on metrics Subscriber

- dc/s2n-quic-dc/Cargo.toml
- dc/s2n-quic-dc/src/task/waker/worker.rs
Our usage of the crossbeam-epoch `Atomic` seems to be incorrect and leaks Wakers. I don't really think our current usage really justifies the complicated (unsafe) interface so i've just replaced it with a Mutex.
> fix(s2n-quic-dc): avoid memory leak in worker waker

- common/s2n-codec/Cargo.toml
- dc/s2n-quic-dc/Cargo.toml
- quic/s2n-quic-core/Cargo.toml
- quic/s2n-quic-crypto/Cargo.toml
- quic/s2n-quic-platform/Cargo.toml
- quic/s2n-quic-rustls/Cargo.toml
- quic/s2n-quic-tls-default/Cargo.toml
- quic/s2n-quic-tls/Cargo.toml
- quic/s2n-quic-transport/Cargo.toml
- quic/s2n-quic/Cargo.toml
- tools/xdp/s2n-quic-xdp/Cargo.toml
S2N-QUIC v1.61.0 Release.
feat(s2n-quic-core, s2n-quic-dc): Access inner context for generated metrics Subscribers
CI test.
> chore(release): v1.61.0 release

- .github/workflows/ci.yml
I detected a CI failure on `udeps` for s2n-quic's CI:
```
Caused by:
rustc 1.85.0-nightly is not supported by the following packages:
cargo@0.89.0 requires rustc 1.86
cargo@0.89.0 requires rustc 1.86
cargo@0.89.0 requires rustc 1.86
cargo-credential-libsecret@0.4.14 requires rustc 1.86
cargo-util@0.2.21 requires rustc 1.86
cargo-util-schemas@0.8.2 requires rustc 1.86
crates-io@0.40.11 requires rustc 1.86
```
`Udeps` did a [release](https://crates.io/crates/cargo-udeps/0.1.57) at around 9:00 PM on July 5th, which bumps its required nightly version to 1.86. Hence, we need to pin that specific nightly version in our CI to make the test pass.
`nightly-1.86.0` is `nightly-2025-01-31`:
```
rust version 1.86.0-nightly (854f22563 2025-01-31)
```
The daily scheduled CI run should capture this …
> ci(fix): pin nightly-1.86.0 for udeps fix

- .github/workflows/codebuild.yml
- codebuild/bin/start_codebuild.sh
Adds a new github action that invokes a script to use the aws CLI tool to trigger a codebuild job.
I didn't add this to our ci.yml file. It feels different to me because it's codebuild? But it is also a github action.
Also note that quic-attack will not run on this PR, unless I manually kick it off, as the github action will not run until it is merged. 
I have a [commit that passes the CI run](https://github.com/aws/s2n-quic/pull/2703) and [a commit that deliberately causes a panic](https://github.com/aws/s2n-quic/pull/2706) to prove that this action is working.
> ci: Adds github action to trigger codebuild job for quic-attack

- README.md
resolves https://github.com/aws/s2n-quic/issues/2261
This PR adds a section to document that S2N-QUIC requires kernel version 5.0 or later, since it needs GSO support that older version doesn't have. This PR specifically address https://github.com/aws/s2n-quic/issues/2261#issuecomment-2223459594.
> doc(README): add minimun supported kernel version section

- dc/s2n-quic-dc/events/map.rs
- dc/s2n-quic-dc/src/event/generated.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
- dc/s2n-quic-dc/src/path/secret/map/cleaner.rs
- dc/s2n-quic-dc/src/path/secret/map/state.rs
* feat(s2n-quic-dc): This tracks the cleaner cycle time. The cleaner holds a lock also taken during handshakes, so long cycle times can interfere with the event loop and slow down our ability to handshake.
n/a
Just adds a few new metrics to the dcQUIC path secret map cleaner.
n/a
We don't have tests (at least that I can see) but the metrics are pretty obvious and fit into the existing framework. I'm not sure a test would add any real value here.
> feat(s2n-quic-dc): Add cleaner duration metrics

- codebuild/spec/cargotiming.yml
related to https://github.com/aws/s2n-quic/pull/2697
In [this PR](https://github.com/aws/s2n-quic/pull/2697), we introduced CloudFlare Quiche as a dev dependency. Our `CargoTiming` job is running on a EC2 fleet which doesn't have `cmake` installed. However, CloudFlare Quiche needs `cmake` to compile its TLS provider `BoringSSL`. Hence, we need to install `cmake` for the `CargoTiming` job.
I put this script into `Codebuild`, and manually kick off a `CargoTiming` job. Quiche finished compiling. The build can be found in this [link](https://us-west-2.console.aws.amazon.com/codesuite/codebuild/003495580562/projects/CargoTiming/build/CargoTiming%3Aed753aaf-d178-48ea-b1ad-7202365b63a4/log?region=us-west-2).
Before this PR:
```
Compiling quiche v0.24.4
--- stderr
--
thread 'main' panicked at …
```
> fix(ci): install cmake to compile quiche on cargotiming job

- dc/s2n-quic-dc/src/msg/segment.rs
We should include a 40 bytes `IPV6_HEADER_LEN` in the calculation for the max payload size that can be sent for IPV6.
I was testing this code on AL2 X86_64 Kernel 5.10 machine, and the max_total_test is consistently failing. I test the limit by changing the constant definition of `MAX_TOTAL_IPV6`, and found out that the maximum amount that can be sent with IPV6 is `u16::MAX - IPV6_HEADER_LEN - UDP_HEADER_LEN`, the current calculation doesn't include `IPV6_HEADER_LEN`.
This problem only happens on AL2 X86_64 Kernel 5.10 machine, and we are not aware of any other platforms that will make this fail.
The next step for this PR is to investigate issue https://github.com/aws/s2n-quic/issues/2728.
I ran the code on AL2 X86_64 Kernel 5.10 machine, and it succeeded:
```
(25-07-25 20:53:59) <0> …
```
> fix(s2n-quic-dc): include ipv6 header length in MAX_TOTAL_IPV6 payload length

- .github/workflows/codebuild.yml
We found a typo in the codebuild.yml file:
https://github.com/aws/s2n-quic/blob/4938450468d9b68c1098634ecf4213dcafe2d091/.github/workflows/codebuild.yml#L64
It should be `echo` not `ehco`.
> fix(typo): fix a typo in codebuild.yml

- Cargo.toml
- examples/tls-offloading/Cargo.toml
- examples/tls-offloading/README.md
- examples/tls-offloading/src/bin/client.rs
- examples/tls-offloading/src/bin/server.rs
- quic/s2n-quic-core/src/crypto/tls.rs
- quic/s2n-quic-core/src/crypto/tls/offload.rs
- quic/s2n-quic-core/src/sync/spsc/recv.rs
- quic/s2n-quic-core/src/sync/spsc/send.rs
- quic/s2n-quic-tests/Cargo.toml
- quic/s2n-quic-tests/src/tests.rs
- quic/s2n-quic-tests/src/tests/offload.rs
- quic/s2n-quic/Cargo.toml
- quic/s2n-quic/src/provider/tls.rs
Adds unstable feature to move s2n-tls operations out of the main event loop.
resolves #2598
Adds a new TLS provider that spawns an asynchronous task which will complete the TLS handshake.
I am closing #2688 in favor of this PR.
New integ tests.
> feat(s2n-quic-core) TLS offloading

- dc/s2n-quic-dc/src/stream/environment/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/server/tokio.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/fresh.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/lazy.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/manager.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp/worker.rs
- dc/s2n-quic-dc/src/stream/testing.rs
- dc/s2n-quic-dc/src/stream/tests/accept_queue.rs
* opt(s2n-quic-dc): skip epoll registration in happy path of TCP acceptor
n/a
Currently, dcQUIC streams over TCP will be accepted, be registered with epoll, attempt reading (usually fails), in <1ms the first data packet arrives and we succeed reading, deregister the socket, and then hand off the stream to the application for further reading.
We'd like to avoid the epoll registration as it uses extra CPU (even if latency impact is minimal) so this patch uses the Linux-only TCP_DEFER_ACCEPT to only accept sockets with data already available. That's combined with lazy registration of sockets with Tokio's epoll by only doing so if we get WouldBlock after attempting a read or write. The net effect is that based on flamegraphs epoll registration in the acceptor isn't visible anymore.
The net …
> opt(s2n-quic-dc): skip epoll registration in happy path

- quic/s2n-quic-core/src/connection/limits.rs
- quic/s2n-quic-core/src/recovery/rtt_estimator.rs
- quic/s2n-quic-qns/src/limits.rs
- quic/s2n-quic-tests/src/tests/pto.rs
- quic/s2n-quic-transport/src/connection/connection_container/tests.rs
- quic/s2n-quic-transport/src/connection/connection_impl.rs
- quic/s2n-quic-transport/src/connection/connection_trait.rs
- quic/s2n-quic-transport/src/connection/mod.rs
- quic/s2n-quic-transport/src/connection/transmission.rs
- quic/s2n-quic-transport/src/endpoint/initial.rs
- quic/s2n-quic-transport/src/endpoint/mod.rs
- quic/s2n-quic-transport/src/path/manager.rs
- quic/s2n-quic-transport/src/path/manager/tests.rs
- quic/s2n-quic-transport/src/path/mod.rs
- quic/s2n-quic-transport/src/recovery/manager.rs
- quic/s2n-quic-transport/src/recovery/manager/tests.rs
- quic/s2n-quic-transport/src/space/application.rs
- quic/s2n-quic-transport/src/space/handshake.rs
- quic/s2n-quic-transport/src/space/initial.rs
- quic/s2n-quic-transport/src/space/mod.rs
- quic/s2n-quic-transport/src/space/session_context.rs
Adds configurable percentage-based random jitter to Probe Timeout (PTO) calculations to prevent synchronized timeouts across multiple connections and reduce network congestion. Users can now configure jitter between 0-50% of the base PTO period, with 0% maintaining current RFC 9002 compliant behavior.
resolves #2730
This PR implements configurable PTO jitter for s2n-quic's loss recovery mechanism. Currently, PTO calculations follow RFC 9002 exactly: `PTO = smoothed_rtt + max(4*rttvar, kGranularity) + max_ack_delay`. This can lead to synchronized timeouts when multiple connections start simultaneously, causing network congestion. The changes add: 
- New `pto_jitter_percentage` field to the `Limits` configuration struct (0-50% range, default 0%) 
- Modified `RttEstimator::pto_period()` …
> feat(s2n-quic): configurable PTO jitter

- dc/s2n-quic-dc/src/psk/client/builder.rs
- dc/s2n-quic-dc/src/psk/io.rs
- dc/s2n-quic-dc/src/psk/server/builder.rs
Sets the default PTO jitter percentage for s2n-quic-dc to 33%
This change adds `pto_jitter_percentage` to the s2n-quic-dc server and client builders, and configures the default value to to 33%
Tested as part of #2756
> feat(s2n-quic-dc): set default PTO jitter to 33%

- .github/workflows/qns.yml
- .github/workflows/retry.yml
As an alternative to https://github.com/aws/s2n-quic/commit/f217c8551739a23fe6485eeddd8571ae6a7eaed7, we could instead retry the interop tests when they fail. As long as we have remaining attempts, we will not report the failure via qns-status-report.
I modeled this solution off of https://github.com/orgs/community/discussions/67654#discussioncomment-8038649.
Currently, I'm retrying the entire "qns" workflow. I could probably limit the retry to just the interop tests by introducing a new "interop-trigger" job that "interop" depends on, and then rerun just that job. HOWEVER, Github counts "attempts" per workflow, NOT per job. So by retrying a subset of jobs, the counter we rely on to check for retries goes up for all jobs anyway. I think that could be confusing? Retrying the entire …
> ci: add interop retries

- dc/s2n-quic-dc/src/event.rs
- dc/s2n-quic-dc/src/psk/client.rs
- dc/s2n-quic-dc/src/psk/client/builder.rs
- dc/s2n-quic-dc/src/psk/io.rs
- dc/s2n-quic-dc/src/psk/server.rs
- dc/s2n-quic-dc/src/psk/server/builder.rs
- dc/s2n-quic-dc/src/stream/client/tokio.rs
- dc/s2n-quic-dc/src/stream/server/tokio.rs
- dc/s2n-quic-dc/src/stream/server/tokio/tcp.rs
This change makes a couple of adjustments for s2n-quic-dc endpoint builders:
* Removes `Clone` and `Default` bounds for TLS and event providers - they aren't needed and a lot of impls don't include those.
* Implements the `Handshake` traits for the client and server `Provider` structs. This makes it more convenient when the application doesn't need the callback.
> fix(s2n-quic-dc): adjust trait bounds for providers

- dc/s2n-quic-dc/events/acceptor.rs
- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- dc/s2n-quic-dc/src/event/generated/metrics/probe.rs
N/A
Fixes a typo. Technically this is a breaking change since it touches a metric name, however, we do not believe anyone has consumed this metric yet as it is for the dc quic crate.
N/A
CI should pass.
> ci: Fixes typo in metrics feature

- dc/s2n-quic-dc/src/stream/server/tokio.rs
* feat(s2n-quic-dc): expose acceptor runtime
n/a
This is primarily intended to help us experiment with optimizing a workload that immediately sends on a different channel. We think this is a quick change to improve that workload, cutting out an intermediate thread which ends up costing ~2% of CPU.
n/a
n/a
> Expose the acceptor runtime

- tools/event-generator/README.md
https://github.com/aws/s2n-quic/pull/2797 created a readme in tools/generate-events, which isn't the correct directory of the event generator. The correct directory is tools/event-generator. This PR fixes the path.
The generate-events directory existed in my local environment because of a previous PR revision, and I accidentally created the readme there.
None
Documentation change.
> docs(s2n-events): Fix event-generator readme path

- quic/s2n-quic-platform/src/socket/ring.rs
- quic/s2n-quic-tests/src/tests/mtu.rs
Fixed bug that caused a hang on Windows platforms.
resolves #2220
s2n-quic has a bug that causes a hang when receiving data on s2n-quic in Windows. The root cause of this issue is that the consumer of the shared ring buffer resets each payload to be its original length without syncing this change in between primary and secondary memory regions. This causes some payloads to remain very small, making it so that the Producer can only make tiny writes to the un-synced payloads. In Windows eventually this causes a hang. 
Notably, this issue was not present on unix as the msghdr struct accesses payload lengths through pointers, meaning that primary and secondary memory regions do not need to be synced for payload length changes.
Another interesting point is that this problem could be seen in …
> bug: Fixes bug causing a hang on Windows

- .github/workflows/ci.yml
- tools/s2n-events/Cargo.toml
- tools/s2n-events/src/bin/generate_test_events.rs
- tools/s2n-events/tests/c_ffi_events/event.rs
- tools/s2n-events/tests/c_ffi_events/event/generated.rs
- tools/s2n-events/tests/c_ffi_events/event/generated/metrics.rs
- tools/s2n-events/tests/c_ffi_events/event/generated/metrics/aggregate.rs
- tools/s2n-events/tests/c_ffi_events/event/generated/metrics/probe.rs
- tools/s2n-events/tests/c_ffi_events/events/common.rs
- tools/s2n-events/tests/c_ffi_events/events/connection.rs
- tools/s2n-events/tests/c_ffi_events/events/endpoint.rs
- tools/s2n-events/tests/c_ffi_events/mod.rs
- tools/s2n-events/tests/test_c_ffi_events.rs
resolves https://github.com/aws/s2n-quic/issues/2765
A new events system with a few test events is generated in order to test upcoming code generation changes to s2n-events (see https://github.com/aws/s2n-quic/issues/2764). 
Committing this test events system will also allow reviewers to observe how future changes to s2n-events affect the resulting generated code, as many of the planned changes will not affect the existing s2n-quic/s2n-quic-dc events systems.
The primary functionality I intend to test with this new events system is the C FFI stuff for https://github.com/aws/s2n-quic/issues/2767, so I named the events system `c_ffi_events`. I'm open to other names for it though.
A lot of the changes in this PR are just committing the generated events system (tests/c_ffi_events/event/*). …
> test(s2n-events): Generate test events system

- dc/s2n-quic-dc/src/event/generated/metrics/aggregate.rs
- quic/s2n-quic-core/src/event/generated/metrics/aggregate.rs
- tools/s2n-events/src/output/metrics/aggregate.rs
- tools/s2n-events/tests/c_ffi_events/event/generated/metrics/aggregate.rs
- tools/s2n-events/tests/c_ffi_events/event/generated/metrics/probe.rs
- tools/s2n-events/tests/c_ffi_events/events/connection.rs
An events system generated by s2n-events will currently [emit a warning](https://github.com/aws/s2n-quic/actions/runs/17778433907/job/50531874815?pr=2811#step:5:2439) when the events system defines no nominal counter metrics. This is because `api` is imported in `nominal_counters()` but is unused, since there are no nominal counter definitions.
This PR ignores the unused_imports warning on this import, [similar to other instances where an import is declared but may be unused](https://github.com/aws/s2n-quic/blob/1d4aa38795acf27e3f4e925e4a9d89c6772fc6e1/tools/s2n-events/src/output/metrics/aggregate.rs#L763-L765).
The manual change is made in src/output/metrics/aggregate.rs (and the event struct update in events/connection.rs). The remaining changes are the resulting code generation.
This …
> fix(s2n-events): Fix warning when no nominal counters are defined

- quic/s2n-quic-tests/src/tests/endpoint_limits.rs
related to https://github.com/aws/s2n-quic/pull/2792, https://github.com/aws/s2n-quic/issues/270
I noticed that I didn't add the compliance test annotation to the `endpoint_limits_close_test` for RFC section 5.2.2. Hence, the [compliance report](https://dnglbrstg7yg.cloudfront.net/5ed195518443a229f93024ec51b63c3a04533d20/compliance.html#/spec/https%3A%2F%2Fwww.rfc-editor.org%2Frfc%2Frfc9000) is showing `missing test` for 5.2.2.
This PR add the test annotation so that it adds that annotation.
We should see section 5.2.2 as complete in the compliance report.
https://dnglbrstg7yg.cloudfront.net/04c39cc0176b2350f83bc0cd432f694b27d8b05a/compliance.html#/spec/https%3A%2F%2Fwww.rfc-editor.org%2Frfc%2Frfc9000/section-5.2.2#A2072
That section is shown as `Complete` now.
By submitting this pull …
> refactor(s2n-quic-tests): add test annotation to endpoint_limits_close_test

- tools/event-generator/src/main.rs
- tools/s2n-events/src/generate_config.rs
- tools/s2n-events/src/lib.rs
- tools/s2n-events/src/output.rs
- tools/s2n-events/src/output/metrics.rs
- tools/s2n-events/src/output/metrics/aggregate.rs
- tools/s2n-events/src/output_config.rs
- tools/s2n-events/src/parser.rs
Part of https://github.com/aws/s2n-quic/issues/2767
The s2n-events code generation is configurable with the `OutputMode` enum, which allows the s2n-quic and s2n-quic-dc event systems to be generated slightly differently. For example, the s2n-quic `Subscriber` trait [is defined to be 'static + Send](https://github.com/aws/s2n-quic/blob/fdf958632f475569705e5d6f81ae34ad62f0215b/quic/s2n-quic-core/src/event/generated.rs#L6968), while the s2n-quic-dc `Subscriber` trait is [defined to be 'static + Send + Sync](https://github.com/aws/s2n-quic/blob/fdf958632f475569705e5d6f81ae34ad62f0215b/dc/s2n-quic-dc/src/event/generated.rs#L4722). This is implemented by [trait_constraints()](https://github.com/aws/s2n-quic/blob/fdf958632f475569705e5d6f81ae34ad62f0215b/tools/s2n-events/src/output_mode.rs#L98-L10 …
> refactor(s2n-events): Move OutputMode into OutputConfig

- .github/workflows/ci.yml
related to https://github.com/aws/s2n-quic/pull/2822
S2N-QUIC Clippy bot can automatically cut PRs to fix clippy updates. However, the PR's commit message is using a default message, while we want the message to be conventional commit message. Hence, I add the option to configure the actual commit message to be `chore: clippy lint updates`.
I previously thought the commit message in main is going to use the PR title, but turns out it is using the first commit message.
Workflow running on my forked which shows the logic runs correctly: https://github.com/boquan-fang/s2n-quic/actions/runs/17850394959/job/50757691653
The new PR cut has the right commit message: https://github.com/boquan-fang/s2n-quic/pull/3
By submitting this pull request, I confirm that my contribution is made under the …
> refactor(clippy-bot): configure the commit message of clippy PR

- dc/s2n-quic-dc/src/stream/server/tokio.rs
* opt(s2n-quic-dc): clamp TCP server concurrency
n/a
The lock contention referenced in the comment is a significant problem as the number of cores increases. In the future we can consider other mitigations for it (e.g., io_uring's fixed fd pool), but that's not possible until we can raise our minimal kernel baseline and is a much larger effort.
n/a
Testing the # of spawns is pretty annoying. I don't think I have any off-by-one logic here but in the worst case 4 becomes 5 or 3, and either is fine too; 4 is not some specially chosen magic number, just "not too high".
> opt(s2n-quic-dc): clamp TCP server concurrency

- dc/s2n-quic-dc/src/clock.rs
- dc/s2n-quic-dc/src/packet/control/decoder.rs
- dc/s2n-quic-dc/src/packet/stream/decoder.rs
- dc/s2n-quic-dc/src/psk/io.rs
- dc/s2n-quic-dc/src/psk/server/builder.rs
- dc/s2n-quic-dc/src/socket/recv/router.rs
- dc/s2n-quic-dc/src/stream/application.rs
- dc/s2n-quic-dc/src/stream/endpoint.rs
- dc/s2n-quic-dc/src/stream/environment/bach.rs
- dc/s2n-quic-dc/src/stream/recv/application.rs
- dc/s2n-quic-dc/src/stream/recv/error.rs
- dc/s2n-quic-dc/src/stream/recv/shared.rs
- dc/s2n-quic-dc/src/stream/recv/state.rs
- dc/s2n-quic-dc/src/stream/recv/worker.rs
- dc/s2n-quic-dc/src/stream/send/application.rs
- dc/s2n-quic-dc/src/stream/send/error.rs
- dc/s2n-quic-dc/src/stream/send/shared.rs
- dc/s2n-quic-dc/src/stream/send/state.rs
- dc/s2n-quic-dc/src/stream/send/worker.rs
- dc/s2n-quic-dc/src/stream/shared.rs
- dc/s2n-quic-dc/src/stream/tests/accept_queue.rs
- dc/s2n-quic-dc/src/stream/tests/behavior.rs
- dc/s2n-quic-dc/src/stream/tests/rpc.rs
- quic/s2n-quic-core/src/dc/testing.rs
This change implements notifications on streams being dropped in the accept queue. The current implementation does not send anything when this happens and the client times out.
The other thing I noticed while implementing this change is that the flow window negotiated to the client is very large, meaning while the recv worker is processing packets while it's waiting in the accept queue it's also increasing the flow window. If the stream never gets accepted by the application then this is wasted work. As part of this change, I've clamped the initial window to 10x the MTU by default, with a configurable separate limit on the server builder. Once the server accepts the stream, it's able to increase the window to the larger value and notify the client.
I've implemented a test harness showing …
> fix(s2n-quic-dc): send connection close frames with pruned streams

- docs/book.toml
mdbook 0.5 [removed the `multilingual` field](https://github.com/rust-lang/mdBook/blob/4e41c844c305bc6f34b79bf5580b9169b1fc6364/CHANGELOG.md?plain=1#L33-L34) from the `book` configuration file. This [caused our CI to fail](https://github.com/aws/s2n-quic/actions/runs/18108878810/job/51530138760?pr=2833#step:6:11), because [we are setting this option](https://github.com/aws/s2n-quic/blob/1cca93bf0b2392781060d1294aa7fde14b747c19/docs/book.toml#L4) (but just setting it to false).
This PR removes this option from our book.toml.
None
The book job [succeeds on this PR](https://github.com/aws/s2n-quic/actions/runs/18109011392/job/51530581841?pr=2834#step:6:1)
> ci: Update book.toml for mdbook 0.5 release

- .github/interop/required.json
The xquic interop tests [recently started failing with s2n-quic](https://github.com/aws/s2n-quic/actions/runs/18101631284/job/51514843000#step:12:24). Looking at the [interop runner report](https://interop.seemann.io/?run=2025-09-29T08:39), it appears that xquic is failing with other QUIC implementations as well. So, this is believed to be an issue with xquic rather than s2n-quic.
This PR temporarily removes xquic from the required interop tests until this issue is resolved in xquic. An issue has been opened to the xquic maintainers: https://github.com/alibaba/xquic/issues/506
None
The interop report job should succeed on this PR.
> ci: Temporarily remove xquic from required interop tests
